### ISSUE TITLE
Реализовать метод Delete(model:Model) для класса CDiscipline унаследованного от класса Controller

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#1]
Реализовать в ветку task-1

**Поведение**:
метод удаляет переданную дисциплину в том случае если поля
```csharp
        string name;
        string code; 
```
есть в списке. Если удаление из таблицы произошло, то метод вернет истину, в других случаях возвращается ложь.

[Ссылка](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit?usp=sharing) на диаграмму классов.

Ветка [task-1](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/tree/task-1).

**Comment by YuriSilenok** [comment]
Здравствуйте @DenisSavelev 
Что за хулиганство?
Зачем Вы поставили метку Group?
Спасибо.

**Comment by YuriSilenok** [comment]
Здравствуйте @Whitetech7417 
Задача с Вас снята из-за бездействия по ней.
Спасибо.

**Comment by YuriSilenok** [comment]
@SergeAlekseev Здравствуйте
Это Ваша новая задача.
Спасибо.

**Comment by YuriSilenok** [comment]
Зачтено

**Comment by DenisSavelev** [comment]
Здравствуйте, я ничего не ставил, вот только сейчас на почту то вошёл

пн, 18 февр. 2019 г. в 15:11, Юрий Силенок <notifications@github.com>:

**Comment by YuriSilenok** [comment]
Здравствуйте @DenisSavelev 
Обратите на историю изменений 5 февраля в 22:57
![image](https://user-images.githubusercontent.com/14871471/53003789-d190f480-3440-11e9-8fb1-44af40419be4.png)
Пожалуйста, будьте внимательнее.
Спасибо.
