### ISSUE TITLE
Автоматизация unit-test для конструктора сущности Group

### ISSUE THREAD

**Issue by noliss** [Students-of-the-city-of-Kostroma/Student-timetable#10]
[План](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.p) тестирования.

[Диаграмма](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit) классов.

[Сценарий](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548).

**Comment by YuriSilenok** [comment]
Добрый день.

- Нужно заасанить на меня что бы я начал с этой задачей работать.
- нет меток
- нет вехи

Спасибо.

**Comment by noliss** [comment]
Добрый день.
Не имею возможности что-либо изменять, соответственно и проставлять метки.
![qwerty](https://user-images.githubusercontent.com/45510680/52279260-3ab93800-296a-11e9-80c7-70397881c7d9.png)

**Comment by YuriSilenok** [comment]
Заасаньте на меня когда все будет готово

**Comment by YuriSilenok** [comment]
Что значит реализовать сценарии в таблицу?
Юнит-тест это код который тестирует другой код по существующим сценариям которые написаны в каком-то документе, в данном случае в таблице.

**Comment by YuriSilenok** [comment]
Ошибка такая как [здесь](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/10#issuecomment-460665820)

И если вы автоматизируете тестирование, значит сценарии уже написаны. Или у вас задача на написание сценариев?

**Comment by YuriSilenok** [comment]
О чем  Вам говорит описание лейбла Script?

**Comment by YuriSilenok** [comment]
План тестирования, разработки, что за план?

**Comment by YuriSilenok** [comment]
Зачтено
