### ISSUE TITLE
Написать сценарии тестирования пригодные для автоматизации модульного тестирования для метода Insert(Model model) сущности Auditor

### ISSUE THREAD

**Issue by bolotovaksenya** [Students-of-the-city-of-Kostroma/Student-timetable#100]
[План разработки](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_102)
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)
[Диаграмма классов](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_0)

**Comment by YuriSilenok** [comment]
Здравствуйте.
- Заголовок не отвечает на нужный вопрос
- Неправильно выставлены метки
Спасибо.

**Comment by bolotovaksenya** [comment]
[сценарий](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)
[Диаграмма классов](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit)
[план разработки](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_102)

**Comment by YuriSilenok** [comment]
Что Вы должны сделать когда закончили работать над задачей?

**Comment by YuriSilenok** [comment]
Здравствуйте
- На какой вопрос должен отвечать заголовок?
- Расскажите, почему Вы выбрали такой набор меток?
Спасибо.

**Comment by bolotovaksenya** [comment]
Формулировка заголовок запроса на слияние совпадает с названием задачи, для которой создан запрос. Описание запроса должен содержать ссылку на номер задачи. 
Выбрала метки по условию задачи

**Comment by YuriSilenok** [comment]
Здравствуйте.
Пожалуйста используйте нумерацию и цитирование. Это упрощает чтение.
- Вы создали запрос на слияние?
> Формулировка заголовок запроса на слияние совпадает с названием задачи, для которой создан запрос.

- А эта цитата зачем?
> Описание запроса должен содержать ссылку на номер задачи.

- Я хотел бы увидеть логику выбора каждой из этих меток. 
> Выбрала метки по условию задачи

Спасибо.

**Comment by bolotovaksenya** [comment]
@YuriSilenok , здравствуйте.
Прошу проверить правильность выполнения ЛР №1.
Спасибо.

**Comment by YuriSilenok** [comment]
Зачтено
