### ISSUE TITLE
Баг при открытии формы вид занятий

### ISSUE THREAD

**Issue by ifuwmnn** [Students-of-the-city-of-Kostroma/Student-timetable#1005]
При открытии формы вид занятий, появляется два окна вместо одного.
![image](https://user-images.githubusercontent.com/47635280/58889326-65858400-86f1-11e9-8830-444c08140322.png)
[Этап разработки](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/1012)
[План на спринт 3](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/839)

**Comment by YuriSilenok** [comment]
Баг не воспроизводится в ветке Testing. [коммит ](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/commit/9ff47db38d286d9f5b6fa661a6cf1f7b4703407a)
