### ISSUE TITLE
Исправить сбой в автотесте UnitTestOfTimetableOfClasses.UT_Delete_CEnclosures.task_395_1()

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#1007]
Исправить сбой в автотесте UnitTestOfTimetableOfClasses.UT_Delete_CEnclosures.task_395_1() в ветке Testing. Обратить внимание, что сбои могли возникнуть из-за введение реляционных связей.

**Comment by bormolei** [comment]
Добрый день.


Относительно этой задачи, попробовал выполнить этот тест руками. Тест не
прошел. При попытке добавить корпус возникает Exception , т.к. в поле ВУЗ
берется полное название, а не краткое, из-за этого заполнение формы не
возможно.


Спасибо.

Комаров Виктор.


ср, 5 июн. 2019 г. в 09:55, Юрий Силенок <notifications@github.com>:

**Comment by YuriSilenok** [comment]
Могу предположить что на данный момент  эта проблема решена.
![image](https://user-images.githubusercontent.com/14871471/59703651-02bcde00-9203-11e9-9c22-16b34c60a8f1.png)
думаю Вам нужно выполнить ряд команд.

```
git checkout Testing
git pull
git checkout task-1007
git pull
git merge Testing
```

Это позволит Вам получить актуальные изменения.

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу
