### ISSUE TITLE
Этап разработки для спринта 3. 17-ИДбо-3а

### ISSUE THREAD

**Issue by ivshr** [Students-of-the-city-of-Kostroma/Student-timetable#1012]
Разработка функционала для формы Вид занятия. 
Реализовать функцию  Добавить
Реализовать функцию Изменить
Реализовать функцию Удалить (+Вопрос при удалении), 
Реализовать функцию сортировки, 
Разработка подсчета количества строк в таблице
Привести имена столбцов в соответствие с программой
Выполнить в соответствии с [планом](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/839)

**Comment by YuriSilenok** [comment]
Закрыто по не активности
