### ISSUE TITLE
Разработать сценарии тестирования пригодных для автоматизации модульным тестированием метода Update(Model model) сущности Корпус

### ISSUE THREAD

**Issue by DenisSavelev** [Students-of-the-city-of-Kostroma/Student-timetable#1016]
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)

**Comment by YuriSilenok** [comment]
С чего вдруг поднят этот таск?

**Comment by DenisSavelev** [comment]
> С чего вдруг поднят этот таск?
Для выполнения Лабораторной работы №4

**Comment by YuriSilenok** [comment]
понятно, сейчас я закрою эту лавочку.

**Comment by DenisSavelev** [comment]
> понятно, сейчас я закрою эту лавочку.

А что тогда делать?

**Comment by YuriSilenok** [comment]
напишите письмо, для должников у меня особенные задания

**Comment by DenisSavelev** [comment]
> напишите письмо, для должников у меня особенные задания

Написал

**Comment by YuriSilenok** [comment]
Видел, в скором времени выдам задание.

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
