### ISSUE TITLE
Невозможно добавить корректный корпус

### ISSUE THREAD

**Issue by bolotovaksenya** [Students-of-the-city-of-Kostroma/Student-timetable#1017]
Название ветки: 17-ИСбо-2а-7
Баг воспроизводиться в v0.20-Testing
Шаги реализации бага:
1. Открыть справочник "Корпуса"
2. Нажать "добавить"
3. В поле "Название корпуса ввести"Е"
4. В поле "ВУЗ" ввести "КГУ"
5. В поле "Адрес" ввести "Малышковская 4"
6. В поле "Телефон" ввести "89621843133"
7. В поле "Примечание" ввести "ИАСТ"
8. Нажать "сохранить"

**Ожидаемый результат:** Добавление экземпляра в таблицу "Корпус"
**Фактический результат:** 
Появление предупреждения о невозможности добавления экземпляра
![image](https://user-images.githubusercontent.com/47633289/59096552-bc729f80-8923-11e9-9cb0-e6f2ec2f7774.png)
#1033

**Comment by YuriSilenok** [comment]
Что я должен с этим сделать?

**Comment by YuriSilenok** [comment]
из этого бага непонятно почему корпус не добавляется.
уточните ожидаемый резцльтат

**Comment by YuriSilenok** [comment]
в каком релизе вы нашли этот баг?

**Comment by bolotovaksenya** [comment]
@YuriSilenok , v0.20-Testing

**Comment by halfer4444** [comment]
@YuriSilenok 
Что делать, если баг не воспроизводится?

**Comment by YuriSilenok** [comment]
Как вы получили исполняемый файл на котором проводили тестирование?

**Comment by YuriSilenok** [comment]
Или даже так, вы проводили тестирование в релизе указанном в баге?

**Comment by halfer4444** [comment]
@YuriSilenok  В ветке 17-исбо-2а-7 взял исполняемый файл. Произвел шаги реализации бага, но баг не появился. И как посмотреть какой релиз у исполняемого файла?

**Comment by YuriSilenok** [comment]
Теперь дела не так обстаят.  Вам не нужно лезть в ветку спринта какой-то команды. 
У нас есть релизы. Смотрите ярлык releases
![image](https://user-images.githubusercontent.com/14871471/60441412-f6377d00-9c27-11e9-94c9-a12177ce446b.png)
Вам нужен самый первый zip файл, в релизе v0.20-Testing он называется 1078.zip . его скачиваете, распаковываете, запускаете и тестируете.
![image](https://user-images.githubusercontent.com/14871471/60441484-2121d100-9c28-11e9-9f3d-cf5df2b9bba3.png)

**Comment by halfer4444** [comment]
@YuriSilenok Я, возможно, знаю, в чем проблема, но как зайти в схему с таблицами, чтобы поменять направления связей? Связь идет от University к Enclousers, а должна быть наоборот.
![Безымянный](https://user-images.githubusercontent.com/52164390/60528232-a4acf200-9cfc-11e9-970e-cd658a58bae9.png)

**Comment by YuriSilenok** [comment]
Связи между таблицами реализуются [здесь](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/Testing/LibOfTimetableOfClasses/RefData.cs)

**Comment by YuriSilenok** [comment]
@halfer4444 я не понимаю что я должен сделать с этой задачей, зачем она на мне висит?

**Comment by YuriSilenok** [comment]
снята по бездействию
