### ISSUE TITLE
Автоматизировать unit-тесты для класса Logs

### ISSUE THREAD

**Issue by Mikleproxorov** [Students-of-the-city-of-Kostroma/Student-timetable#1018]
#978  [Сценарий](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=1813879881) 
GetInfo, GetError

#955  план

**Comment by YuriSilenok** [comment]
имеется ввиду автоматизация сценариев тестирования или разработка сценариев тестирования?

**Comment by Mikleproxorov** [comment]
Автоматизация. Исправил.

**Comment by YuriSilenok** [comment]
описание должно содержать ссылку на таск в котором были разработаны эти сценарии тестирования

**Comment by YuriSilenok** [comment]
> #956 план

это не план
