### ISSUE TITLE
Разработать сценарии тестирования формы Вид занятия

### ISSUE THREAD

**Issue by MasterDesigner** [Students-of-the-city-of-Kostroma/Student-timetable#1020]
Этап тестирования https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/842
[Сценарий](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=812383542)
[Разработка функционала](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/1021) (Story)

**Comment by YuriSilenok** [comment]
- атрибуты?
- зачем ссылка на план тестирования которая на самом деле ведет на план спринта?
- где ссылка на тестируемую Story?

**Comment by MasterDesigner** [comment]
> * атрибуты?

Не очень понимаю что подразумевается под атрибутами
> * зачем ссылка на план тестирования которая на самом деле ведет на план спринта?

Опечатка, исправил 
> * где ссылка на тестируемую Story?

Если под тестируемой Story подразумевается план разработки, то также исправил

**Comment by YuriSilenok** [comment]
после цитаты нужно отступать еще одну строку

**Comment by MasterDesigner** [comment]
> после цитаты нужно отступать еще одну строку

Исправил, атрибуты изначально были, но по неведомой причине исчезли, вернул

**Comment by YuriSilenok** [comment]
> Если под тестируемой Story подразумевается план разработки, то также исправил

[ЛР01](https://docs.google.com/document/d/1k8ILnmYVi3Cz-mTge3h6RI0OV4DbAHviQseScRRpUxI/edit#heading=h.sta96g3ennf1)
Достаточно ли описания?

**Comment by MasterDesigner** [comment]
> > Если под тестируемой Story подразумевается план разработки, то также исправил
> 
> [ЛР01](https://docs.google.com/document/d/1k8ILnmYVi3Cz-mTge3h6RI0OV4DbAHviQseScRRpUxI/edit#heading=h.sta96g3ennf1)
> Достаточно ли описания?

Да, благодарю, я честно ставил метки, но они не остались

**Comment by YuriSilenok** [comment]
> > > Если под тестируемой Story подразумевается план разработки, то также исправил
> > 
> > 
> > [ЛР01](https://docs.google.com/document/d/1k8ILnmYVi3Cz-mTge3h6RI0OV4DbAHviQseScRRpUxI/edit#heading=h.sta96g3ennf1)
> > Достаточно ли описания?
> 
> Да, благодарю, я честно ставил метки, но они не остались

Это ни как не скажется на оценке. Это всего лишь замечание которые не игнорируются.

**Comment by MasterDesigner** [comment]
> > > > Если под тестируемой Story подразумевается план разработки, то также исправил
> > > 
> > > 
> > > [ЛР01](https://docs.google.com/document/d/1k8ILnmYVi3Cz-mTge3h6RI0OV4DbAHviQseScRRpUxI/edit#heading=h.sta96g3ennf1)
> > > Достаточно ли описания?
> > 
> > 
> > Да, благодарю, я честно ставил метки, но они не остались
> 
> Это ни как не скажется на оценке. Это всего лишь замечание которые не игнорируются.

Хорошо, теперь все правильно?

**Comment by YuriSilenok** [comment]
- для чего в этой задаче ссылка на план спринта?
- для чего ссылка на этап разработки?

**Comment by MasterDesigner** [comment]
> * для чего в этой задаче ссылка на план спринта?

В соответствии с планом, который вы рисовали, она лишняя, сейчас уберу

> * для чего ссылка на этап разработки?

В соответствии с этим же планом ссылка также лишняя, нужны только ссылки на этап тестирования и разработку функционала

**Comment by YuriSilenok** [comment]
> В соответствии с этим же планом ссылка также лишняя, нужны только ссылки на этап тестирования и разработку функционала

На Story (разработку функционала) когда ожидать ссылку?

**Comment by MasterDesigner** [comment]
> > В соответствии с этим же планом ссылка также лишняя, нужны только ссылки на этап тестирования и разработку функционала
> 
> На Story (разработку функционала) когда ожидать ссылку?

Сегодня тимлид его создаст и она появится

**Comment by YuriSilenok** [comment]
Что-то я сценарии найти не могу. Какой у них Test ID?

**Comment by MasterDesigner** [comment]
> Что-то я сценарии найти не могу. Какой у них Test ID?

Сценарий вот https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=812383542
Только из него pre condition исчез, не понимаю кто удалил, придется заново писать

**Comment by YuriSilenok** [comment]
Ссылка на сценарии есть и так в описании. 
Я просил Test ID указать

**Comment by MasterDesigner** [comment]
Правильно ли я понимаю, что нужно создать на гитхабе отдельный таск для каждого сценария?
На данный момент Test ID:
872
874
876
997

**Comment by YuriSilenok** [comment]
В данном случае вы перечислили test suite. Все эти сценарии были написаны одним человеком?

Почему у этих сюитов такая нумерация?

**Comment by MasterDesigner** [comment]
Да, одним человеком.

Нумерация в соответствии с созданными тасками по тестированию на гитхабе.

**Comment by YuriSilenok** [comment]
номера создаются в соответствии с тасками разработку тестовых сценариев. Это значит что сценарий получает номер в процессе написания, а не в процессе тестирования.

**Comment by MasterDesigner** [comment]
Исправил, теперь номера следующие:
1040
1042
1043
1044

**Comment by MasterDesigner** [comment]
> номера создаются в соответствии с тасками разработку тестовых сценариев. Это значит что сценарий получает номер в процессе написания, а не в процессе тестирования.

Прошу перепроверить сценарий

**Comment by MasterDesigner** [comment]
Прошло 24 часа, напоминаю о просьбе проверить сценарий

**Comment by YuriSilenok** [comment]
24 часа работает с письмами. С задачами работает другое правило. Нужно задачу повесить на того, кто должен с ней поработать.

**Comment by YuriSilenok** [comment]
Добрый день.

> 24 часа работает с письмами. С задачами работает другое правило. Нужно задачу повесить на того, кто должен с ней поработать.

Дополнение. Семестр кончилась и это значит что время для проверки Ваших работ закончилось. Это значит что я буду проверять Ваши работы, но только тогда, когда у меня будет на это время.

Спасибо.

**Comment by YuriSilenok** [comment]
- ожидаемый результат прописывается для конкретного шага. Необходимо его указывать.
- сценарии избыточны, но ничего страшного

в остальном все нормально.

**Comment by MasterDesigner** [comment]
> * ожидаемый результат прописывается для конкретного шага. Необходимо его указывать.

Исправил, прошу проверить

**Comment by YuriSilenok** [comment]
- неправильная нумерация в Test ID
- если требуется ввести значение, то в сценарии пишется какое именно значение
- начиная с теста task-1020-3 перенести шаги из прекондишена в степы

**Comment by MasterDesigner** [comment]
> * неправильная нумерация в Test ID
> * если требуется ввести значение, то в сценарии пишется какое именно значение
> * начиная с теста task-1020-3 перенести шаги из прекондишена в степы

Нумерацию исправил
Значения, по-моему, везде написаны
Не понимаю зачем нужна из прекондишена в степы переносить, ведь в прекондишине мы выполняем действия до степов?

**Comment by YuriSilenok** [comment]
> Не понимаю зачем нужна из прекондишена в степы переносить, ведь в прекондишине мы выполняем действия до степов?

В прекондишене указывается состояние системы.Например, таблица ВУЗ имеет не менее одной записей. Например если тест направлен на проверку создания института, в котором обязательно должен быть указан существующий ВУЗ. В прикондишене могут быть указаны шаги, но это ооооочень редкая ситуация и распространение этой традиции в сценариях я не смог вовремя присечь. Теперь туда запихивают все что не поподя, лишь бы ожидаемый результат не прописывать.

Оставляем так, зачтено
