### ISSUE TITLE
Функциональные требования к форме "Вид занятия"

### ISSUE THREAD

**Issue by ivshr** [Students-of-the-city-of-Kostroma/Student-timetable#1021]
Форма "Вид занятия" (TypesOfOccupations) должна содержать следующие столбцы:
  - Вид занятия (FullName)
  - Краткий вид занятия (ShortName)

![image](https://user-images.githubusercontent.com/47637247/59175795-84f03700-8b5f-11e9-94be-962a8fde5d44.png)

На форме должны быть реализованы следующие кнопки:

  - Добавить
При нажатии на кнопку "Добавить" должна открываться форма "Добавление вида занятия"

![image](https://user-images.githubusercontent.com/47637247/59175826-a0f3d880-8b5f-11e9-9aaf-1890b4416b10.png)

  - Изменить 
Кнопка "Изменить" должна быть доступна для нажатия, только при условии, что создана хотя бы одна запись вида занятия. Кнопка активируется нажатием на любую из созданных записей вида занятия. При нажатии на кнопку "Изменить" должна открываться форма "Изменение вида занятия"

![image](https://user-images.githubusercontent.com/47637247/59176059-90902d80-8b60-11e9-9ece-342495063308.png)

  - Удалить 
Кнопка "Удалить" должна быть доступна для нажатия, только при условии, что создана хотя бы одна запись вида занятия. Кнопка активируется нажатием на любую из созданных записей вида занятия. При нажатии на кнопку "Удалить" появляется предупреждающее сообщение "Удалить ***?"  и две кнопки: подтверждающая кнопка "Ок" при нажатии на которую, запись вида занятия - удаляется и отменяющая кнопка "Отмена", при нажатии на которую, предупреждающее сообщение закрывается, а запись вида занятия - не удаляется.

Требования к функционалу формы "Добавление вида занятия":

1. Форма должна содержать два поля для ввода информации: "Полное название вида занятия" (FullName) и "Краткое название вида занятия" (ShortName).
2. На форме должны быть реализованы следующие кнопки: 

   - Создать и закрыть
     - Если поля "Полное название вида занятия" и  "Краткое название вида занятия" заполнены, то при нажатии на кнопку "Создать и закрыть" данные должны добавиться на форму "Вид занятия", а форма "Добавление вида занятия" должна закрыться

      - Если поля "Полное название вида занятия" и  "Краткое название вида занятия" не заполнены, то при нажатии на кнопку "Создать и закрыть" должно появиться сообщение "Заполните все поля"
   - Создать и очистить
      - Если поля "Полное название вида занятия" и  "Краткое название вида занятия" заполнены, то при нажатии на кнопку "Создать и очистить" данные должны добавиться на форму "Вид занятия", форма "Добавление вида занятия" должна остаться открытой, а поля "Полное название вида занятия" и  "Краткое название вида занятия" должны очиститься

      - Если поля "Полное название вида занятия" и  "Краткое название вида занятия" не заполнены, то при нажатии на кнопку "Создать и очистить" должно появиться сообщение "Заполните все поля"

   - Отмена
      - При нажатии на кнопку "Отмена" форма "Добавление вида занятия" должна закрыться
3. Если на форме создаётся запись вида занятия с таким же "кратким названием", как у уже созданного, то такая запись не должна добавляться
4. Если на форме создаётся запись вида занятия с таким же "полным названием", как у уже созданного, то такая запись не должна добавляться

Требования к функционалу формы "Изменение вида занятия":
1. Форма должна содержать два поля для ввода информации: "Полное название вида занятия" (FullName) и "Краткое название вида занятия" (ShortName).

2. На форме должны быть реализованы следующие кнопки: 

   - Сохранить

      - Если были сделаны изменения, то при нажатии на кнопку "Сохранить" форма "Изменение вида занятия" должна закрываться, а на форме "Вид занятия" в столбцах "Вид занятия" и "Краткий вид занятия" должна появиться обновлённая информация. 

      - Если изменения не были сделаны, то при нажатии на кнопку "Сохранить" форма "Изменения вида занятия" закрывается, а данные на форме "Вид занятия" не меняются
    - Отмена
      - При нажатии на кнопку "Отмена" форма "Изменение вида занятия" должна закрыться
3. Должна быть возможность редактирования обоих полей: "Полное название вида занятия" и "Краткое название вида занятия"
4. Если при изменении поля "Краткое название вида занятия" было указано такое же "краткое название", как у уже созданной записи, то такого изменения не должно происходить
5. Если при изменении поля "Полное название вида занятия" было указано такое же "полное название", как у уже созданной записи, то такого изменения не должно происходить

На форме "Вид занятия" должна быть реализована сортировка по времени создания записи. При нажатии на один из столбцов формы: "Вид занятия" или "Краткий вид занятия" записи должны сортироваться в порядке убывания, при повторном нажатии - в порядке возрастания.

При изменении ширины формы - столбцы должны пропорционально сужаться и расширяться.

Реализовать в соответствии [этапом разработки](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/1012)

**Comment by YuriSilenok** [comment]
Этот функционал реализован?

**Comment by ivshr** [comment]
На данный момент большая часть функционала реализована

**Comment by YuriSilenok** [comment]
- я не вижу что бы эту стори ссылался запрос на слияние?
- одна Story реализуется одним человеком. Это правило выполняется?
- Это план или стори?

**Comment by ivshr** [comment]
> - я не вижу что бы эту стори ссылался запрос на слияние?

Исправили

> - одна Story реализуется одним человеком. Это правило выполняется?

Да, каждая задача на разработку реализуется одним человеком

> - Это план или стори?

Это задача на разработку функциональности с указанием основных требований

**Comment by YuriSilenok** [comment]
Стори реализовано, замечания устранены
