### ISSUE TITLE
При проведении мануального тестирования формы "Кафедра" были найдены баги.

### ISSUE THREAD

**Issue by ZhizhikinIvan** [Students-of-the-city-of-Kostroma/Student-timetable#1024]
Этап тестирования #961
Задача по мануальному тестированию #967

**Баги:**
1. Данные, вводимые в строку "Зав. кафедры", не должны начинаться с "-".
2. В строке "Зав. кафедры", не может содержаться подряд два символа "-". 
3. В строках "Краткое название" и "Полное название", можно вводить цифры (1234 и т.д.) и различные символы (? / \ , и т.д.).
4. В строках "Зав. кафедры" и "Институт", можно вводить цифры (1234 и т.д.) и различные символы (? / \ , и т.д.).
5. Допустимое количество вводимых символов в строке "Краткое название", не должно быть больше, чем в "Полное название". 
6. В строках "Краткое название", "Полное название" и "Институт", можно добавлять не ограниченное кол-во пробелов.
7. Данные, вводимые в строках "Краткое название", "Полное название" и "Институт", не могут начинаться с пробела.

![Баги](https://user-images.githubusercontent.com/47943099/59146981-e26c7280-89fd-11e9-9a9d-66c4ceb5ea83.jpg)

**Comment by YuriSilenok** [comment]
К прочтению
https://m.habr.com/ru/company/docsvision/blog/264163/

**Comment by YuriSilenok** [comment]
Зачем ссылка на план?

**Comment by sidelong44** [comment]
@ZhizhikinIvan 

> https://m.habr.com/ru/company/docsvision/blog/264163/

Почитай, в свободное время поправь

**Comment by sidelong44** [comment]
Ошибки исправлены
