### ISSUE TITLE
Разработать сценарии unit-тестов модели ВУЗ LR-04

### ISSUE THREAD

**Issue by abramovaalina** [Students-of-the-city-of-Kostroma/Student-timetable#1025]
Story ВУЗ #176 
[Таблица сценариев](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)

**Comment by YuriSilenok** [comment]
Метка лабораторной

**Comment by YuriSilenok** [comment]
Ссылка на story?

**Comment by abramovaalina** [comment]
Сценарий добавлен в [таблицу](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)

**Comment by YuriSilenok** [comment]
- все важные ссылки добавляются в описание
- все сценарии тестирования пишутся в общую таблицу. Она есть в папке практика или других задачах такого типа.

**Comment by abramovaalina** [comment]
Исправила

**Comment by YuriSilenok** [comment]
Вы выбрали пустой таск в качестве стори, в нем нет никакого описания. Обратите внимание на задачу #176 и метки которые у неё есть.

**Comment by abramovaalina** [comment]
указала таск 176.

**Comment by YuriSilenok** [comment]
сценарии должны содержать конкретные значения

**Comment by abramovaalina** [comment]
поправила сценарии

**Comment by YuriSilenok** [comment]
зачтено
