### ISSUE TITLE
Проверка всех сценариев и юнит тестов сущьности "Ученые знания" + Добавление сценариев на ограничения.

### ISSUE THREAD

**Issue by GubanovAndrey** [Students-of-the-city-of-Kostroma/Student-timetable#1029]
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=1153322464)
Добавлены сценарии на проверку ограничений методов Добавить и Изменить 
task-361-4, task-361-5, task-363-3, task-363-4
Все юнит тесты соответствуют сценариям.
Задачи на тестирование с меткой Story не найдены.

**Comment by GubanovAndrey** [comment]
Здравствуйте 

Прошу проверить ЛР4.1

Спасибо

**Comment by YuriSilenok** [comment]
Претерпели ли автотесты изменения?

**Comment by GubanovAndrey** [comment]
Нет, не претерпели.

**Comment by YuriSilenok** [comment]
Понять не могу, почему появилась эта задача?

**Comment by YuriSilenok** [comment]
а, все понял, по поводу вопроса о претерпевании автотестов.
Если появились новые сценарии, значит они должны быть автоматизированы.
Эта задача появилась из-за отсутствия покрытия автотестастами функциональности в классе CTitle.
Желтым указана непокрытая часть кода, для них и нужны тесты.
![image](https://user-images.githubusercontent.com/14871471/59295055-71da8580-8c8b-11e9-87b0-09056f5cfdbb.png)
![image](https://user-images.githubusercontent.com/14871471/59295127-98002580-8c8b-11e9-8971-7473b1511294.png)

**Comment by GubanovAndrey** [comment]
Понял , спасибо. Сделаю

**Comment by YuriSilenok** [comment]
Если по запросу не будет активности 7 дней, задача будет снята.

**Comment by YuriSilenok** [comment]
закрыта по неактивности
