### ISSUE TITLE
Реализовать функционал кнопок "Создать и закрыть" и "Создать и очистить" для формы "Добавить дисциплину"

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#103]
При реализации функционала использовать контроллер. 
Контроллер находятся в классе Controllers

**Comment by yuliagolubevaa5** [comment]
Здравствуйте, @YuriSilenok .
Дело в том, что при нажатии кнопок у меня не записываются добавленные дисциплины в общий список дисциплин и я не знаю, как это исправить.
Подскажите, пожалуйста.
Заранее благодарю.
![image](https://user-images.githubusercontent.com/47320351/53742220-328ce380-3ea9-11e9-9eaa-dda51581978d.png)

**Comment by YuriSilenok** [comment]
Так как таблице не указан ресурс. Вы можете это прописать в конструкторе форма Дисциплины 
`dataGriedView1.Source = Controllers.CDiscipline.Select();`
Должно по идее начать работаь после этого.

**Comment by yuliagolubevaa5** [comment]
Должно по идее начать работаь после этого.
Спасибо, теперь действительно работает. Однако в форме Дисциплины теперь появились поля ID, Code, Name вместо русскоязычных "Код" и "Наименование". Мне нужно это исправлять?
![image](https://user-images.githubusercontent.com/47320351/53822306-8b7b7b00-3f80-11e9-8cd2-01d3605019f0.png)

**Comment by YuriSilenok** [comment]
Нет. Не нужно.На это потом баг поднимем.

**Comment by YuriSilenok** [comment]
Улучшает #77

**Comment by YuriSilenok** [comment]
Забыл закрыть.
Давно было зачтено.
