### ISSUE TITLE
Исправить сбои в автотестах расположенных в файле UT_Insert_CTeacher

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#1032]
- Составить тесты методом белого ящика и [предоставить отчет](https://docs.google.com/document/d/1H6353mZjLjMmCq-1A7IrnKdwBUQXyg81wjauXlad3XY/edit)
- Обновить [сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit) указам у заголовка тест-комплекта ссылку на гугл документ с исследованием по белому ящику.
- Автоматизировать полученные сценарии
- Перенести комментарии методов в шаблон `///`
- Комментарии должны совпадать с описанием тестового сценария

**Comment by YuriSilenok** [comment]
зачтено

**Comment by FvckNeighbors** [comment]
Задача снята по причине бездействия.

**Comment by YuriSilenok** [comment]
Зачтено как ЛР04.2

**Comment by YuriSilenok** [comment]
```

Failed   Task_246_1
Error Message:
 Assert.AreEqual failed. Expected:<True>. Actual:<False>. 
Stack Trace:
   at UnitTestOfTimetableOfClasses.UT_Insert_CTeacher.Task_246_1() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Insert_CTeacher.cs:line 43
Failed   Task_246_2
Error Message:
 Assert.AreEqual failed. Expected:<True>. Actual:<False>. 
Stack Trace:
   at UnitTestOfTimetableOfClasses.UT_Insert_CTeacher.Task_246_2() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Insert_CTeacher.cs:line 62
Passed   Task_246_3
Failed   Task_246_4
Error Message:
 Assert.AreEqual failed. Expected:<True>. Actual:<False>. 
Stack Trace:
   at UnitTestOfTimetableOfClasses.UT_Insert_CTeacher.Task_246_4() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Insert_CTeacher.cs:line 100
Failed   Task_246_5
Error Message:
 Assert.AreEqual failed. Expected:<True>. Actual:<False>. 
Stack Trace:
   at UnitTestOfTimetableOfClasses.UT_Insert_CTeacher.Task_246_5() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Insert_CTeacher.cs:line 121
Failed   Task_246_6
Error Message:
 Assert.AreEqual failed. Expected:<True>. Actual:<False>. 
Stack Trace:
   at UnitTestOfTimetableOfClasses.UT_Insert_CTeacher.Task_246_6() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Insert_CTeacher.cs:line 142
Passed   Task_246_7
```

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1032 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1032 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1032 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1032 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1032 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1032 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1032 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1032 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1032 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1032 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1032 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1032 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1032 давно не было активности

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by YuriSilenok** [comment]
Устаревшая ветка для этой задачи будет удалена в ближайшее время

**Comment by YuriSilenok** [comment]
> Устаревшая ветка для этой задачи будет удалена в ближайшее время

Ветка удалена

**Comment by NordScandinavian** [comment]
Прошу не снимать задачи по не активности, отчёты будут выложены 25.08

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by NordScandinavian** [comment]
@YuriSilenok, прошу вернуть задачу, в ней была активность 19 часов назад.
прошу проверить в пул реквесте отчёты, необходимое кол-во аппрувов есть.

**Comment by YuriSilenok** [comment]
Предоставьте скрин активности между 30.08.2020 17:44 и 01.09.2020 17:44
![image](https://user-images.githubusercontent.com/14871471/91957005-225bfb80-ed0e-11ea-8085-a5375a1fc2ed.png)
Сможете?

**Comment by YuriSilenok** [comment]
я задачу вам верну, но скрин жду

**Comment by NordScandinavian** [comment]
Не могу найти тот коммент, от которого  я отталкивался. указывая 19 часов с последней активности.
Самый близкий по времени коммент

![image](https://user-images.githubusercontent.com/47521360/92140070-507a3200-ee19-11ea-84de-3c5ddbca9745.png)
На скрине не могу показать время, но он был оставлен в 14.50 1.08

**Comment by YuriSilenok** [comment]
То есть активность была после того, как с вас сняли задачу.

**Comment by NordScandinavian** [comment]
Нет, задача была снята 1.08 в 17.44, а последняя активность(на то время) была в 14.50 1.08

**Comment by YuriSilenok** [comment]
Да, возможно это было связано с одним багом, связанным с часовым поясом. Сейчас он исправлен.

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности. Активность по основной задаче #1032 составляет 17 дней. Ветка отсутствует. Запрос отсутствует. Нет запросов, которые должен проверить преподаватель

**Comment by NordScandinavian** [comment]
Прошу не снимать задачу по неактивности. Болею, не мог сесть за задачи, не позволяло состояние.

**Comment by YuriSilenok** [comment]
Задача с Вас  снята, так как по ней давно не было активности. Активность по основной задаче #1032 составляет 3 дней. Активность в ветке issue-1032 составляет 3 дней. Активность по запросу #1356 составляет 2 дней. Нет запросов, которые должен проверить преподаватель

**Comment by YuriSilenok** [comment]
Ветка issue-1032 удалена

**Comment by YuriSilenok** [comment]
Задача с Вас  снята, так как по ней давно не было активности. Активность по основной задаче #1032 составляет 43 дней. Активность в ветке issue-1032 составляет 33 дней. Активность по запросу #1356 составляет 14 дней. Нет запросов, которые должен проверить преподаватель

**Comment by YuriSilenok** [comment]
Ветка issue-1032 удалена
