### ISSUE TITLE
Ликвидация долгов за 4 семестр

### ISSUE THREAD

**Issue by bolotovaksenya** [Students-of-the-city-of-Kostroma/Student-timetable#1033]
#1017
#1034 
#1035
#1037 
#1038
#1039
#1041 
#1045
#1046

**Comment by YuriSilenok** [comment]
- Указать во все баги в ком релизе был найден баг

**Comment by YuriSilenok** [comment]
- баги должны ссылаться на задачу ликвидации

**Comment by YuriSilenok** [comment]
Указать в каждом баге резил в котором он был найден

**Comment by YuriSilenok** [comment]
Зачтено за 3 спринт
