### ISSUE TITLE
В справочнике "Дисциплина" можно добавить поля с некорректными данными

### ISSUE THREAD

**Issue by bolotovaksenya** [Students-of-the-city-of-Kostroma/Student-timetable#1034]
Баг воспроизводиться в v0.20-Testing
Шаги реализации бага:
1.Открыть справочник "Дисциплина"
2. Нажать "создать"
![image](https://user-images.githubusercontent.com/47633289/59157910-caf3bf00-8abb-11e9-9191-70c1c942d1c5.png)
3. В поле "Полное название дисциплины" ввести 147
4. В поле "Краткое название дисциплины" ввести 222
5. В поле "Цикл дисциплин" ввести 15
![image](https://user-images.githubusercontent.com/47633289/59157914-d2b36380-8abb-11e9-97fa-3cbe9afb6b63.png)
6. Нажать "создать и закрыть"
Ожидаемый результат:
Новая дисциплина не создастся и появится форма с предупреждением
Фактический результат:
![image](https://user-images.githubusercontent.com/47633289/59157916-dcd56200-8abb-11e9-9c77-64312a37be9b.png)
#1033

**Comment by YuriSilenok** [comment]
Задача снята

**Comment by YuriSilenok** [comment]
Не вешайте задачу на меня, она еще не готова
