### ISSUE TITLE
В справочнике "Группы" можно ввести нулевое количество студентов

### ISSUE THREAD

**Issue by bolotovaksenya** [Students-of-the-city-of-Kostroma/Student-timetable#1035]
Название ветки: 17-ИСбо-2б-7
Баг воспроизводиться в v0.20-Testing
Шаги реализации бага:
1.Открыть справочник"группы"
2. Нажать "добавить"
3. В поле "Группа" ввести "00-ААаа-0а"
4. В поле "Семестр" ввести "1"
5. В поле "Смена" ввести "1"
6. В поле "Студентов" ввести "0"
7. В поле "Пар/день min" ввести "0"
8. В поле "Пар/день max" ввести "0"
9. В поле "Выходные" ввести "Воскресенье"
10. Нажать "сохранить"
![image](https://user-images.githubusercontent.com/47633289/59158169-31c6a780-8abf-11e9-8157-4f5ea7c841d3.png)
Ожидаемый результат:
Новая группа не создастся и появится форма с предупреждением об ограничении значения минимального кол-ва студентов
Фактический результат: 
![image](https://user-images.githubusercontent.com/47633289/59158175-460aa480-8abf-11e9-90b5-eb102f875683.png)
#1033

**Comment by YuriSilenok** [comment]
> Новая группа не создастся и появится форма с предупреждением

Предупреждение о чем? о каком ограничении ?

**Comment by bolotovaksenya** [comment]
@YuriSilenok, ограничение о значении минимального количества студентов

**Comment by YuriSilenok** [comment]
> @YuriSilenok, ограничение о значении минимального количества студентов

Об этом всём нужно писать

**Comment by YuriSilenok** [comment]
требуется ретест в ветке Testing

**Comment by bolotovaksenya** [comment]
@YuriSilenok , ретест провела, сейчас этот баг в ветке Testing не воспроизводится.
