### ISSUE TITLE
Исправить сбои в автотестах расположенных в файле UT_Update_CTeacher

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#1036]
- Составить тесты методом белого ящика и [предоставить отчет](https://docs.google.com/document/d/1H6353mZjLjMmCq-1A7IrnKdwBUQXyg81wjauXlad3XY/edit)
- Обновить [сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit) указам у заголовка тест-комплекта ссылку на гугл документ с исследованием по белому ящику.
- Автоматизировать полученные сценарии
- Перенести комментарии методов в шаблон `///`
- Комментарии должны совпадать с описанием тестового сценария

**Comment by YuriSilenok** [comment]
зачтено

**Comment by DenisSavelev** [comment]
> зачтено

Когда можно поставить зачёт в зачётную книжку?

**Comment by YuriSilenok** [comment]
как сможете, в ведомость в любом случае поставлю

**Comment by DenisSavelev** [comment]
Завтра, можно как-нибудь?

пт, 21 июн. 2019 г. в 23:51, Юрий Силенок <notifications@github.com>:

**Comment by YuriSilenok** [comment]
точное время не знаю, когда я буду в КГУ

**Comment by FvckNeighbors** [comment]
Задача снята по отсутствию активности.

**Comment by Proffet78** [comment]
Начал выполнение

**Comment by Proffet78** [comment]
выполнено

**Comment by YuriSilenok** [comment]
@NordScandinavian пожалуйста, поясните, что значит закрашенная ячейка в бэклоге у текущей не закрытой задачи?
![image](https://user-images.githubusercontent.com/14871471/70502905-236f4c00-1b33-11ea-9fbf-b22505e17deb.png)

**Comment by YuriSilenok** [comment]
@Proffet78 почему задача на вас висит, вы еще над ней работаете?

**Comment by Proffet78** [comment]
@YuriSilenok , исправил, нет я над ней не работаю, я жду одобрения выполнения работы и, как следствие, закрытие последней лабораторной работы по вашему предмету!

**Comment by Proffet78** [comment]
@YuriSilenok , скажите, ЛР зачтена?

**Comment by Proffet78** [comment]
Скажите пожалуйста, в тоге ЛР зачтена? Просто это последняя работа и она сделана уже больше чем 10 дней, а в журнале до сих пор стоит не закрытой! Очень хочется закрыть долг!

Спасибо!

**Comment by YuriSilenok** [comment]
Ваше слияние в ветку элита сломало автотесты,

восстановить ветку и справить последствия в ней, после предложить новый запрос на слияние

**Comment by Proffet78** [comment]
Начал исправлять

**Comment by Proffet78** [comment]
Выполнено!

**Comment by YuriSilenok** [comment]
зачтено

**Comment by YuriSilenok** [comment]
```
Failed   Task_247_1
Error Message:
 Assert.AreEqual failed. Expected:<True>. Actual:<False>. 
Stack Trace:
   at UnitTestOfTimetableOfClasses.UT_Update_CTeacher.Task_247_1() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Update_CTeacher.cs:line 20
Failed   Task_247_5
Error Message:
 Assert.AreEqual failed. Expected:<True>. Actual:<False>. 
Stack Trace:
   at UnitTestOfTimetableOfClasses.UT_Update_CTeacher.Task_247_5() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Update_CTeacher.cs:line 51
Failed   Task_247_6
Error Message:
 Assert.AreEqual failed. Expected:<True>. Actual:<False>. 
Stack Trace:
   at UnitTestOfTimetableOfClasses.UT_Update_CTeacher.Task_247_6() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Update_CTeacher.cs:line 79
Failed   Task_247_7
Error Message:
 Assert.AreEqual failed. Expected:<True>. Actual:<False>. 
Stack Trace:
   at UnitTestOfTimetableOfClasses.UT_Update_CTeacher.Task_247_7() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Update_CTeacher.cs:line 106
Failed   Task_247_8
Error Message:
 Assert.AreEqual failed. Expected:<True>. Actual:<False>. 
Stack Trace:
   at UnitTestOfTimetableOfClasses.UT_Update_CTeacher.Task_247_8() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Update_CTeacher.cs:line 135

```

**Comment by ssas18** [comment]
@YuriSilenok ,
![image](https://user-images.githubusercontent.com/47377817/86507855-10301080-bde4-11ea-880f-507cde71ea9d.png)
Возможно добавление преподавателей работает некорректно, так как даже преподавателей из RefData не добавляет по той же самой ошибке

**Comment by YuriSilenok** [comment]
> @YuriSilenok ,
> ![image](https://user-images.githubusercontent.com/47377817/86507855-10301080-bde4-11ea-880f-507cde71ea9d.png)
> Возможно добавление преподавателей работает некорректно, так как даже преподавателей из RefData не добавляет по той же самой ошибке

Поднимите баг, ссылку в чат.

**Comment by ssas18** [comment]
Юрий Викторович, баг до сих пор остался, переоткрывать #1288  ?

**Comment by YuriSilenok** [comment]
Вы в какой ветке это проверили?

**Comment by ssas18** [comment]
создал ветку 1036 и проверил

**Comment by YuriSilenok** [comment]
Нужно проверить в ветке dev, если там не воспроизводится, то смержите в вашу ветку ветку дев, если в дев воспроизводится, то переоткройте баг и дайте сценарий воспроизведения в нем со всеми скринами.

**Comment by ssas18** [comment]
@YuriSilenok  , После исправления бага ошибок в автотестах нет. мне все же заливать отчет или Вы мне выдадите мне
 другую задачу?

**Comment by YuriSilenok** [comment]
Вы уже начали делать, вы вполне можете закончить работу над белым ящиком и привести автотесты в соответствие с полученными тестами. Там могут и новые сбои вылезти. Мое пожелание продолжить, по право выбора за вами.

**Comment by ssas18** [comment]
> Вы уже начали делать, вы вполне можете закончить работу над белым ящиком и привести автотесты в соответствие с полученными тестами. Там могут и новые сбои вылезти. Мое пожелание продолжить, по право выбора за вами.

Понял, хорошо, продолжу

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1036 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1036 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1036 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1036 давно не было активности

**Comment by ssas18** [comment]
Прошу не удалять, т.к. жду проверки

**Comment by YuriSilenok** [comment]
Где метка приоритета?

**Comment by ssas18** [comment]
Прошу меня простить, но примерно сутки буду находиться в отъезде, по приезду будут исправлены все замечания

**Comment by ssas18** [comment]
@YuriSilenok  , я снова тут и очень жду Вашей проверки по #1309

**Comment by ssas18** [comment]
В данной задаче нет активности т.к жду проверки

**Comment by YuriSilenok** [comment]
так, я хотел связать активности в связанных задачах.
Сейчас этим займусь

**Comment by YuriSilenok** [comment]
Все, с завтрашнего утра к активности задачи будет приплюсовываться активность запроса. Тогда не будет нужны писать комментарии в основную задачу, что бы продлить ее активность, если не было коммитов.

**Comment by YuriSilenok** [comment]
[зачтено](https://docs.google.com/spreadsheets/d/1uBd4d3VvI4rYeuXkXmqLyEZSitS8K9pfVUDtM3i1Vg4/edit#gid=1274241490&range=O5)
