### ISSUE TITLE
В справочнике "Профиль подготовки" можно ввести некорректные данные

### ISSUE THREAD

**Issue by bolotovaksenya** [Students-of-the-city-of-Kostroma/Student-timetable#1037]
Название ветки:17-ИСбо-2б-7
Баг воспроизводиться в v0.20-Testing
Шаги реализации бага:
1. Открыть справочник "Профиль подготовки"
2.Нажать "добавить"
![image](https://user-images.githubusercontent.com/47633289/59158342-97b42e80-8ac1-11e9-818c-29d75b56f9ea.png)
3.В поле "Полное название профиля" ввести "12345678"
4.В поле "Краткое название профиля" ввести "12345678"
5.В поле "Шифр" выбрать "12о12о12"
6. Нажать "создать и закрыть"
![image](https://user-images.githubusercontent.com/47633289/59158362-e9f54f80-8ac1-11e9-8656-525897547298.png)
Ожидаемый результат:
Новая группа не создастся и появится форма с предупреждением
Фактический результат:
![image](https://user-images.githubusercontent.com/47633289/59158367-f8dc0200-8ac1-11e9-9cd3-effcc6dccd98.png)
#1033

**Comment by Proffet78** [comment]
Здравствуйте, @bolotovaksenya !

Почему данная задача была заасанина на меня?
 
Спасибо!

**Comment by venecon1** [comment]
В данной версии Testing данный баг не воспроизводиться, ввод цифр в поля Полное и краткое название запрещен.

**Comment by YuriSilenok** [comment]
Это значит что баг уже был исправлен, значит что текущий баг является дубликатом. Если найдёте оригинальный баг, зачту этот баг.

**Comment by YuriSilenok** [comment]
И если считаете что вы закончили работать над задачей, с себя её нужно снимать.

**Comment by venecon1** [comment]
Данный баг является оригинальным https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/796.

**Comment by YuriSilenok** [comment]
Зачтено
Duplicate of #796
