### ISSUE TITLE
В справочнике "Дисциплина" можно ввести одинаковое количество символов в полях "Полное название" и "Краткое название"

### ISSUE THREAD

**Issue by bolotovaksenya** [Students-of-the-city-of-Kostroma/Student-timetable#1038]
Название ветки:17-ИСбо-2б-7
Баг воспроизводиться в v0.20-Testing
Шаги реализации бага:
1.Открыть справочник "Дисциплина"
2.Нажать "добавить"
![image](https://user-images.githubusercontent.com/47633289/59159083-35f9c180-8acd-11e9-99e2-1c8e2a4dbbbe.png)
3.В поле "Полное название профиля" ввести "ааааа"
4.В поле "Краткое название профиля" ввести "ааааа"
5.В поле "Шифр" выбрать "12"
6. Нажать "создать и закрыть"
![image](https://user-images.githubusercontent.com/47633289/59159087-41e58380-8acd-11e9-8438-f41b9a678236.png)
Ожидаемый результат:
Новая группа не создастся и появится форма с предупреждением
Фактический результат:
![image](https://user-images.githubusercontent.com/47633289/59159091-4dd14580-8acd-11e9-8d3b-7ab1750766db.png)
#1033

**Comment by YuriSilenok** [comment]
в каком релизе найдено?

**Comment by bolotovaksenya** [comment]
@YuriSilenok , v0.20-Testing

**Comment by Proffet78** [comment]
Здравствуйте, @bolotovaksenya !

Почему данная задача была заасанина на меня?

Спасибо!

**Comment by YuriSilenok** [comment]
> v0.20-Testing

эту информацию нужно указать в описании бага

**Comment by Proffet78** [comment]
Здравствуйте, @YuriSilenok !

Прошу проверить выполнение ЛР3.2!

Спасибо

**Comment by YuriSilenok** [comment]
Зачтено
