### ISSUE TITLE
Некорректное название формы "Добавить Корпус"

### ISSUE THREAD

**Issue by bolotovaksenya** [Students-of-the-city-of-Kostroma/Student-timetable#1039]
Название ветки:17-ИСбо-2а-7
Баг воспроизводиться в v0.20-Testing
Шаги реализации бага:
1.Открыть справочник "Корпус"
![image](https://user-images.githubusercontent.com/47633289/59158599-f3cc8200-8ac4-11e9-963e-f9974c797c3b.png)
2. Нажать "Добавить"
Ожидаемый результат:
Появится форма с добавлением корпуса "Добавить корпус"
Фактический результат:
![image](https://user-images.githubusercontent.com/47633289/59159153-1dd67200-8ace-11e9-840c-1ac86539ada8.png)

#1099

**Comment by YuriSilenok** [comment]
если Вы занимаетесь задачей, то она должна висеть на Вас
![image](https://user-images.githubusercontent.com/14871471/59273056-04fdc600-8c60-11e9-906f-49b89cd6c05d.png)

**Comment by YuriSilenok** [comment]
@bolotovaksenya ретест в ветке Testing, если не воспроизводится сообщить и закрыть

**Comment by bolotovaksenya** [comment]
@YuriSilenok , проверила - более не воспроизводится.
