### ISSUE TITLE
Автоматизировать тестирование модульными тестами для метода Insert(Model model)  класса CAuditor

### ISSUE THREAD

**Issue by MasterDesigner** [Students-of-the-city-of-Kostroma/Student-timetable#104]
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)
[Диаграмма классов](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit)
[План разработки](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_102)

**Comment by YuriSilenok** [comment]
Добрый день.
- Обратите внимание на какой вопрос должен отвечать заголовок

В остальном замечаний нет.

Спасибо.

**Comment by YuriSilenok** [comment]
Зачтено
