### ISSUE TITLE
В справочнике "Преподаватели" невозможно выбрать поле "ученая степень"

### ISSUE THREAD

**Issue by bolotovaksenya** [Students-of-the-city-of-Kostroma/Student-timetable#1045]
Название ветки:17-ИСбо-2б-7
Баг воспроизводиться в v0.20-Testing
Шаги реализации бага:
1.Открыть справочник "Преподаватели"
![image](https://user-images.githubusercontent.com/47633289/59159250-6b071380-8acf-11e9-8d43-a47cb5700b67.png)
2. Нажать "Изменить"
Ожидаемый результат:
Заполнено поле "Ученое звание"
Фактический результат:
![image](https://user-images.githubusercontent.com/47633289/59159275-ca652380-8acf-11e9-8ee9-a513d2971cfd.png)

#1033

**Comment by YuriSilenok** [comment]
снято по не активности

**Comment by YuriSilenok** [comment]
@litdex зачтено
