### ISSUE TITLE
В справочнике "Преподаватели" невозможно выбрать поле "ученое звание"

### ISSUE THREAD

**Issue by bolotovaksenya** [Students-of-the-city-of-Kostroma/Student-timetable#1046]
Название ветки:17-ИСбо-2б-7
Баг воспроизводиться в v0.20-Testing
Шаги реализации бага:
1.Открыть справочник "Преподаватели"
![image](https://user-images.githubusercontent.com/47633289/59159250-6b071380-8acf-11e9-8d43-a47cb5700b67.png)
2. Нажать "Изменить"
Ожидаемый результат:
Заполнены данные поля "Ученую степень"
Фактический результат:
![image](https://user-images.githubusercontent.com/47633289/59159262-9984ee80-8acf-11e9-9dfe-877ca4208a02.png)

#1033

**Comment by YuriSilenok** [comment]
снято по не активности

**Comment by litdex** [comment]
@YuriSilenok Добрый день, можно ли создать одну ветку для решения #1046 и #1045 ?

**Comment by YuriSilenok** [comment]
Да, но этот запрос должен содержать ссылки на эти две задачи

**Comment by YuriSilenok** [comment]
@litdex зачтено
Этот баг должен быть проверен в ближайшем релизе и не может выдан в качестве ликцвидации задолжености
