### ISSUE TITLE
В справочнике "Ученая степень" можно добавить "Краткое название" длиннее "Полное название"

### ISSUE THREAD

**Issue by bolotovaksenya** [Students-of-the-city-of-Kostroma/Student-timetable#1047]
Название ветки: Союз-5
Шаги реализации бага:
1. Открыть справочник "Ученая степень"
![image](https://user-images.githubusercontent.com/47633289/59159311-93434200-8ad0-11e9-86da-51c0bd801487.png)
2. Нажать "Добавить"
3. Ввести"Ргррищтыт" в поле "Сокращенная запись ученой степени"
4.Ввести"Пват" в поле "Полная запись ученой степени"
![image](https://user-images.githubusercontent.com/47633289/59159321-b241d400-8ad0-11e9-9ac6-f7246b7c4bdc.png)
5. Нажать "Создать и закрыть"
Ожидаемый результат:
Выводится сообщение об ошибке
Фактический результат:
![image](https://user-images.githubusercontent.com/47633289/59159326-ba017880-8ad0-11e9-98b3-23b6170e6108.png)
#1033

**Comment by YuriSilenok** [comment]
снято по не активности

**Comment by YuriSilenok** [comment]
@litdex зачтено

**Comment by YuriSilenok** [comment]
Этот таск не может быть выдан в качестве ликвидации задолженности.
Необходимо проверить воспроизводимость бага в ближайшем релизе.
