### ISSUE TITLE
Написать сценарии тестирования пригодные для автоматизации модульного тестирования для метода Insert(Model model) сущности Auditor

### ISSUE THREAD

**Issue by bolotovaksenya** [Students-of-the-city-of-Kostroma/Student-timetable#105]
[сценарий](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)
[Диаграмма классов](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit)
[план разработки](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_102)

**Comment by YuriSilenok** [comment]
1. Как правило закрывает задачу тот, кто в данный момент ответственный за нее.
2. Если задача закрывается не по причине ее выполнения, то нужно указать, по какой причине она закрывается.

**Comment by YuriSilenok** [comment]
[Дубликат](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/100)

**Comment by bolotovaksenya** [comment]
@YuriSilenok , здравствуйте.
Прошу проверить правильность выполнения ЛР №1.
Спасибо.

**Comment by YuriSilenok** [comment]
Почему была открыта эта задача если она является дубликатом?

**Comment by bolotovaksenya** [comment]
Извиняюсь, перепутала, хотела оригинал исправить

**Comment by bolotovaksenya** [comment]
@YuriSilenok
