### ISSUE TITLE
Исправить сбои в автотестах расположенных в файле  UT_Delete_CGroup 

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#1065]
- Составить тесты методом белого ящика и [предоставить отчет](https://docs.google.com/document/d/1H6353mZjLjMmCq-1A7IrnKdwBUQXyg81wjauXlad3XY/edit)
- Обновить [сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit)
- Перенести комментарии методов в шаблон `///`
- Комментарии должны совпадать с описанием тестового сценария 

Этап тестирования #1182

**Comment by YuriSilenok** [comment]
Если в запросе не будет активности в течении 7 дней, задача будет снята.

**Comment by YuriSilenok** [comment]
задача снята по неактивности

**Comment by YuriSilenok** [comment]
На еще не выполнили задачу, что бы вешать ее на меня.

**Comment by MaximTrapeznikov** [comment]
@YuriSilenok 
А что еще по этой задаче нужно выполнить?
Спасибо.

**Comment by YuriSilenok** [comment]
Я должен проверить ваш запрос, в процессе этого могут возникнуть конфликты, и вот когда Вы запрос закончите мержем, тогда Ваша часть по этой задаче закончится

**Comment by YuriSilenok** [comment]
зачтено

**Comment by YuriSilenok** [comment]
Есть ли какие-то обновления по этой задаче?

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1065 давно не было активности

**Comment by NesgovorovVS** [comment]
> Добрый день. В ветке task-1065 давно не было активности

Здравствуйте, ветка не заброшена, как и две другие, в ближайшее время будут выгружены изменения и добавлены на проверку все участники группы.

**Comment by YuriSilenok** [comment]
Изменения должны выгружаться сразу. Не держите изменения только локально. Про самолёт рассказывать не буду.

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1065 давно не было активности

**Comment by NesgovorovVS** [comment]
> Добрый день. В ветке task-1065 давно не было активности

Ветка не заброшена, я не забываю о ней, я пытаюсь разобраться в этом. Ещё день посижу и если не пойму, будет ряд вопросов, которые задам в общей конфе.

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1065 давно не было активности

**Comment by YuriSilenok** [comment]
Нет доказательств того, что вы что-то пробуете, отправляйте данные каждый раз, как что-то меняете. Такова политика проекта.

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1065 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1065 давно не было активности

**Comment by NesgovorovVS** [comment]
> Добрый день. В ветке task-1065 давно не было активности

Добрый день, комментарии читаю, сегодня изменения будут залиты.

**Comment by NesgovorovVS** [comment]
> > Добрый день. В ветке task-1065 давно не было активности
> 
> Добрый день, комментарии читаю, сегодня изменения будут залиты.

Появились трудности с заливом на гитхаб, не видит, что я создал папку и добавил туда файл
![image](https://user-images.githubusercontent.com/47756995/89110648-8bbdc580-d455-11ea-9692-a9c2e5f8d2cb.png)

**Comment by NesgovorovVS** [comment]
> > > Добрый день. В ветке task-1065 давно не было активности
> > 
> > 
> > Добрый день, комментарии читаю, сегодня изменения будут залиты.
> 
> Появились трудности с заливом на гитхаб, не видит, что я создал папку и добавил туда файл
> ![image](https://user-images.githubusercontent.com/47756995/89110648-8bbdc580-d455-11ea-9692-a9c2e5f8d2cb.png)

отложил на сутки, до решения проблемы

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1065 давно не было активности

**Comment by NesgovorovVS** [comment]
![image](https://user-images.githubusercontent.com/47756995/89134258-6059da00-d52c-11ea-971a-60efe5a6fdb2.png)
пронумерованный код для отчёта, чтобы не потерять

**Comment by YuriSilenok** [comment]
У вас получилось залить картинки?

**Comment by NesgovorovVS** [comment]
Прошу задачу не снимать, проставлю приоритеты в течении суток.

**Comment by YuriSilenok** [comment]
> Прошу задачу не снимать, проставлю приоритеты в течении суток.

[Коммент](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/1240#issuecomment-672127384)

**Comment by NesgovorovVS** [comment]
> > Прошу задачу не снимать, проставлю приоритеты в течении суток.
> 
> [Коммент](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/1240#issuecomment-672127384)

в течение суток новые изменения будут загружены

**Comment by NesgovorovVS** [comment]
Прошу задачу не снимать, идут оставшиеся работы над ней.

**Comment by YuriSilenok** [comment]
> Прошу задачу не снимать, идут оставшиеся работы над ней.

Где хоть один коммит, уже 4 задача в которой я наблюдаю этот комментарий, а ни одного свежего коммита не видел, ГДЕ?

**Comment by NesgovorovVS** [comment]
> > Прошу задачу не снимать, идут оставшиеся работы над ней.
> 
> Где хоть один коммит, уже 4 задача в которой я наблюдаю этот комментарий, а ни одного свежего коммита не видел, ГДЕ?

Сегодня вечером будут коммиты

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by NesgovorovVS** [comment]
> Задача с Вас снята, так как по ней давно не было активности.

![image](https://user-images.githubusercontent.com/47756995/91935238-f3399000-ecf5-11ea-9086-33e9192747bc.png)
можно вернуть задачу?

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности. Активность по основной задаче #1065 составляет 18 дней. Ветка отсутствует. Запрос отсутствует. Нет запросов, которые должен проверить преподаватель

**Comment by YuriSilenok** [comment]
Задача с Вас  снята, так как по ней давно не было активности. Активность по основной задаче #1065 составляет 19 дней. Активность в ветке issue-1065 составляет 25 дней. Активность по запросу #1360 составляет 13 дней. Нет запросов, которые должен проверить преподаватель

**Comment by YuriSilenok** [comment]
Задача с Вас  снята, так как по ней давно не было активности. Активность по основной задаче #1065 составляет 13 дней. Активность в ветке issue-1065 составляет 38 дней. Активность по запросу #1360 составляет 26 дней. Нет запросов, которые должен проверить преподаватель
