### ISSUE TITLE
Исправить сбои в автотестах расположенных в файле  UT_Update_CGroup 

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#1066]
- Составить тесты методом белого ящика и [предоставить отчет](https://docs.google.com/document/d/1H6353mZjLjMmCq-1A7IrnKdwBUQXyg81wjauXlad3XY/edit)
- Обновить [сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit) указам у заголовка тест-комплекта ссылку на гугл документ с исследованием по белому ящику.
- Автоматизировать полученные сценарии
- Перенести комментарии методов в шаблон `///`
- Комментарии должны совпадать с описанием тестового сценария

**Comment by YuriSilenok** [comment]
- сценарии не обновлены в соответствии с автотестами

**Comment by YuriSilenok** [comment]
Если в запросе не будет активности в течении 7 дней, задача будет снята.

**Comment by YuriSilenok** [comment]
снято по неактивности

**Comment by YuriSilenok** [comment]
@FvckNeighbors я вижу что @GubanovAndrey ничего не делал со статусами задачи, пожалуйста, пусть он попробует повесить на меня эту задачу.

**Comment by YuriSilenok** [comment]
Зачтено

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Разобраться со странной нумерацией

```
Failed   Task_250_1_1
Error Message:
 Assert.IsTrue failed. 
Stack Trace:
   at UnitTestOfTimetableOfClasses.UT_Update_CGroup.DeleteData() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Update_CGroup.cs:line 29
   at UnitTestOfTimetableOfClasses.UT_Update_CGroup.Task_250_1_1() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Update_CGroup.cs:line 66
Failed   Task_250_1_3
Error Message:
 Assert.IsTrue failed. 
Stack Trace:
   at UnitTestOfTimetableOfClasses.UT_Update_CGroup.DeleteData() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Update_CGroup.cs:line 29
   at UnitTestOfTimetableOfClasses.UT_Update_CGroup.Task_250_1_3() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Update_CGroup.cs:line 97
Failed   Task_250_1_4
Error Message:
 Assert.IsTrue failed. 
Stack Trace:
   at UnitTestOfTimetableOfClasses.UT_Update_CGroup.DeleteData() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Update_CGroup.cs:line 29
   at UnitTestOfTimetableOfClasses.UT_Update_CGroup.Task_250_1_4() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Update_CGroup.cs:line 129
Failed   Task_250_1_5
Error Message:
 Assert.IsTrue failed. 
Stack Trace:
   at UnitTestOfTimetableOfClasses.UT_Update_CGroup.DeleteData() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Update_CGroup.cs:line 29
   at UnitTestOfTimetableOfClasses.UT_Update_CGroup.Task_250_1_5() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Update_CGroup.cs:line 161
Failed   Task_250_1_6
Error Message:
 Assert.IsTrue failed. 
Stack Trace:
   at UnitTestOfTimetableOfClasses.UT_Update_CGroup.DeleteData() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Update_CGroup.cs:line 29
   at UnitTestOfTimetableOfClasses.UT_Update_CGroup.Task_250_1_6() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Update_CGroup.cs:line 193
Failed   Task_250_1_7
Error Message:

```

**Comment by ssas18** [comment]
Юрий Викторович, можете проверить и сказать что здесь не так?
https://docs.google.com/document/d/1HYClxoAFzQ8clVSmZNnhXsSXjoydJSrqHJwvI-yATUY/edit?usp=sharing

**Comment by YuriSilenok** [comment]
> Юрий Викторович, можете проверить и сказать что здесь не так?
> https://docs.google.com/document/d/1HYClxoAFzQ8clVSmZNnhXsSXjoydJSrqHJwvI-yATUY/edit?usp=sharing

Запросил доступ к документу

**Comment by ssas18** [comment]
Исправил параметры доступа
https://docs.google.com/document/d/1HYClxoAFzQ8clVSmZNnhXsSXjoydJSrqHJwvI-yATUY/edit?usp=sharing

**Comment by YuriSilenok** [comment]
См. Чат

**Comment by ssas18** [comment]
Вроде бы как исправил указанную ошибку

**Comment by YuriSilenok** [comment]
Не исправили. Давайте эту задачу приостановил пока не поймёте как делать белый ящик в другой задаче. Не хочу видеть одни и те же ошибки дважды.

**Comment by ssas18** [comment]
Хорошо

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1066 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1066 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1066 давно не было активности

**Comment by ssas18** [comment]
Прошу не удалять, т.к. жду проверки

**Comment by YuriSilenok** [comment]
Где метки приоритета?

**Comment by ssas18** [comment]
Прошу меня простить, но примерно сутки буду находиться в отъезде, по приезду будут исправлены все замечания

**Comment by ssas18** [comment]
@YuriSilenok  , я снова тут и очень жду Вашей проверки по #1295

**Comment by YuriSilenok** [comment]
> @YuriSilenok  , я снова тут и очень жду Вашей проверки по #1295   

Я бы так же хотел видеть ответы на мои вопросы, даже если вы решили что-то исправить исходя из моего вопроса

**Comment by ssas18** [comment]
> > @YuriSilenok  , я снова тут и очень жду Вашей проверки по #1295
> 
> Я бы так же хотел видеть ответы на мои вопросы, даже если вы решили что-то исправить исходя из моего вопроса

Прошу прощения, сейчас все исправлю

**Comment by ssas18** [comment]
В данной задаче нет активности т.к жду проверки

**Comment by YuriSilenok** [comment]
[Зачтено](https://docs.google.com/spreadsheets/d/1uBd4d3VvI4rYeuXkXmqLyEZSitS8K9pfVUDtM3i1Vg4/edit#gid=1274241490&range=N5)
