### ISSUE TITLE
Не происходит уведомления, о том что данные уже существуют в форме Учетные звания при попытке добавить идентичные данные

### ISSUE THREAD

**Issue by Jeen99** [Students-of-the-city-of-Kostroma/Student-timetable#1067]
Баг воспроизводиться в v0.20-Testing

При попытке повторного добавления уже существующего учетного звания через **"Создать и очистить"** не происходит уведомления, о том что данные уже существуют.

Шаги реализации бага:

1. Открыть справочник "Учетные звания"
2. Нажать "добавить"
3. В поле "Сокращенная запись уч. звания" ввести "тест"
4. В поле "Полная запись уч. звания" ввести "тест"
5. Нажать "Создать и очистить"
6. В поле "Сокращенная запись уч. звания" ввести "тест"
7. В поле "Полная запись уч. звания" ввести "тест"
8. Нажать "Создать и очистить"

**Фактический результат**: Данные не добавляются. Не отображается уведомление о том, что данные уже существуют
**Ожидаемый результат**: Данные не добавляются. Отображается уведомление о том, что данные уже существуют

**Comment by Jeen99** [comment]
#1078

**Comment by YuriSilenok** [comment]
зачтено в КП
