### ISSUE TITLE
Некорректное название формы Добавить Корпус

### ISSUE THREAD

**Issue by Jeen99** [Students-of-the-city-of-Kostroma/Student-timetable#1070]
Баг воспроизводиться в v0.20-Testing

Шаги реализации бага:

1. Открыть справочник "Корпуса"
2. Нажать "добавить"

![image](https://user-images.githubusercontent.com/32433285/59184273-6ea1a580-8b76-11e9-9398-7cb78f7d12f6.png)

Ожидается: Добавить корпус.

**Comment by Jeen99** [comment]
#1078

**Comment by YuriSilenok** [comment]
не вешайте на меня задачу, пока запрос не будет решен
