### ISSUE TITLE
Поле для ввода не защищено от вставки данных из буфера обмена на форме Добавить Корпус.

### ISSUE THREAD

**Issue by Jeen99** [Students-of-the-city-of-Kostroma/Student-timetable#1071]
Баг воспроизводиться в v0.20-Testing
Поле "Телефон" защищено от ввода букв с клавиатуры, но если попытаться вставить данные, операция проходит успешно.

Шаги реализации бага:

1. Открыть справочник "Корпуса"
2. Нажать "добавить"
3. Переключаемся на поле "Телефон"
4. Копируем в буфер обмена текст "ТЕСТ"
5. При помощи правой кнопки мыши используем команду "Вставить"

![image](https://user-images.githubusercontent.com/32433285/59184391-b45e6e00-8b76-11e9-916a-07c3ae9a7ed4.png)

**Фактический результат**: изменяются данные на поле "Телефон" на некорректные (т.е. могут содержать буквы)
**Ожидаемый результат**: данные на поле "Телефон" не изменяются. (или изменяются на допустимые)

**Comment by Jeen99** [comment]
#1078

**Comment by YuriSilenok** [comment]
снята по бездейсвию
