### ISSUE TITLE
Некорректный вывод уведомления при добавлении Направления подготовки.

### ISSUE THREAD

**Issue by Jeen99** [Students-of-the-city-of-Kostroma/Student-timetable#1074]
Баг воспроизводиться в v0.20-Testing
Форма выдает, что данные не добавляются, но в таблице они появляются.

Шаги реализации бага:
1. Открыть справочник "Направление подготовки"
2. Нажать "добавить"
3. В поле "Код направления подготовки" вводим "222222"
4. В поле "Наименование направления подготовки" вводим "Радиофизика"
5. Нажать "Создать и очистить"

![image](https://user-images.githubusercontent.com/32433285/64068315-278bf380-cc3f-11e9-80c5-0c258a928111.png)

**Фактический результат**: добавляются заполненные  данные в таблицу и выводится уведомление "Невозможно добавить ...".
**Ожидаемый результат**: добавляются заполненные  данные в таблицу.

**Comment by Jeen99** [comment]
#1078

**Comment by YuriSilenok** [comment]
снято по не активности

**Comment by YuriSilenok** [comment]
> Форма выдает, что данные не добавляются, но в таблице они появляются.

Это нужно разбить на ожидаемый результат и фактический результат. В ожидамеом результате описать что происходит добавление записи, а в фактическом описать что что выдается предупреждение и добавляется запись.

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
