### ISSUE TITLE
Не возможно использовать горячие клавиши в полях Аудитория и Кафедра при добавлении Аудитории

### ISSUE THREAD

**Issue by Jeen99** [Students-of-the-city-of-Kostroma/Student-timetable#1075]
Баг воспроизводиться в v0.20-Testing
Шаги реализации бага:
1. Открыть справочник "Аудитории"
2. Нажать "добавить"
3. Переключаемся на поле "Аудитория " или "Кафедра"
4. Пытаемся использовать горячие клавиши (пример: ctrl + V (_при наличии текста в буфере обнена_)) 

![image](https://user-images.githubusercontent.com/32433285/59185107-4c108c00-8b78-11e9-8eec-4f80361a2485.png)
**Фактический результат**: В поле корпус и аудитория не вставляется текст из буфера обмена (при сочетании клавиш ctrl + V).
**Ожидаемый результат**: В поле корпус и аудитория вставляется текст из буфера обмена (при сочетании клавиш ctrl + V).

**Comment by Jeen99** [comment]
#1078

**Comment by YuriSilenok** [comment]
В баге кроме ожидаемого результат прописывается и фактический результат.
Ожидаемый результат лучше прописать более конкретно. По сути обработка горячих клавиш осущесествляется, но для пользователя нет явных признаков для этого. Нужно написать в ожидаемый результат что-то типа `В поле корпус и аудитория вставляется вставляется текст из буфера обмена`

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
