### ISSUE TITLE
Ликвидация долгов за 2 Sprint

### ISSUE THREAD

**Issue by Jeen99** [Students-of-the-city-of-Kostroma/Student-timetable#1078]
Задача для тимлида

**Comment by Jeen99** [comment]
@YuriSilenok, выполнил поиск 8-ми багов для закрытия долгов за 2-ой спринт.

**Comment by YuriSilenok** [comment]
Добрый день @Rogachev99 
- Напоминаю, что если Вы не заасаните на меня задачу, я не буду на нее смотреть. указание никнема лишь дает конкретизацию в обращении.

Спасибо,
Юрий

**Comment by Jeen99** [comment]
Добрый день @YuriSilenok 
Необходимо каждую задачу на вас заасанить или хватит только этой?
Спасибо.

**Comment by YuriSilenok** [comment]
Достаточно только текущую задачу. 
Баги и другие типы задач будут жить по своему стандартному циклу.

**Comment by YuriSilenok** [comment]
#1075 - необходимо прописать сценарий воспроизведения по шагам, начиная с перехода по меню Справочники. Заголовок должен отвечать на 3 вопроса. Что, где, когда. Что - `Не возможно использовать горячие клавиши`, где - `в полях Аудитория и Кафедра`, когда - `на добавлении аудитории`
#1074 - те же ошибки. Непонятно после нажатия на какую кнопку получается этот фактический результат.
проверить все баги на предмет вышеуказанных ошиок

**Comment by Jeen99** [comment]
@YuriSilenok, исправил недочеты. Проверьте, пожалуйста.

**Comment by YuriSilenok** [comment]
общее замечение.
проработать отдельно фактический и ожидаемый результат. 
Человеку который должен будет исправлять должно бытьпоняитно к какому поведению претензия и на какое поведение нужно исправить функциональность.

**Comment by YuriSilenok** [comment]
Закрыто по неактивности.

**Comment by Jeen99** [comment]
@YuriSilenok, UPD

**Comment by YuriSilenok** [comment]
- Первое письмо мне пришло, когда Вы переоткрыли этот таск
- Второе письмо мне пришло, когда Вы перевесили задачу на меня
- Третье письмо мне пришло, когда Вы написали комментарий.

Думаю комментарий был излишним, тем более что он не несет никакой полезной нагрузки.

**Comment by YuriSilenok** [comment]
- #1075 - Выполнив шаги в вашем сценарии вы не сможете получить оидаемый результат, даже если включить обработку клавишь. 
- #1074 - 222222 не подходит под шаблон кода направления подготовки, не думаю что такое направление подготовки доллно создаться
- #1073 - претензий нет
- To be continued

**Comment by YuriSilenok** [comment]
Закрыто по неактивности.

**Comment by Jeen99** [comment]
#1074 - поправил (хотя и не согласен с вами, т.к. к багу это не имеет никакого отношения. Он при любых данных воспроизводится.)
#1075 - поправил.

**Comment by YuriSilenok** [comment]
Время на ликвидацию задолженностей истекло, об этом было письмо.

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
