### ISSUE TITLE
Исправить сбои в автотестах расположенных в файле UT_Delete_CEnclosures 

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#1082]
- Выявить причину сбоев в автотестах.
- При необходимости исправить автотесты и [сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit?usp=sharing)
- Перенести комментарии методов в шаблон` ///`
- Комментарии должны совпадать со описанием тестового сценария

Этап тестирования #1182

**Comment by YuriSilenok** [comment]
Зачтено

**Comment by YuriSilenok** [comment]
Работы все еще ведутся

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1082 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1082 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1082 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1082 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1082 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1082 давно не было активности

**Comment by ifuwmnn** [comment]
Здравствуйте, я же написал в ветке, что нет активности т.к. по идее всё
проходит кроме одного теста, который фэйлится из-за refdata, я поднял
задачу на её отделение, и как эта задача будет решена то и ветку можно
будет закрыть, но никто не берётся за
эту задачу.


вс, 9 авг. 2020 г. в 08:02, Юрий Силенок <notifications@github.com>:

**Comment by YuriSilenok** [comment]
Сегодня задача выдана, Следите за ней.
Необходимо в комментарием сослаться на задачу которая вас блокирует.
Тогда я смогу понять что в задаче нет активности из-за конкретной ОТКРЫТОЙ задачи.
И если задача будет с вас снята, то потом я снова ее на вас перевешу.

**Comment by ifuwmnn** [comment]
В задаче нет активности, т.к. меня блокирует задача #1323

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by YuriSilenok** [comment]
@ifuwmnn думаю Вам стоит поинтересоваться когда будет завершена блокирующая вас задача, возможно оказать помощь.

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by Alphavite51** [comment]
Ветка смержена, можете продолжать работу, вам нужно мержить dev в вашу ветку!

**Comment by YuriSilenok** [comment]
Вы можете продолжить работу над задачей.

**Comment by YuriSilenok** [comment]
За одну задачу может быть ответсвеннен только один человек

**Comment by YuriSilenok** [comment]
[Зачтено](https://docs.google.com/spreadsheets/d/1uBd4d3VvI4rYeuXkXmqLyEZSitS8K9pfVUDtM3i1Vg4/edit#gid=718242162&range=L4)
