### ISSUE TITLE
Исправить сбои в автотестах расположенных в файле UT_Insert_CEnclosurse

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#1085]
- Выявить причину сбоев в автотестах.
- При необходимости исправить автотесты и сценарии
- Перенести комментарии методов в шаблон` ///`
- Комментарии должны совпадать со описанием тестового сценария
#397 Script

Этап тестирования #1182

**Comment by YuriSilenok** [comment]
Снято по не активности.

**Comment by YuriSilenok** [comment]
Задача снята по бездействию

**Comment by DemiKor** [comment]
Тесты не работают из-за связи с таблицей ВУЗов

**Comment by YuriSilenok** [comment]
Исправляйте, знаете как?

**Comment by DemiKor** [comment]
Всё исправил, работают все тесты, кроме 7-го сценария. Либо неверная реализация возможности, либо сценарий тестирования.

**Comment by YuriSilenok** [comment]
Все эти тесты когда-то работали, нужно разбираться.

**Comment by DemiKor** [comment]
Я попробовал вручную сценарий 7, также выскакивает ошибка, что невозможно добавить запись

**Comment by YuriSilenok** [comment]
Сценарии очень плохии. Название диаметрально противоречит содержимому.

У [корпуса](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/Task-1085/LibOfTimetableOfClasses/CEnclosures.cs) есть составной ключ, который задает ограничение, на то, что название корпуса должен быть уникален в пределах ВУЗа.

Но думаю проблема в другом, на телефоне и адрисе корпуса, не зависимо от вуза и друг от друга, стоит ограничение уникальности. Ваш автотест соответсвует сценарию.

Думаю возможеным решением здесь будет пересмотреть тест-компелкт `task-397 (Тестирование метода Insert(Model model) сущности CEnclosures)`

Предлагаю переписать сценарии
1. добавление в пустую таблицу. exp true
2. прекондишен = 1 тест. Проверка наличия ограничения составного ключа на атрибуты название корпуса и ВУЗ. exp false
3. прекоднишен = 1 тест. Проверка наличия ограничения уникальности на атрибут адрес. exp false
4. прекоднишен = 1 тест. Проверка наличия ограничения уникальности на атрибут телефон. exp false
5. прекоднишен = 1 тест. Проверка **отсутствия** ограничения уникальности на атрибут комментарий. exp true

Это тесты первого приоритета.

**Comment by DemiKor** [comment]
А можно просто тесты переписать, без редактирования таблицы со сценариями?

**Comment by YuriSilenok** [comment]
Нет, но можете задание сменить.

**Comment by DemiKor** [comment]
Хорошо

**Comment by YuriSilenok** [comment]
Зачтено как лр04 #1254
