### ISSUE TITLE
Исправить сбои в автотестах расположенных в файле  UT_Delete_CTrainingProfile

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#1086]
- Выявить причину сбоев в автотестах.
- При необходимости исправить автотесты и сценарии
- Перенести комментарии методов в шаблон` ///`
- Комментарии должны совпадать со описанием тестового сценария
#422 Script

**Comment by YuriSilenok** [comment]
Передано по неактивности

**Comment by VinogradovAlexandr781227** [comment]
Здравствуйте

Выдайте мне пожалуйста новую задачу в замен этой

Спасибо
Виноградов Александр
17-ИСбо-2б

среда, 19 июня 2019 г. пользователь Юрий Силенок <notifications@github.com>
написал:

**Comment by YuriSilenok** [comment]
Берите #838

**Comment by YuriSilenok** [comment]
снято по неактиыности

**Comment by DemiKor** [comment]
Тесты не работают, потому что сначала пытаются добавить запись, а запись нельзя добавить из-за связи с таблицей ВУЗы

**Comment by YuriSilenok** [comment]
Исправляйте, знаете как?

**Comment by DemiKor** [comment]
Второй тест не проходит, т.к. в контроллере не обрабатывается исключения

**Comment by YuriSilenok** [comment]
> Второй тест не проходит, т.к. в контроллере не обрабатывается исключения

Об этом пиишите в запросе и лучше с привязкой к коду и скринами

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу
