### ISSUE TITLE
Исправить сбои в автотестах расположенных в файле  UT_Insert_CUniversity

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#1087]
- Составить тесты методом белого ящика и [предоставить отчет](https://docs.google.com/document/d/1H6353mZjLjMmCq-1A7IrnKdwBUQXyg81wjauXlad3XY/edit)
- Обновить [сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit) указам у заголовка тест-комплекта ссылку на гугл документ с исследованием по белому ящику.
- Автоматизировать полученные сценарии
- Перенести комментарии методов в шаблон `///`
- Комментарии должны совпадать с описанием тестового сценария

**Comment by YuriSilenok** [comment]
Задача снята по бездействию

**Comment by VinogradovAlexandr781227** [comment]
Здравствуйте, Юрий Викторович

Проверьте пожалуйста ЛР4.2

Спасибо.

**Comment by YuriSilenok** [comment]
зачтено #1254

**Comment by YuriSilenok** [comment]
Зачтено как ЛР04

**Comment by YuriSilenok** [comment]
```
Failed   Task_496_1
Error Message:
 Assert.AreEqual failed. Expected:<True>. Actual:<False>. 
Stack Trace:
   at UnitTestOfTimetableOfClasses.UT_Insert_CUniversity.Task_496_1() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Insert_CUniversity.cs:line 19
Failed   Task_496_2
Error Message:
 Assert.IsTrue failed. 
Stack Trace:
   at UnitTestOfTimetableOfClasses.UT_Insert_CUniversity.Task_496_2() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Insert_CUniversity.cs:line 36
Passed   Task_496_3
Failed   Task_496_4
Error Message:
 Assert.IsTrue failed. 
Stack Trace:
   at UnitTestOfTimetableOfClasses.UT_Insert_CUniversity.Task_496_4() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Insert_CUniversity.cs:line 80
Failed   Task_496_5
Error Message:
 Assert.IsTrue failed. 
Stack Trace:
   at UnitTestOfTimetableOfClasses.UT_Insert_CUniversity.Task_496_5() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Insert_CUniversity.cs:line 102
Failed   Task_496_6
Error Message:
 Assert.IsTrue failed. 
Stack Trace:
   at UnitTestOfTimetableOfClasses.UT_Insert_CUniversity.Task_496_6() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Insert_CUniversity.cs:line 124
Failed   Task_496_7
Error Message:
 Assert.IsTrue failed. 
Stack Trace:
   at UnitTestOfTimetableOfClasses.UT_Insert_CUniversity.Task_496_7() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Insert_CUniversity.cs:line 146
Failed   Task_496_8
Error Message:
 Assert.IsTrue failed. 
Stack Trace:
   at UnitTestOfTimetableOfClasses.UT_Insert_CUniversity.Task_496_8() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Insert_CUniversity.cs:line 167
Failed   Task_496_9

```

**Comment by NesgovorovVS** [comment]
![image](https://user-images.githubusercontent.com/47756995/89134654-4d94d480-d52f-11ea-85fd-b7340ecc9700.png)
Разметка кода

**Comment by NesgovorovVS** [comment]
![image](https://user-images.githubusercontent.com/47756995/89218014-ee3dcf80-d5d5-11ea-804c-275440373b08.png)
исправленная разметка для отчёта

**Comment by YuriSilenok** [comment]
Все это должно попасть в отчёт в репозиторий, а не сюда

**Comment by NesgovorovVS** [comment]
Прошу задачу не снимать, проставлю приоритеты в течении суток.

**Comment by YuriSilenok** [comment]
> Прошу задачу не снимать, проставлю приоритеты в течении суток.

[Коммент](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/1240#issuecomment-672127384)

**Comment by NesgovorovVS** [comment]
> > Прошу задачу не снимать, проставлю приоритеты в течении суток.
> 
> [Коммент](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/1240#issuecomment-672127384)

в течение суток новые изменения будут загружены

**Comment by NesgovorovVS** [comment]
Прошу задачу не снимать, идут оставшиеся работы над ней.

**Comment by YuriSilenok** [comment]
Какие работы? Вы только спамите в комментариях, где коммиты?!!

**Comment by NesgovorovVS** [comment]
> Какие работы? Вы только спамите в комментариях, где коммиты?!!

Сегодня вечером будут коммиты

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by NesgovorovVS** [comment]
> Задача с Вас снята, так как по ней давно не было активности.

![image](https://user-images.githubusercontent.com/47756995/91935280-0b111400-ecf6-11ea-9275-66c26e13fd5a.png)
можно вернуть задачу?

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности. Активность по основной задаче #1087 составляет 18 дней. Ветка отсутствует. Запрос отсутствует. Нет запросов, которые должен проверить преподаватель

**Comment by YuriSilenok** [comment]
Задача с Вас  снята, так как по ней давно не было активности. Активность по основной задаче #1087 составляет 19 дней. Активность в ветке issue-1087 составляет 25 дней. Активность по запросу #1368 составляет 13 дней. Нет запросов, которые должен проверить преподаватель

**Comment by YuriSilenok** [comment]
Задача с Вас  снята, так как по ней давно не было активности. Активность по основной задаче #1087 составляет 13 дней. Активность в ветке issue-1087 составляет 38 дней. Активность по запросу #1368 составляет 26 дней. Нет запросов, которые должен проверить преподаватель
