### ISSUE TITLE
Исправить сбои в автотестах расположенных в файле UT_Update_CUniversity 

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#1088]
- Составить тесты методом белого ящика и [предоставить отчет](https://docs.google.com/document/d/1H6353mZjLjMmCq-1A7IrnKdwBUQXyg81wjauXlad3XY/edit)
- Обновить [сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit) указам у заголовка тест-комплекта ссылку на гугл документ с исследованием по белому ящику.
- Автоматизировать полученные сценарии
- Перенести комментарии методов в шаблон `///`
- Комментарии должны совпадать с описанием тестового сценария

**Comment by bormolei** [comment]
Добрый день, @YuriSilenok .
В данных тестах я сбоев не нашел, тесты все выполняются успешно. Из всех поставленных задач единственно что требует исправление это перенести комментарии методов в шаблон.

**Comment by YuriSilenok** [comment]
Смотрю

**Comment by YuriSilenok** [comment]
Да, действительно, эти тесты проходят без сбоев.

**Comment by YuriSilenok** [comment]
Скоро выдам другое задание

**Comment by YuriSilenok** [comment]
Duplicate of #892

**Comment by YuriSilenok** [comment]
Зачтено

**Comment by YuriSilenok** [comment]
Снова сбои
```
Passed   Task_497_1
Passed   Task_497_2
Passed   Task_497_3
Passed   Task_497_4
Passed   Task_497_5
Passed   Task_497_6
Failed   Task_497_7
Error Message:
 Assert.IsTrue failed. 
Stack Trace:
   at UnitTestOfTimetableOfClasses.UT_Update_CUniversity.Task_497_7() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Update_CUniversity.cs:line 196
```

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1088 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1088 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1088 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1088 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1088 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1088 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1088 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1088 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1088 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1088 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1088 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1088 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1088 давно не было активности

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by YuriSilenok** [comment]
Устаревшая ветка для этой задачи будет удалена в ближайшее время

**Comment by YuriSilenok** [comment]
> Устаревшая ветка для этой задачи будет удалена в ближайшее время

Ветка удалена

**Comment by NordScandinavian** [comment]
Прошу не снимать задачи по не активности, отчёты будут выложены 25.08

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by NordScandinavian** [comment]
Прошу вернуть задачу, жду вашей проверки в пул реквесте

**Comment by NordScandinavian** [comment]
@YuriSilenok, здравствуйте.
Прилагаю скрин, подтверждающий активность в пул реквесте.
4 дня назад(25.08) был залит отчёт, 26 чиcла был одобрен одним человеком, и 28 ещё одним.
Правило 2 дней активности, по идее, соблюдено.
Считаются ли аппрувы активностью в задаче?
![image](https://user-images.githubusercontent.com/47521360/91641872-c9e7de00-ea2f-11ea-8366-dd9314a5349f.png)

**Comment by YuriSilenok** [comment]
Апрувы считаются активностью, забирайте свою задачу.

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by YuriSilenok** [comment]
Устаревшая ветка task-1088 будет удалена в ближайшее время

**Comment by NordScandinavian** [comment]
@YuriSilenok , здравствуйте, 
Прошу не удалять ветку и проверить пул реквест, необходимое кол-во аппрувов есть.

**Comment by NordScandinavian** [comment]
@YuriSilenok , прошу проверить в пул реквесте отчёты, необходимое кол-во аппрувов есть.

**Comment by YuriSilenok** [comment]
В скором времени

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности. Активность по основной задаче #1088 составляет 3 дней. Активность в ветке task-1088 составляет 13 дней. Активность по запросу #1333 составляет 3 дней. Нет запросов, которые должен проверить преподаватель

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности. Активность по основной задаче #1088 составляет 10 дней. Ветка отсутствует. Запрос отсутствует. Нет запросов, которые должен проверить преподаватель

**Comment by NordScandinavian** [comment]
Прошу не снимать задачу по неактивности. Болею, не мог сесть за задачи, не позволяло состояние.

**Comment by YuriSilenok** [comment]
Задача с Вас  снята, так как по ней давно не было активности. Активность по основной задаче #1088 составляет 3 дней. Активность в ветке issue-1088 составляет 3 дней. Активность по запросу #1357 составляет 2 дней. Нет запросов, которые должен проверить преподаватель

**Comment by YuriSilenok** [comment]
Ветка issue-1088 удалена

**Comment by YuriSilenok** [comment]
Задача с Вас  снята, так как по ней давно не было активности. Активность по основной задаче #1088 составляет 43 дней. Активность в ветке issue-1088 составляет 20 дней. Активность по запросу #1357 составляет 17 дней. Нет запросов, которые должен проверить преподаватель

**Comment by YuriSilenok** [comment]
Ветка issue-1088 удалена
