### ISSUE TITLE
Создать форму "Справочники"

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#109]
Вызывается из стартовой формы в верхнем меню пунктом Справочники-Справочники.
Имя формы Directory
Графический интерфейс:
- Заголовок формы **Справочники**
- Таблица привязанная к всем сторонам формы. И имеет отступ 3px от кнопок снизу.
- Кнопка **Добавить** имеет стандартные размеры и привязку к правому и нижнему краю формы. Отступ со всех сторон 3px. Расположена в правом нижнем углу формы.
- Кнопка **Удалить** имеет стандартные размеры и привязана к правому и нижнему краю формы. Отступ со всех сторон 3px. Расположена внизу формы, левее кнопки **Добавить** с отступом в 3px.
- Реализовать метод public void UploadTable(DataTable table);
Метод извлекает имя таблицы и записывает в заголовок формы.
В ресурсы (источник данных) элемента управления типа DataGridView передать table (входной параметр метода).

Ветка task-109

**Comment by KharlamovaAlexandra** [comment]
Добрый вечер @YuriSilenok 
Можно получить комментарии к содержанию метода и пояснить, что имеется в виду под ресурсами элемента управления?
Непонятны эти две строки: "Метод извлекает имя таблицы и записывает в заголовок формы.
В ресурсы элемента управления типа DataGridView передать table (входной параметр метода)."
Спасибо

**Comment by YuriSilenok** [comment]
Здравствуйте @KharlamovaAlexandra 
Если Вы задаете несколько вопросов, оправдано использование списков.
Используйте цитаты, это оправдано в тех случаях, когда у Вас есть вопрос к конкретному фрагменту текста.

Я надеюсь что Вы пробовали [искать информацию](https://www.google.com/search?q=datagridview+source&oq=DataGridView+%D1%8B%D1%89%D0%B3%D0%BA%D1%81%D1%83&aqs=chrome.1.69i57j0l5.13763j0j7&sourceid=chrome&ie=UTF-8)
> что имеется в виду под ресурсами элемента управления?
> > В ресурсы элемента управления типа DataGridView передать table (входной параметр метода).

Это не вопрос, пожалуйста, формулируйте более точно, не может быть что бы было совсем все непонятно. Еще раз прочтите документ "Как писать письма?" о том, как формулировать вопросы. Я должен увидеть логику Ваших рассуждений.
>Непонятны эти две строки:

**Comment by KharlamovaAlexandra** [comment]
Добрый день @YuriSilenok

1. Как следует из описания задачи после создания формы 
![1](https://user-images.githubusercontent.com/47320583/53693391-d8105c00-3db0-11e9-9e6f-884a80ade639.PNG)
в ее коде требуется создать метод UploadTable.
![2](https://user-images.githubusercontent.com/47320583/53693397-f0807680-3db0-11e9-9af3-6cbcbef85821.PNG)
Если я правильно поняла задание, то метод должен извлекать актуальное на данный момент имя таблицы и присвоить это значение заголовку формы. То есть в  какой - то момент времени форма изменит заголовок "Справочники" на имя таблицы?

2.  

> "В ресурсы элемента управления типа DataGridView передать table (входной параметр метода)." 

 Это значит что при загрузке формы таблица должна заполнятся данными из table? Мне не доводилось работать с подобными вещами, поэтому я не понимаю как прикрепить здесь DataTable table
![3](https://user-images.githubusercontent.com/47320583/53693512-8a94ee80-3db2-11e9-9cb6-6f588b3d25b3.PNG)

С уважением, Харламова Александра
17-ИСбо-2б

**Comment by YuriSilenok** [comment]
Здравствуйте.

Этот момент времени будет метод UploadTable
> То есть в какой - то момент времени форма изменит заголовок "Справочники" на имя таблицы?

table это и есть источник данных переданный в метод UploadTable. У вашей таблицы будетет свойство Source или как-то так. Вот в него и нужно присвоить таблицу.
> Это значит что при загрузке формы таблица должна заполнятся данными из table?\

Спасибо.

**Comment by YuriSilenok** [comment]
Зачтено
