### ISSUE TITLE
Проверка всех сценариев и юнит-тестов сущности "Корпус" + Добавление сценариев на ограничения.

### ISSUE THREAD

**Issue by Proffet78** [Students-of-the-city-of-Kostroma/Student-timetable#1091]
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)
Задачи на тестирование с меткой Story не найдены.
Добавлены ограничения  в сценарии Update и Insert сущности Корпус:
task-397 и task-396
Существующие автотесты соответствуют написанным сценариям, кроме ограничений, так как они были добавлены в ходе выполнения данного задания.
Так же была обнаружена копия задания в таске #171 . В нём не актуальная информация по поводу написания автотестов из за несоответствия атрибутов в настоящее время.

**Comment by Proffet78** [comment]
Здравствуйте

Прошу проверить ЛР 4.1

Спасибо

**Comment by YuriSilenok** [comment]
Закрыто, клон #1085

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by Proffet78** [comment]
Здравствуйте,
Возможно эта задача уже не актуальна, так как у меня закрыты все долги по семестру и проставлен зачёт.
Спасибо.

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
