### ISSUE TITLE
Разработать тестовые сценарии для вкладки День формы Параметры

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#1093]
Разработать сценарии тестирования для функционального тестирования.
Задача реализована в Story #517

**Comment by stasshtaub** [comment]
[Ссылка на сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)

**Comment by stasshtaub** [comment]
[Ссылка на сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=983700952)

**Comment by YuriSilenok** [comment]
- ожидаемый результат прописать для каждого шага с указанием к какому шагу относится ожидаемый результат.

**Comment by YuriSilenok** [comment]
зачтено
