### ISSUE TITLE
Исправить сбои в автотестах расположенных в файле  UT_Delete_CInstitute 

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#1095]
- Составить тесты методом белого ящика и [предоставить отчет](https://docs.google.com/document/d/1H6353mZjLjMmCq-1A7IrnKdwBUQXyg81wjauXlad3XY/edit)
- Обновить [сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit)
- Перенести комментарии методов в шаблон `///`
- Комментарии должны совпадать с описанием тестового сценария 

Этап тестирования #1182

**Comment by YuriSilenok** [comment]
Задача снята по бездействию

**Comment by DemiKor** [comment]
Не выполняется из-за того, что не может вначале добавить запись в таблицу
![image](https://user-images.githubusercontent.com/36473373/60918047-f4f6f780-a29a-11e9-96c8-2360fa3f00c9.png)

**Comment by YuriSilenok** [comment]
Вы знаете как исправлять?

**Comment by FvckNeighbors** [comment]
Задача снята по отсутствию активности

**Comment by YuriSilenok** [comment]
Передано по не активности

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by NordScandinavian** [comment]
1>------ Сборка запущено: проект: LibOfTimetableOfClasses, конфигурация: Debug|AnyCPU ------
D:\_Универсам\ТРПО\Student-timetable\LibOfTimetableOfClasses\LibOfTimetableOfClasses.csproj(116,5): error : Данный проект ссылается на пакеты NuGet, отсутствующие на этом компьютере. Используйте восстановление пакетов NuGet, чтобы скачать их.  Дополнительную информацию см. по адресу: http://go.microsoft.com/fwlink/?LinkID=322105. Отсутствует следующий файл: ..\packages\MSTest.TestAdapter.1.4.0\build\net45\MSTest.TestAdapter.props.
2>------ Сборка запущено: проект: TimetableOfClasses, конфигурация: Debug|AnyCPU ------
D:\_Универсам\ТРПО\Student-timetable\TimetableOfClasses\TimetableOfClasses.csproj(392,5): error : Данный проект ссылается на пакеты NuGet, отсутствующие на этом компьютере. Используйте восстановление пакетов NuGet, чтобы скачать их.  Дополнительную информацию см. по адресу: http://go.microsoft.com/fwlink/?LinkID=322105. Отсутствует следующий файл: ..\packages\MSTest.TestAdapter.1.4.0\build\net45\MSTest.TestAdapter.props.
3>------ Сборка запущено: проект: UnitTestOfTimetableOfClasses, конфигурация: Debug|AnyCPU ------
D:\_Универсам\ТРПО\Student-timetable\UnitTestOfTimetableOfClasses\UnitTestOfTimetableOfClasses.csproj(115,5): error : Данный проект ссылается на пакеты NuGet, отсутствующие на этом компьютере. Используйте восстановление пакетов NuGet, чтобы скачать их.  Дополнительную информацию см. по адресу: http://go.microsoft.com/fwlink/?LinkID=322105. Отсутствует следующий файл: ..\packages\MSTest.TestAdapter.1.4.0\build\net45\MSTest.TestAdapter.props.
========== Сборка: 0 успешно, 3 неудачно, 0 актуально, 0 пропущено ==========


Сейчас я просто пытаюсь собрать проект и запустить тесты
Но VS отписывает, что у меня в проекте содержатся ссылки на пакеты, которых у меня нет на компьютере
Возникает несколько конкретных вопросов, которые тормозят всю работу

1) Я не знаю, почему в файле UnitTestOfTimetableOfClasses.csproj указывается (и в прошлых нормальных коммитах) для импорта путь к ../packages/... которой нет в проекте. Зачем нужен этот packages и почему его в проекте нет

2) Как я понял, он строит какие-то зависимости и использует ссылки на эти ресурсы. Зачем вообще в файле UnitTestOfTimetableOfClasses.csproj указываются ссылки на эти ресурсы - ..\packages\MSTest.TestAdapter.1.4.0\build\net45\MSTest.TestAdapter.props.? 

3) Где найти документацию, что должно быть установлено и почему vs вообще ругается, что у меня чего-то нет? И нужно ли на основании всего вышеизложенного менять что-то в файле UnitTestOfTimetableOfClasses.csproj (и остальных) чтобы проект собрался и я смог проверить работу UT?

**Comment by YuriSilenok** [comment]
Код или другие сообщения в IDE и прочем нужно оформлять как положено, вот так
```
1>------ Сборка запущено: проект: LibOfTimetableOfClasses, конфигурация: Debug|AnyCPU ------
D:_Универсам\ТРПО\Student-timetable\LibOfTimetableOfClasses\LibOfTimetableOfClasses.csproj(116,5): error : Данный проект ссылается на пакеты NuGet, отсутствующие на этом компьютере. Используйте восстановление пакетов NuGet, чтобы скачать их. Дополнительную информацию см. по адресу: http://go.microsoft.com/fwlink/?LinkID=322105. Отсутствует следующий файл: ..\packages\MSTest.TestAdapter.1.4.0\build\net45\MSTest.TestAdapter.props.
2>------ Сборка запущено: проект: TimetableOfClasses, конфигурация: Debug|AnyCPU ------
D:_Универсам\ТРПО\Student-timetable\TimetableOfClasses\TimetableOfClasses.csproj(392,5): error : Данный проект ссылается на пакеты NuGet, отсутствующие на этом компьютере. Используйте восстановление пакетов NuGet, чтобы скачать их. Дополнительную информацию см. по адресу: http://go.microsoft.com/fwlink/?LinkID=322105. Отсутствует следующий файл: ..\packages\MSTest.TestAdapter.1.4.0\build\net45\MSTest.TestAdapter.props.
3>------ Сборка запущено: проект: UnitTestOfTimetableOfClasses, конфигурация: Debug|AnyCPU ------
D:_Универсам\ТРПО\Student-timetable\UnitTestOfTimetableOfClasses\UnitTestOfTimetableOfClasses.csproj(115,5): error : Данный проект ссылается на пакеты NuGet, отсутствующие на этом компьютере. Используйте восстановление пакетов NuGet, чтобы скачать их. Дополнительную информацию см. по адресу: http://go.microsoft.com/fwlink/?LinkID=322105. Отсутствует следующий файл: ..\packages\MSTest.TestAdapter.1.4.0\build\net45\MSTest.TestAdapter.props.
========== Сборка: 0 успешно, 3 неудачно, 0 актуально, 0 пропущено ==========
```
Тогда это становится читабельным.

> Я не знаю, почему в файле UnitTestOfTimetableOfClasses.csproj указывается (и в прошлых нормальных коммитах) для импорта путь к ../packages/... которой нет в проекте. Зачем нужен этот packages и почему его в проекте нет

packages это папка в которую будут устанавливаться пакеты из NuGet. Ее нет в репозитории и не должно быть. Это инсталируемые пакеты. Видимо вы недавно склонировали проект и получили эту проблему. Вам нужно установить через диспетчер пакетов NuGet недостающие пакеты.

>Зачем вообще в файле UnitTestOfTimetableOfClasses.csproj указываются ссылки на эти ресурсы

Начнем с того, что эти пакеты нужны для тестирования и есть некоторая совместимость между версиями фреймворка и пакетами тестирования.

> Где найти документацию?

Ответ прост в интернете на официальных сайта майкрософт.

> И нужно ли на основании всего вышеизложенного менять что-то в файле UnitTestOfTimetableOfClasses.csproj

Ни в коем случае, если вы только не докажете почему это нужно сделать.

**Comment by NordScandinavian** [comment]
Где мне узнать имя пакета, который нужно установить?
Конкретное имя, которое я смогу прописать в командной строке (или где-то в менеджере NuGet)

**Comment by NordScandinavian** [comment]
Разобрался
Уточняю

"Исправить сбои в автотестах"
Что конкретно надо сделать?
Поправить тесты чтобы выполнялись (проблема в них)
Или поправить код чтобы тесты выполнялись (проблема в коде)?
@YuriSilenok

**Comment by NordScandinavian** [comment]
Идём дальше
Столкнулся с непреодолимой проблемой в методе CInstitute.Insert

![image](https://user-images.githubusercontent.com/47521360/86500826-8872e380-bd9c-11ea-8338-a0f4c88fb60d.png)


Для того, чтобы понять, что делать дальше - что менять - нужно знать структуру и связи таблиц
Где я могу посмотреть структуру и связи таблиц проекта?

Кроме этого, нашёл проблему в коде, связанную с неверной валидацией в классе MInstitute

![image](https://user-images.githubusercontent.com/47521360/86500833-a6404880-bd9c-11ea-9706-f12fb85bc6f8.png)

Метод не учитывает такие символы как ( ) -

Отчёт по работе

**Comment by YuriSilenok** [comment]
> Разобрался
> Уточняю
> 
> "Исправить сбои в автотестах"
> Что конкретно надо сделать?
> Поправить тесты чтобы выполнялись (проблема в них)
> Или поправить код чтобы тесты выполнялись (проблема в коде)?
> @YuriSilenok 

Вы проектируете тесты, они могут оставаться прежними или измениться. Если они прежние, то причина сбоя две. Или появилось новое ограничение и тесты устарели или что-то стало не правильно работать. Тогда вы поднимаете баг и бросает ссылку сюда. Свои баги справлять нельзя.

**Comment by YuriSilenok** [comment]
> Идём дальше
> Столкнулся с непреодолимой проблемой в методе CInstitute.Insert
> 
> ![image](https://user-images.githubusercontent.com/47521360/86500826-8872e380-bd9c-11ea-8338-a0f4c88fb60d.png)
> 
> 
> Для того, чтобы понять, что делать дальше - что менять - нужно знать структуру и связи таблиц
> Где я могу посмотреть структуру и связи таблиц проекта?
> 
> Кроме этого, нашёл проблему в коде, связанную с неверной валидацией в классе MInstitute
> 
> ![image](https://user-images.githubusercontent.com/47521360/86500833-a6404880-bd9c-11ea-9706-f12fb85bc6f8.png)
> 
> Метод не учитывает такие символы как ( ) -
> 
> Отчёт по работе

Все связи вы можете найти в библиотеке классов в файле рефдата

**Comment by YuriSilenok** [comment]
> Метод не учитывает такие символы как ( ) -

Поднимите баг

**Comment by NordScandinavian** [comment]
> Все связи вы можете найти в библиотеке классов в файле рефдата

Я не могу по этому файлу понять, какие ограничения на вставку у меня есть, потому что конкретно всё ломается в методе вставки
И поэтому надо знать, какая структура хранения данных применяется и знать её технические особенности
Поэтому где я это могу взять, не зная структуры проекта до этого?

**Comment by NordScandinavian** [comment]
Вопрос такой
Что осталось сделать ещё?
Тесты поправил, в соответствии с ограничениями, сценарии составлены верно но не учтены как раз таки эти ограничения
Мне внести это в Pre-condition или не стоит?

**Comment by YuriSilenok** [comment]
Осталось научится вести ветки как положено.

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1095 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1095 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1095 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1095 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1095 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1095 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1095 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1095 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1095 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1095 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1095 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1095 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1095 давно не было активности

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by NordScandinavian** [comment]
Прошу вернуть задачу, разбирался с нюансами оформления графов

**Comment by YuriSilenok** [comment]
> Прошу вернуть задачу, разбирался с нюансами оформления графов

А где тогда промежуточные результаты за 4 дня?
Почему их нет?
![image](https://user-images.githubusercontent.com/14871471/91541371-ecd99b80-e924-11ea-954d-bd1d9f93faaf.png)

**Comment by YuriSilenok** [comment]
В место этой задачи вы можете взять задачу #1199

**Comment by NordScandinavian** [comment]
2 дня ждал проверки, на второй день после проверки сделал изменения.

**Comment by YuriSilenok** [comment]
Вам было сказано

> 2 дня ждал проверки, на второй день после проверки сделал изменения.

Ну давайте, покажите, какие работы Вы проверили?

**Comment by NordScandinavian** [comment]
@YuriSilenok, здравствуйте. Хочу разобраться с активностью в этой задаче. Может, и не вернуть задачу, но на будущее, чтобы понимать принцип.
24.08 были залиты изменения, ожидал проверки коллегами.
26.08 был оставлен комментарий с ошибкой, 
28.06 исправления по комментарию были произведены и залиты.
По идее, правило 2 дней было соблюдено, активность была создана обсуждением ошибок.
Я правильно понял ситуацию?
![image](https://user-images.githubusercontent.com/47521360/91642227-4bd90680-ea32-11ea-92fc-0f4b282deda2.png)
![image](https://user-images.githubusercontent.com/47521360/91642325-2698c800-ea33-11ea-9096-3ce57fe117ba.png)

**Comment by YuriSilenok** [comment]
Вы можете забрать свою задачу

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by NordScandinavian** [comment]
@YuriSilenok , здравствуйте, прошу вернуть задачу, в ней активность была 13 часов назад. 
Прошу проверить пул реквест, он имеет необходимое кол-во аппрувов.

**Comment by NordScandinavian** [comment]
@YuriSilenok , прошу проверить в пул реквесте отчёты, необходимое кол-во аппрувов есть.

**Comment by YuriSilenok** [comment]
Мне приходят уведомления о запросах на проверку и о проверках других участников команды. Учитывая новые правила валидация, можно больше не писать об этом в основной задаче.

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности. Активность по основной задаче #1095 составляет 3 дней. Активность в ветке task-1095 составляет 10 дней. Активность по запросу #1329 составляет 3 дней. Нет запросов, которые должен проверить преподаватель

**Comment by YuriSilenok** [comment]
У вас есть шанс.

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности. Активность по основной задаче #1095 составляет 10 дней. Ветка отсутствует. Запрос отсутствует. Нет запросов, которые должен проверить преподаватель

**Comment by NordScandinavian** [comment]
Прошу не снимать задачу по неактивности. Болел, не мог сесть за задачи, не позволяло состояние.

**Comment by YuriSilenok** [comment]
следите пожалуйста за дедлайнами по вашим задачам.
правильно предупреждать в первый день больничного.
завтра вечером, например, вы можете написать о том. когда вы приступите к выполнению задач или когда вас выписывают или когда это станет известно. 
держите нас в курсе.

**Comment by NordScandinavian** [comment]
> следите пожалуйста за дедлайнами по вашим задачам.
> правильно предупреждать в первый день больничного.
> завтра вечером, например, вы можете написать о том. когда вы приступите к выполнению задач или когда вас выписывают или когда это станет известно.
> держите нас в курсе.

Сегодня приходил врач, направил завтра на выписку. 
Завтра же приступлю к работе вновь

**Comment by YuriSilenok** [comment]
Хорошо

**Comment by NordScandinavian** [comment]
> Хорошо

Состояние ухудшилось, оставили на больничном до 02.10, прошу прощения за отсутствие в рабочем составе.

**Comment by YuriSilenok** [comment]
> > Хорошо
> 
> Состояние ухудшилось, оставили на больничном до 02.10, прошу прощения за отсутствие в рабочем составе.

Главное что предупредили, спасибо.

**Comment by YuriSilenok** [comment]
Задача с Вас  снята, так как по ней давно не было активности. Активность по основной задаче #1095 составляет 3 дней. Активность в ветке issue-1095 составляет 2 дней. Активность по запросу #1358 составляет 2 дней. Нет запросов, которые должен проверить преподаватель

**Comment by YuriSilenok** [comment]
Задача с Вас  снята, так как по ней давно не было активности. Активность по основной задаче #1095 составляет 40 дней. Активность в ветке issue-1095 составляет 33 дней. Активность по запросу #1358 составляет 13 дней. Нет запросов, которые должен проверить преподаватель

**Comment by YuriSilenok** [comment]
Ветка issue-1095 удалена
