### ISSUE TITLE
Исправить сбои в автотестах расположенных в файле UT_Insert_CInstitute

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#1096]
- Составить тесты методом белого ящика и [предоставить отчет](https://docs.google.com/document/d/1H6353mZjLjMmCq-1A7IrnKdwBUQXyg81wjauXlad3XY/edit) на гитхаб
- Перенести комментарии методов в шаблон `///`
- Комментарии должны совпадать с описанием тестового сценария 

Этап тестирования #1182

**Comment by YuriSilenok** [comment]
Задача снята по бездействию

**Comment by DemiKor** [comment]
Тест не выполняется из-за связи таблиц
![image](https://user-images.githubusercontent.com/36473373/60917894-9d588c00-a29a-11e9-8a8d-94fa320c1dc4.png)

**Comment by YuriSilenok** [comment]
Вы знаете как это исправить?

**Comment by DemiKor** [comment]
Можно добавить запись, но там слишком много связей получается

**Comment by YuriSilenok** [comment]
Вы можете сделать более универсальное, написать метод, который бы создавал реф дату один раз.

**Comment by DemiKor** [comment]
А где его прописать?

**Comment by YuriSilenok** [comment]
В библиотеке есть рефдата, в ней Создайте закрытый статический метод Init. Вызовите его в конце конструктора рефдаты.

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by Heriuple** [comment]
Веха была изменена.
Не совсем понятно, как именно использовать метод белого ящика, в данной ошибке.
Граф строить требуется, по условиям добавления полей университета?

![image](https://user-images.githubusercontent.com/49808925/86491309-1e921400-bd73-11ea-981d-5277fa629fe4.png)

**Comment by YuriSilenok** [comment]
Вы должны изучить код метода insert и для него строить, выходными параметрами или состоянием системы вы создаёте лишь условия для прохождения какого либо маршрута

**Comment by Heriuple** [comment]
![image](https://user-images.githubusercontent.com/49808925/86493551-9f084300-bd7a-11ea-8e9d-b400ea62c0c3.png)
![image](https://user-images.githubusercontent.com/49808925/86493563-a92a4180-bd7a-11ea-971c-0f6319a8f625.png)
Граф должен выглядеть в таком ключе?
Прошу прощения за использование отличного от других редактора

**Comment by Heriuple** [comment]
Прошу прощения, что использовал отличный от других редактор

**Comment by Heriuple** [comment]
Здравствуйте, Юрий Викторович. Проработал таблицу тестирования, нужно глубже уходить, в метод добавления строк или так достаточно?

![image](https://user-images.githubusercontent.com/49808925/86511642-c2c39b80-be03-11ea-9d99-788a598d29eb.png)

**Comment by YuriSilenok** [comment]
Жду от вас ссылку на гугл документ со всеми расчетами

**Comment by Heriuple** [comment]
https://docs.google.com/document/d/1De5UsTnpPy3oPA5Gcd2JWyQGcfZS7ip0MVPxgiQGTpc/edit?usp=sharing
Большая часть документа это скриншоты , из-за работы на разных устройствах с разным программным обеспечением, прошу прощения.

**Comment by YuriSilenok** [comment]
В связи с новыми правилами, жду вашего отчета на гитхаб, обсуждение в запросе

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1096 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1096 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1096 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1096 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1096 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1096 давно не было активности

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by YuriSilenok** [comment]
Устаревшая ветка для этой задачи будет удалена в ближайшее время

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by YuriSilenok** [comment]
Устаревшая ветка для этой задачи будет удалена в ближайшее время

**Comment by YuriSilenok** [comment]
> Устаревшая ветка для этой задачи будет удалена в ближайшее время

удалена
