### ISSUE TITLE
Разработать тестовые сценарии для вкладки Даты формы Параметры

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#1098]
Разработать сценарии тестирования для функционального тестирования.
Задача реализована в Story #518

**Comment by badsster** [comment]
[Ссылка на сценарий](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)
task-1098

**Comment by YuriSilenok** [comment]
Ожидаемый результат прописать к каждому шагу.

**Comment by YuriSilenok** [comment]
Если в течении 7 дней не будет активности, задача будет закрыта без возмложности открытия.

**Comment by YuriSilenok** [comment]
закрыта по бездействию

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу
