### ISSUE TITLE
Ликвидация долгов за Sprint 4

### ISSUE THREAD

**Issue by bolotovaksenya** [Students-of-the-city-of-Kostroma/Student-timetable#1099]
#1035
#1039
#288
#1041 
#1105

**Comment by YuriSilenok** [comment]
найденный баг #1035 зачтен как 1 из 8 тасков

**Comment by YuriSilenok** [comment]
найденный баг #1039 зачтен как 2 из 8 тасков, вы можете исправить этот баг, тогда он зачтется как еще одна задача.

**Comment by bolotovaksenya** [comment]
@YuriSilenok , почему Вы считаете, что я должна сделать 8 тасков
Если я уже подняла 4 бага и их же исправила
#1035:  #1056 
#1039 : #1059 
#288:  #1101 
#1041:   #1102
 я получается закрыла спринт

**Comment by YuriSilenok** [comment]
> Если я уже подняла 4 бага и их же исправила

Потому что Вы исправили их в ветке для таска, а мержа, на тот момент, небыло.

Я исхожу из тех задач, кторые здесь перечислены.
Спринт без команды альтернативен 8 задачам.
Скажите, вы смотрите на оповещения, у Вас заопрувелные запросы по 10 дней весят, когда я их закрыл, тогда Вы только их переоткрываете и мержите.
Давайте посчитаем как у вас дела на настоящий момент.

1. #1035 - найден баг - нужен ретест в ветке Testing
2. #1056 - исправлен баг #1035
3. #1039 - найден баг - нужен ретест в ветке Testing
4. #1059 - исправлен баг #1039
5. #288 - Не Вы нашли этот баг
6. #1101 - ожидает мержа
7. #1041 - найден баг - нужен ретест в ветке Testing после мержа #1102
8. #1102 - ожидает мержа

Итог: 7 потенциальных тасков из которых законченыв полностью 2 мержа.

**Comment by bolotovaksenya** [comment]
@YuriSilenok , ожидающие мержа сделала, ретесты так же провела

**Comment by YuriSilenok** [comment]
Вы писали что Вам не приходит оповещение.
Я проверил эту информацию, гитхаб оповещает пользователей об этом.
![image](https://user-images.githubusercontent.com/14871471/59947702-9fd37d00-9476-11e9-8a6f-3ca5ce7e4ad0.png)

**Comment by YuriSilenok** [comment]
После мержа ветки нужно удалять

**Comment by YuriSilenok** [comment]
1. #1035 - зачтено
2. #1056 - удалить ветку
3. #1039 - зачтено
4. #1059 - удалить ветку
5. #1101 - удалить ветку
6. #1041 - зачтено
7. #1102 - удалить ветку
8. нужна еще одна задача

**Comment by bolotovaksenya** [comment]
@YuriSilenok , ветки удалены

**Comment by YuriSilenok** [comment]
8 таск будет?

**Comment by YuriSilenok** [comment]
вижу

**Comment by YuriSilenok** [comment]
1. #1035 - зачтено
2. #1056 - зачтено
3. #1039 - зачтено
4. #1059 - зачтено
5. #1101 - зачтено
6. #1041 - зачтено
7. #1102 - зачтено
8. #1105 - Уточнить правило проверки ожидаемого результата

**Comment by YuriSilenok** [comment]
1. #1035 - зачтено
2. #1056 - зачтено
3. #1039 - зачтено
4. #1059 - зачтено
5. #1101 - зачтено
6. #1041 - зачтено
7. #1102 - зачтено
8. #1105 - зачтено

Спринт зачтен
