### ISSUE TITLE
Реализовать метода Update(Model model) сущности Group

### ISSUE THREAD

**Issue by Mikleproxorov** [Students-of-the-city-of-Kostroma/Student-timetable#11]
**Поведение:**
в метод передается объект, проверяется его существование в таблице, если такой есть, далее метод изменяет информацию о существующей группе в том случае если поля
       

`       byte population;`
`        string cipher;`

являются уникальными и не пустыми (производится проверка). Если изменение произошло, то метод вернет истину, в других случаях метод возвращает ложь.
[Ссылка](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit?usp=sharing) на диаграмму классов.

**Comment by YuriSilenok** [comment]
Добрый день.

- Что бы я с не асанить на меня
- Нет дискрипшена
- нет меток
- нет вехи

Спасибо

**Comment by Mikleproxorov** [comment]
Что такое "асанить" и как это делается?
Что такое вехи?
Также не совсем понимаю что надо написать в дискрипшене и как ставить метки.


вт, 5 февр. 2019 г. в 17:10, Юрий Силенок <notifications@github.com>:

**Comment by YuriSilenok** [comment]
![image](https://user-images.githubusercontent.com/14871471/52280455-009d6580-296d-11e9-8457-5de1b1df4cc0.png)
![image](https://user-images.githubusercontent.com/14871471/52280493-13179f00-296d-11e9-8606-aa85da90dea8.png)
Вы можете найти эти атрибуты с права от задачи
![image](https://user-images.githubusercontent.com/14871471/52280512-2460ab80-296d-11e9-8fcc-cc9716ad867b.png)

**Comment by YuriSilenok** [comment]
Нет дискрипшена
В целом вы уже близки к истине.

**Comment by Mikleproxorov** [comment]
А что конкретно должно быть в дескрипошене?

вт, 5 февр. 2019 г. в 17:55, Юрий Силенок <notifications@github.com>:

**Comment by YuriSilenok** [comment]
[Здесь](https://gitlab.com/YuriSilenok/Student-timetable/issues) вы найдете исчерпывающее количество примеров.

**Comment by YuriSilenok** [comment]
Я так и не увидел дискрипшен

**Comment by Mikleproxorov** [comment]
Готов (наверное)

вт, 5 февр. 2019 г. в 18:19, Юрий Силенок <notifications@github.com>:

**Comment by YuriSilenok** [comment]
Зачтено

**Comment by YuriSilenok** [comment]
Здравствуйте @netever,
Это Ваша новая задача на реализацию.
Спасибо.

**Comment by YuriSilenok** [comment]
@netever зачтено
