### ISSUE TITLE
Создать форму редактирования или добавления записи таблицы.

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#110]
Реализована в ветке task-110-1
Форма имеет имя AddOrEditDirectory и минимальный размер 266;300
Вызывается не модально из формы **Справочники** (меню Справочники-Справочники) при нажатии на кнопку **Добавить** или при двойном клике ЛКМ по строке или ячейке таблицы.
Заголовок формы должен носить одно из двух названий: **Редактировать запись** или **Добавить запись**. Какой именно будет заголовок зависит от вызванного метода перед показом этой формы.
На форме располагается элемент управления TableLayoutPanel. Dock:Fill. До загрузки данных в форму содержит 1 строку и 2 столбца. Нижняя левая ячейка содержит элемент FlowLayoutPanel высота панели 44px. Dock:Top. ColumnSpan:2.  В контейнере элемента FlowLayoutPanel размещены 3 кнопки размер каждой 75*37px. расположены с лева на право в порядке их перечисления ниже:
- **Отмена**
- **Создать и очистить** если вызван метод по созданию новой строки или **Изменить и очистить** если вызван метод по изменению строки.
- **Создать и закрыть** если вызван метод по созданию новой строки или  **Изменить и закрыть** если вызван метод по изменению строки.
Форма имеет два метода:
- public void NewRow(DataRow dataRow) - при вызове этого метода, устанавливается имя заголовка формы **Добавить запись** и устанавливает имена кнопок **Создать и очистить** и **Создать и закрыть**
- public void EditRow(DataRow dataRow) - при вызове этого метода, устанавливается имя заголовка формы **Редактировать запись** и устанавливает имена кнопок **Изменить** и **Изменить и закрыть**

**Comment by purplegen** [comment]
Здравствуйте, @YuriSilenok. 

Как мне реализовывать задачу, если форма в которой надо реализовать задачу еще не создана?

Спасибо.

**Comment by YuriSilenok** [comment]
Здравствуйте.

Уточнил заголовок задачи. Я бы ожидал что Вы создадите форму согласно описания этой задачи.
Уточните, что Вы имеете ввиду под "форма в которой надо реализовать".

Спасибо.

**Comment by purplegen** [comment]
@YuriSilenok 

Я думал, что помимо создания формы, нужно еще прописать её вызов.

Спасибо.

**Comment by YuriSilenok** [comment]
@isengrims 

Теперь Ваш вопрос понятен.
Нет, ее вызов реализовывать не нужно, так как, Вы правильно подметили, вызывающей формы нет.
В место этого добавил Вам две заглушки.
На них Вы можете реализововать вызов вашей формы в различных режимах.
Не забудте выполнить команду git pull для ветки Testing
![image](https://user-images.githubusercontent.com/14871471/53731507-07e06200-3e8c-11e9-9d8b-baed84de15df.png)

**Comment by YuriSilenok** [comment]
Здравствуйте.
До конца задача еще не решена.
Вы выполнили [мерж ](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/commit/62a7f7cbc2686fb7ae46c9860281258c8ad8c680)из ветки Testin в ветку task-110-1.
При этом было удалено часть элементов меню, которыми вызывалась Ваша форма в различных режимах.
Вам нужно их восстановить создав ветку task-110-2 из ветки Testing
Плюс к этому, в момент решения конфликта, ветка Testing имела состояние кода при котором проект не мог запуститься из-за многочисленных ошибок. И Вашу ветку попали эти изменения.
На данный момент эта проблема решена.

**Comment by purplegen** [comment]
@YuriSilenok 

Т.е мне сейчас нужно только восстановить кнопки?

Спасибо

**Comment by YuriSilenok** [comment]
Зачтено
