### ISSUE TITLE
Ввод некорректных данных в справочнике "ВУЗы" в поле "Фактический адрес"

### ISSUE THREAD

**Issue by bolotovaksenya** [Students-of-the-city-of-Kostroma/Student-timetable#1105]
Название ветки:17-ИСбо-2а-7
Баг воспроизводиться в v0.20-Testing
Шаги реализации бага:
1.Открыть справочник "ВУЗы"
![image](https://user-images.githubusercontent.com/47633289/59948023-85e66a00-9477-11e9-8d21-940b83f1d2fb.png)
2. Нажать "Добавить"
3. В поле "Краткое название" ввести "КГУ"
4. В поле "Полное название" ввести "Костромской Государственный Университет"
5. В поле "Фактический адрес" ввести "1"
6. В поле "Юридический адрес" ввести "1"
7. В поле "ФИО ректора" ввести "Наумов Александр Рудольфович"
8. В поле "Почта" ввести "info@kstu.edu.ru"
9. В поле "Телефон" ввести "84942317960"
10. В поле "ИНН" ввести "4401006286"
![image](https://user-images.githubusercontent.com/47633289/59948050-a8788300-9477-11e9-9653-26bc57e53cb1.png)
11. Нажать "сохранить"
Ожидаемый результат:
Появится сообщение об ошибке:"Некорректный ввод данных" Длина записи должна быть не менее 2 символов и должны присутствовать буквы
Фактический результат:
![image](https://user-images.githubusercontent.com/47633289/59948441-c1356880-9478-11e9-92c8-647025f550f0.png)
#1099

**Comment by YuriSilenok** [comment]
В ожидаемый результат необходимо прописать привило, по которому определяется что фактический адрес введен верно.

**Comment by bolotovaksenya** [comment]
@YuriSilenok исправила

**Comment by YuriSilenok** [comment]
зачтено

**Comment by YuriSilenok** [comment]
@litdex зачтено

**Comment by YuriSilenok** [comment]
Этот таск не может быть выдан в качестве ликвидации задолженности.
Необходимо проверить воспроизводимость бага в ближайшем релизе.

**Comment by YuriSilenok** [comment]
не воспроизводится, но требует конкретизации описания поведения
