### ISSUE TITLE
В справочник "Преподаватель" невозможно добавить преподавателя с теми же параметрами что уже есть

### ISSUE THREAD

**Issue by venecon1** [Students-of-the-city-of-Kostroma/Student-timetable#1131]
1. Добавляем в справочник преподавателя со следующими данными
![image](https://user-images.githubusercontent.com/52324023/60701497-9b8e7180-9f04-11e9-80c7-1f3cf0b36b8b.png)
2.Добавляем ещё одного преподавателя с теми же данными

Ожидаемый результат: Добавиться новый преподаватель.
Фактический выдает ошибку:
![image](https://user-images.githubusercontent.com/52324023/60701589-ef00bf80-9f04-11e9-9143-f5ff7008d8db.png)

Предположительное решение: Так как поля в форме не могут быть уникальными, ибо на одной и той же кафедре может быть два разных преподавателя с одними данными. Поэтому должно быть уникальной поле наподобие номера телефона или серии и номера паспорта.

**Comment by YuriSilenok** [comment]
Добавить в качестве первичного ключа ИНН физ.лица. ИНН не относится к категории персональных данных.
@venecon1 зачтено в (ТРПО КП) 16-ИСбо-2

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
