### ISSUE TITLE
Неверное название формы "Добавить вид занятия"

### ISSUE THREAD

**Issue by venecon1** [Students-of-the-city-of-Kostroma/Student-timetable#1144]
1.Открыть Справочники-Вид занятия
2.Нажать кнопку Добавить
Ожидаемый результат: Добавить вид занятия
Фактический результат: AddTypesOfOccupations
![image](https://user-images.githubusercontent.com/52324023/61030161-75b21280-a3c5-11e9-8188-4497e7ee7e13.png)

**Comment by YuriSilenok** [comment]
Зачтено за найденый баг.

**Comment by DemiKor** [comment]
Балл в счет зачета

**Comment by YuriSilenok** [comment]
зачтено в ТРПО

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
