### ISSUE TITLE
При изменении размера формы "Добавить вид занятия" кнопки элементы окна не меняются

### ISSUE THREAD

**Issue by venecon1** [Students-of-the-city-of-Kostroma/Student-timetable#1145]
Релиз v0.20-Testing
1.Зайти Справочники-Вид занятия
2.Нажать добавить
3.Изменить размер окна
Ожидаемый результат: элементы ввода привязаны к правому краю формы, а кнопки к правому нижнему краю
Фактический результат: элементы не меняют своего положения
![image](https://user-images.githubusercontent.com/52324023/61030469-19032780-a3c6-11e9-8ca7-f08d248fa3a6.png)

**Comment by YuriSilenok** [comment]
Опишите более конкретно поведение элементов формы с учетом этого комментария https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/1152#issuecomment-510578011 и я зачту как за найденый баг.

**Comment by YuriSilenok** [comment]
> элементы ввода привязаны к правому и нижнему краю формы

не согласен, они не должны быть призязаны к нижнему краю

я так и не увидел какое поведение должно быть у кнопок

**Comment by YuriSilenok** [comment]
зачтено как найденый баг

**Comment by YuriSilenok** [comment]
зачтено, приходите с направлением Ленина 20

**Comment by DariaMann** [comment]
Сегодня к 17:00 на Meetup можно?

**Comment by YuriSilenok** [comment]
Да
