### ISSUE TITLE
Неправильное изменение окна "Добавление ученой степени" при изменении его размера

### ISSUE THREAD

**Issue by venecon1** [Students-of-the-city-of-Kostroma/Student-timetable#1146]
Релиз v0.20-Testing
1.Зайти Справочники-Ученые степени
2.Нажать Добавить
3.Изменить размер окна
Ожидаемый результат: Окно и элементы плавно изменяются или запрещено изменение
Фактический результат: Окно увеличивается, элементы не меняются.
![image](https://user-images.githubusercontent.com/52324023/61031058-6d5ad700-a3c7-11e9-8f85-fd12113a042d.png)

**Comment by YuriSilenok** [comment]
Вертикального рястягивания не должно быть.
https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/1152#issuecomment-510578011
но вы моежете поднять баг на то, что у текстовых полей нет призязки к правому краю.

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
