### ISSUE TITLE
Неправильное изменение окна "Добавление преподавателя" при изменении его размера

### ISSUE THREAD

**Issue by venecon1** [Students-of-the-city-of-Kostroma/Student-timetable#1147]
Релиз v0.20-Testing
1.Зайти Справочники-Преподаватели
2.Нажать Добавить
3.Изменить размер окна
Ожидаемый результат: Окно и элементы плавно изменяются или запрещено изменение
Фактический результат: Окно увеличивается, элементы частично не меняются в ширь, и полностью не меняются в высоту.
![image](https://user-images.githubusercontent.com/52324023/61031313-f114c380-a3c7-11e9-9b4a-9cec6d3b7851.png)

**Comment by YuriSilenok** [comment]
https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/1152#issuecomment-510578011

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
