### ISSUE TITLE
Неправильное изменение окна "Добавление группы" при изменении его размера

### ISSUE THREAD

**Issue by venecon1** [Students-of-the-city-of-Kostroma/Student-timetable#1148]
Релиз v0.20-Testing
1.Зайти Справочники-Группы
2.Нажать Добавить
3.Изменить размер окна
Ожидаемый результат: Окно и элементы плавно изменяются или запрещено изменение
Фактический результат: Окно увеличивается, элементы частично не меняются в ширь, и полностью не меняются в высоту.
![image](https://user-images.githubusercontent.com/52324023/61031519-5b2d6880-a3c8-11e9-910c-9fcba82188b3.png)

**Comment by YuriSilenok** [comment]
https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/1152#issuecomment-510578011

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
