### ISSUE TITLE
Некорректное растягивание столбцов на форме "Аудитория" при растягивании формы в ширину.

### ISSUE THREAD

**Issue by venecon1** [Students-of-the-city-of-Kostroma/Student-timetable#1149]
Релиз v0.20-Testing
1.Зайти Справочники-Аудитория
2.Изменить размер окна в ширину.
Ожидаемый результат: Все столбцы изменятся равномерно
Фактический результат: Столбец Кафедра изменяет свой размер остальные нет.
![image](https://user-images.githubusercontent.com/52324023/61032018-4dc4ae00-a3c9-11e9-8a6f-d290e9651ac6.png)

**Comment by YuriSilenok** [comment]
Действительно, было такое требование.
Зачтено как найденый баг.

**Comment by YuriSilenok** [comment]
зачтено
