### ISSUE TITLE
Неправильное изменение окна "Добавить Университет" при изменении его размера

### ISSUE THREAD

**Issue by venecon1** [Students-of-the-city-of-Kostroma/Student-timetable#1150]
Релиз v0.20-Testing
1.Зайти Справочники-ВУЗы
2.Нажать Добавить
3.Изменить размер окна
Ожидаемый результат: Окно и элементы плавно изменяются или запрещено изменение
Фактический результат: Окно увеличивается, элементы не меняются в высоту.
![image](https://user-images.githubusercontent.com/52324023/61032333-e8bd8800-a3c9-11e9-8aad-347834b3b706.png)

**Comment by YuriSilenok** [comment]
https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/1152#issuecomment-510578011

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
