### ISSUE TITLE
Неправильное название формы "Добавить Учебную неделю"

### ISSUE THREAD

**Issue by venecon1** [Students-of-the-city-of-Kostroma/Student-timetable#1151]
Релиз v0.20-Testing
1.Зайти Справочники-Учебные недели
2.Нажать Добавить
Ожидаемый результат: Добавить Учебную неделю
Фактический результат: Добавить Преподавателя
![image](https://user-images.githubusercontent.com/52324023/61032733-aba5c580-a3ca-11e9-8987-16c3ecf57fe1.png)

**Comment by YuriSilenok** [comment]
Зачтено как найденый баг

**Comment by DemiKor** [comment]
Балл в счет зачета

**Comment by YuriSilenok** [comment]
зачтено в ТРПО

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
