### ISSUE TITLE
Неправильное изменение окна "Добавить Учебную неделю" при изменении его размера

### ISSUE THREAD

**Issue by venecon1** [Students-of-the-city-of-Kostroma/Student-timetable#1152]
Релиз v0.20-Testing
1.Зайти Справочники-Учебные недели
2.Нажать Добавить
3.Изменить размер окна
Ожидаемый результат: Окно и элементы плавно изменяются или запрещено изменение
Фактический результат: Окно увеличивается, элементы не меняются в высоту.
![image](https://user-images.githubusercontent.com/52324023/61032940-1f47d280-a3cb-11e9-88d2-fec8adb49715.png)

**Comment by YuriSilenok** [comment]
Вы не указали номер релиза где Вы нашли этот баг.

**Comment by YuriSilenok** [comment]
![image](https://user-images.githubusercontent.com/14871471/61045265-31ce0600-a3e3-11e9-8112-91d3867305f3.png)
Если это Релиз v0.20-Testing, тогда почему формы добавить преподавателя так сильно отличаются?

**Comment by venecon1** [comment]
> ![image](https://user-images.githubusercontent.com/14871471/61045265-31ce0600-a3e3-11e9-8112-91d3867305f3.png)
> Если это Релиз v0.20-Testing, тогда почему формы добавить преподавателя так сильно отличаются?

Это еще один баг описаный в данном https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/1151
Так как неправильное название формы

**Comment by YuriSilenok** [comment]
> Фактический результат: Окно увеличивается, элементы не меняются в высоту.

я бы сказал что это ожидаемое поведение, так как вводимые значения являются однострочными, а по условиям макета кнопки должны быть привязаны к провому и нижнему краю формы. Возможность изменять размер формы это доступная функция для всех форма в этом ПО.

**Comment by venecon1** [comment]
> > Фактический результат: Окно увеличивается, элементы не меняются в высоту.
> 
> я бы сказал что это ожидаемое поведение, так как вводимые значения являются однострочными, а по условиям макета кнопки должны быть привязаны к провому и нижнему краю формы. Возможность изменять размер формы это доступная функция для всех форма в этом ПО.

Тогда невозможность менять размер у некоторых окон это баг или по условию так было?

**Comment by YuriSilenok** [comment]
> > > Фактический результат: Окно увеличивается, элементы не меняются в высоту.
> > 
> > 
> > я бы сказал что это ожидаемое поведение, так как вводимые значения являются однострочными, а по условиям макета кнопки должны быть привязаны к провому и нижнему краю формы. Возможность изменять размер формы это доступная функция для всех форма в этом ПО.
> 
> Тогда невозможность менять размер у некоторых окон это баг или по условию так было?

Правило такое. Любые окна вызываемые через справочники должны иметь возможность менять свой размер. Так как вы занялись проблемой верстки, то обратите внимание что у многих окон нет минимальных размеров при которых внутренние элементы становяться нечитаемые или наезжаеют джруг на друга.

**Comment by DariaMann** [comment]
Здравствуйте @YuriSilenok 
В чем заключается данная задача?
Что именно нужно сделать? (постановка задачи не понятная)
Сама форма изменяется правильно, кнопки привязаны правильно, единственное что не так, дак это Название формы.
Спасибо

**Comment by YuriSilenok** [comment]
так все так здесь, человек который открывал этот баг ушел из дискуссии и задача повисла, мое видение макета говорит что фактический результат является ожидаемым. По иджее он должен был закрыть эту задачу, когды бы согласился что это не баг.
