### ISSUE TITLE
Краш приложения при добавлении Направления подготовки

### ISSUE THREAD

**Issue by DemiKor** [Students-of-the-city-of-Kostroma/Student-timetable#1153]
Баг воспроизводиться в Testing

Шаги реализации бага:

1. Вводим данные для добавления
![image](https://user-images.githubusercontent.com/36473373/61044095-8b810100-a3e0-11e9-891f-7351f9162371.png)

2. Жмем "Создать и закрыть"
3. Выскакивает предупреждение 
![image](https://user-images.githubusercontent.com/36473373/61044172-ac495680-a3e0-11e9-9a8b-1cb780d7cc94.png)
4. Жмем "Ок"
 
Ожидаемый результат:
1. Предупреждение закрывается
2. Остаётся экран заполнения данных

Фактический результат:
![image](https://user-images.githubusercontent.com/36473373/61044258-e31f6c80-a3e0-11e9-9517-fe7f2451f8d5.png)

**Comment by YuriSilenok** [comment]
Зачтено за найденый баг

**Comment by YuriSilenok** [comment]
зачтено

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
