### ISSUE TITLE
Создать метод заполнения рефдаты

### ISSUE THREAD

**Issue by DemiKor** [Students-of-the-city-of-Kostroma/Student-timetable#1157]
В классе RefData создать закрытый метод Init который заполняет каждую таблицу минимум по 3 записи. Метод вызвать в конце конструктора класса RefData

**Comment by YuriSilenok** [comment]
снято по бездействию

**Comment by YuriSilenok** [comment]
Зачтено за ЛР02
Возьмите следующую задачу #1177

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by ghost** [comment]
Здравствуйте,

Возможно, я что-то не понимаю, но добавить веху к задачам нужно мне или вы
это пишите для должников?

Спасибо.

вс, 28 июн. 2020 г. в 08:12, Юрий Силенок <notifications@github.com>:

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
