### ISSUE TITLE
У текстовых полей формы "Добавление ученой степени" нет привязке к краю

### ISSUE THREAD

**Issue by venecon1** [Students-of-the-city-of-Kostroma/Student-timetable#1161]
Релиз v0.20-Testing
1.Зайти Справочники-Ученые степени
2.Нажать Добавить
3.Изменить размер окна
Ожидаемый результат: Элементы привязаны к правой стороне
Фактический результат: Элементы статичны.
![image](https://user-images.githubusercontent.com/52324023/61073417-103e4000-a41e-11e9-8fca-54c8cad087bf.png)

**Comment by YuriSilenok** [comment]
зачтено как найденый баг

**Comment by YuriSilenok** [comment]
зачтено в ТРПО

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
