### ISSUE TITLE
Отсутствие минимального размера окна "Добавить ВУЗ"

### ISSUE THREAD

**Issue by venecon1** [Students-of-the-city-of-Kostroma/Student-timetable#1162]
Релиз: v20-Testing
1.Зайти в Справочники-Университет
2.Нажать кнопку добавить
3.Уменьшить окно в высоту
Ожидаемый результат : Кнопки остановятся у текстовых полей и не будут на них наезжать.
Фактический результат: Кнопки уходят на задний план за ИНН
![image](https://user-images.githubusercontent.com/52324023/61076113-2949ef80-a424-11e9-8ea1-7de4c4525c04.png)

**Comment by YuriSilenok** [comment]
зачтено
