### ISSUE TITLE
Отсутствие минимального размера окна "Добавление ученой степени"

### ISSUE THREAD

**Issue by venecon1** [Students-of-the-city-of-Kostroma/Student-timetable#1163]
Релиз: v20-Testing
1.Зайти в Справочники-Ученая степень
2.Нажать кнопку добавить
3.Уменьшить размер окна
Ожидаемый результат : Окно можно будет уменьшить до минимального размера и кнопки не будут наезжать
Фактический результат: Окно можно полностью уменьшить и кнопки уходят на задний план элементов ввода
![image](https://user-images.githubusercontent.com/52324023/61076447-f0f6e100-a424-11e9-9304-4679f6ad878b.png)
![image](https://user-images.githubusercontent.com/52324023/61076456-f81def00-a424-11e9-9b86-070163883a89.png)

**Comment by YuriSilenok** [comment]
зачтено
