### ISSUE TITLE
Отсутствие минимального размера окна "Добавить вид занятия"

### ISSUE THREAD

**Issue by venecon1** [Students-of-the-city-of-Kostroma/Student-timetable#1164]
Релиз: v20-Testing
1.Зайти в Справочники-Вид занятия
2.Нажать кнопку добавить
3.Уменьшить окно в высоту
Ожидаемый результат : Окно может быть уменьшено до определеного размера
Фактический результат: Окно можно сузить вплоть до одного только названия
![image](https://user-images.githubusercontent.com/52324023/61076661-6f538300-a425-11e9-8999-8d84599e9bfc.png)

**Comment by YuriSilenok** [comment]
зачтено
