### ISSUE TITLE
Отсутствие минимального размера окна "Добавить институт"

### ISSUE THREAD

**Issue by venecon1** [Students-of-the-city-of-Kostroma/Student-timetable#1165]
Релиз: v20-Testing
1.Зайти в Справочники-Институт
2.Нажать кнопку добавить
3.Уменьшить окно в высоту
Ожидаемый результат : Кнопки остановятся у текстовых полей и не будут на них наезжать, форму не возможно будет уменьшить до не читаемого текста
Фактический результат: Форму можно уменьшить до одного названия формы, кнопки уходят на задний план
![image](https://user-images.githubusercontent.com/52324023/61077421-08cf6480-a427-11e9-85c5-b30c1de61426.png)
![image](https://user-images.githubusercontent.com/52324023/61077434-11279f80-a427-11e9-8dc5-68fdcd41b0db.png)

**Comment by MaximTrapeznikov** [comment]
Здравствуйте @YuriSilenok
Подскажите пожалуйста, а в какую ветку мержить пулреквест?
Спасибо.

**Comment by YuriSilenok** [comment]
Testing

**Comment by YuriSilenok** [comment]
зачтено в (ТРПО) 17-ИСбо-2б
