### ISSUE TITLE
 Исправить сбои в автотестах расположенных в файле UT_Insert_CGroup 

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#1177]
- Составить тесты методом белого ящика и [предоставить отчет](https://docs.google.com/document/d/1H6353mZjLjMmCq-1A7IrnKdwBUQXyg81wjauXlad3XY/edit)
- Обновить [сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit)
- Перенести комментарии методов в шаблон `///`
- Комментарии должны совпадать с описанием тестового сценария

**Comment by ghost** [comment]
Здравствуйте.

Ряд тестов при проведении всех тестов не проходят, но при прогоне одного теста они проходят.
Что с ними делать?

Спасибо.

**Comment by YuriSilenok** [comment]
Здравсвуйте.

- я не вижу ветки в которой Вы вносите изменения, не держите изменения локально.
- то что тесты не проходят пачко, означает что одни тесты влияют на другие. Могу предположить что Вы не разобрались в чем именно проблема, но исправляется все стандартно, прекондитшеном для тестов.

Спасибо

**Comment by YuriSilenok** [comment]
Вы забыли удалить ветку

**Comment by YuriSilenok** [comment]
Зачтено в ЛР04

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
> Зачтено в ЛР04

**Comment by YuriSilenok** [comment]
Сбои воспроизводятся

**Comment by ZhizhikinIvan** [comment]
Ссылка на отчёт: https://docs.google.com/document/d/18LIF6k2ZP5xZom-4-y8Bb9HLqf4zR814ewl1bEfyipg/edit?usp=sharing

**Comment by YuriSilenok** [comment]
1 тест, не думаю что таблица должна быть обязательно пустой, что бы тест прошел
11 тест, избыточный, так как дублирует предыдущие тесты.

**Comment by ZhizhikinIvan** [comment]
Да, в первом тесте, таблица необязательно должна быть пустой. Поправил отчёт.

**Comment by YuriSilenok** [comment]
А что думаете про 11 тест, считаете его избыточным?

**Comment by ZhizhikinIvan** [comment]
11 тест по смыслу дублирует предыдущие, но в 11 тесте мы добавляем дважды абсолютно одинаковые данные и в других тестах мы этого не делали.

**Comment by YuriSilenok** [comment]
Да, мы ещё и парами не проверяем и тройками не проверяем. Мы хотим экономить ресурсы, так как исчерпывабщее тестирование недостедимо. Можете загуглить термин исчерпывающее тестирование. Невада цель решить задачу оптимизации, как за меньшее количества тестов проверить больше количество функционала. И по этому я предлагаю 11 тест убрать.

**Comment by YuriSilenok** [comment]
Да, мы ещё и парами не проверяем и тройками не проверяем. Мы хотим экономить ресурсы, так как исчерпывабщее тестирование недостедимо. Можете загуглить термин исчерпывающее тестирование. Невада цель решить задачу оптимизации, как за меньшее количества тестов проверить больше количество функционала. И по этому я предлагаю 11 тест убрать.

**Comment by ZhizhikinIvan** [comment]
Отчёт поправил.

**Comment by YuriSilenok** [comment]
У вас уже написаны автотесты что ставит статус passed?

**Comment by ZhizhikinIvan** [comment]
Да, написаны.

**Comment by YuriSilenok** [comment]
Тогда жду запроса для проверки

**Comment by YuriSilenok** [comment]
В ваших тестах предусмотрены проверки реляционных связей?

**Comment by ZhizhikinIvan** [comment]
Да, предусмотрены.

**Comment by YuriSilenok** [comment]
Жду размещения отчета на гитхаб, а раз так, то дальнейшее обсуждение в запросе.

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1177 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1177 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1177 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1177 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1177 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1177 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1177 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1177 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1177 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1177 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1177 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1177 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1177 давно не было активности

**Comment by YuriSilenok** [comment]
[Зачтено](https://docs.google.com/spreadsheets/d/1uBd4d3VvI4rYeuXkXmqLyEZSitS8K9pfVUDtM3i1Vg4/edit#gid=1029316146&range=K10)
