### ISSUE TITLE
Исправить сбои в автотестах расположенных в файле UT_Delete_CInstitute

### ISSUE THREAD

**Issue by Mikleproxorov** [Students-of-the-city-of-Kostroma/Student-timetable#1185]
- Составить тесты методом белого ящика и [предоставить отчет](https://docs.google.com/document/d/1H6353mZjLjMmCq-1A7IrnKdwBUQXyg81wjauXlad3XY/edit)
- Обновить [сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit)
- Перенести комментарии методов в шаблон `///`
- Комментарии должны совпадать с описанием тестового сценария 

Этап тестирования #1182

**Comment by Mikleproxorov** [comment]
Duplicate of #1095

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта
