### ISSUE TITLE
Исправить сбои в автотестах расположенных в файле UT_Delete_TrainigProfile

### ISSUE THREAD

**Issue by Mikleproxorov** [Students-of-the-city-of-Kostroma/Student-timetable#1186]
- Выявить причину сбоев в автотестах.
- При необходимости исправить автотесты и сценарии
- Перенести комментарии методов в шаблон `///`
- Комментарии должны совпадать с описанием тестового сценария 

Этап тестирования #1182

**Comment by YuriSilenok** [comment]
Ветку забыли удалить

**Comment by YuriSilenok** [comment]
Зачтено как лр04
