### ISSUE TITLE
Исправить сбои автотестов расположенных в файле UT_Delete_CTeacher

### ISSUE THREAD

**Issue by Mikleproxorov** [Students-of-the-city-of-Kostroma/Student-timetable#1187]
- Выявить причину сбоев в автотестах.
- При необходимости исправить автотесты и сценарии
- Перенести комментарии методов в шаблон `///`
- Комментарии должны совпадать с описанием тестового сценария 

Этап тестирования #1182

**Comment by YuriSilenok** [comment]
Какие есть обновления по этой задаче?

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1187 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1187 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1187 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1187 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1187 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1187 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1187 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1187 давно не было активности

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by YuriSilenok** [comment]
Устаревшая ветка для этой задачи будет удалена в ближайшее время

**Comment by YuriSilenok** [comment]
> Устаревшая ветка для этой задачи будет удалена в ближайшее время

Ветка удалена

**Comment by KoprovDmitry** [comment]
у меня возник вопрос, сбои автотестов в файле UT_Delete_CTeacher прокомментированы напротив методов
мне нужно исправить прокомментированый сломанный автотест?

**Comment by YuriSilenok** [comment]
> у меня возник вопрос, сбои автотестов в файле UT_Delete_CTeacher прокомментированы напротив методов
> мне нужно исправить прокомментированый сломанный автотест?

Ознакомьтесь с [этой](https://www.github.com/Students-of-the-city-of-Kostroma/Student-timetable/tree/dev/Docs%2FWhite-box%2FREADME.md) инструкцией.

**Comment by KoprovDmitry** [comment]
ознакомился и возник другой вопрос, следуя этой инструкции я должен сделать отчёт тестируемого метода Delete?
а так же, если я сделаю отчёт, то в каком формате его предпочтительно делать и куда его отправлять для проверки?

**Comment by YuriSilenok** [comment]
> ознакомился и возник другой вопрос, следуя этой инструкции я должен сделать отчёт тестируемого метода Delete?
> а так же, если я сделаю отчёт, то в каком формате его предпочтительно делать и куда его отправлять для проверки?

В идеале инструкция должна быть исчерпывающее, но это только первая версия. Поступи следующим образом. Вы поднимаете задачу с заголовком: "Улучшить методические рекомендации для белого ящика" в тело задачи вы перечислите что нужно добавить в инструкцию. В той задаче мы продолжим обсуждение со всей командой.

**Comment by KoprovDmitry** [comment]
Боюсь я не смогу поднять задачу из-за двух причин: 1) где поднять задачу; 2) незнание как поднимать задачи.
Вопросы возникли в результате ограничения времени по выполнению работы ( активности работы ), чем грозит мне закрытием выполнения данного задания.

**Comment by YuriSilenok** [comment]
> Боюсь я не смогу поднять задачу из-за двух причин: 1) где поднять задачу; 2) незнание как поднимать задачи.
> Вопросы возникли в результате ограничения времени по выполнению работы ( активности работы ), чем грозит мне закрытием выполнения данного задания.

Если вы с компьютера, то в правом верхнем углу зелёная кнопка New Issue. Нажмите на неё.

**Comment by YuriSilenok** [comment]
Вопросы о том, как пользоваться git и github можно задавать в общий чат.

**Comment by KoprovDmitry** [comment]
я поднял задачу [1351](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/1351), можете проверить, правильно ли я поднял задачу?

**Comment by YuriSilenok** [comment]
Вам нужно исправить замечания

**Comment by KoprovDmitry** [comment]
я выявил причину сбоев автотеста, могу ли я добавить/изменить код по своему усмотрению?

**Comment by KoprovDmitry** [comment]
или мне сделать отчёт по выявленной причине сбоев автотеста, как по инструкции?

**Comment by YuriSilenok** [comment]
> я выявил причину сбоев автотеста, могу ли я добавить/изменить код по своему усмотрению?

Конечно, вы вправе делать в отдельной ветке все что угодно. Когда вы посчитаете что вме готово, вам нужно будет представить работу на проверку через pull request.

**Comment by YuriSilenok** [comment]
> или мне сделать отчёт по выявленной причине сбоев автотеста, как по инструкции?

Отчёт делается не по выявленным причинам. Вы берете указанный метод и составляет для него сценарии по белому ящику, потом автоматизация этих сценариев. Скорее всего часть существующих автотестов вы измените, вплодь до их количества.

**Comment by KoprovDmitry** [comment]
я обновил автотест UT_Delete_CTeacher используя отчёт по [методу тестирования "белый ящик"](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/White-box/README.md) в ветке task-1187, можете проверить на правильность выполнения ( правильность следования логике выполнения задачи )?

**Comment by YuriSilenok** [comment]
> я обновил автотест UT_Delete_CTeacher используя отчёт по [методу тестирования "белый ящик"](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/White-box/README.md) в ветке task-1187, можете проверить на правильность выполнения ( правильность следования логике выполнения задачи )?

Для того, что бы я что-то проверил, у вас должен быть создан запрос на проверку, где нужно указать в качестве проверяющих всю коману, включая меня. Вот список команды: 
VinogradovAlexandr781227
ifuwmnn
JennyShel18
NesgovorovVS
MyachevM
badsster
ZhizhikinIvan
NordScandinavian
Heriuple
Alphavite51

**Comment by YuriSilenok** [comment]
Об этом написано [здесь](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/task-1352/Docs/life-cycle.md).

**Comment by KoprovDmitry** [comment]
Ссылка не корректна ( [выдает ошибку](https://prnt.sc/uj2pq2) ), можете переотправить?

**Comment by YuriSilenok** [comment]
Да, теперь этот документ переехал в dev и теперь документ доступен [здесь](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/life-cycle.md)

**Comment by KoprovDmitry** [comment]
извините, но вторая ссылка в "В рамках созданной задачи создается ветка (branch), соответсвующая требованиям."
тоже некорректна в [документе](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/life-cycle.md)

**Comment by YuriSilenok** [comment]
> извините, но вторая ссылка в "В рамках созданной задачи создается ветка (branch), соответсвующая требованиям."
> тоже некорректна в [документе](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/life-cycle.md)

Действительно, не очень хорошо получилось, ссылка теперь работает, проверьте, пожалуйста.

**Comment by YuriSilenok** [comment]
Задача с Вас  снята, так как по ней давно не было активности. Активность по основной задаче #1187 составляет 3 дней. Активность в ветке issue-1187 составляет 2 дней. Запрос отсутствует. Нет запросов, которые должен проверить преподаватель

**Comment by YuriSilenok** [comment]
Ветка issue-1187 удалена
