### ISSUE TITLE
Исправить сбои в автотетстах расположенных в файле UT_Insert_CAcademicDegree

### ISSUE THREAD

**Issue by Mikleproxorov** [Students-of-the-city-of-Kostroma/Student-timetable#1188]
- Составить тесты методом белого ящика и [предоставить отчет](https://docs.google.com/document/d/1H6353mZjLjMmCq-1A7IrnKdwBUQXyg81wjauXlad3XY/edit)
- Обновить [сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit)
- Перенести комментарии методов в шаблон `///`
- Комментарии должны совпадать с описанием тестового сценария 

Этап тестирования #1182

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1188 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1188 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1188 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1188 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1188 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1188 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1188 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1188 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1188 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1188 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1188 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1188 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1188 давно не было активности

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by YuriSilenok** [comment]
Устаревшая ветка для этой задачи будет удалена в ближайшее время

**Comment by YuriSilenok** [comment]
> Устаревшая ветка для этой задачи будет удалена в ближайшее время

Ветка удалена
