### ISSUE TITLE
Исправить сбои автотестов расположенных в файле UT_Insert_CTitle

### ISSUE THREAD

**Issue by Mikleproxorov** [Students-of-the-city-of-Kostroma/Student-timetable#1192]
- Составить тесты методом белого ящика и [предоставить отчет](https://docs.google.com/document/d/1H6353mZjLjMmCq-1A7IrnKdwBUQXyg81wjauXlad3XY/edit)
- Обновить [сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit) указам у заголовка тест-комплекта ссылку на гугл документ с исследованием по белому ящику.
- Автоматизировать полученные сценарии
- Перенести комментарии методов в шаблон `///`
- Комментарии должны совпадать с описанием тестового сценария

**Comment by VinogradovAlexandr781227** [comment]
Приступил к выполнению задания

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Обсуждаем белый ящик тут.
Как правильно расставлять регионы?
Я считаю что в регионах у вас ошибка

**Comment by ZhizhikinIvan** [comment]
Юрий Викторович, поясните, какая у меня ошибка в регионах?

Я исходил из того, что в модели, 2 поля, каждое из которых должно быть уникальным. Поэтому у меня 3 региона: 
Первый (R1) для добавления новых данных.
Второй (R2) и третий (R3) проверяют уникальность каждого из полей.

**Comment by YuriSilenok** [comment]
Во первых слинкуйте запрос с задачей, без этого сложно искать ваш запрос что бы посмотреть отчет.

Во вторых , в управляющие графе всегда одна начальная вершина и одна конечная. Последняя скобка так же нумеруется.

**Comment by YuriSilenok** [comment]
Относительно регионов.
Один внешний регион, он как правило R1, остальные внутренние, это зевать что они со всех сторон ограничены рёбрами графа.

**Comment by ZhizhikinIvan** [comment]
Ссылка на задачу: https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1286

Добавил конечную вершину, изменил граф. 
Прошу провести ревью.

**Comment by YuriSilenok** [comment]
Линк сделали не правильно, сы сослались на комментарий из запроса.

**Comment by YuriSilenok** [comment]
Потрудитесь оформить все в виде гугл документа и ссылку предоставить здесь а не в запросе

**Comment by ZhizhikinIvan** [comment]
Ссылка на отчёт: https://docs.google.com/document/d/1pgoKuwV36YeAschSRpbugzQxA1XXBiTPVSjkndgf9iM/edit?usp=sharing

**Comment by YuriSilenok** [comment]
Разбираем ошибки в чате

пт, 3 июл. 2020 г., 23:01 Жижикин Иван <notifications@github.com>:

**Comment by YuriSilenok** [comment]
[Зачтено](https://docs.google.com/spreadsheets/d/1uBd4d3VvI4rYeuXkXmqLyEZSitS8K9pfVUDtM3i1Vg4/edit#gid=1029316146&range=J10)
