### ISSUE TITLE
Исправить сбои в автотестах расположенных в файле UT_Update_CEnclosurse

### ISSUE THREAD

**Issue by Mikleproxorov** [Students-of-the-city-of-Kostroma/Student-timetable#1194]
- Выявить причину сбоев в автотестах.
- При необходимости исправить автотесты и сценарии
- Перенести комментарии методов в шаблон `///`
- Комментарии должны совпадать с описанием тестового сценария 

Этап тестирования #1182

**Comment by YuriSilenok** [comment]
Зачтено
