### ISSUE TITLE
Исправить сбои автотестов расположенных в файле UT_Update_CTeacher

### ISSUE THREAD

**Issue by Mikleproxorov** [Students-of-the-city-of-Kostroma/Student-timetable#1196]
-     Выявить причину сбоев в автотестах.
-     При необходимости исправить автотесты и сценарии
-     Перенести комментарии методов в шаблон `///`
-     Комментарии должны совпадать с описанием тестового сценария

**Comment by FvckNeighbors** [comment]
Duplicate of #1036

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу
