### ISSUE TITLE
Разработать форму "Нагрузка"

### ISSUE THREAD

**Issue by FvckNeighbors** [Students-of-the-city-of-Kostroma/Student-timetable#1198]
Разработать форму "Нагрузка" по макету.
Назвать файл с формой "AcademicLoad"

Форма состоит из:
1. Два выпадающих списков
2. Таблица, в которой следующие столбцы: Группа (поток), Часов всего, Дисциплина, Преподаватель, Вид занятия
Таблицу заполнять не нужно
3. Кнопки: Удалить/Изменить/Добавить. Кнопки должны быть привязаны к правому нижнему углу. 

Ссылка на [макеты](https://docs.google.com/presentation/d/1sLVZc-DRTHR1IAhNWKoXsJriw-2qOXptdX6BDLMNxcU/edit?usp=sharing)
![image](https://user-images.githubusercontent.com/47756995/65393489-d4aee300-dd89-11e9-97a4-75537a338934.png)

**Comment by YuriSilenok** [comment]
Приатачит сохраненное изображение слайда

**Comment by NesgovorovVS** [comment]
@YuriSilenok  добавил

**Comment by YuriSilenok** [comment]
Задачи закрываю я, после того как выставлю баллы.
В бэклоге я буду их помечать серым фоном, те задачи, которые были зачтены.
Не забывайте после удачного мержа перевешивать на меня задачи.

**Comment by YuriSilenok** [comment]
Зачтено
