### ISSUE TITLE
Разработать форму "Добавить нагрузку"

### ISSUE THREAD

**Issue by FvckNeighbors** [Students-of-the-city-of-Kostroma/Student-timetable#1199]
Разработать форму "Добавить нагрузку" по макету.
Назвать файл с формой "AddAcademicLoad"

Кнопки "Отмена" и "Сохранить" должны быть привязаны к правому нижнему углу.

Ссылка на [макеты](https://docs.google.com/presentation/d/1sLVZc-DRTHR1IAhNWKoXsJriw-2qOXptdX6BDLMNxcU/edit?usp=sharing)
![Макет](https://user-images.githubusercontent.com/47320314/65393927-3bcf9600-dd90-11e9-846f-3175c5971eb0.png)

**Comment by YuriSilenok** [comment]
> Ссылка на [макеты](https://docs.google.com/presentation/d/1sLVZc-DRTHR1IAhNWKoXsJriw-2qOXptdX6BDLMNxcU/edit?usp=sharing)

Кроме ссылки должен быть скрин макета, это нужно, что бы не запутаться в версиях, когда макет начнет вдруг меняться.

**Comment by YuriSilenok** [comment]
![image](https://user-images.githubusercontent.com/14871471/65393078-e93cac80-dd84-11e9-8e14-5adfda4352b3.png)

**Comment by FvckNeighbors** [comment]
Добавил

**Comment by YuriSilenok** [comment]
Работа выполнена не верно, обо всех замечаниях указано в чате
Ожидаю новый запрос на слияние

**Comment by YuriSilenok** [comment]
Какие есть обновления по этой задаче?

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1199 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1199 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1199 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1199 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1199 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1199 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1199 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1199 давно не было активности

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by YuriSilenok** [comment]
ПОЧЕМУ ВЫ НИЧЕГО НЕ ДЕЛАЕТЕ ПО ЗАДАЧЕ?

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by YuriSilenok** [comment]
Устаревшая ветка task-1199 будет удалена в ближайшее время

**Comment by YuriSilenok** [comment]
Устаревшая ветка task-1199 будет удалена в ближайшее время

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности. Активность по основной задаче #1199 составляет 0 дней. Активность по ветке task-1199 составляет 8. Актовность по запросуотсутствует.

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности. Активность по основной задаче #1199 составляет 12 дней. Активность в ветке task-1199 составляет 21 дней. Активность по запросу #1228 составляет 3 дней. Нет запросов, которые должен проверить преподаватель

**Comment by YuriSilenok** [comment]
Ветка task-1199 удалена
