### ISSUE TITLE
Реализовать метод Insert(Model model) класса CTeacher унаследованного от класса Controller

### ISSUE THREAD

**Issue by purplegen** [Students-of-the-city-of-Kostroma/Student-timetable#12]
[Ссылка](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit) на диаграмму классов

**Comment by YuriSilenok** [comment]
Добрый день, 

у Вас не указана веха.

Спасибо.

**Comment by YuriSilenok** [comment]
Зачтено

**Comment by YuriSilenok** [comment]
@netever  Зачтено
