### ISSUE TITLE
Создать контроллер СAcademicLoad  и реализовать конструктор CAcademicLoad() : base("Нагрузка") для данного класса

### ISSUE THREAD

**Issue by FvckNeighbors** [Students-of-the-city-of-Kostroma/Student-timetable#1200]
Создать публичный класс CAcademicLoad, унаследованный от DataTable. В данном классе создать конструктор таблицы  CAcademicLoad() : base("Нагрузка"), в котором формируются поля таблицы.

Добавить документацию кода.

**Comment by YuriSilenok** [comment]
Неправильно указаны ответственные в запросе

**Comment by FvckNeighbors** [comment]
Изменил

**Comment by YuriSilenok** [comment]
Максим, почему ты за всех все делаешь?
Твоя задача проконтролировать исполнение задач и замечаний к ним + собственные замечания
Реализация и исправления замечаний лежит на ответственном на задаче.
Напоминайте исполнителям что если задача на мне не будет перевешена, то и задача не будет проверена мной.

**Comment by YuriSilenok** [comment]
зачтено
