### ISSUE TITLE
Создать класс MAcademicLoad со свойствами определяющих модель Нагрузки

### ISSUE THREAD

**Issue by FvckNeighbors** [Students-of-the-city-of-Kostroma/Student-timetable#1201]
Создать публичный класс MAcademicLoad, унаследованный от Model, для объявления свойств определяющих модель Нагрузки.

Добавить валидацию полей: Группа (поток), Дисциплина, Преподаватель и Вид занятия с такими ограничениями:
1. Строка не может быть пустой.
2. Строка может состоять только из русских букв.
3. Строка должна начинаться с заглавной буквы.
4. Строка не должна превышать больше 25 символов.

Для поля "Часов всего" и "Распределено" добавить следующие ограничения
1. Строка не может быть пустой
2. Строка может содержать только цифры

Добавить документацию кода.

**Comment by YuriSilenok** [comment]
Я не вижу этой задачи в бэклоге

**Comment by FvckNeighbors** [comment]
@YuriSilenok находится в ячейке F5

**Comment by YuriSilenok** [comment]
> @YuriSilenok находится в ячейке F5

В этой ячейке указан другой класс 
`Создать класс MAcademicDegree со свойствами определяющих модель Нагрузки`

**Comment by FvckNeighbors** [comment]
Да, присмотрелся и увидел. Извиняюсь, исправил.

**Comment by YuriSilenok** [comment]
В запросе не верно указаны ответственные

**Comment by FvckNeighbors** [comment]
Убрал Вас

**Comment by YuriSilenok** [comment]
@FvckNeighbors почему это ты делаешь?

**Comment by FvckNeighbors** [comment]
Потому что я сначала повесил, моя ошибка

**Comment by YuriSilenok** [comment]
Зачтено
