### ISSUE TITLE
Реализовать метод Delete(Model model) сущности Нагрузка

### ISSUE THREAD

**Issue by FvckNeighbors** [Students-of-the-city-of-Kostroma/Student-timetable#1203]
Разработать метод Delete(Model model) сущности Нагрузка.
Добавить документацию кода.

**Comment by YuriSilenok** [comment]
Вы еще не закончили с запросом на слияние, мне в этой задаче делдать нечего

**Comment by YuriSilenok** [comment]
Ветка не удалена

**Comment by YuriSilenok** [comment]
Зачтено как Sprint 1
