### ISSUE TITLE
Реализовать метод Update(Model model) сущности Нагрузка

### ISSUE THREAD

**Issue by FvckNeighbors** [Students-of-the-city-of-Kostroma/Student-timetable#1204]
Реализовать метод Update(Model model) сущности Нагрузка. 
Добавить документацию кода.

**Comment by YuriSilenok** [comment]
@FvckNeighbors я ожидаю что @GubanovAndrey сам на меня свою задачу перевести и с себя её снимет

**Comment by YuriSilenok** [comment]
Зачтено
