### ISSUE TITLE
Заполнить RefData сущности Дисциплина для группы 17-ИДбо

### ISSUE THREAD

**Issue by FvckNeighbors** [Students-of-the-city-of-Kostroma/Student-timetable#1225]
Заполнить RefDataсущности Дисциплины для группы 17-ИДбо, в соответствии с расписанием на сайте КГУ за 1 семестр 2019 года, в методе init()

**Comment by YuriSilenok** [comment]
Ветка не удалена

**Comment by YuriSilenok** [comment]
зачтено как ЛР03 #1254
