### ISSUE TITLE
Доработать форму "Расписание" по макету

### ISSUE THREAD

**Issue by FvckNeighbors** [Students-of-the-city-of-Kostroma/Student-timetable#1227]
Доработать форму "Расписание" по макету. 

Файл с формой: Timetable.cs

[Ссылка на макет](https://docs.google.com/presentation/d/1sLVZc-DRTHR1IAhNWKoXsJriw-2qOXptdX6BDLMNxcU/edit?usp=sharing)

![Макеты (1)](https://user-images.githubusercontent.com/47320314/65630708-9bbb7c00-dfde-11e9-8581-00b08bb41414.png)
![Макеты (2)](https://user-images.githubusercontent.com/47320314/65630711-9ceca900-dfde-11e9-8178-ecb98e0207e0.png)
![Макеты (3)](https://user-images.githubusercontent.com/47320314/65630715-9d853f80-dfde-11e9-93f1-76c2b450ae00.png)

**Comment by FvckNeighbors** [comment]
Снято по отсутствию активности

**Comment by YuriSilenok** [comment]
Снято по отсутствию активности

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by YuriSilenok** [comment]
Эта задача будет разбита на три другие
