### ISSUE TITLE
Добавить контроллер Нагрузка в RefData и реализовать связи с другими таблицами

### ISSUE THREAD

**Issue by FvckNeighbors** [Students-of-the-city-of-Kostroma/Student-timetable#1232]
Добавить контроллер Нагрузка в RefData и реализовать связи со следующими таблицами: 
1) Группа 
2) Дисциплина 
3) Преподаватель 
4) Вид занятия

**Comment by FvckNeighbors** [comment]
Снять по отсутствию активности по задаче

**Comment by Proffet78** [comment]
Выполнено, просьба проверить!
Спасибо

**Comment by YuriSilenok** [comment]
Зачтено
