### ISSUE TITLE
Заполнить RefData для сущности Нагрузка для группы 17-ВТбо-1

### ISSUE THREAD

**Issue by Jeen99** [Students-of-the-city-of-Kostroma/Student-timetable#1238]
Заполнить RefData сущности Нагрузка для группы 17-ВТбо-1, в соответствии с расписанием на сайте КГУ за 1 семестр 2019 года, в методе init()

**Comment by YuriSilenok** [comment]
[Зачтено](https://docs.google.com/spreadsheets/d/1uBd4d3VvI4rYeuXkXmqLyEZSitS8K9pfVUDtM3i1Vg4/edit#gid=870820066&range=L4)
