### ISSUE TITLE
Разработать и автоматизировать сценарии тестирования метода Insert (Model model) сущности Нагрузка

### ISSUE THREAD

**Issue by Jeen99** [Students-of-the-city-of-Kostroma/Student-timetable#1240]
- Составить тесты методом белого ящика и [предоставить отчет](https://docs.google.com/document/d/1H6353mZjLjMmCq-1A7IrnKdwBUQXyg81wjauXlad3XY/edit)
- Обновить [сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit) указам у заголовка тест-комплекта ссылку на гугл документ с исследованием по белому ящику.
- Автоматизировать полученные сценарии
- Перенести комментарии методов в шаблон `///`
- Комментарии должны совпадать с описанием тестового сценария

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1240 давно не было активности

**Comment by NesgovorovVS** [comment]
![image](https://user-images.githubusercontent.com/47756995/89134451-0823d780-d52e-11ea-905c-28701e295a81.png)
Для отчёта

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1240 давно не было активности

**Comment by NesgovorovVS** [comment]
![image](https://user-images.githubusercontent.com/47756995/89218210-555b8400-d5d6-11ea-8c09-51fbb4bc6efb.png)
Исправлена разметка кода для будущего отчёта

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1240 давно не было активности

**Comment by NesgovorovVS** [comment]
Прошу задачу не снимать, проставлю приоритеты в течении суток.

**Comment by YuriSilenok** [comment]
Если у вас нет уважительной причины по которой нет активности, задача будет с вас снята.

**Comment by NesgovorovVS** [comment]
> Если у вас нет уважительной причины по которой нет активности, задача будет с вас снята.

в течение суток новые изменения будут загружены

**Comment by NesgovorovVS** [comment]
Прошу задачу не снимать, идут оставшиеся работы над ней.

**Comment by YuriSilenok** [comment]
Все промежуточные результаты должны быть отображены в коммитах, ваше сообщение не несет полезной нагрузки

**Comment by NesgovorovVS** [comment]
> Все промежуточные результаты должны быть отображены в коммитах, ваше сообщение не несет полезной нагрузки

Сегодня вечером будут коммиты.

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by NesgovorovVS** [comment]
> Задача с Вас снята, так как по ней давно не было активности.

![image](https://user-images.githubusercontent.com/47756995/91935325-2845e280-ecf6-11ea-9527-f5d55da3e9c5.png)
можно вернуть задачу?

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности. Активность по основной задаче #1240 составляет 18 дней. Ветка отсутствует. Запрос отсутствует. Нет запросов, которые должен проверить преподаватель

**Comment by YuriSilenok** [comment]
Задача с Вас  снята, так как по ней давно не было активности. Активность по основной задаче #1240 составляет 13 дней. Активность в ветке issue-1240 составляет 31 дней. Активность по запросу #1367 составляет 19 дней. Нет запросов, которые должен проверить преподаватель
