### ISSUE TITLE
Решить 2 мерж-конфликта

### ISSUE THREAD

**Issue by Jeen99** [Students-of-the-city-of-Kostroma/Student-timetable#1241]
https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1221
https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1223

**Comment by YuriSilenok** [comment]
сами мержи прошли нормально, но в запросе #1221 многое сделано неправильно. 
Не могу зачеть так как в бэклоге нет задачи с таким заголовком

**Comment by Jeen99** [comment]
@YuriSilenok, название задачи в backlog поправил. Про #1221 знал. Дал т.к. нужно хоть какие-то задания давать.

**Comment by YuriSilenok** [comment]
Запросы должны ссылаться на задачу

**Comment by YuriSilenok** [comment]
Зачтено как ЛР02 #1254

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу
