### ISSUE TITLE
Заполнить RefData сущности Институт

### ISSUE THREAD

**Issue by Jeen99** [Students-of-the-city-of-Kostroma/Student-timetable#1244]
Заполнить RefDataсущности Институт в соответствии с расписанием на сайте КГУ за 1 семестр 2019 года, в методе init()

**Comment by ssas18** [comment]
Изменения замержены

**Comment by YuriSilenok** [comment]
[зачтено](https://docs.google.com/spreadsheets/d/1uBd4d3VvI4rYeuXkXmqLyEZSitS8K9pfVUDtM3i1Vg4/edit#gid=1274241490&range=M5)
