### ISSUE TITLE
Разработать и автоматизировать сценарии тестирования метода Update (Model model) сущности Нагрузка

### ISSUE THREAD

**Issue by Jeen99** [Students-of-the-city-of-Kostroma/Student-timetable#1245]
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=1813879881)

**Comment by Nosolev** [comment]
@YuriSilenok засчитайте работу

**Comment by YuriSilenok** [comment]
Зачтено как за спринт
