### ISSUE TITLE
Решить мерж-конфликт

### ISSUE THREAD

**Issue by Jeen99** [Students-of-the-city-of-Kostroma/Student-timetable#1246]
Решить конфликт для работы #1229

**Comment by YuriSilenok** [comment]
Запросы должны ссылаться на задачу

**Comment by YuriSilenok** [comment]
Зачтено как ЛР02  #1254

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу
