### ISSUE TITLE
Заполнить RefData сущности Преподаватель

### ISSUE THREAD

**Issue by Jeen99** [Students-of-the-city-of-Kostroma/Student-timetable#1252]
Заполнить RefDataсущности Преподаватель (5-10 преподавателей) и связанные с ними данные в соответствии с расписанием на сайте КГУ в методе init().

**Comment by YuriSilenok** [comment]
Не нужно вешать на меня задачу, пока вы не закончили работу с запросом на слияние.

**Comment by YuriSilenok** [comment]
Зачтено как ЛР03 в рамках #1256
