### ISSUE TITLE
Разработал и автоматизировал сценарии тестирования метода Insert (Model model) сущности Нагрузка

### ISSUE THREAD

**Issue by NesgovorovVS** [Students-of-the-city-of-Kostroma/Student-timetable#1261]
#1240

**Comment by NesgovorovVS** [comment]
https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=1813879881&range=A52:F57
ссылка на сценарий

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
