### ISSUE TITLE
Решить мерж-конфликт

### ISSUE THREAD

**Issue by NordScandinavian** [Students-of-the-city-of-Kostroma/Student-timetable#1263]
Решить конфликт для работы [#1250](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1250)

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу
