### ISSUE TITLE
Разработка метода хранения данных

### ISSUE THREAD

**Issue by NordScandinavian** [Students-of-the-city-of-Kostroma/Student-timetable#1264]
Разработать метод для хранения получаемых данных в XML формате.

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1264 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1264 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1264 давно не было активности

**Comment by NesgovorovVS** [comment]
> Добрый день. В ветке task-1264 давно не было активности

Ветка не заброшена, займусь ей в течение 2-3 дней, после добавления отчётов в 3 ветки

**Comment by YuriSilenok** [comment]
> > Добрый день. В ветке task-1264 давно не было активности
> 
> Ветка не заброшена, займусь ей в течение 2-3 дней, после добавления отчётов в 3 ветки

Постарайтесь делать их параллельно.

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1264 давно не было активности

**Comment by YuriSilenok** [comment]
> Добрый день. В ветке task-1264 давно не было активности

Сегодня будет активность по задаче?

**Comment by NesgovorovVS** [comment]
> > Добрый день. В ветке task-1264 давно не было активности
> 
> Сегодня будет активность по задаче?

Нет, параллельно делаю три ветки, в них изменения будут позже, с этой тоже разберусь, тут вроде только нет документации xml

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1264 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1264 давно не было активности

**Comment by NesgovorovVS** [comment]
Прошу задачу не снимать, проставлю приоритеты в течении суток.

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1264 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1264 давно не было активности

**Comment by YuriSilenok** [comment]
@NesgovorovVS  На каком основании Вы отменили мое решение и забрали задачу себе?

**Comment by NesgovorovVS** [comment]
> @NesgovorovVS На каком основании Вы отменили мое решение и забрали задачу себе?

ошибся задачей видимо, 1265 моя

**Comment by NesgovorovVS** [comment]
> @NesgovorovVS На каком основании Вы отменили мое решение и забрали задачу себе?

ошибся задачей видимо, 1265 моя

**Comment by YuriSilenok** [comment]
А 1265 это запрос к текущей задача и все равно задача с вас снята, я не вижу оснований по которым вы вдруг начали заниматься этой задачей, а запрос нужно закрыть.
Тем более что коммит который выкатили ровным счетом ничего не меняет, те изменения которые вы сделали не делают комментарии технической документацией.
Запрос будет закрыт в ближайшее время.

**Comment by NesgovorovVS** [comment]
> А 1265 это запрос к текущей задача и все равно задача с вас снята, я не вижу оснований по которым вы вдруг начали заниматься этой задачей, а запрос нужно закрыть.
> Тем более что коммит который выкатили ровным счетом ничего не меняет, те изменения которые вы сделали не делают комментарии технической документацией.
> Запрос будет закрыт в ближайшее время.

"Вообще не заметил, как вы у меня забрали задачу, аж 20 июня
Вы бы хоть поправили, когда я вам на сообщения отвечал и когда заливал изменения,что задача уже не моя"

**Comment by YuriSilenok** [comment]
О любых изменениях в задачах приходит уведомление на почту. Читайте почту.
Хотите сказать что я должен при чтении каждого сообщения проверять на ком висит задача, извините, но Ваша обязанность следить за СВОИМИ задачами!

**Comment by YuriSilenok** [comment]
Закрыта, так как потеряла свою актуальность
