### ISSUE TITLE
Изменить максимальную длину полного имени сущности "Институт"

### ISSUE THREAD

**Issue by ssas18** [Students-of-the-city-of-Kostroma/Student-timetable#1276]
Увеличить кол-во символов поля _fullname  до 60

**Comment by ssas18** [comment]
Изменения замержены

**Comment by YuriSilenok** [comment]
Задачи нужно на меня вешать после мержа, что бы я их  в журнале отмечал и сам закрывал

**Comment by YuriSilenok** [comment]
[Зачтено](https://docs.google.com/spreadsheets/d/1uBd4d3VvI4rYeuXkXmqLyEZSitS8K9pfVUDtM3i1Vg4/edit#gid=1274241490&range=K5)
