### ISSUE TITLE
Изменить набор допустимых символов для полного имени сущности "Институт"

### ISSUE THREAD

**Issue by ssas18** [Students-of-the-city-of-Kostroma/Student-timetable#1277]
Добавить в проверку "точку", добавить возможность использования заглавных букв в поле, помимо первой.

**Comment by ssas18** [comment]
Изменения замержены

**Comment by YuriSilenok** [comment]
[зачтено](https://docs.google.com/spreadsheets/d/1uBd4d3VvI4rYeuXkXmqLyEZSitS8K9pfVUDtM3i1Vg4/edit#gid=1274241490&range=L5)
