### ISSUE TITLE
Разработать сценарии тестирования пригодных для автоматизации unit-test для метода Insert(Model model) класса CTeacher

### ISSUE THREAD

**Issue by Nosolev** [Students-of-the-city-of-Kostroma/Student-timetable#128]
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)
Реализовать сценарии пригодные для Unit-тестирования
[План разработки](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_102)
[Ссылка на диаграмму классов](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_0)

**Comment by YuriSilenok** [comment]
Зачтено

**Comment by map82top** [comment]
Состояние таблицы контроллера CTeacher | Атрибут INN ∈ [0-9]{10 &12} | Атрибут surname ∈ [A-Я]{1}[а-я]{0,49} | Атрибут name ∈ [A-Я]{1}[а-я]{0,49} | Атрибут middlename ∈ [A-Я]{1}[а-я]{0,49} | Атрибут academicDegree <> null (лучше поменять на перечисление) | Атрибут academicRank <> null (лучше поменять на перечисление) | Атрибут sizeOfTeachingExperience ∈ [0-50]
-- | -- | -- | -- | -- | -- | -- | --
Таблица не имеет записей | task-128-1 | task-128-1 | task-128-1 | task-128-1 | task-128-1 | task-128-1 | task-128-1
Добавляемая запись не имеет аналогов в таблице | task-128-2 | task-128-2 | task-128-2 | task-128-2 | task-128-2 | task-128-2 | task-128-2
В таблице существует запись с атрибутом совпадающим с атрибутом добавляемой записи | task-128-3 | task-128-4 | task-128-5 | task-128-6 | task-128-7 | task-128-8 | task-128-9

**Comment by map82top** [comment]
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548) написал в общей таблице

**Comment by map82top** [comment]
Нашел задачу #13 очень похожую на мою. Как нужно разрешить данный конфликт?

**Comment by YuriSilenok** [comment]
Я в замешательстве.
- Доводы в пользу того, что бы снять с Вас задачу:
  - Следую алгоритму ЛР Вы должны были найти данную ЛР.
  - Я просил договориться в пределах аудитории о том, кто и что будет делать. #13 Выполняет студент с той же подгруппы что и Вы.
- Доводы в пользу того, что бы задачу оставить:
  - На момент лабораторной работы она была без исполнителя, это значит что я сам на кануне ее так пометил и указал на нее как на возможную свободную задачу.
  - Вы сами указали на это несоответствие.
Думаю право выбора остается за Вами.
> Нашел задачу #13 очень похожую на мою. Как нужно разрешить данный конфликт?

По поводу тех таблиц которые Вы мне прислали.
В первой таблице (из пункта 5 ЛР) в первом столбце нужно указывать состояние контроллера. После второй строки Вы перечисляете атрибуты,  а нужно состояния контроллера относительно тестируемого метода. К обязательным состояниям контроллера в Вашем случае будут относится: в таблице нет записей, в таблице содержится запись(и) 1 атрибут которой совпадает с атрибутом добавляемой записи.

По поводу второй таблицы. Видимо было не очевидно, что нужно было перейти по ссылке и заполнить уже существующую таблицу. Там же было сказано что нужно **заполнить** таблицу со сценариями. Не было сказано ее прикреплять в комментарий.

**Comment by map82top** [comment]
@YuriSilenok 
>По поводу второй таблицы. Видимо было не очевидно, что нужно было перейти по ссылке и заполнить уже существующую таблицу. Там же было сказано что нужно заполнить таблицу со сценариями. Не было сказано ее прикреплять в комментарий.
>
Я так и сделал сначала, Но на практике, в эту среду, вы ее удалили, и поэтому я ее решил  вставить здесь

**Comment by map82top** [comment]
Переделал таблицу со сценариями

**Comment by YuriSilenok** [comment]
@map82top Почему запрос на слияние для задачи на автоматизацию сценариев ссылается на задачу по разработке сценариев?

**Comment by YuriSilenok** [comment]
@map82top По сценариям. В ожидаемом результате необходимо указать цифру шага к которому указан ожидаемый результат.

**Comment by map82top** [comment]
> @map82top Почему запрос на слияние для задачи на автоматизацию сценариев ссылается на задачу по разработке сценариев?

Потому что я не догадался о том, что для этого надо подымать отдельную задачу

**Comment by map82top** [comment]
@YuriSilenok 
Исправил таблицу со сценариями

**Comment by YuriSilenok** [comment]
У вас есть два утверждения:
- В таблице существует запись с атрибутом совпадающим с атрибутом добавляемой записи
- Записи с ключом как у новой добавляемой записи уже есть в таблице

И есть  это:
- Атрибут surname ∈ [A-Я]{1}[а-я]{0,49} 
- Атрибут name ∈ [A-Я]{1}[а-я]{0,49} 
- Атрибут middlename ∈ [A-Я]{1}[а-я]{0,49} 
- Атрибут academicDegree <> null (лучше поменять на перечисление) 
- Атрибут academicRank <> null (лучше поменять на перечисление) 
- Атрибут sizeOfTeachingExperience ∈ [0-50]

Во втором списке у вас пеерчислены атрибуты, а которые из них ключи?
Если они ключи, будут ли они являтся атрибутами?

**Comment by map82top** [comment]
@YuriSilenok 
Уникальным ключом для данной таблици ялвяется составной ключ из фамилии, имени, отчества и стажа работы. Только повторении всех 4 атрибутов одновременно может привести к не добавлению новой записи в таблицу.
Данные 4 атрибута являются составным уникальным ключом данной таблицы.

**Comment by YuriSilenok** [comment]
все атрибуты запихать в составной ключ это плохая идея. И все равно остается ничтожная вероятность полных тесок и стажа. Кажется есть подобные случаи с близнецами. Есть такая вещь как нормализация данных, в следующем году Вам предстоит ее пройти с Ниной Олеговной. Так вот, после нормализации данных Вы должны получить первичный ключ что-то типа ИНН или СНИЛС. И то и другое требуется при трудоустройстве. все остальное может повторяться в различных комбинациях.

**Comment by map82top** [comment]
@YuriSilenok 
> все атрибуты запихать в составной ключ это плохая идея. И все равно остается ничтожная вероятность полных тесок и стажа. Кажется есть подобные случаи с близнецами. Есть такая вещь как нормализация данных, в следующем году Вам предстоит ее пройти с Ниной Олеговной. Так вот, после нормализации данных Вы должны получить первичный ключ что-то типа ИНН или СНИЛС. И то и другое требуется при трудоустройстве. все остальное может повторяться в различных комбинациях.

Мне переделывать тесты к уже несуществующей таблицы или не надо?

**Comment by YuriSilenok** [comment]
Мы не будем обращать внимание к уже существующей таблице Преподаватель. Будем доделывать с теми атрибутами какие у Вас есть сейчас в текущем таске.

**Comment by map82top** [comment]
Я почему-то не могу вносить изменения в таблицу со сценариями тестов

**Comment by YuriSilenok** [comment]
Доступ предоставил, обновите страницу

**Comment by map82top** [comment]
Получил, спасибо

**Comment by map82top** [comment]
Исправил сценарии, новый первичных ключ ИНН

**Comment by YuriSilenok** [comment]
@map82top Зачтено
