### ISSUE TITLE
Исправить сбои в автотестах расположенных в файле UT_Update_CAcademicLoad

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#1280]
- Составить тесты методом белого ящика и [предоставить отчет](https://docs.google.com/document/d/1H6353mZjLjMmCq-1A7IrnKdwBUQXyg81wjauXlad3XY/edit)
- Обновить [сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit) указам у заголовка тест-комплекта ссылку на гугл документ с исследованием по белому ящику.
- Автоматизировать полученные сценарии
- Перенести комментарии методов в шаблон `///`
- Комментарии должны совпадать с описанием тестового сценария

**Comment by ssas18** [comment]
@YuriSilenok , я нашел причину сбоя автотеста
 ![image](https://user-images.githubusercontent.com/47377817/86507296-d0672a00-bddf-11ea-958c-d47a10a05013.png)
После добавления в рефдату этих данных: 
![image](https://user-images.githubusercontent.com/47377817/86507320-14f2c580-bde0-11ea-9b4b-96c877659d40.png)
Автотест проходит успешно
![image](https://user-images.githubusercontent.com/47377817/86507333-32c02a80-bde0-11ea-93c8-980ae8456a9d.png)
Так же тест проходит при изменении группы на ту, которая уже находится в рефдате.
Мне необходимо описать весь процесс работы этого автотеста?

**Comment by ssas18** [comment]
В данном автотесте при изменении поля Discipline изменение проходит внутреннюю проверку, в следствие чего никакие символы кроме букв русской раскладки не проходят, вываливается exception, следовательно до метода update не доходит.
Изменять сценарий автотеста?

**Comment by ssas18** [comment]
Можете пожалуйста проверить и сказать что здесь не так:
https://docs.google.com/document/d/1j1WoxQgpvsnNo4nunZRD_sw_wNAxTa1UUu0-uiDu0d8/edit?usp=sharing

**Comment by YuriSilenok** [comment]
> Можете пожалуйста проверить и сказать что здесь не так:
> https://docs.google.com/document/d/1j1WoxQgpvsnNo4nunZRD_sw_wNAxTa1UUu0-uiDu0d8/edit?usp=sharing

У меня нет доступа к файлу

**Comment by ssas18** [comment]
Теперь должно работать
https://docs.google.com/document/d/1j1WoxQgpvsnNo4nunZRD_sw_wNAxTa1UUu0-uiDu0d8/edit?usp=sharing

**Comment by YuriSilenok** [comment]
У управляющего графа всегда должна быть одна конечная вершина.

**Comment by ssas18** [comment]
Исправил указанную ошибку

**Comment by YuriSilenok** [comment]
Я вижу все равно 4 конечных вершины

**Comment by ssas18** [comment]
Вы видите данный скриншот?
![image](https://user-images.githubusercontent.com/47377817/86517999-3a122300-be36-11ea-8279-e87686920e3a.png)

**Comment by YuriSilenok** [comment]
> Вы видите данный скриншот?
> ![image](https://user-images.githubusercontent.com/47377817/86517999-3a122300-be36-11ea-8279-e87686920e3a.png)
> 

Нет, возможно файл не успел обновиться, посмотрю ещё раз.

**Comment by YuriSilenok** [comment]
Вершина 3. Это условие с двойным ветвлением но из вершины 3 у вас выходит только одно ребро

**Comment by ssas18** [comment]
Исправил 
https://docs.google.com/document/d/1j1WoxQgpvsnNo4nunZRD_sw_wNAxTa1UUu0-uiDu0d8/edit?usp=sharing

**Comment by YuriSilenok** [comment]
Добрый день. Жду вашего отчета на гитхаб, дальнейшее обсуждение в запросе

**Comment by ssas18** [comment]
Здравствуйте, отчет уже в пул реквесте

**Comment by YuriSilenok** [comment]
![image](https://user-images.githubusercontent.com/14871471/86580005-c895ba00-bf86-11ea-97a2-15d72319bbf8.png)
укажите его, пожалуйста

**Comment by YuriSilenok** [comment]
и судя по всему вы не запросили у меня проверку, я там назначен проверяющим?

**Comment by ssas18** [comment]
Да, я забыл сделать запрос на проверку

**Comment by ssas18** [comment]
@YuriSilenok , в пул реквесте по данной задаче я, как Вы и просили, назначил ревьюверами 2-ух человек, это произошло где-то в 10 утра, они не проявляли никакой активности, я назначил ревьюверами еще 2-ух человек, где-то 3-4 часа назад, от них тоже нет активности.
Что мне делать?

**Comment by YuriSilenok** [comment]
Вы можете назначать всю команду, как я упоминал, те кто освободяться раньше с работы или других дел, посмотрят.

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1280 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1280 давно не было активности

**Comment by ssas18** [comment]
Прошу не удалять, т.к. жду проверки

**Comment by YuriSilenok** [comment]
Где метки приоритета?

**Comment by ssas18** [comment]
Прошу меня простить, но примерно сутки буду находиться в отъезде, по приезду будут исправлены все замечания

**Comment by ssas18** [comment]
@YuriSilenok  , я снова тут и очень жду Вашей проверки по #1294

**Comment by YuriSilenok** [comment]
> @YuriSilenok  , я снова тут и очень жду Вашей проверки по #1294  

Проверять я буду завтра утром, может быть коллеги смогут чем-то помочь в проверке, но это что-то невероятное, только вы работаете в этом плане нормально.

**Comment by ssas18** [comment]
> > @YuriSilenok  , я снова тут и очень жду Вашей проверки по #1294
> 
> Проверять я буду завтра утром, может быть коллеги смогут чем-то помочь в проверке, но это что-то невероятное, только вы работаете в этом плане нормально.

Хорошо, жду проверки

**Comment by ssas18** [comment]
В данной задаче нет активности т.к жду проверки

**Comment by YuriSilenok** [comment]
> В данной задаче нет активности т.к жду проверки

Активность по основной задаче считается по времени комментариев и коммита в ветке. В дальнейшем будет расширении функционала проверки и будут учитываться время комментариев в связанных задачах и запросах.

**Comment by YuriSilenok** [comment]
[зачтено](https://docs.google.com/spreadsheets/d/1uBd4d3VvI4rYeuXkXmqLyEZSitS8K9pfVUDtM3i1Vg4/edit#gid=1274241490&range=V5)
