### ISSUE TITLE
Исправлен сбой в автотестах расположенных в файле UT_Insert_CInstitute

### ISSUE THREAD

**Issue by Heriuple** [Students-of-the-city-of-Kostroma/Student-timetable#1283]
#1096

**Comment by Heriuple** [comment]
![image](https://user-images.githubusercontent.com/49808925/86485417-52643e00-bd61-11ea-8a41-4b3deeb57105.png)
Прошу прощения за глупые вопросы. Ошибка возникает в таске 616_1, который добавляет в пустую таблицу данные института. Не могу понять, на каком этапе возникает проблема, вероятнее всего таблица уже поступает не пустой. Как в данном случае проверить, заполнена таблица или нет?

**Comment by YuriSilenok** [comment]
> ![image](https://user-images.githubusercontent.com/49808925/86485417-52643e00-bd61-11ea-8a41-4b3deeb57105.png)
> Прошу прощения за глупые вопросы. Ошибка возникает в таске 616_1, который добавляет в пустую таблицу данные института. Не могу понять, на каком этапе возникает проблема, вероятнее всего таблица уже поступает не пустой. Как в данном случае проверить, заполнена таблица или нет?

Появилась задача #1323, которая могла бы вам помочь решить эту проблему.

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by Alphavite51** [comment]
Ветка смержена, можете продолжать работу, вам нужно мержить dev в вашу ветку!

**Comment by YuriSilenok** [comment]
> Ветка смержена, можете продолжать работу, вам нужно мержить dev в вашу ветку!

https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1217#issuecomment-685427703
