### ISSUE TITLE
Разработка тестов для конструктора класса MTeacher

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#1284]
- Составить тесты методом белого ящика и [предоставить отчет](https://docs.google.com/document/d/1H6353mZjLjMmCq-1A7IrnKdwBUQXyg81wjauXlad3XY/edit)
- Обновить [сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit) указам у заголовка тест-комплекта ссылку на гугл документ с исследованием по белому ящику.
- Автоматизировать полученные сценарии
- Перенести комментарии методов в шаблон `///`
- Комментарии должны совпадать с описанием тестового сценария

**Comment by VinogradovAlexandr781227** [comment]
Приступил к выполнению задания

**Comment by YuriSilenok** [comment]
> Приступил к выполнению задания

3 дня назад вы писали что приступили к выполнению задачи, но нет ни запроса ни ветки, почему?

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1284 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1284 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1284 давно не было активности

**Comment by VinogradovAlexandr781227** [comment]
Разрабатываю отчет. Надеюсь сегодня, завтра залью

**Comment by YuriSilenok** [comment]
Заливайте промежуточные результаты, такова политика проекта.

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1284 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1284 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1284 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1284 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1284 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1284 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1284 давно не было активности

**Comment by VinogradovAlexandr781227** [comment]
@YuriSilenok Это задача, которую я реализую в task-1310

**Comment by YuriSilenok** [comment]
Вы хотите сказать что эта задача дубликат?

**Comment by YuriSilenok** [comment]
Дубликат #1310
