### ISSUE TITLE
Критический сбой при работе со  связью группа-нагрузка

### ISSUE THREAD

**Issue by JennyShel18** [Students-of-the-city-of-Kostroma/Student-timetable#1285]
Является необходимым для задачи https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1228

1.В справочнике открыть форму нагрузка
2.Нажать Добавить
3.При вводе данных в форме добавления нагрузки нажимаем кнопку "Сохранить"
Ожидаемый результат: Успешное добавление нагрузки в форму нагрузка
Фактический результат: При добавлении нагрузки возникает ошибка, внешний ключ из группы ссылается на нагрузку, должно быть наоборот.

**Comment by YuriSilenok** [comment]
В описании бага нужно написать сценарий при котором будет воспроизводится этот баг. Именно выполнение этого сценариев и будет потом алгоритмом проверки того, что баг не воспроизводится

**Comment by YuriSilenok** [comment]
Когда создадите запрос на слияние, он должен быть слинкован с этой задачей

**Comment by JennyShel18** [comment]
Сценарий добавлен

**Comment by ssas18** [comment]
Еще один метод воспроизведения данного бага:
1.В приложении найти класс CTeacher и в нем метод Insert.
2.Поставить точку остановы на одной из первых строк блока try.
3.Пройти шагом с обходом до строки "Debug.WriteLine(ex.Source);"
4 Увидеть сообщение об ошибке.
Ожидаемый результат: Успешное добавление преподавателя
Фактический результат: Ошибка ексепшена "
  "Для ForeignKeyConstraint AcademicLoad-Teacher требуется, чтобы в родительской таблице присутствовали значения дочерних ключей (Иванов Иван Иванович)." .

**Comment by YuriSilenok** [comment]
[Зачтено](https://docs.google.com/spreadsheets/d/1uBd4d3VvI4rYeuXkXmqLyEZSitS8K9pfVUDtM3i1Vg4/edit#gid=1274241490&range=K10)

**Comment by ssas18** [comment]
Баг все же воспроизводится, это мы можем проверить 2 способами:
1.  Запускаем приложение, справочники - преподаватели - добавить 
![image](https://user-images.githubusercontent.com/47377817/86758036-3d7ef780-c04c-11ea-8d07-49cd51d2e621.png)
выбираем ученую степень, ученое звание, нажимаем сохранить.
Видим сообщение об ошибке:
![image](https://user-images.githubusercontent.com/47377817/86758338-77e89480-c04c-11ea-97ea-3a08e3c478bc.png)
2. Заходим в класс CTeacher.cs переходим в метод Insert(76 строка) 
Поставить точку остановы на одной из первых строк блока try.
Пройти шагом с обходом до строки "Debug.WriteLine(ex.Source);" Увидеть сообщение об ошибке.
Ожидаемый результат: Успешное добавление преподавателя
Фактический результат: Ошибка ексепшена "
"Для ForeignKeyConstraint AcademicLoad-Teacher требуется, чтобы в родительской таблице присутствовали значения дочерних ключей (Иванов Иван Иванович)." .
![image](https://user-images.githubusercontent.com/47377817/86759448-36a4b480-c04d-11ea-9b33-e55002955089.png)

**Comment by YuriSilenok** [comment]
@JennyShel18 обратите внимание что баг вами не был исправлен.

**Comment by JennyShel18** [comment]
@ssas18 но твой сбой не относится к моему багу, который я исправляла. У меня баг возникал при добавлении нагрузки, когда указываешь группу, а у тебя баг возникает при добавлении учителя, то есть при добавлении имени учителя у тебя вылетает исключение. Изначально мой баг был не связан с исправлением твоего.

**Comment by JennyShel18** [comment]
Теперь сбой Саши исправлен

**Comment by JennyShel18** [comment]
@YuriSilenok Задачу можно закрывать?

**Comment by YuriSilenok** [comment]
Задачу должен закрыть @ssas18, так как он переоткрыл этот баг и он должен подтвердить что сбой больше не наблюдается

**Comment by JennyShel18** [comment]
Хорошо

**Comment by ssas18** [comment]
Бага больше не наблюдаю
