### ISSUE TITLE
Критический сбой метода Insert класса CTeacher

### ISSUE THREAD

**Issue by ssas18** [Students-of-the-city-of-Kostroma/Student-timetable#1288]
Является необходимым для задачи #1036 
1.В приложении найти класс CTeacher и в нем метод Insert.
2.Поставить точку остановы на одной из первых строк блока try.
3.Пройти шагом с обходом до строки "Debug.WriteLine(ex.Source);"
4 Увидеть сообщение об ошибке.
Ожидаемый результат: Успешное добавление преподавателя
Фактический результат: Ошибка ексепшена "
   "Для ForeignKeyConstraint AcademicLoad-Teacher требуется, чтобы в родительской таблице присутствовали значения дочерних ключей (Иванов Иван Иванович)." .

**Comment by YuriSilenok** [comment]
Дубликат #1285

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by ssas18** [comment]
Юрий Викторович, почему данный таск снова открыт?
Что мне нужно с ним делать, я просто не понимаю

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
То что и было написано, задачи не могут быть без ответственного, даже закрытые.

**Comment by ssas18** [comment]
Баг все же воспроизводится, это мы можем проверить 2 способами:
1  Запускаем приложение, справочники - преподаватели - добавить преподавателя

**Comment by YuriSilenok** [comment]
Вы написали в клон, пишите в оригинальный баг

**Comment by YuriSilenok** [comment]
И я сказал вам переоткрыть его, а не просто комментарий написать

**Comment by ssas18** [comment]
Извините, случайно опубликовал комментарий
