### ISSUE TITLE
Разработать сценарии тестирования пригодные для автоматизации модульным тестированием метода Insert(Model model) сущности Преподаватель

### ISSUE THREAD

**Issue by SergeAlekseev** [Students-of-the-city-of-Kostroma/Student-timetable#13]
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=1813879881)

**Comment by YuriSilenok** [comment]
Добрый день.

Обратите на описание лейбла Auto test, им помечаются задачи на автоматизацию тестирования
У вас не указана веха.

Спасибо.

**Comment by YuriSilenok** [comment]
Не указана веха
Обратите внимание  на описание метки Insert(Model model)

**Comment by SergeAlekseev** [comment]
Здравствуйте, Юрий Викторович.

Обратил внимание на описание метки Insert(Model model) и добавил метку Controller.
Понял, что такое веха и указал.

Спасибо.

**Comment by YuriSilenok** [comment]
Зачтено

**Comment by KharlamovaAlexandra** [comment]
Входной параметр | Позитивный класс
-- | --
Surname | ∈ a , a ∈[A-Я]{1}[а-я]{1,50} or ∈ b , b ∈ [А-Я]{1}[а-я]{1,50}-[А-Я]{1}[а-я]{1,50}
Name | ∈ a , a ∈[A-Я]{1}[а-я]{1,50} or ∈ b , b ∈ [А-Я]{1}[а-я]{1,50}-[А-Я]{1}[а-я]{1,50}
MiddleName | ∈ a , a ∈[A-Я]{1}[а-я]{1,50} or ∈ b , b ∈ [А-Я]{1}[а-я]{1,50}-[А-Я]{1}[а-я]{1,50} or null
AcademicDegree | ∈ a , a ∈[Кандидат наук] or ∈ b , b ∈  [Доктор наук] or null
AcademicRank | ∈ a , a ∈[доцент] or ∈ b , b ∈ [Профессор]
SizeOfTeachingExperience | ∈ [0-9]{1,2}

**Comment by KharlamovaAlexandra** [comment]
Добрый вечер @YuriSilenok , можно узнать насколько моя таблица соответствует заданию?

**Comment by YuriSilenok** [comment]
Здравствуйте @KharlamovaAlexandra 
- Нет столбца для негативных классов
- 1 входной параметр 1 буква. смотрите слайды
- стилистическое оформление не сохранено
- 1 класс описывается в одной ячейке.

Спасибо.

**Comment by KharlamovaAlexandra** [comment]
Входной параметр | Позитивный класс | негативный класс
-- | -- | --
Surname | ∈ a1 , a1 ∈[A-Я]{1}[а-я]{1,50}∈ a2 , a2 ∈ [А-Я]{1}[а-я]{1,50}-[А-Я]{1}[а-я]{1,50} | ∈ a3 , a3 = null∈ a4 , a4 ∈[A-Z]{1}[a-z]{1,50}∈ a5 , a5 ∈[A-Z]{1}[a-z]{1,50}-[A-Z]{1}[a-z]{1,50}∈ a6, a6 ∈[0-9]{1,50}



Name | ∈ b1, b1 ∈[A-Я]{1}[а-я]{1,50}∈ b2, b2 ∈ [А-Я]{1}[а-я]{1,50}-[А-Я]{1}[а-я]{1,50} | ∈ b3 , b3 = null∈ b4 , b4 ∈[A-Z]{1}[a-z]{1,50}∈ b5 , b5 ∈[A-Z]{1}[a-z]{1,50}-[A-Z]{1}[a-z]{1,50}∈ b6, b6 ∈[0-9]{1,50}



MiddleName | ∈ c1 , c1 ∈[A-Я]{1}[а-я]{1,50}∈ c2 , c2 ∈ [А-Я]{1}[а-я]{1,50}-[А-Я]{1}[а-я]{1,50}∈ c3 , c3 = null | ∈ c4 , c4 ∈[A-Z]{1}[a-z]{1,50}∈ c5 , c5 ∈[A-Z]{1}[a-z]{1,50}-[A-Z]{1}[a-z]{1,50}∈ c6, c6 ∈[0-9]{1,50}


AcademicDegree | ∈ d1 , d1 ∈[Кандидат наук]∈ d2 , d2 ∈ [Доктор наук]∈ d3 , d3 = null∈ d4 , d4 ∈[кандидат наук]∈ d5 , d5 ∈ [доктор наук] | ∈ d6 , d6∈[A-Z]{1}[a-z]{1,50} [a-z]{1,50}∈ d7 , d7∈[a-z]{1,50} [a-z]{1,50}∈ d8 , d8 ∈[A-Я]{1}[а-я]{1,50} [а-я]{1,50}⋃∉ [Доктор наук]⋃∉ [Кандидат наук]∈ d9 , d9∈[A-Z]{1}[a-z]{1,50}∈ d10 , d10∈[a-z]{1,50}




AcademicRank | ∈ e1 , e1 ∈[Доцент]∈ e2 , e2 ∈ [Профессор]∈ e3 , e3 ∈[доцент]∈ e4 , e4 ∈ [профессор] | ∈ e5 , e5 = null∈ e6 , e6∈[A-Z]{1}[a-z]{1,50}∈ e7 , e7∈[a-z]{1,50}∈ e8 , e8∈[A-Я]{1}[а-я]{1,50}⋃∉ [Доцент]⋃∉ [Профессор]



SizeOfTeachingExperience | ∈ f1, f1∈[0-9]{1,2} | ∈ f2 , f2∈[a-z]{1,50}∈ f3 , f3∈[A-Z]{1}[a-z]{1,50}∈ f4 , f4 ∈[A-Я]{1,50}∈ f5 , f5 ∈[а-я]{1,50}

**Comment by KharlamovaAlexandra** [comment]
Входной параметр | Позитивный класс | негативный класс
-- | -- | --
Surname | ∈ a1 , a1 ∈[A-Я]{1}[а-я]{1,50}∈ a2 , a2 ∈ [А-Я]{1}[а-я]{1,50}-[А-Я]{1}[а-я]{1,50} | ∈ a3 , a3 = null∈ a4 , a4 ∈[A-Z]{1}[a-z]{1,50}∈ a5 , a5 ∈[A-Z]{1}[a-z]{1,50}-[A-Z]{1}[a-z]{1,50}∈ a6, a6 ∈[0-9]{1,50}



Name | ∈ b1, b1 ∈[A-Я]{1}[а-я]{1,50}∈ b2, b2 ∈ [А-Я]{1}[а-я]{1,50}-[А-Я]{1}[а-я]{1,50} | ∈ b3 , b3 = null∈ b4 , b4 ∈[A-Z]{1}[a-z]{1,50}∈ b5 , b5 ∈[A-Z]{1}[a-z]{1,50}-[A-Z]{1}[a-z]{1,50}∈ b6, b6 ∈[0-9]{1,50}



MiddleName | ∈ c1 , c1 ∈[A-Я]{1}[а-я]{1,50}∈ c2 , c2 ∈ [А-Я]{1}[а-я]{1,50}-[А-Я]{1}[а-я]{1,50}∈ c3 , c3 = null | ∈ c4 , c4 ∈[A-Z]{1}[a-z]{1,50}∈ c5 , c5 ∈[A-Z]{1}[a-z]{1,50}-[A-Z]{1}[a-z]{1,50}∈ c6, c6 ∈[0-9]{1,50}


AcademicDegree | ∈ d1 , d1 ∈[Кандидат наук]∈ d2 , d2 ∈ [Доктор наук]∈ d3 , d3 = null∈ d4 , d4 ∈[кандидат наук]∈ d5 , d5 ∈ [доктор наук] | ∈ d6 , d6∈[A-Z]{1}[a-z]{1,50} [a-z]{1,50}∈ d7 , d7∈[a-z]{1,50} [a-z]{1,50}∈ d8 , d8 ∈[A-Я]{1}[а-я]{1,50} [а-я]{1,50}⋃∉ [Доктор наук]⋃∉ [Кандидат наук]∈ d9 , d9∈[A-Z]{1}[a-z]{1,50}∈ d10 , d10∈[a-z]{1,50}




AcademicRank | ∈ e1 , e1 ∈[Доцент]∈ e2 , e2 ∈ [Профессор]∈ e3 , e3 ∈[доцент]∈ e4 , e4 ∈ [профессор] | ∈ e5 , e5 = null∈ e6 , e6∈[A-Z]{1}[a-z]{1,50}∈ e7 , e7∈[a-z]{1,50}∈ e8 , e8∈[A-Я]{1}[а-я]{1,50}⋃∉ [Доцент]⋃∉ [Профессор]



SizeOfTeachingExperience | ∈ f1, f1∈[0-9]{1,2} | ∈ f2 , f2∈[a-z]{1,50}∈ f3 , f3∈[A-Z]{1}[a-z]{1,50}∈ f4 , f4 ∈[A-Я]{1,50}∈ f5 , f5 ∈[а-я]{1,50}

**Comment by KharlamovaAlexandra** [comment]
Входной параметр | Позитивный класс | Негативный класс
-- | -- | --
Surname | ∈ a1 , a1 ∈[A-Я]{1}[а-я]{1,50}∈ a2 , a2 ∈ [А-Я]{1}[а-я]{1,50}-[А-Я]{1}[а-я]{1,50} | ∈ a3 , a3 = null∈ a4 , a4 ∈[A-Z]{1}[a-z]{1,50}∈ a5 , a5 ∈[A-Z]{1}[a-z]{1,50}-[A-Z]{1}[a-z]{1,50}∈ a6, a6 ∈[0-9]{1,50}
Name | ∈ b1, b1 ∈[A-Я]{1}[а-я]{1,50}∈ b2, b2 ∈ [А-Я]{1}[а-я]{1,50}-[А-Я]{1}[а-я]{1,50} | ∈ b3 , b3 = null∈ b4 , b4 ∈[A-Z]{1}[a-z]{1,50}∈ b5 , b5 ∈[A-Z]{1}[a-z]{1,50}-[A-Z]{1}[a-z]{1,50}∈ b6, b6 ∈[0-9]{1,50}
MiddleName | ∈ c1 , c1 ∈[A-Я]{1}[а-я]{1,50}∈ c2 , c2 ∈ [А-Я]{1}[а-я]{1,50}-[А-Я]{1}[а-я]{1,50}∈ c3 , c3 = null | ∈ c4 , c4 ∈[A-Z]{1}[a-z]{1,50}∈ c5 , c5 ∈[A-Z]{1}[a-z]{1,50}-[A-Z]{1}[a-z]{1,50}∈ c6, c6 ∈[0-9]{1,50
AcademicDegree | ∈ d1 , d1 ∈[Кандидат наук]∈ d2 , d2 ∈ [Доктор наук]∈ d3 , d3 = null∈ d4 , d4 ∈[кандидат наук]∈ d5 , d5 ∈ [доктор наук] | ∈ d6 , d6∈[A-Z]{1}[a-z]{1,50} [a-z]{1,50}∈ d7 , d7∈[a-z]{1,50} [a-z]{1,50}∈ d8 , d8 ∈[A-Я]{1}[а-я]{1,50} [а-я]{1,50}⋃∉ [Доктор наук]⋃∉ [Кандидат наук]∈ d9 , d9∈[A-Z]{1}[a-z]{1,50}∈ d10 , d10∈[a-z]{1,50}
AcademicRank | ∈ e1 , e1 ∈[Доцент]∈ e2 , e2 ∈ [Профессор]∈ e3 , e3 ∈[доцент]∈ e4 , e4 ∈ [профессор] | ∈ e5 , e5 = null∈ e6 , e6∈[A-Z]{1}[a-z]{1,50}∈ e7 , e7∈[a-z]{1,50}∈ e8 , e8∈[A-Я]{1}[а-я]{1,50}⋃∉ [Доцент]⋃∉ [Профессор]
SizeOfTeachingExperience | ∈ f1, f1∈[0-9]{1,2} | ∈ f2 , f2∈[a-z]{1,50}∈ f3 , f3∈[A-Z]{1}[a-z]{1,50}∈ f4 , f4 ∈[A-Я]{1,50}∈ f5 , f5 ∈[а-я]{1,50}

**Comment by KharlamovaAlexandra** [comment]
Добрый день,@YuriSilenok
Посмотрите пожалуйста у меня первую часть задания.
Сильный - Нормальный: (a1,b1,c1,d1,e1,f1);(a2,b2,c2,d2,e2,f2);(a3,b3,c3,d3,e3,f3);(a4,b4,c4,d4,e4,f4);(a5,b5,c5,d5,e5,f5);(a6,b6,c6,d6,e6,f1);(a1,b1,c1,d7,e7,f2);(a2,b2,c2,d8,e8,f3);(a3,b3,c3,d9,e1,f4);(a4,b4,c4,d10,e2,f5);

**Comment by YuriSilenok** [comment]
Здравствуйте,
так как подход в тестировании будет сменен (в место классов эквивалентности будет тестирование методом белый ящик) то классы эквивалентности не могут быть приняты в качестве ЛР, но если Вас интересует ошибки в том что Вы уже сделали, я могу проверить по Вашему желанию.
Спасибо.

**Comment by KharlamovaAlexandra** [comment]
Добрый вечер, @YuriSilenok 
Я бы хотела узнать свои ошибки в уже проделанной части работы.
Спасибо.
С уважением, Александра

**Comment by YuriSilenok** [comment]
Добрый вечер.
У Вас форма записи данных неправильная в таблице.
Думаю [эти](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/42#issuecomment-467965366) комментарии помогут понять если не все, то большую половину.
Спасибо, Юрий

**Comment by KharlamovaAlexandra** [comment]
Состояние таблицы контроллера | Surname ∈ [[A-Я]{1}[а-я]{1,50} or А-Я]{1}[а-я]{1,50}-[А-Я]{1}[а-я]{1,50}] | Name ∈ [[A-Я]{1}[а-я]{1,50} or [А-Я]{1}[а-я]{1,50}-[А-Я]{1}[а-я]{1,50} ] | MiddleName ∈[[A-Я]{1}[а-я]{1,50} or [А-Я]{1}[а-я]{1,50}-[А-Я]{1}[а-я]{1,50} or null] | AcademicDegree ∈["Кандидат наук" or "Доктор наук" or null or "кандидат наук" or "доктор наук" ] | AcademicRank ∈[ "Доцент" or "Профессор" or "доцент" or "профессор"] | SizeOfTeachingExperience ∈ [[0-9]{1,2}]
-- | -- | -- | -- | -- | -- | --
null | task-13-1 | task-13-1 | task-13-1 | task-13-1 | task-13-1 | task-13-1
Наличие записи с эдентичным полем | task-13-2 | task-13-3 | task-13-4 | task-13-5 | task-13-6 | task-13-7
Полностью эдентичная запись | task-13-8 | task-13-8 | task-13-8 | task-13-8 | task-13-8 | task-13-8

**Comment by KharlamovaAlexandra** [comment]
Здравствуйте, @YuriSilenok 
Хочется узнать правильно ли выполнена таблица выше, что бы перейти к заполнению таблицы сценариев.

**Comment by YuriSilenok** [comment]
null - не верно, так как таблица создается в контрукторе, null не значит 0 строк и не значит пустая таблица и не значит нет записей.
В целом думаю Вы можете приступить к написанию сценариев.

**Comment by KharlamovaAlexandra** [comment]
Состояние таблицы контроллера | Surname ∈ [[A-Я]{1}[а-я]{1,50} or А-Я]{1}[а-я]{1,50}-[А-Я]{1}[а-я]{1,50}] | Name ∈ [[A-Я]{1}[а-я]{1,50} or [А-Я]{1}[а-я]{1,50}-[А-Я]{1}[а-я]{1,50} ] | MiddleName ∈[[A-Я]{1}[а-я]{1,50} or [А-Я]{1}[а-я]{1,50}-[А-Я]{1}[а-я]{1,50} or null] | AcademicDegree ∈["Кандидат наук" or "Доктор наук" or null or "кандидат наук" or "доктор наук" ] | AcademicRank ∈[ "Доцент" or "Профессор" or "доцент" or "профессор"] | SizeOfTeachingExperience ∈ [[0-9]{1,2}]
-- | -- | -- | -- | -- | -- | --
Пустая таблица без записей | task-13-1 | task-13-1 | task-13-1 | task-13-1 | task-13-1 | task-13-1
Наличие записи с эдентичным полем | task-13-2 | task-13-3 | task-13-4 | task-13-5 | task-13-6 | task-13-7
Полностью эдентичная запись | task-13-8 | task-13-8 | task-13-8 | task-13-8 | task-13-8 | task-13-8
Наличие неэдентичных записей | task-13-9 | task-13-9 | task-13-9 | task-13-9 | task-13-9 | task-13-9

**Comment by YuriSilenok** [comment]
Ответил устно

**Comment by YuriSilenok** [comment]
Пожалуйста, отформатируйте сценарии, так что бы каждый задаваемый атрибут начинался с нвоой строки. Что я имею ввиду посмотрите в task-16

**Comment by KharlamovaAlexandra** [comment]
@YuriSilenok  Замечания исправлены

**Comment by YuriSilenok** [comment]
Зачтено

**Comment by YuriSilenok** [comment]
Необходим о изучить сценарии которые уже есть, перенести их на ваш лист таблицы сценариев, доработать недостающие сценарии или убрать устаревшие сценарии.

**Comment by YuriSilenok** [comment]
> Необходим о изучить сценарии которые уже есть, перенести их на ваш лист таблицы сценариев, доработать недостающие сценарии или убрать устаревшие сценарии.

@PopovMilan подобное сообщение должны были оставить Вы

**Comment by YuriSilenok** [comment]
Меня услышали?

**Comment by PopovMilan** [comment]
Да, услышали. Буду знать, спасибо.
