### ISSUE TITLE
Разработал тесты для конструктора класса MTeacher

### ISSUE THREAD

**Issue by VinogradovAlexandr781227** [Students-of-the-city-of-Kostroma/Student-timetable#1310]
#1284 
[Сценарии (исправления task-252)](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=1813879881)

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1310 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1310 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1310 давно не было активности

**Comment by VinogradovAlexandr781227** [comment]
Начал разработку отчёта по задаче. Надеюсь сегодня, завтра залью

**Comment by YuriSilenok** [comment]
Залили?

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1310 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1310 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1310 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1310 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1310 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1310 давно не было активности

**Comment by VinogradovAlexandr781227** [comment]
@YuriSilenok  Извините за возможно глупый вопрос. У меня задача: Разработка тестов для конструктора класса MTeacher.
У меня по ходу изучения вопроса появился вопрос: Мне для всего конструктора в совокупности писать или для каждого отдельного элемента типа FirstName, SecondName и т.д.?

**Comment by YuriSilenok** [comment]
![Screenshot_20200805_232736_com.vkontakte.android.jpg](https://user-images.githubusercontent.com/14871471/89462270-d43af300-d775-11ea-8a4d-407bb235da3b.jpg)

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1310 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1310 давно не было активности

**Comment by VinogradovAlexandr781227** [comment]
@YuriSilenok Понял ваш ответ. Делаю задание.

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1310 давно не было активности

**Comment by YuriSilenok** [comment]
> @YuriSilenok Понял ваш ответ. Делаю задание. 

22 часа назад вы начали делать задание, где результаты вашего труда?

**Comment by YuriSilenok** [comment]
Добрый день. В ветке task-1310 давно не было активности

**Comment by VinogradovAlexandr781227** [comment]
@YuriSilenok А изменения получается нужно заливать вообще все, какими бы они не были по итогу деятельности?

**Comment by YuriSilenok** [comment]
Дам именно так. В ветку вы заливаете все, а запрос вы создаёте тогда, когда
можно проверять, полностью или частично.

пн, 10 авг. 2020 г., 0:06 Александр Виноградов <notifications@github.com>:

**Comment by VinogradovAlexandr781227** [comment]
@YuriSilenok 
Извиняюсь, что долго не было продвижения. 
Что вы имеете ввиду под кодом свойств и как его раскрыть?

**Comment by YuriSilenok** [comment]
У класса есть свойства, каждое свойство запрограммировано и имеет исходный код. Конструктор поочерёдно вызывает эти свойства. Есть еще какие-то вопросы?

**Comment by VinogradovAlexandr781227** [comment]
Извините, затупил. 
Нет. Больше вопросов нет.

**Comment by YuriSilenok** [comment]
5 дней? серьезно?

**Comment by VinogradovAlexandr781227** [comment]
Осталось корректировать отчёт и выложить.

**Comment by YuriSilenok** [comment]
> Осталось корректировать отчёт и выложить.

Если Вы заявляете такое, то нужно говорить и о том, когда вы это сделаете, КОГДА?

**Comment by YuriSilenok** [comment]
ГДЕ ПРОМЕЖУТОЧНЫЕ РЕЗУЛЬТАТЫ?

**Comment by VinogradovAlexandr781227** [comment]
Извините пожалуйста. Дома сейчас с интернетом проблемы. Буду с работы изменения вливать. Завтра на работе будет коммит

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by YuriSilenok** [comment]
Устаревшая ветка task-1310 будет удалена в ближайшее время

**Comment by YuriSilenok** [comment]
Устаревшая ветка task-1310 будет удалена в ближайшее время
