### ISSUE TITLE
Дефект в методе update класса CAcademicLoad.cs

### ISSUE THREAD

**Issue by ssas18** [Students-of-the-city-of-Kostroma/Student-timetable#1312]
Проверка  MAcademic.Group == null  не нужна в данном классе , а точнее в методе update  по причине того, что данная проверка осуществляется вне этого метода. Данная ошибка находится [здесь](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/409fc228c17b1a23e27838b812a70de3f6a8bab0/LibOfTimetableOfClasses/CAcademicLoad.cs) 

#1280

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ссылки на код где допущена данная ошибка

**Comment by ssas18** [comment]
Ошибка находится в классе CAcademicLoad.cs в методе Update(119 строка)

**Comment by YuriSilenok** [comment]
Вы дали описание, а нужна ссылка, что бы кликнул по ней я смог перейти к версии файла в котором  содержится ошибка.

**Comment by ssas18** [comment]
Данная ошибка находиться [здесь ](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/LibOfTimetableOfClasses/CAcademicLoad.cs)

**Comment by YuriSilenok** [comment]
Почти правильно.
Теперь расскажу сокровенное. 
Слова "Версия файла" означает что есть некий коммит в котором зафиксировано состояние файла.
То есть новый коммит порождает новую версию файла, даже если файл не менялся.
Суть вот в чем, каждый коммит знает из какого другого коммита он был сделан, таким образом получается древовидная структура. И каждая ветка этого дерева имеет свое название. Давайте представим что коммиты на этом дереве это листочки. И суть в том что когда вы говорите, посмотрите вон на той ветке файл в котором ошибка, то да, она там есть, но только ее можно будет увидеть на некоторых коммитах (листочках). Такие ветки растут и на ней появляются новые коммиты (листочки). И в какой-то момент получится так, что когда вы скажете: "Посмотрите, на той ветке в файле ошибка", то когда отрастут новые листочки исправляющие ошибку, нам будет сложно разобюраться в каких листиках эта ошибка есть, а в каких нет.

Ах да, к чему это я.
Нужно предоставлять ссылку на файл не в ветке, а на определенный коммит, в котором точно будет существовать эта ошибка, например [вот так](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/tree/5fa073a4211841b358cccdfe4ac123c50e2a2a85)

Обратите внимание как это отображается в браузере
![image](https://user-images.githubusercontent.com/14871471/87705475-97975f80-c7a6-11ea-8aed-72a89465a361.png)

**Comment by ssas18** [comment]
То есть

> Почти правильно.
> Теперь расскажу сокровенное.
> Слова "Версия файла" означает что есть некий коммит в котором зафиксировано состояние файла.
> То есть новый коммит порождает новую версию файла, даже если файл не менялся.
> Суть вот в чем, каждый коммит знает из какого другого коммита он был сделан, таким образом получается древовидная структура. И каждая ветка этого дерева имеет свое название. Давайте представим что коммиты на этом дереве это листочки. И суть в том что когда вы говорите, посмотрите вон на той ветке файл в котором ошибка, то да, она там есть, но только ее можно будет увидеть на некоторых коммитах (листочках). Такие ветки растут и на ней появляются новые коммиты (листочки). И в какой-то момент получится так, что когда вы скажете: "Посмотрите, на той ветке в файле ошибка", то когда отрастут новые листочки исправляющие ошибку, нам будет сложно разобюраться в каких листиках эта ошибка есть, а в каких нет.
> 
> Ах да, к чему это я.
> Нужно предоставлять ссылку на файл не в ветке, а на определенный коммит, в котором точно будет существовать эта ошибка, например [вот так](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/tree/5fa073a4211841b358cccdfe4ac123c50e2a2a85)
> 
> Обратите внимание как это отображается в браузере
> ![image](https://user-images.githubusercontent.com/14871471/87705475-97975f80-c7a6-11ea-8aed-72a89465a361.png)

То есть мне нужно указать на тот коммит в котором появился этот файл или данные строчки, с которыми связана ошибка?
и я не совсем понял как мне перейти на конкретный коммит, как здесь
![image](https://user-images.githubusercontent.com/47377817/87756981-82f0b100-c812-11ea-9c01-d6bfed71f192.png)

**Comment by YuriSilenok** [comment]
![image](https://user-images.githubusercontent.com/14871471/87877739-b422da00-c9e8-11ea-9803-54a24d25abd7.png)
- 1 Вы попадете на последний коммит ветки
- 2 Вы попадете на список коммитов ветки из которого вы сможете перейти на интересующий вас коммит.

А так способов перейти на коммит, достаточно много, я показал самые простые.

**Comment by ssas18** [comment]
это правильный [коммит ?](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/409fc228c17b1a23e27838b812a70de3f6a8bab0/UnitTestOfTimetableOfClasses/UT_Update_CAcademicLoad.cs)

**Comment by YuriSilenok** [comment]
Да, вы указали верно, теперь разберемся с тем, где находится на самом деле ошибка.
`MAcademic.Group == null` эта строчка находится в тесте?

**Comment by ssas18** [comment]
понял свою ошибку, простите за невнимательность получается [так](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/409fc228c17b1a23e27838b812a70de3f6a8bab0/LibOfTimetableOfClasses/CAcademicLoad.cs)

**Comment by YuriSilenok** [comment]
> понял свою ошибку, простите за невнимательность получается [так](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/409fc228c17b1a23e27838b812a70de3f6a8bab0/LibOfTimetableOfClasses/CAcademicLoad.cs)

Да, совершенно верно, теперь осталось собраться с мыслью, и подробно описать суть проблемы в описании этой задачи.

**Comment by YuriSilenok** [comment]
@ssas18 Обратил внимание на заголовок бага. Могли бы поправить описав суть бага. Можно воспользоваться вот [этой](https://habr.com/ru/company/docsvision/blog/264163/) статьей для понимания того что там должно быть.

**Comment by ssas18** [comment]
> @ssas18 Обратил внимание на заголовок бага. Могли бы поправить описав суть бага. Можно воспользоваться вот [этой](https://habr.com/ru/company/docsvision/blog/264163/) статьей для понимания того что там должно быть.

Исправить баг расположенный в UT_Update_CAcademicLoad?

**Comment by YuriSilenok** [comment]
> > @ssas18 Обратил внимание на заголовок бага. Могли бы поправить описав суть бага. Можно воспользоваться вот [этой](https://habr.com/ru/company/docsvision/blog/264163/) статьей для понимания того что там должно быть.
> 
> Исправить баг расположенный в UT_Update_CAcademicLoad?

Давайте не будет путать термины, [ознакомьтесь](http://okiseleva.blogspot.com/2015/05/blog-post_29.html)
Дефект находится в другом месте. И мы как бы уже даже определились где она находится. Сами юнит тесты воспроизводят сбой, они не содержат дефекта.

**Comment by ssas18** [comment]
Логичес

> > > @ssas18 Обратил внимание на заголовок бага. Могли бы поправить описав суть бага. Можно воспользоваться вот [этой](https://habr.com/ru/company/docsvision/blog/264163/) статьей для понимания того что там должно быть.
> > 
> > 
> > Исправить баг расположенный в UT_Update_CAcademicLoad?
> 
> Давайте не будет путать термины, [ознакомьтесь](http://okiseleva.blogspot.com/2015/05/blog-post_29.html)
> Дефект находится в другом месте. И мы как бы уже даже определились где она находится. Сами юнит тесты воспроизводят сбой, они не содержат дефекта.

Логическая ошибка в классе CAcademicLoad.cs?

**Comment by YuriSilenok** [comment]
Не ошибка, а дефект. Ошибка это момент когда разработчик ошибся, в результате которой в программном продукте появляется дефект, который проявляется в виде сбоя при выполнении определенного сценария. Для описания сбоя создается баг. На основании описания разработчик должен иметь возможность понять как воспроизвести сбой. В нашем случае сбоя у нас не будет, так как по сути это дублирующая проверка. По этому это скорее не баг, а улучшение. Нужно описать что нужно сделать разработчику для улучшения кода.

**Comment by YuriSilenok** [comment]
Так, а описание?

**Comment by ssas18** [comment]
> Так, а описание?

Изменить автотест на класс?

**Comment by YuriSilenok** [comment]
Вы можете упоминать автотесты только для того, что бы не забыть потом его исправить.

**Comment by Alphavite51** [comment]
> > @ssas18 Обратил внимание на заголовок бага. Могли бы поправить описав суть бага. Можно воспользоваться вот [этой](https://habr.com/ru/company/docsvision/blog/264163/) статьей для понимания того что там должно быть.
> 
> Исправить баг расположенный в UT_Update_CAcademicLoad?

**Comment by Alphavite51** [comment]
> Логичес
> 
> > > > @ssas18 Обратил внимание на заголовок бага. Могли бы поправить описав суть бага. Можно воспользоваться вот [этой](https://habr.com/ru/company/docsvision/blog/264163/) статьей для понимания того что там должно быть.
> > > 
> > > 
> > > Исправить баг расположенный в UT_Update_CAcademicLoad?
> > 
> > 
> > Давайте не будет путать термины, [ознакомьтесь](http://okiseleva.blogspot.com/2015/05/blog-post_29.html)
> > Дефект находится в другом месте. И мы как бы уже даже определились где она находится. Сами юнит тесты воспроизводят сбой, они не содержат дефекта.
> 
> Логическая ошибка в классе CAcademicLoad.КС?

получается в классе CAcademicLoad.CS есть часть кода которая написано не рационально и ее нужно изменить?

**Comment by ssas18** [comment]
> > Логичес
> > > > > @ssas18 Обратил внимание на заголовок бага. Могли бы поправить описав суть бага. Можно воспользоваться вот [этой](https://habr.com/ru/company/docsvision/blog/264163/) статьей для понимания того что там должно быть.
> > > > 
> > > > 
> > > > Исправить баг расположенный в UT_Update_CAcademicLoad?
> > > 
> > > 
> > > Давайте не будет путать термины, [ознакомьтесь](http://okiseleva.blogspot.com/2015/05/blog-post_29.html)
> > > Дефект находится в другом месте. И мы как бы уже даже определились где она находится. Сами юнит тесты воспроизводят сбой, они не содержат дефекта.
> > 
> > 
> > Логическая ошибка в классе CAcademicLoad.КС?
> 
> получается в классе CAcademicLoad.CS есть часть кода которая написано не рационально и ее нужно изменить?

Да, а точнее в методе update

**Comment by YuriSilenok** [comment]
@Alphavite51 есть причина по которой вы закрыли эту задачу?

**Comment by Alphavite51** [comment]
> @Alphavite51 есть причина по которой вы закрыли эту задачу?

У меня она не закрыта

**Comment by YuriSilenok** [comment]
> > @Alphavite51 есть причина по которой вы закрыли эту задачу?
> 
> У меня она не закрыта

Так, интересно, можете показать скрин?

**Comment by Alphavite51** [comment]
![Screenshot_2020-07-24-18-33-23.png](https://user-images.githubusercontent.com/47320668/88408492-4d346500-cddc-11ea-9acc-98079cd175f5.png)

**Comment by YuriSilenok** [comment]
Я на этом скрине вижу что задача закрыта.
![image](https://user-images.githubusercontent.com/14871471/88408847-c764e980-cddc-11ea-8518-3ee84b9635c5.png)

**Comment by YuriSilenok** [comment]
А вот запись о том что вы задачу закрыли
![image](https://user-images.githubusercontent.com/14871471/88408910-dea3d700-cddc-11ea-9c1d-d89302f59ed5.png)

**Comment by YuriSilenok** [comment]
А вы как определяете что задача открыта?

**Comment by Alphavite51** [comment]
Как ее теперь открыть?

**Comment by Alphavite51** [comment]
Все, вроде разобрался

**Comment by Alphavite51** [comment]
> понял свою ошибку, простите за невнимательность получается [так](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/409fc228c17b1a23e27838b812a70de3f6a8bab0/LibOfTimetableOfClasses/CAcademicLoad.cs)

Что должен делать метод?

**Comment by Alphavite51** [comment]
> Ошибка находится в классе CAcademicLoad.cs в методе Update(119 строка)

Что должен этот метод делать?

**Comment by ssas18** [comment]
> > Ошибка находится в классе CAcademicLoad.cs в методе Update(119 строка)
> 
> Что должен этот метод делать?

Обновляет данные в рефдате

**Comment by Alphavite51** [comment]
> > > Ошибка находится в классе CAcademicLoad.cs в методе Update(119 строка)
> > 
> > 
> > Что должен этот метод делать?
> 
> Обновляет данные в рефдате

так он и обновляет вроде, что не верно то там

**Comment by Alphavite51** [comment]
у меня выдает ошибку референсов в которой не подключены сборки " IController " , " Model " и " MAcademicLoad "

**Comment by ssas18** [comment]
> > > > Ошибка находится в классе CAcademicLoad.cs в методе Update(119 строка)
> > > 
> > > 
> > > Что должен этот метод делать?
> > 
> > 
> > Обновляет данные в рефдате
> 
> так он и обновляет вроде, что не верно то там

В нем есть излишняя проверка

**Comment by YuriSilenok** [comment]
> у меня выдает ошибку референсов в которой не подключены сборки " IController " , " Model " и " MAcademicLoad "

Если вы обнаружили сбой, то нужно поднять баг.

**Comment by YuriSilenok** [comment]
@ssas18 
Подтвердите что претензий по багу у вас больше нет

**Comment by ssas18** [comment]
Баг устранён

**Comment by YuriSilenok** [comment]
@ssas18 возвращает задачу @Alphavite51 так как он проверку выполнил,
@Alphavite51 назначает на меня для выставления отметки в журнал.

**Comment by YuriSilenok** [comment]
[Зачтено](https://docs.google.com/spreadsheets/d/1uBd4d3VvI4rYeuXkXmqLyEZSitS8K9pfVUDtM3i1Vg4/edit#gid=1640195575&range=J8)
