### ISSUE TITLE
Отделение инициализации данных рефдаты из её конструктора.

### ISSUE THREAD

**Issue by ifuwmnn** [Students-of-the-city-of-Kostroma/Student-timetable#1323]
Требуется отделить инициализацию данных рефдаты из её конструктора.

**Comment by YuriSilenok** [comment]
При таком отделении, возникнет множество сбоев в автотестах, по идее все можно решить за 15 минут, главное уметь пользоваться автозаменой по проекту. Количество сбоев не должно увеличется.
@Students-of-the-city-of-Kostroma/17-elite кто возьмётся?

**Comment by YuriSilenok** [comment]
@ifuwmnn вы и я проверяем запрос, вы не можете делать эту задачу

**Comment by YuriSilenok** [comment]
@Students-of-the-city-of-Kostroma/17-elite
Если кто-то умеет грамотно пользоваться заменой, то это задача для вас.

**Comment by YuriSilenok** [comment]
У вас уже есть первые наработки? Ожидал увидеть ветку, вдруг что-то есть на что можно посмотреть?

**Comment by Alphavite51** [comment]
с каким фаилом необходимо работать RefData.cs ??

**Comment by YuriSilenok** [comment]
> с каким фаилом необходимо работать RefData.cs ??

- В конструкторе указанного Вами файла есть часть, которая заполняет таблицы данными, ее нужно перенести в отдельный метод.
- Когда вы сделаете предыдущий шаг, половина +- автотестов упадет. Нужно будет во всем тестах, которые упали из-за ваших изменений добавить вызов метода добавление данных в таблице.

У Вас остались еще вопросы?

**Comment by Alphavite51** [comment]
> > с каким фаилом необходимо работать RefData.cs ??
> 
> - В конструкторе указанного Вами файла есть часть, которая заполняет таблицы данными, ее нужно перенести в отдельный метод.
> - Когда вы сделаете предыдущий шаг, половина +- автотестов упадет. Нужно будет во всем тестах, которые упали из-за ваших изменений добавить вызов метода добавление данных в таблице.
> 
> У Вас остались еще вопросы?

Нет, спасибо за объснение

**Comment by Alphavite51** [comment]
> > с каким фаилом необходимо работать RefData.КС ??
> 
> * В конструкторе указанного Вами файла есть часть, которая заполняет таблицы данными, ее нужно перенести в отдельный метод.
> * Когда вы сделаете предыдущий шаг, половина +- автотестов упадет. Нужно будет во всем тестах, которые упали из-за ваших изменений добавить вызов метода добавление данных в таблице.
> 
> У Вас остались еще вопросы?

InitData же уже в отдельном методе, получается первый пункт уже выполене, или я что то не понимаю

**Comment by YuriSilenok** [comment]
Да, хорошо что вы разобрались.
Теперь вызов этого метода в конструкторе нужно убрать и сделать  этот метод доступным для вызова из вне

**Comment by Alphavite51** [comment]
> Да, хорошо что вы разобрались.
> Теперь вызов этого метода в конструкторе нужно убрать и сделать  этот метод доступным для вызова из вне

Вызов InitData нужно удалить?

**Comment by YuriSilenok** [comment]
> > Да, хорошо что вы разобрались.
> > Теперь вызов этого метода в конструкторе нужно убрать и сделать  этот метод доступным для вызова из вне
> 
> Вызов InitData нужно удалить?

Думаю да. Но вы лучше делайте, а не спрашивайте.

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by Alphavite51** [comment]
> Задача с Вас снята, так как по ней давно не было активности.
Ветку делать из dev или из мастера

**Comment by Alphavite51** [comment]
> Задача с Вас снята, так как по ней давно не было активности.

Пул реквест делать из дев или из мастера

**Comment by YuriSilenok** [comment]
> > Задача с Вас снята, так как по ней давно не было активности.
> 
> Пул реквест делать из дев или из мастера

Об этом написано в документации, в чате и например вот в [этой](https://habr.com/ru/post/106912/) статье.

**Comment by YuriSilenok** [comment]
- если вы закончили задачу, почему вы её еще держите на себе?
- вы во все связанные задачи написали о том, что нужно получить обновления из дев?

**Comment by YuriSilenok** [comment]
Я не увидел что бы вы во все ОТКРЫТЫЕ связанные запросы и задачи написали.

**Comment by YuriSilenok** [comment]
Задача была на меня перевешана потому что вы отказываетесь её выполнять?

**Comment by Alphavite51** [comment]
> Задача была на меня перевешана потому что вы отказываетесь её выполнять? 

Она же выполнена

**Comment by Alphavite51** [comment]
> Задача была на меня перевешана потому что вы отказываетесь её выполнять? 

И вы сами просили ее на вас перевести для отметки

**Comment by Alphavite51** [comment]
@YuriSilenok перевел на вас задачу, проверьте ее пожалуйста

**Comment by YuriSilenok** [comment]
> @YuriSilenok перевел на вас задачу, проверьте ее пожалуйста

[Зачтено](https://docs.google.com/spreadsheets/d/1uBd4d3VvI4rYeuXkXmqLyEZSitS8K9pfVUDtM3i1Vg4/edit#gid=1640195575&range=K8)
