### ISSUE TITLE
На форму расписание добавить расписание для студентов

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#1326]
Эта задача является частью #1227
---
Я как студент должен иметь возможность просмотреть свое расписание.
Для того что бы я мог увидеть свое расписание, я должен выбрать из выпадающего списка институт.
После выбора института, поле "Выберите направление подготовки" должно стать доступным и содержать значения соответствующие моему институту.
После выбора профиля подготовки, поле "Выберите группу" должно сталь доступным и содержать значения соответствующие моему профилю подготовки.
После выбора группы из выпадающего списка, таблица с расписанием должна заполнится.
Если после выбора группы, я сменю институт, то поля направления подготовки должны принять первоначальное значение и стать неактивными.
если после выбора группы, я сменю направление подготовки, то поле группа, должна принять первоначальное значение и стать неактивным.

**Comment by ZhizhikinIvan** [comment]
Здравствуйте Юрий Викторович.
Программа не запускается. Есть ошибки в данных RefData.cs. Мне править их?

**Comment by ZhizhikinIvan** [comment]
Юрий Викторович, не могли бы вы конкретизировать задачу, я не особо понимаю, что мне надо сделать. 
Какой выпадающий список вы имеете ввиду (на форме "Расписание" их 3 штуки)?

![image](https://user-images.githubusercontent.com/47943099/90814101-43494780-e331-11ea-804d-ebf991329717.png)

**Comment by YuriSilenok** [comment]
> Здравствуйте Юрий Викторович.
> Программа не запускается. Есть ошибки в данных RefData.cs. Мне править их?

Программа должна запускаться, в какой ветке вы это делаете?

**Comment by YuriSilenok** [comment]
> Юрий Викторович, не могли бы вы конкретизировать задачу, я не особо понимаю, что мне надо сделать. 
> Какой выпадающий список вы имеете ввиду (на форме "Расписание" их 3 штуки)?
> 
> ![image](https://user-images.githubusercontent.com/47943099/90814101-43494780-e331-11ea-804d-ebf991329717.png)
> 

Все интересующие вас вы падающие списки находятся на снимке экрана в левом верхнем углу, над таблицей. Вы их не видите?

**Comment by ZhizhikinIvan** [comment]
Юрий Викторович, я так понял, что мне необходимо реализовать вот эти выпадающие списки (на снимке макета обведены красным)? 
Так же хотелось бы уточнить, входит ли в мою задачу, реализация заполнения расписания (на снимке макета обведено синим)? Если да, то откуда мне взять само расписание?

![image](https://user-images.githubusercontent.com/47943099/90980999-2bf39f80-e567-11ea-9000-922b4b61cbb7.png)

**Comment by YuriSilenok** [comment]
> После выбора группы из выпадающего списка, **таблица с расписанием должна заполнится**.

Для вас эта формулировка не означает что таблица с расписанием должна заполняться?

**Comment by YuriSilenok** [comment]
> откуда мне взять само расписание?

Все контроллеры (таблицы) которые имеются на данный момент, находятся в классе RefData. Изучите их пожалуйста. Если окажется что контролёров и слюнки к ней не будет существовать, то вам нужно будет поднять задачу, её выполнением займётся другой человек, а вы будете принимать эту задачу.

**Comment by ZhizhikinIvan** [comment]
Задача не заброшена. Работа над ней продолжается.

**Comment by YuriSilenok** [comment]
> Задача не заброшена. Работа над ней продолжается.

Чем докажете? Где ваша ветка на гитхаб с промежуточными результатами?
![image](https://user-images.githubusercontent.com/14871471/91398283-77969980-e844-11ea-83bd-d376bce0124f.png)

**Comment by ZhizhikinIvan** [comment]
Переделал форму "Расписание" согласно макету. Сейчас пытаюсь разобраться с реализацией загрузки данных в выпадающие списки и в само расписание. Ветка с результатом будет в скором времени.

![image](https://user-images.githubusercontent.com/47943099/91496522-f3d0c180-e8c4-11ea-9a7c-173755b39afa.png)

**Comment by YuriSilenok** [comment]
> Переделал форму "Расписание" согласно макету. Сейчас пытаюсь разобраться с реализацией загрузки данных в выпадающие списки и в само расписание. Ветка с результатом будет в скором времени.
> 
> ![image](https://user-images.githubusercontent.com/47943099/91496522-f3d0c180-e8c4-11ea-9a7c-173755b39afa.png)

вы нормальные слова понимаете, я спрашиваю ветку, вы мне скрин пихаете.

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by ZhizhikinIvan** [comment]
@YuriSilenok Юрий Викторович, можно как-нибудь вернуть задачу? В запросе была активность.

**Comment by YuriSilenok** [comment]
Возвращайте, завтра ещё посмотрю почему так получилось.

вт, 1 сент. 2020 г., 20:53 Жижикин Иван <notifications@github.com>:

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности. Активность по основной задаче #1326 составляет 10 дней. Активность в ветке task-1326 составляет 4 дней. Активность по запросу #1338 составляет 3 дней. Нет запросов, которые должен проверить преподаватель

**Comment by ZhizhikinIvan** [comment]
@YuriSilenok Юрий Викторович, а можно как-нибудь вернуть задачу? Сегодня вечером планировал залить обновление в решении.

**Comment by YuriSilenok** [comment]
Добрый день,
в чем проблема, Вы в принципе четвертый день нечего не делаете?

**Comment by ZhizhikinIvan** [comment]
Я третий день болею. Был не в состоянии работать. Сегодня получше стало, думал доделать задачу, ну или попытаться это сделать.

**Comment by YuriSilenok** [comment]
Если вы поняли что не в состоянии работать и есть возможность ответить, пожалуйста, предупреждайте об этом. иначе это выглядит неправдоподобно.

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности. Активность по основной задаче #1326 составляет 5 дней. Ветка отсутствует. Запрос отсутствует. Нет запросов, которые должен проверить преподаватель

**Comment by YuriSilenok** [comment]
Задание обсуждать правильнее в самом задании.
В ответ на Ваш [вопрос](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1338#issuecomment-695819377)

> Не могли бы вы объяснить, как определить направление подготовки для конкретного института?

У выпадающих списков есть поле с ресурсами, в которое можно подключить таблицу. В список можно вывести только один столбец из какой-то таблицы, а так же можно выполнить фильтрацию этих данных. Ничего хардкодить особо не придется. Сообщите что вы сможете найти по этому поводу.

**Comment by ZhizhikinIvan** [comment]
В данный момент направление подготовки никак не связанно с институтом. Как это должно быть реализовано?

**Comment by YuriSilenok** [comment]
> В данный момент направление подготовки никак не связанно с институтом. Как это должно быть реализовано?

Думаю должна быть связь между ними. Сможете ее сделать?

**Comment by ZhizhikinIvan** [comment]
Сделать то смогу, но это потребует изменений в RefData и возможно в юнит тестах.
В CDirectionOfPreparation добавить поле с коротким именем института, а в RefData добавить Relation между таблицами CDirectionOfPreparation и CInstitute.

**Comment by YuriSilenok** [comment]
> Сделать то смогу, но это потребует изменений в RefData и возможно в юнит тестах.
> В CDirectionOfPreparation добавить поле с коротким именем института, а в RefData добавить Relation между таблицами CDirectionOfPreparation и CInstitute.

За тесты не волнуйтесь, на вашу работу не повлияет. Реализуйте связь.

**Comment by YuriSilenok** [comment]
Задача с Вас  снята, так как по ней давно не было активности. Активность по основной задаче #1326 составляет 77 дней. Ветка отсутствует. Запрос отсутствует. Нет запросов, которые должен проверить преподаватель

**Comment by YuriSilenok** [comment]
[зачтено](https://docs.google.com/spreadsheets/d/1uBd4d3VvI4rYeuXkXmqLyEZSitS8K9pfVUDtM3i1Vg4/edit#gid=1029316146&range=L10)
