### ISSUE TITLE
На форму расписание добавить расписание для преподавателей

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#1328]
Эта задача является частью #1227
---
Я как преподаватель должен иметь возможность отфильтровать свое расписание, что бы ускорить поиск своего расписания
Для того что бы я мог увидеть свое расписание я должен иметь возможность ввести в поисковую строку свою фамилию. 
После ввода своей фамилии в списке должны остаться только те, преподаватели, которые содержат искомое фразу.
При выборе из списка фамилии, таблица ниже должна заполнится.

**Comment by NesgovorovVS** [comment]
Прошу не снимать задачу, работаю над ней.

**Comment by YuriSilenok** [comment]
Если вы работаете над дней, где ветка с коммитами?

**Comment by NesgovorovVS** [comment]
> Если вы работаете над дней, где ветка с коммитами?

Сегодня вечером будут коммиты
Ветка уже пущена.

**Comment by NesgovorovVS** [comment]
![image](https://user-images.githubusercontent.com/47756995/91092410-a8b67480-e660-11ea-8615-4ad20356bd12.png)
появилась проблема в запуске проекта + появились файлы, которые показывает гит, что я менял, но я их не трогал, исправляю
![image](https://user-images.githubusercontent.com/47756995/91092579-e915f280-e660-11ea-922c-bd7cdd5572a7.png)

**Comment by NesgovorovVS** [comment]
> ![image](https://user-images.githubusercontent.com/47756995/91092410-a8b67480-e660-11ea-8615-4ad20356bd12.png)
> появилась проблема в запуске проекта + появились файлы, которые показывает гит, что я менял, но я их не трогал, исправляю
> ![image](https://user-images.githubusercontent.com/47756995/91092579-e915f280-e660-11ea-922c-bd7cdd5572a7.png)

решил проблему, вечером выгружу новые изменения

**Comment by NesgovorovVS** [comment]
Не было возможности продолжать работу из-за ошибки. Прошу задачу не снимать.
![image](https://user-images.githubusercontent.com/47756995/91689498-eb9aaf80-eb6c-11ea-8feb-79adf6698904.png)

**Comment by YuriSilenok** [comment]
Судя по активности в ветке, вы решили проблему. если это так, то нужно отписывать что проблема решена, что бы человек читающий о вашей проблеме знал, что проблема еще актуальна. На тот случай если он соберется помочь вам решить ее.

**Comment by NesgovorovVS** [comment]
> Судя по активности в ветке, вы решили проблему. если это так, то нужно отписывать что проблема решена, что бы человек читающий о вашей проблеме знал, что проблема еще актуальна. На тот случай если он соберется помочь вам решить ее.

А я отписывал,но в диалог, что проблема решена.

**Comment by YuriSilenok** [comment]
Чаты не главное, все должно документироваться в задачах, запросах, коммита.

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности. Активность по основной задаче #1328 составляет 17 дней. Ветка отсутствует. Запрос отсутствует. Нет запросов, которые должен проверить преподаватель

**Comment by YuriSilenok** [comment]
Задача с Вас  снята, так как по ней давно не было активности. Активность по основной задаче #1328 составляет 18 дней. Активность в ветке issue-1328 составляет 2 дней. Запрос отсутствует. Нет запросов, которые должен проверить преподаватель

**Comment by YuriSilenok** [comment]
Ветка issue-1328 удалена
