### ISSUE TITLE
Создать форму Кафедры

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#133]
Вызывается из стартовой формы в верхнем меню пунктом Справочники-Кафедры подготовки
Имя формы Department
Графический интерфейс:

- Заголовок формы Кафедры
- Таблица привязанная ко всем сторонам формы. И имеет отступ 3px от кнопок снизу.
- Кнопка Добавить имеет стандартные размеры и привязку к правому и нижнему краю формы. Отступ со всех сторон 3px. Расположена в правом нижнем углу формы.
- Кнопка Удалить имеет стандартные размеры и привязана к правому и нижнему краю формы. Отступ со всех сторон 3px. Расположена внизу формы, левее кнопки Добавить с отступом в 3px.

**Comment by VinogradovAlexandr781227** [comment]
Сколько столбцов и строчек должно быть в таблице и какими значениями их заполнять?

**Comment by YuriSilenok** [comment]
Ничего добавлять не нужно. Таблица пустая. Потом будет привязываться источник данных. Это только гуя.

**Comment by YuriSilenok** [comment]
@Students-of-the-city-of-Kostroma/17idb 
- Где ваша доска (Project)
- Когда ожидать активности по этой задаче?

**Comment by sidelong44** [comment]
Мы же её уже сделали, не?

**Comment by VinogradovAlexandr781227** [comment]
Здравствуйте

пт, 31 мая 2019 г. в 09:00, Юрий Силенок <notifications@github.com>:

**Comment by VinogradovAlexandr781227** [comment]
Здравствуйте

Сделаю сегодня, завтра утром обязательно. Вернее исправлю конфликты. Я
забыл что там были конфликты. Думал она уже зачтена. Извиняюсь за задержку

Спасибо
Александра Виноградов
17-ИСбо-2б

пт, 31 мая 2019 г. в 09:00, Юрий Силенок <notifications@github.com>:

**Comment by YuriSilenok** [comment]
Что с этим таском?

**Comment by VinogradovAlexandr781227** [comment]
Здравствуйте 

Готовился к экзамену. Завтра экзамен пройдёт и 2 дня будут полностью свободными, сделаю и отправлю на проверку. 

Спасибо
Виноградов Александр
17-ИСбо-2б

Отправлено с iPhone

**Comment by YuriSilenok** [comment]
Эта задача еще актуальна?

**Comment by VinogradovAlexandr781227** [comment]
Здравствуйте

Если я могу исправить в ней конфликты и это зачтется за лабораторную, то я
сделаю. Просто Я сказал что сделаю её, там сообщение кривое пришло и вы
закрыли эту задачу

Спасибо
Виноградов Александр
17-ИСбо-2б

вторник, 18 июня 2019 г. пользователь Юрий Силенок <notifications@github.com>
написал:

**Comment by YuriSilenok** [comment]
Вы можете открыть новый запрос на слияние.
При проверке открытых запросов и задач я обращаю внимание на те, по которым не было активности 7 и более дней.
