### ISSUE TITLE
Разработать функцию корректировки норм учебной нагрузки для сотрудников вуза

### ISSUE THREAD

**Issue by Heriuple** [Students-of-the-city-of-Kostroma/Student-timetable#1339]
User Story v 0.11

"Мне, как члену учебного отдела, требуется функция корректировки норм учебной нагрузки для преподавателей вуза, чтобы автоматизировать работу по проверке нагрузки установленным нормам".

Критерии приемки:
1) В зависимости от занимаемой должности (декан, заведующий кафедры) или же учебного звания (профессор, старший преподаватель) можно было у каждого из них изменять максимальное и минимальное количество часов.
2) Лекционные работы, система, при такой возможности ставит профессорам, деканам, поскольку она является наиболее сложной и трудоемкой.
3)объем лекционной нагрузки профессорам и доцентам планируется не менее 10% от общей нагрузки в год.
4)Объем учебной нагрузки сокращается для Декана, зав кафедры и тп.Они имеют значения по умолчанию, равные: Декан - 150 ч, Зав Кафедры - 100 ч, Зам. Декана - 100 ч.

Обработка ошибок:
1)При вводе отрицательных значений, система должна либо считывать с отрицанием, либо же выводить оповещение об ошибке.
2)При вводе символов, отличающихся от цифр, система должна выводить ошибку, либо же не допускать введение данных символов, так же с оповещением.
(Может дополняться, по ходу разработки)

Тех заметки:
Отсутствуют.

**Comment by Heriuple** [comment]
По задаче работа продолжается, из-за технических осложнений ход её замедлился.

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности. Активность по основной задаче #1339 составляет 6 дней. Активность в ветке task-1339 составляет 6 дней. Активность по запросу #1342 составляет 3 дней. Нет запросов, которые должен проверить преподаватель

**Comment by YuriSilenok** [comment]
Тэк. Понятно. Пора делать документы

**Comment by YuriSilenok** [comment]
Приступайте пока к реализации, формулировки по ходу уточним

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности. Активность по основной задаче #1339 составляет 11 дней. Ветка отсутствует. Запрос отсутствует. Нет запросов, которые должен проверить преподаватель
