### ISSUE TITLE
Исправление опечаток в документе README.MD

### ISSUE THREAD

**Issue by NesgovorovVS** [Students-of-the-city-of-Kostroma/Student-timetable#1340]
@YuriSilenok  сразу извиняюсь за инициативу, просто при повторном прочтении заметил опечатки и решил исправить.

**Comment by YuriSilenok** [comment]
думаю эту задачу можно будет зачесть за долг.
Но так как это задача не имеет отношения к программированию, то попробуйте 5 человек заставить проверить ваш запрос.

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности. Активность по основной задаче #1340 составляет 6 дней. Ветка отсутствует. Запрос отсутствует. Нет запросов, которые должен проверить преподаватель

**Comment by YuriSilenok** [comment]
А перевешивать кто будет?
пробуйте

**Comment by NesgovorovVS** [comment]
> А перевешивать кто будет?
> пробуйте

Перевесил задачу на вас

**Comment by YuriSilenok** [comment]
[зачтено](https://docs.google.com/spreadsheets/d/1uBd4d3VvI4rYeuXkXmqLyEZSitS8K9pfVUDtM3i1Vg4/edit#gid=870820066&range=L7)
