### ISSUE TITLE
Разработать методические рекомендации к составлению пользовательской истории

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#1344]
- требования к заголовку
- критерии качества user story
- указать из каких пунктов должен состоять документ.
- раскрыть критерии приемлемости каждого пункта.
- указать роль документа в жизненном цикле ПО
- указать какие документы должны быть изменены и созданы на основании пользовательской истории. 
- информацию разместить в файлы Docs/Contributers/user_story.md
- отсылка на метки

**Comment by badsster** [comment]
@YuriSilenok добрый вечер. Я посмотрела видео о составлении пользовательских историй и хотелось бы понять, что является объектом моих рассуждений. Программа расписания или это будет какой-то отдельный документ, файл?

И хотелось бы ещё узнать про какую аудио конференцию Вы писали, когда она состоится и какой жизненный цикл проекта мне нужно описать, потому что пока не понятно, с чего мне нужно начать.

Спасибо.

**Comment by YuriSilenok** [comment]
Создайте файл в репозитрии, опишите  в нем требования к пользовательской истории. Все что сможете

**Comment by badsster** [comment]
![IMG_20200911_211958](https://user-images.githubusercontent.com/47521045/92960557-7f765080-f476-11ea-9d4b-a6a1164d1ffe.png)
@YuriSilenok Подскажите, пожалуйста, я создала ветку 1344 и файл user_story.md. 
Его создание вроде бы должно отображаться в этой задаче, а надписи Create user_story.md не появилось. Я создала как-то не так или пока там нет текста, он не отображается?

**Comment by YuriSilenok** [comment]
Изменения в ветке отображаются в запросе на слияние, а не в задаче

**Comment by badsster** [comment]
@YuriSilenok добрый вечер, написала заголовки в документе user_story.md.
Хотелось бы узнать :
1) Можно ли словарь терминов сделать в этом же документе или лучше создать новый ?

**Comment by YuriSilenok** [comment]
Обычно словари делают отдельным документом, а если терминов не много. то их расшифровывают прямо в тексте. что за термины. если они на прямую не относятся к материалу, то расшифровка терминов не должна производится, должна быть отсылка. вообщем все от контекста.

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности. Активность по основной задаче #1344 составляет 7 дней. Ветка отсутствует. Запрос отсутствует. Нет запросов, которые должен проверить преподаватель

**Comment by badsster** [comment]
@YuriSilenok Юрий Викторович, добрый вечер. Верните, пожалуйста, задачу. Я веду ежедневную работу по данному документу. Пытаюсь понять, как оформить последние 2 пункта. Не понимаю, как это нет ветки, если я создала ветку в которой хранится документ user_story.md.

**Comment by YuriSilenok** [comment]
![image](https://user-images.githubusercontent.com/14871471/93917866-38a91600-fd14-11ea-8e23-eca42a36ae40.png)
- почему у нас 2 ветки?

**Comment by YuriSilenok** [comment]
и при этом вы ведете не правильную?

**Comment by badsster** [comment]
@YuriSilenok Добрый вечер, Юрий Викторович. Увидела в беседе вк, что task обновился на issue, поэтому создала issue-1344. Мне нужно вести issue-1344 или все также продолжать работу в task-1344?

И еще один вопрос по созданию документации. 
У меня остался последний пункт и я не понимаю, какие документы мне нужно создать. 
Пункты отчета я расписала и мне нужно понять, что еще кроме отчета должно описывать User Story по Вашему мнению. Ссылку на отчет прилагаю к письму. Посмотрите, пожалуйста.

[Отчет](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/issue-1344/Docs/Contributers/user_story.md)

**Comment by YuriSilenok** [comment]
![image](https://user-images.githubusercontent.com/14871471/93930654-6008de80-fd26-11ea-8f35-729ec9bbd812.png)
Вам нужно было создать issue из task, а вы создали из dev. по этому у вас две параллельные ветки. вам нужно смержить ветку task в issue и удалить task

**Comment by YuriSilenok** [comment]
> Документы, которые должны быть изменены и созданы на основании пользовательской истории.

после беседы с пользователем, мы находим какое улучшение хотим сделать. все это мы описываем в user story, на основании нее нужно внести правки в ТЗ, так же нужно будет внести в тестовый план новую стори для тестирования и на основании user story составляются функциональные тесты.

**Comment by badsster** [comment]
> ![образ](https://user-images.githubusercontent.com/14871471/93930654-6008de80-fd26-11ea-8f35-729ec9bbd812.png)
> Вам нужно было создать issue из task, а вы создали из dev. по этому у вас две параллельные ветки. вам нужно смержить ветку task в issue и удалить task

@YuriSilenok Лучше уточню у Вас, чтобы не допустить ошибки повторно. Правильно ли я понимаю мне нужно зайти в gitbush и написать команду $ git branch -d issue-1344.
И после удаления, зайти в task-1344 и создать внутри issue-1344 ?
Скриншот прилагаю для примера.

![image](https://user-images.githubusercontent.com/47521045/93932693-3ef5bd00-fd29-11ea-9852-db927bf838d5.png)

**Comment by YuriSilenok** [comment]
выглядит верно, делайте, а там проверю

**Comment by YuriSilenok** [comment]
осталось удалить ветку task

**Comment by badsster** [comment]
@YuriSilenok Надеюсь, что внесла изменения верно.  Спасибо Вам за помощь. 
Закончила написание документации, ожидаю Вашей проверки и внесения необходимых корректировок.

[Документ](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/issue-1344/Docs/Contributers/user_story.md)

**Comment by YuriSilenok** [comment]
проверка осуществляется при помощи запросов на слияние [pull request](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/compare)

**Comment by badsster** [comment]
@YuriSilenok Добрый день,Юрий Викторович. Правильно я понимаю мне нужно произвести слияние запросов из dev в issue - 1344? 
![IMG_20200924_133526](https://user-images.githubusercontent.com/47521045/94134790-242b6180-fe6b-11ea-8329-046e34f7c9ed.png)

**Comment by YuriSilenok** [comment]
Интерпретация не верная, вы не сливаете запросы.
Вы создаете запрос на слияние двух веток.
Нужно нажать на зеленую кнопку.

**Comment by YuriSilenok** [comment]
Задача с Вас  снята, так как по ней давно не было активности. Активность по основной задаче #1344 составляет 3 дней. Активность в ветке issue-1344 составляет 3 дней. Запрос отсутствует. Нет запросов, которые должен проверить преподаватель

**Comment by YuriSilenok** [comment]
Задача с Вас  снята, так как по ней давно не было активности. Активность по основной задаче #1344 составляет 21 дней. Активность в ветке issue-1344 составляет 5 дней. Активность по запросу #1361 составляет 2 дней. Нет запросов, которые должен проверить преподаватель

**Comment by YuriSilenok** [comment]
[Зачтено](https://docs.google.com/spreadsheets/d/1uBd4d3VvI4rYeuXkXmqLyEZSitS8K9pfVUDtM3i1Vg4/edit#gid=1029316146&range=M6)
