### ISSUE TITLE
Разработать функцию корректировки учебной нагрузки для студентов вуза

### ISSUE THREAD

**Issue by VinogradovAlexandr781227** [Students-of-the-city-of-Kostroma/Student-timetable#1346]
Мне как члену учебного отдела, требуется функция корректировки нагрузки для студентов вуза, чтобы   не тратить время на проверку соблюдений норм при составлении нагрузки.
__________________________
Критерии приёмки:

- Объем учебной нагрузки обучающегося должен составлять 54 академических часа в неделю, включая все виды аудиторной и вне аудиторной учебной нагрузки.
- Объем обязательных аудиторных занятий (практическое занятие, лабораторное занятие, консультация, лекция, семинар) и практики не должен превышать 36 академических часов в неделю.
- Так как у разных направлений подготовки разная нагрузка, мы должны иметь возможность выставить индивидуальную нагрузку каждой группе, которая не будет выходить за обозначенные максимальные рамки.
__________________________
Обработка ошибок:

- При вводе значения выше максимального, система должна выводить оповещение об ошибке.
- При вводе отрицательного значения система должна выводить оповещение об ошибке.
- При вводе символов, отличающихся от цифр, система должна выводить ошибку, либо же не допускать введение данных символов.
__________________________
Тех заметки:

Отсутствуют

**Comment by VinogradovAlexandr781227** [comment]
@YuriSilenok Забыл вчера вас заассанить для проверки

**Comment by YuriSilenok** [comment]
> Мне как члену учебного отдела, требуется функция корректировки учебной нагрузки для студентов.

для чего она ему требуется?

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by VinogradovAlexandr781227** [comment]
@YuriSilenok Есть законодательные нормы нагрузки для студентов По Федеральном закону «Об образовании в Российской Федерации» при реализации образовательных программ. Думаю для соблюдения законности деятельности университета такая функция нам потребуется с учётом того, что это приложение призвано облегчить деятельность по созданию расписания

**Comment by YuriSilenok** [comment]
Для сотрудника, соблюдение норм, это головная боль. формулировка в этом направлении будет такая. 
... для того, что бы я не смог ошибиться при составлении учебной нагрузки для студентов.

**Comment by YuriSilenok** [comment]
ну или не тратить время на проверку соблюдений норм при составлении нагрузки. это дажее правильнее, так как заказчик увидит что вот именно здесь будет экономится время и деньги.

**Comment by VinogradovAlexandr781227** [comment]
@YuriSilenok замечание учтено и исправлено

**Comment by VinogradovAlexandr781227** [comment]
@YuriSilenok Я могу начинать прописывать реализацию и реализовывать данную функцию?

**Comment by YuriSilenok** [comment]
> @YuriSilenok Я могу начинать прописывать реализацию и реализовывать данную функцию?

Да

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности. Активность по основной задаче #1346 составляет 3 дней. Ветка отсутствует. Запрос отсутствует. Нет запросов, которые должен проверить преподаватель

**Comment by VinogradovAlexandr781227** [comment]
@YuriSilenok Юрий Викторович. Я затупил если честно. Мне ведь требуется сейчас создать ветку, скинуть туда сторис ссылкой и расписать какие конкретно изменения я буду поэтапно вносить в проект?

**Comment by YuriSilenok** [comment]
Сейчас идет разработка требований в рамках задачи #1344, вы можете почитать то что там уже сделано. 
Читать нужно в ветке, а вопросы задавать в той задаче.

**Comment by VinogradovAlexandr781227** [comment]
@YuriSilenok Понял, изучу материал и приступаю

**Comment by VinogradovAlexandr781227** [comment]
@YuriSilenok Хочу уточнить. Я создаю ветку, создаю файл user_story.md, в котором описываю действия, которые находятся в описании задачи #1344 
Соответственно вливаю эти изменения и жду вашей проверки? Я правильно понял?

**Comment by YuriSilenok** [comment]
Вам нужно создать документ user story в git и реализовать ее в рамках той же задачи.

**Comment by VinogradovAlexandr781227** [comment]
Сегодня вечером залью

**Comment by YuriSilenok** [comment]
Задача с Вас  снята, так как по ней давно не было активности. Активность по основной задаче #1346 составляет 2 дней. Активность в ветке issue-1346 составляет 3 дней. Запрос отсутствует. Нет запросов, которые должен проверить преподаватель

**Comment by VinogradovAlexandr781227** [comment]
Залил изменение. @YuriSilenok  Проверьте пожалуйста на соответствие документации. Сделал вроде все примерно по инструкции задачи #1344. Не совсем понял некоторые моменты к примеру про: Требования к атрибутам и Acceptance Criteria, так же не уверен, что правильно написал тестирование. Старался расписывать все в соответствии с рекомендательнным документом.

**Comment by YuriSilenok** [comment]
Создавайте запрос, будем проверять

**Comment by YuriSilenok** [comment]
Относительно требований к вашей стори, то что вы меня здесь спрашивали и я вам отвечал, не имеет особой силы, так как есть конкретная задача и запрос к ней, где вы должны все уточнять.

**Comment by VinogradovAlexandr781227** [comment]
@YuriSilenok Получается сейчас создавать запрос на проверку этого или сначала пилить функционал и тогда уже запрос на проверку всего?

**Comment by YuriSilenok** [comment]
создавайте запрос на проверку user story и поднимите задачу на кодирование user story.
Думаю это можно зачесть за 2 ЛР.

**Comment by VinogradovAlexandr781227** [comment]
Понял. Буду у компьютера, сделаю запрос и назначу ревьюверов

**Comment by YuriSilenok** [comment]
Задача с Вас  снята, так как по ней давно не было активности. Активность по основной задаче #1346 составляет 3 дней. Активность в ветке issue-1346 составляет 2 дней. Запрос отсутствует. Нет запросов, которые должен проверить преподаватель

**Comment by VinogradovAlexandr781227** [comment]
@YuriSilenok  Здравствуйте. Можно ли вернуть задачу? Переделал пул реквест. Если ответ положительный, то жду ревьюверов и поднимаю задачу на реализацию данного контента

**Comment by YuriSilenok** [comment]
Задача с Вас  снята, так как по ней давно не было активности. Активность по основной задаче #1346 составляет 2 дней. Активность в ветке issue-1346 составляет 3 дней. Запрос отсутствует. Нет запросов, которые должен проверить преподаватель

**Comment by YuriSilenok** [comment]
Задача с Вас  снята, так как по ней давно не было активности. Активность по основной задаче #1346 составляет 8 дней. Активность в ветке issue-1346 составляет 4 дней. Активность по запросу #1366 составляет 2 дней. Нет запросов, которые должен проверить преподаватель

**Comment by YuriSilenok** [comment]
Ветка issue-1346 удалена

**Comment by YuriSilenok** [comment]
Возобновите работу над задачей

**Comment by VinogradovAlexandr781227** [comment]
Понял. Спасибо. Завтра же загружу изменённые файлы, как доберусь до ноутбука.

**Comment by VinogradovAlexandr781227** [comment]
Простите пожалуйста. Проблема с ноутбуком, я сегодня все залью

**Comment by YuriSilenok** [comment]
Задача с Вас  снята, так как по ней давно не было активности. Активность по основной задаче #1346 составляет 26 дней. Активность в ветке issue-1346 составляет 25 дней. Активность по запросу #1372 составляет 17 дней. Нет запросов, которые должен проверить преподаватель

**Comment by YuriSilenok** [comment]
Ветка issue-1346 удалена
