### ISSUE TITLE
Методические рекомендации к составлению пользовательской истории

### ISSUE THREAD

**Issue by badsster** [Students-of-the-city-of-Kostroma/Student-timetable#1349]
#1344 
В данной задаче необходимо создать методические рекомендации к составлению пользовательской истории. 
Должны быть реализованы следующие требования:
- требования к заголовку 
- требования к атрибутам 
- указать из каких пунктов должен состоять документ.
- раскрыть критерии приемлемости каждого пункта.
- указать роль документа в жизненном цикле ПО
- указать какие документы должны быть изменены и созданы на основании пользовательской истории.

Информация должна быть размещена в отчёте Docs/Contributers/user_story.md

**Comment by YuriSilenok** [comment]
Clone #1344
