### ISSUE TITLE
Улучшить методические рекомендации для белого ящика

### ISSUE THREAD

**Issue by KoprovDmitry** [Students-of-the-city-of-Kostroma/Student-timetable#1351]
- добавить более подробное описание "Тестовые сценарии" в [Методические рекомендации к использованию метода тестирования "Белый ящик"](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/White-box/README.md)

**Comment by KoprovDmitry** [comment]
https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/White-box/README.md
добавить в инструкцию "что делать с отчётом после его заполнения"

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче(запросу)

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче(запросу)

**Comment by YuriSilenok** [comment]
Пожалуйста, заполните описание

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки

**Comment by YuriSilenok** [comment]
Пожалуйста, заполните описание

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки

**Comment by YuriSilenok** [comment]
Пожалуйста, заполните описание

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки

**Comment by YuriSilenok** [comment]
Пожалуйста, заполните описание

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки

**Comment by YuriSilenok** [comment]
> https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/White-box/README.md
> добавить в инструкцию "что делать с отчётом после его заполнения"

Поднял задачу #1352

**Comment by YuriSilenok** [comment]
> > https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/White-box/README.md
> > добавить в инструкцию "что делать с отчётом после его заполнения"
> 
> Поднял задачу #1352

Пожалуйста, ознакомьтесь с коротким документам из запроса #1353. Отвечает ли он на ваш вопрос?

**Comment by KoprovDmitry** [comment]
после ознакомления с короткими документами мне стало все более непонятно

**Comment by YuriSilenok** [comment]
> после ознакомления с короткими документами мне стало все более непонятно

Задавайте вопросы

**Comment by KoprovDmitry** [comment]
Когда знакомился с документами, то мне показалось что я хожу по кругу между тремя задачами и в итоге не смог уловить суть как других задач ( #1352 и #1353  ), так и этой.

Единственное что понял, наверное не правильно, в этой задаче ( #1351 ) в описании предоставляется выбор/описание для добавления изменений в существующую инструкцию, а всё, что вне описания это разбор какие изменения стоит добавлять в инструкцию, а какие не стоит.

**Comment by YuriSilenok** [comment]
- описание/тело текущей задачи вы так и не заполнили, но думаю опять же для этого Вам, как человеку не посвящённого, термин непонятен.
- я так и не увидел конкретного вопроса. Что вы не можете сделать?

**Comment by KoprovDmitry** [comment]
могу я сначала взять некоторое время для ознакомления с работой github?

**Comment by YuriSilenok** [comment]
Да, конечно, двое суток вам на это хватит?

**Comment by KoprovDmitry** [comment]
хватит, если можете дать мне ссылку где я могу ознакомиться с github, если я начну искать сам нужное, то это займёт больше времени

**Comment by YuriSilenok** [comment]
Вам нужно
- для git c командами:
  - git clone
  - git status
  - git add
  - git commit
  - git pull
  - git push
  - git branch
  - git checkout

Все эти команды описаны на [официальном сайте](https://git-scm.com/book/ru/v2/%D0%92%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5-%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D1%8B-Git)

- для github с понятиями
  - issue
  - pull request
  - label
  - milestone
  - project

Есть введение на [официальном сайте](https://github.com/deepmipt/dlschl/wiki/%D0%98%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%86%D0%B8%D1%8F-%D0%BF%D0%BE-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B5-%D1%81-Git)

**Comment by KoprovDmitry** [comment]
возможно я  не так выразился, но я не знаю как пользоваться сайтом github, но самой git я могу пользоваться на базовом уровне

**Comment by YuriSilenok** [comment]
Я не могу устроить Вам индивидуальное занятие по изучению ресурса github. 
Воспринимайте его как обычный таск-менеджер (если с таковыми работали). 
Вы входите в состав команды и общие вопросы, относящиеся к github, git и жизненным циклом проекта, Вы можете интересоваться в чате. Коллеги Вам ответят и Вы со временем сможете помочь коллегам.
