### ISSUE TITLE
Реструктуризация проекта UnitTestOfTimetableOfClasse

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#1354]
Привести структуру проекта в соответствие с документами [White-box](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/White-box/README.md) и [Unit-test](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Unit-test/README.md)

**Comment by YuriSilenok** [comment]
У одной задачи может быть только один ответсвенный

**Comment by YuriSilenok** [comment]
Задача с Вас  снята, так как по ней давно не было активности. Активность по основной задаче #1354 составляет 21 дней. Активность в ветке issue-1354 составляет 2 дней. Запрос отсутствует. Нет запросов, которые должен проверить преподаватель

**Comment by YuriSilenok** [comment]
Задача с Вас  снята, так как по ней давно не было активности. Активность по основной задаче #1354 составляет 4 дней. Активность в ветке issue-1354 составляет 5 дней. Активность по запросу #1371 составляет 2 дней. Нет запросов, которые должен проверить преподаватель

**Comment by YuriSilenok** [comment]
Задача с Вас  снята, так как по ней давно не было активности. Активность по основной задаче #1354 составляет 19 дней. Активность в ветке issue-1354 составляет 21 дней. Активность по запросу #1371 составляет 10 дней. Нет запросов, которые должен проверить преподаватель

**Comment by NesgovorovVS** [comment]
https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1377#issuecomment-738037801
