### ISSUE TITLE
Создать форму Институты

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#137]
Реализовано в ветку task-137
Вызывается из стартовой формы в верхнем меню пунктом Справочники-Институты подготовки
Имя формы Institutes
Графический интерфейс:

- Заголовок формы Институты
- Таблица привязанная ко всем сторонам формы. И имеет отступ 3px от кнопок снизу.
- Кнопка Добавить имеет стандартные размеры и привязку к правому и нижнему краю формы. Отступ со всех сторон 3px. Расположена в правом нижнем углу формы.
- Кнопка Удалить имеет стандартные размеры и привязана к правому и нижнему краю формы. Отступ со всех сторон 3px. Расположена внизу формы, левее кнопки Добавить с отступом в 3px.

**Comment by Takunava** [comment]
Форма была создана и функционал реализован в ветке Alliance-5
