### ISSUE TITLE
Исправить замечания предъявляемые к проверке кода для запроса #1371

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#1373]
Привести код в соответствие с [требованиями](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) в запросе #1371 .

**Comment by NesgovorovVS** [comment]
https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1367#issuecomment-723635061

**Comment by NesgovorovVS** [comment]
> [#1367 (comment)](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1367#issuecomment-723635061)

https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1367#issuecomment-726659794

**Comment by NesgovorovVS** [comment]
Завтра займусь этой задачей.

**Comment by NesgovorovVS** [comment]
https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1377#issuecomment-738037801
