### ISSUE TITLE
Уточнить структуру для модульных тестов моделей

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#1374]
Проблема возникла в [этом](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1371#issuecomment-720076729) комментарии. 
Необходимо определить шаблоны имен для тестовый методов, классов, пространства имен. определить имена файлов и расположения этих файлов в проекте модульных тестов и папках

**Comment by NesgovorovVS** [comment]
@YuriSilenok готов взять эту задачу, если вы её переоткроете и завершил бы полностью лабы с реструктуризацией т.е 1354 и 1373, этими тремя лабами закрыл бы все долги.

**Comment by YuriSilenok** [comment]
Думаю эта задача имеет решение вот в [этом](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Unit-test/README.md) документе. Проверьте, так ли это?

**Comment by NesgovorovVS** [comment]
> Думаю эта задача имеет решение вот в [этом](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Unit-test/README.md) документе. Проверьте, так ли это?

Нет, не имеет, поэтому эта задача и была создана.

**Comment by YuriSilenok** [comment]
Да, я не сразу вспомнил зачем эта задача была создана, в документации, которую я привел выше, описывались названия относительно контроллера и его методом, а относительно модели нет описания.
