### ISSUE TITLE
Реализовать конструктор CGroup() : base("Группа") для класса CGroup унаследованного от класса Controller

### ISSUE THREAD

**Issue by Takunava** [Students-of-the-city-of-Kostroma/Student-timetable#14]
Реализовать в ветку task-14
Поведение:
Инициализирует заголовок таблицы и ограничения уникальности столбцов.
Для группы уникальными являются комбинация двух полей (составной ключ)
 ```
       byte population;
        string cipher;
``` 
Примером может служить конструктор  **CDiscipline() : base("Дисциплина")**
[Ссылка](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit) на диаграмму классов.

**Comment by Takunava** [comment]
``

**Comment by YuriSilenok** [comment]
Добрый день,
Что у вас происходит с задачей?
Она не должна быть закрытой.

**Comment by Takunava** [comment]
Здравствуйте.
Я не смог добавить метки, поэтому закрыл.
Метки добавить не получалось

**Comment by YuriSilenok** [comment]
Добрый день.
Зачем была добавлена метка Insert(Model model)?

**Comment by YuriSilenok** [comment]
Добрый день.
Я не просил удалять эту метку, я спросил зачем она была добавлена?
Могли бы Вы пояснить зачем были добавлены остальные метки?
Спасибо.

**Comment by Takunava** [comment]
Здравствуйте.
Controller, потому что это задача на разработку конструктора
Group, потому что задача относится к сущности Group 
Insert(Model model), потому что данная метка ставится вместе с меткой Controller
new(), потому что это задача на разработку конструктора 
Story, потому что это задача на разработку функциональности

**Comment by YuriSilenok** [comment]
Здравствуйте.
Могли бы Вы уточнить где была взята эта формулировка или на основании какого описания Вы сделали такой вывод?

> Insert(Model model), потому что данная метка ставится вместе с меткой Controller

Спасибо.

**Comment by Takunava** [comment]
Здравствуйте.
![image](https://user-images.githubusercontent.com/47320250/52426460-15196380-2b0f-11e9-930a-a1a6e6e14d5a.png)
Вот тут написано что её надо использовать вместе с меткой Controller.

**Comment by Takunava** [comment]
Но похоже я что-то не так понял

**Comment by YuriSilenok** [comment]
Описание получилось двусмысленным. Имелось ввиду что если вы ставите эту метку Insert, то нужно поставить метку контроллер. 
Ниже цитата из задания, доработанная пару дней назад. Рекомендую прочитать добавленный раздел "Типы задач". Он даст большее понимание назначения меток и когда их ставить.
> Если задача имеет цель разработки конструктор, методов Insert, Update или Delete , то задача должна быть помечена меткой Controller.

**Comment by Takunava** [comment]
Здравствуйте.
Я так понимаю что метка Insert(Model model) не нужна, да?

**Comment by Takunava** [comment]
А метка контроллер нужна, потому что задача имеет цель разработки конструктора

**Comment by YuriSilenok** [comment]
Здравствуйте @Takunava .
Если Вы закончили работать с задачей, то вы должны с себя ее снять и назначить тому, кто должен с ней работать дальше, если таковой есть.
Спасибо.

**Comment by YuriSilenok** [comment]
**Поле Assignees**
В этом поле указывается человек (или общая учетная запись команды) который в данный должен заниматься этой задачей. Задача может назначаться другому человеку, при этом с себя задачу нужно снять, так как Вы ее передаете для решения какого-либо вопроса. Задача не должна находиться без исполнителя. Случаи когда задача может передаться другому пользователю:
- Для проверки выполнения этой задачи
- Для уточнение информации по этой задаче
- В случае если Вы не можете выполнять задачу (увольнение, длительная болезнь и т.д.)

**Comment by YuriSilenok** [comment]
Зачтено

**Comment by YuriSilenok** [comment]
Здравствуйте @netever 
Эта Ваша новая задача.
Спасибо.

**Comment by YuriSilenok** [comment]
@netever зачтено
