### ISSUE TITLE
Программа крашиться(вылетает), если удалить дисциплину в пустой таблице "дисциплина"

### ISSUE THREAD

**Issue by Whitetech7417** [Students-of-the-city-of-Kostroma/Student-timetable#142]
**Шаги для реализации бага:** 

1. Перейти по меню Справочники-Дисциплины
2. Нажать на кнопку Удалить.

**Ожидаемый результат:** Изменений нет.
**Фактический результат:** Программа вылетает, и выдает ошибку(исключение). Метод в котором вылетает ошибка private void Delete_Click(object sender, EventArgs e)

**Comment by YuriSilenok** [comment]
Здравствуйте @Whitetech7417 
Повысил привилегии для вашей команды.
Теперь у вас есть возможность управлять метаданными задачи.
Спасибо.

**Comment by YuriSilenok** [comment]
Здравствуйте @Whitetech7417 .
Используйте форматирование в описании бага
Спасибо.

**Comment by Whitetech7417** [comment]
@YuriSilenok готово. 
Спасибо.

**Comment by YuriSilenok** [comment]
@Whitetech7417 зачтено

**Comment by YuriSilenok** [comment]
@ssas18 в какой ветке и с каким результатом был воспроизведен или не воспроизведен баг?

**Comment by YuriSilenok** [comment]
@Баг не воспроизводится в [v0.12-Testing]( https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/releases/tag/v0.12-Testing)
