### ISSUE TITLE
Невозможно удалить несколько учителей

### ISSUE THREAD

**Issue by Whitetech7417** [Students-of-the-city-of-Kostroma/Student-timetable#143]
**Шаги для реализации бага:**

1. Перейти по меню Справочники-Преподаватели
2. Выбрать несколькиx преподавателей нажать кнопку "Удалить"

**Ожидаемый результат:** удаление несколькиx учителей.
**Фактический результат:** Удаляет одного учителя.
Я так понимаю там реализован функционал удаления последнего. Это неверно. нужно удалять выбранного, а не последнего из списка.

**Comment by YuriSilenok** [comment]
Здравствуйте @Whitetech7417 .
Используйте форматирование в описании бага
Спасибо.

**Comment by Whitetech7417** [comment]
@YuriSilenok готово.

**Comment by YuriSilenok** [comment]
@Whitetech7417 Зачтено

**Comment by GubanovAndrey** [comment]
@YuriSilenok Здравствуйте.

 Давно сделал работу , возможно вы ее не видели , потому что ее закрыл другой человек.  Что мне делать?

Спасибо.

**Comment by YuriSilenok** [comment]
Скорее всего видел и ваша задача не в приоритете. Если кто-то закрыл
ошибочно или без комментария, откройте её снова. Там будет кнопка reopen.

вт, 2 апр. 2019 г., 20:34 Губанов Андрей <notifications@github.com>:

**Comment by YuriSilenok** [comment]
На будущее, если у Вас вопрос по пулреквесту, там и пишите вопросы.

**Comment by GubanovAndrey** [comment]
@YuriSilenok Здравствуйте.

Давно выполнил задачу. К сожалению вы ее не проверили, сначала из-за того что задача была по ошибке закрыта другим студентом. После из-за того, что не вовремя заменил пробелы на табы. После спринта нерабочий кусок кода уже не актуален. Что мне делать? Работа будет зачтена?

Спасибо.

**Comment by YuriSilenok** [comment]
Зачтено
