### ISSUE TITLE
Некорректное отображение таблицы при открытии

### ISSUE THREAD

**Issue by Whitetech7417** [Students-of-the-city-of-Kostroma/Student-timetable#144]
**Шаги для реализации бага:**
Перейти по меню Справочники-Группы

**Ожидаемый результат:** 
Столбец численность отображается
на скриншоте видно, что столбца "численность" между ID и Шифр не видно
![image](https://user-images.githubusercontent.com/38256956/53980965-b6053980-4122-11e9-8f80-95b575f042f7.png)

**Фактический результат:** 
Не отображается корректно Столбец "численность"
На скриншоте пример корректного отображения
![image](https://user-images.githubusercontent.com/38256956/53980996-c87f7300-4122-11e9-9d3a-256b02fe870a.png)

**Comment by YuriSilenok** [comment]
Здравствуйте @Whitetech7417 
Что значит корректно?
> Не отображается корректно численность.

Спасибо.

**Comment by Whitetech7417** [comment]
> Здравствуйте @Whitetech7417
> Что значит корректно?
> 
> > Не отображается корректно численность.
> 
> Спасибо.

Добрый день @YuriSilenok 
Я так понимаю, что при открытии формы, верстка windows form должна верстаться так чтобы видны были сразу все столбцы. Я не уверен что я логически правильно мыслю. 
Но к сожалению баги как то сложно искать когда функциональности не так много, поэтому цепляюсь за каждую мелочь. 
Спасибо

**Comment by YuriSilenok** [comment]
Теперь увидел.
При уменьшении ширины формы, столбце "Численность" перестает отображаться.
Это нормальный баг.
Вы молодец.
Но результат не может быть просто картинкой. Картинка это способ облегчить преставления того что написано. Это значит, что что-то должно быть написано.
Пожалуйста, исправьте описание бага.
Учтите что читающий не держит в голове что "Численность" это заголовок столбца.

**Comment by YuriSilenok** [comment]
Здравствуйте @Pipyao 
Это  Ваша задача к ЛР03.
Спасибо.

**Comment by Whitetech7417** [comment]
@YuriSilenok  
Обновил описание,
Спасибо за понимание.

**Comment by YuriSilenok** [comment]
Здравствуйте @Whitetech7417 .
Используйте форматирование в описании бага
Спасибо.

**Comment by Whitetech7417** [comment]
@YuriSilenok готово.

**Comment by YuriSilenok** [comment]
@Whitetech7417 Зачтено

**Comment by map82top** [comment]
В ветке 17-ISbo-2b-6 баг не воспроизводится
