### ISSUE TITLE
A closing curly bracket must not be preceded by a blank line

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#1445]
[CodeFactor](https://www.codefactor.io/repository/github/students-of-the-city-of-kostroma/student-timetable) found multiple issues last seen at 2e0647fe5852987d3bea7c00e4d54b2764699793:

#### A closing curly bracket must not be preceded by a blank line.
- [x]  [UnitTestOfTimetableOfClasses\UT_CGroup\UT_Update\UnitTest.cs:72](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CGroup/UT_Update/UnitTest.cs#L72)
- [x]  [UnitTestOfTimetableOfClasses\UT_CGroup\UT_Update\UnitTest.cs:185](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CGroup/UT_Update/UnitTest.cs#L185)
- [x]  [UnitTestOfTimetableOfClasses\UT_CGroup\UT_Update\UnitTest.cs:110](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CGroup/UT_Update/UnitTest.cs#L110)
- [x]  [UnitTestOfTimetableOfClasses\UT_CGroup\UT_Update\UnitTest.cs:147](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CGroup/UT_Update/UnitTest.cs#L147)
- [x]  [UnitTestOfTimetableOfClasses\UT_CGroup\UT_Update\UnitTest.cs:225](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CGroup/UT_Update/UnitTest.cs#L225)
- [x]  [UnitTestOfTimetableOfClasses\UT_CGroup\UT_Update\UnitTest.cs:256](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CGroup/UT_Update/UnitTest.cs#L256)
- [ ]  [UnitTestOfTimetableOfClasses\UT_CUniversity\UT_Update\UnitTest.cs:68](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CUniversity/UT_Update/UnitTest.cs#L68)
- [x]  [UnitTestOfTimetableOfClasses\UT_CAcademicLoad\UT_Update\UnitTest.cs:47](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CAcademicLoad/UT_Update/UnitTest.cs#L47)
- [x]  [UnitTestOfTimetableOfClasses\UT_CAcademicLoad\UT_Update\UnitTest.cs:151](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CAcademicLoad/UT_Update/UnitTest.cs#L151)
- [x]  [UnitTestOfTimetableOfClasses\UT_CTeacher\UT_Update\UnitTest.cs:46](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CTeacher/UT_Update/UnitTest.cs#L46)
- [x]  [UnitTestOfTimetableOfClasses\UT_CTeacher\UT_Update\UnitTest.cs:67](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CTeacher/UT_Update/UnitTest.cs#L67)
- [ ]  [UnitTestOfTimetableOfClasses\UT_CTeacher\UT_Update\UnitTest.cs:96](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CTeacher/UT_Update/UnitTest.cs#L96)
- [x]  [UnitTestOfTimetableOfClasses\UT_CInstitute\UT_Update\UnitTest.cs:56](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CInstitute/UT_Update/UnitTest.cs#L56)
- [ ]  [UnitTestOfTimetableOfClasses\UT_CInstitute\UT_Update\UnitTest.cs:73](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CInstitute/UT_Update/UnitTest.cs#L73)
- [x]  [UnitTestOfTimetableOfClasses\UT_CInstitute\UT_Update\UnitTest.cs:23](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CInstitute/UT_Update/UnitTest.cs#L23)
- [x]  [UnitTestOfTimetableOfClasses\UT_CInstitute\UT_Update\UnitTest.cs:89](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CInstitute/UT_Update/UnitTest.cs#L89)
- [ ]  [UnitTestOfTimetableOfClasses\UT_CInstitute\UT_Update\UnitTest.cs:40](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CInstitute/UT_Update/UnitTest.cs#L40)
- [x]  [UnitTestOfTimetableOfClasses\UT_CAcademicDegree\UT_Update\UnitTest.cs:48](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CAcademicDegree/UT_Update/UnitTest.cs#L48)
- [x]  [UnitTestOfTimetableOfClasses\UT_CAcademicDegree\UT_Update\UnitTest.cs:68](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CAcademicDegree/UT_Update/UnitTest.cs#L68)
- [ ]  [UnitTestOfTimetableOfClasses\UT_CTitle\UT_Update\UnitTest.cs:24](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CTitle/UT_Update/UnitTest.cs#L24)

_Originally posted by @codefactor-io[bot] in https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/1444#issuecomment-848762227_

**Comment by DdarryyA** [comment]
Сысуева Дарья

**Comment by anita111art** [comment]
взяла задачу
