### ISSUE TITLE
The code must not contain multiple blank lines in a row

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#1446]
[CodeFactor](https://www.codefactor.io/repository/github/students-of-the-city-of-kostroma/student-timetable) found multiple issues last seen at 2e0647fe5852987d3bea7c00e4d54b2764699793:

#### The code must not contain multiple blank lines in a row.
- [x]  [UnitTestOfTimetableOfClasses\UT_CGroup\UT_Update\UnitTest.cs:112](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CGroup/UT_Update/UnitTest.cs#L112)
- [x]  [UnitTestOfTimetableOfClasses\UT_CGroup\UT_Update\UnitTest.cs:74](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CGroup/UT_Update/UnitTest.cs#L74)
- [x]  [UnitTestOfTimetableOfClasses\UT_CGroup\UT_Update\UnitTest.cs:224](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CGroup/UT_Update/UnitTest.cs#L224)
- [x]  [UnitTestOfTimetableOfClasses\UT_CGroup\UT_Update\UnitTest.cs:183](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CGroup/UT_Update/UnitTest.cs#L183)
- [x]  [UnitTestOfTimetableOfClasses\UT_CGroup\UT_Update\UnitTest.cs:223](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CGroup/UT_Update/UnitTest.cs#L223)
- [x]  [UnitTestOfTimetableOfClasses\UT_CGroup\UT_Update\UnitTest.cs:4](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CGroup/UT_Update/UnitTest.cs#L4)
- [x]  [UnitTestOfTimetableOfClasses\UT_CGroup\UT_Update\UnitTest.cs:184](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CGroup/UT_Update/UnitTest.cs#L184)
- [x]  [UnitTestOfTimetableOfClasses\UT_CGroup\UT_Update\UnitTest.cs:255](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CGroup/UT_Update/UnitTest.cs#L255)
- [x]  [UnitTestOfTimetableOfClasses\UT_CGroup\UT_Update\UnitTest.cs:68](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CGroup/UT_Update/UnitTest.cs#L68)
- [x]  [UnitTestOfTimetableOfClasses\UT_CUniversity\UT_Update\UnitTest.cs:180](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CUniversity/UT_Update/UnitTest.cs#L180)
- [x]  [UnitTestOfTimetableOfClasses\UT_CUniversity\UT_Update\UnitTest.cs:210](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CUniversity/UT_Update/UnitTest.cs#L210)
- [x]  [UnitTestOfTimetableOfClasses\UT_CUniversity\UT_Update\UnitTest.cs:4](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CUniversity/UT_Update/UnitTest.cs#L4)
- [x]  [UnitTestOfTimetableOfClasses\UT_CEnclosurse\UT_Update\UnitTest.cs:4](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CEnclosurse/UT_Update/UnitTest.cs#L4)
- [x]  [UnitTestOfTimetableOfClasses\UT_CTeacher\UT_Update\UnitTest.cs:45](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CTeacher/UT_Update/UnitTest.cs#L45)
- [x]  [UnitTestOfTimetableOfClasses\UT_CTeacher\UT_Update\UnitTest.cs:66](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CTeacher/UT_Update/UnitTest.cs#L66)
- [x]  [UnitTestOfTimetableOfClasses\UT_CTeacher\UT_Update\UnitTest.cs:4](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CTeacher/UT_Update/UnitTest.cs#L4)
- [x]  [UnitTestOfTimetableOfClasses\UT_CTeacher\UT_Update\UnitTest.cs:44](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CTeacher/UT_Update/UnitTest.cs#L44)
- [x]  [UnitTestOfTimetableOfClasses\UT_CTeacher\UT_Update\UnitTest.cs:98](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CTeacher/UT_Update/UnitTest.cs#L98)
- [x]  [UnitTestOfTimetableOfClasses\UT_CInstitute\UT_Update\UnitTest.cs:81](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CInstitute/UT_Update/UnitTest.cs#L81)
- [x]  [UnitTestOfTimetableOfClasses\UT_CInstitute\UT_Update\UnitTest.cs:34](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CInstitute/UT_Update/UnitTest.cs#L34)
- [x]  [UnitTestOfTimetableOfClasses\UT_CInstitute\UT_Update\UnitTest.cs:48](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CInstitute/UT_Update/UnitTest.cs#L48)
- [x]  [UnitTestOfTimetableOfClasses\UT_CInstitute\UT_Update\UnitTest.cs:58](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CInstitute/UT_Update/UnitTest.cs#L58)
- [x]  [UnitTestOfTimetableOfClasses\UT_CInstitute\UT_Update\UnitTest.cs:65](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CInstitute/UT_Update/UnitTest.cs#L65)
- [x]  [UnitTestOfTimetableOfClasses\UT_CInstitute\UT_Update\UnitTest.cs:31](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CInstitute/UT_Update/UnitTest.cs#L31)

_Originally posted by @codefactor-io[bot] in https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/1444#issuecomment-848762227_

**Comment by SeaBreaze** [comment]
Иванюк

**Comment by Daria-Vinogradova** [comment]
Виноградова
