### ISSUE TITLE
An opening curly bracket must not be followed by a blank line

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#1447]
[CodeFactor](https://www.codefactor.io/repository/github/students-of-the-city-of-kostroma/student-timetable) found multiple issues last seen at 2e0647fe5852987d3bea7c00e4d54b2764699793:

#### An opening curly bracket must not be followed by a blank line.
- [x]  [UnitTestOfTimetableOfClasses\UT_CInstitute\UT_Update\UnitTest.cs:44](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CInstitute/UT_Update/UnitTest.cs#L44)
- [x]  [UnitTestOfTimetableOfClasses\UT_CInstitute\UT_Update\UnitTest.cs:12](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CInstitute/UT_Update/UnitTest.cs#L12)
- [x]  [UnitTestOfTimetableOfClasses\UT_CInstitute\UT_Update\UnitTest.cs:27](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CInstitute/UT_Update/UnitTest.cs#L27)
- [x]  [UnitTestOfTimetableOfClasses\UT_CInstitute\UT_Update\UnitTest.cs:61](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CInstitute/UT_Update/UnitTest.cs#L61)
- [x]  [UnitTestOfTimetableOfClasses\UT_CInstitute\UT_Update\UnitTest.cs:77](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CInstitute/UT_Update/UnitTest.cs#L77)
- [x]  [UnitTestOfTimetableOfClasses\UT_CTitle\UT_Update\UnitTest.cs:12](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/2e0647fe5852987d3bea7c00e4d54b2764699793/UnitTestOfTimetableOfClasses/UT_CTitle/UT_Update/UnitTest.cs#L12)

_Originally posted by @codefactor-io[bot] in https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/1444#issuecomment-848762227_

**Comment by AMAT0RY** [comment]
Татаринов
