### ISSUE TITLE
Рефакторинг файлов с тестами для моделей

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#1448]
[CodeFactor](https://www.codefactor.io/repository/github/students-of-the-city-of-kostroma/student-timetable) found multiple issues last seen at 76926157959a9092267e34141d539392eb0b1596:

#### The code must not contain multiple blank lines in a row.
- [x]  [UnitTestOfTimetableOfClasses\MGroup\UnitTest.cs:5](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/76926157959a9092267e34141d539392eb0b1596/UnitTestOfTimetableOfClasses/MGroup/UnitTest.cs#L5)
- [x]  [UnitTestOfTimetableOfClasses\MUniversity\UnitTest.cs:142](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/76926157959a9092267e34141d539392eb0b1596/UnitTestOfTimetableOfClasses/MUniversity/UnitTest.cs#L142)
- [x]  [UnitTestOfTimetableOfClasses\MAcademicDegree\UnitTest.cs:30](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/76926157959a9092267e34141d539392eb0b1596/UnitTestOfTimetableOfClasses/MAcademicDegree/UnitTest.cs#L30)
- [x]  [UnitTestOfTimetableOfClasses\MAcademicDegree\UnitTest.cs:5](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/76926157959a9092267e34141d539392eb0b1596/UnitTestOfTimetableOfClasses/MAcademicDegree/UnitTest.cs#L5)
- [x]  [UnitTestOfTimetableOfClasses\MTitle\UnitTest.cs:5](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/76926157959a9092267e34141d539392eb0b1596/UnitTestOfTimetableOfClasses/MTitle/UnitTest.cs#L5)

#### The code must not contain blank lines at the end of the file.
- [x]  [UnitTestOfTimetableOfClasses\MUniversity\UnitTest.cs:142](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/76926157959a9092267e34141d539392eb0b1596/UnitTestOfTimetableOfClasses/MUniversity/UnitTest.cs#L142)

#### An opening curly bracket must not be followed by a blank line.
- [x]  [UnitTestOfTimetableOfClasses\MAuditor\UnitTest.cs:6](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/76926157959a9092267e34141d539392eb0b1596/UnitTestOfTimetableOfClasses/MAuditor/UnitTest.cs#L6)
- [x]  [UnitTestOfTimetableOfClasses\MAcademicDegree\UnitTest.cs:10](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/76926157959a9092267e34141d539392eb0b1596/UnitTestOfTimetableOfClasses/MAcademicDegree/UnitTest.cs#L10)

_Originally posted by @codefactor-io[bot] in https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/1441#issuecomment-848771107_

**Comment by Gelikan44** [comment]
Копанцев
