### ISSUE TITLE
Некорректная обработка "Добавить преподавателя"

### ISSUE THREAD

**Issue by Whitetech7417** [Students-of-the-city-of-Kostroma/Student-timetable#145]
**Шаги для реализации бага:**

В верхнем меню выбрать Справочники-Преподаватели

1. Нажать кнопку "Добавить"
2. Открыть текстовый редактор и напечатать в нем имя в середине которого будет пробел
3. Скопировать из текстового редактора имя с пробелом и вставить его в поле "Имя" формы "Добавить преподавателя" (ПКМ по полю, затем "Вставить")
4. Нажать кнопку "Создать и закрыть"

**Ожидаемый результат:** Отобразится модальное сообщение о некорректном имени преподавателя.
**Фактический результат:** Форма "Добавить преподавателя" закрывается, в таблице на форме "Преподаватели" отображается новая строка с введенными данными, где пробел заменяется на дефис "-" и вторая "половина" имени, стоявшая после пробела, пишется с заглавной буквы.

**Название ветки:** task-145

**Comment by YuriSilenok** [comment]
Для воспроизведения.
> Шаги для реализации бага:

Общее замечание для всех багов, используйте нумерованный список, а слова ожидаемый результат и фактический результат нужно выделять жирным.

Покажу здесь для образца.

**Steps:**
1. В верхнем меню выбрать Справочники-Преподаватели
2. Нажать кнопку "Добавить"
3. Открыть текстовый редактор и напечатать в нем имя в середине которого будет пробел
4. Скопировать из текстового редактора имя с пробелом и вставить его в поле "Имя" формы "Добавить преподавателя"
5. Нажать кнопку "Создать и закрыть"

**Ожидаемый результат**: Отобразится модальное сообщение о некорректном имени преподавателя.
**Фактический результат**: Форма "Добавить преподавателя" закрывается, в таблице на форме "Преподаватели" отображается новая строка введенными данными в форме "Добавить преподавателя"

**Comment by Whitetech7417** [comment]
@YuriSilenok ошибку понял, По багу нет вопросов?

**Comment by YuriSilenok** [comment]
Здравствуйте @Whitetech7417 .
Используйте форматирование в описании бага
Я ожидаю что Вы внесете изменение в описание бага.
Кнопка Edit
![image](https://user-images.githubusercontent.com/14871471/54308170-7afd7d00-45de-11e9-86f5-33658b3fd260.png)

Спасибо.

**Comment by Whitetech7417** [comment]
@YuriSilenok готово.

**Comment by YuriSilenok** [comment]
@Whitetech7417 Зачтено

**Comment by YuriSilenok** [comment]
@stasshtaub Ваша новая задача

**Comment by stasshtaub** [comment]
@YuriSilenok Когда я пытаюсь запустить программу для воспроизведения бага из созданной ветки (task-145), VS выдает ошибку: **"Два имени выходных файлов разрешаются в один и тот же выходной путь: "obj\Debug\TimetableOfClasses.AddTeacher.resources"**

**Comment by YuriSilenok** [comment]
Вам нужно выполнить команду rebase.
Она позволит переместить начало вашей ветки к последнему коммиту ветки Testing.
Это произошло из-за попадания в ветку Tedting некачественного коммита.

**Comment by stasshtaub** [comment]
Здравствуйте.

Вы отправили мне две задачи: 145 и 152. Какую из них мне брать?

ср, 20 мар. 2019 г., 22:41 Юрий Силенок <notifications@github.com>:

**Comment by YuriSilenok** [comment]
Это произошло потому что Вы написали мне два письма в двух разных цепочках писем.
В каждом из писем я выдал Вам задание.
Разберитесь что такое цепочка писем и выполняйте оба задания.
Если Вы указываете на номера задач, нужно ставить решетки, вот так #145 и #152

**Comment by YuriSilenok** [comment]
Зачтено
