### ISSUE TITLE
Правка Insert

### ISSUE THREAD

**Issue by xShende** [Students-of-the-city-of-Kostroma/Student-timetable#1489]
- Распределить по папкам файлы, связанные с Insert в формате "CAcademicDegree/Insert/UnitTest.cs"
- Изменить namespace в формате "UnitTestOfTimetableOfClasses.UT_CAuditor.UT_Insert"
- Изменить названия методов с Task по формату "UT_ICAuditor".

**Comment by xShende** [comment]
Взята мной.

**Comment by YuriSilenok** [comment]
была допущена опечатка
