### ISSUE TITLE
Второй экземпляр формы "Справочники" крашит программу 

### ISSUE THREAD

**Issue by Whitetech7417** [Students-of-the-city-of-Kostroma/Student-timetable#151]
Баг затрагивает issue #109

**Шаги для реализации бага:**

1. Перейти по меню "Справочники-Справочники"
2. Открыть еще один раз "Справочники-Справочники".
3. Во второй форме кликнуть на столбец "numbers"

**Ожидаемый результат:** Ничего не происходит
**Фактический результат:** 
При попытке работы с второй формой вылетает ошибка (исключение)
![image](https://user-images.githubusercontent.com/38256956/54073581-284c5a00-429a-11e9-8d47-6cd9eca44683.png)

**Comment by YuriSilenok** [comment]
Баг не воспроизвелся, могли Вы проверить его воспроизведение у себя на компьютере.
Если баг воспроизведется, сообщите версию ОС и VS.

**Comment by Whitetech7417** [comment]
@YuriSilenok  Я немного не так описал баг. При открытии второй формы, попробуйте в ней покликать на поля и в частности на поле "nubmers"

**Comment by YuriSilenok** [comment]
Не воспроизводится.
При клике на столбец "number", произошла сортировка в обоих окнах.
![image](https://user-images.githubusercontent.com/14871471/54636334-49c9f480-4a97-11e9-8487-014ff34cfde5.png)

**Comment by YuriSilenok** [comment]
зачтено, все равно балл поставлю

**Comment by YuriSilenok** [comment]
@Whitetech7417 
Почему вы решили закрыть баГ?

**Comment by YuriSilenok** [comment]
Баг закрыт, так как Справочники-Справочники удалены из программы

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой
