### ISSUE TITLE
"Дисциплины", при добавлении  дисциплины кнопка "удалить" не активна

### ISSUE THREAD

**Issue by Whitetech7417** [Students-of-the-city-of-Kostroma/Student-timetable#152]
Когда заxодишь в "дисциплины" кнопка "удалить" активна. При добавлнии преподавателя она становиться не активной.  
Предполагаема ошибка в условии класса Discipline.cs 
private void DG_Disc_SelectionChanged(object sender, EventArgs e)

**Шаги для реализации бага:**

1. Перейти по меню Справочники-Дисциплины
2. Создать Дисциплину

**Ожидаемый результат:** Кнопка "Удалить" активна 
**Фактический результат:** Кнопка "Удалить" стала не активной.

**Название ветки:**  task-152

**Comment by YuriSilenok** [comment]
Зачтено

**Comment by bormolei** [comment]
Исправлено, работает корректно.

**Comment by YuriSilenok** [comment]
> При добавлнии преподавателя она становиться не активной.

Причем тут преподаватель?

> Исправлено, работает корректно.

Видимо баг не воспроизвелся, в какой версии?

**Comment by bormolei** [comment]
Баг не воспроизвелся в ветке 17-ISbo-2a-5
