### ISSUE TITLE
[Дисциплина] При удалении нескольких строк, удаляется только одна

### ISSUE THREAD

**Issue by Whitetech7417** [Students-of-the-city-of-Kostroma/Student-timetable#153]
**Шаги для реализации бага:**

1. Перейти по меню Справочники-Дисциплины
2. Создать несколько Дисциплин
3. Выбираем несколько дисциплин для удаления

**Ожидаемый результат:** Удаляет выбранные дисциплины
**Фактический результат:** Удаляет самую первую в списке выборки дисциплину.

**Comment by YuriSilenok** [comment]
@ssas18 в какой ветке и с каким результатом был воспроизведен или не воспроизведен баг?

**Comment by ssas18** [comment]
Баг не воспроизводится в текущей ветке
