### ISSUE TITLE
Duplication issues in multiple files

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#1557]
[CodeFactor](https://www.codefactor.io/repository/github/students-of-the-city-of-kostroma/student-timetable) found an issue: Duplicate Code

It's currently on:
[TimetableOfClasses\AddTeacher.cs:141-151](https://www.codefactor.io/repository/github/students-of-the-city-of-kostroma/student-timetable/source/dev/TimetableOfClasses/AddTeacher.cs#L141)
[TimetableOfClasses\AddAcademicDegree.cs:119-130](https://www.codefactor.io/repository/github/students-of-the-city-of-kostroma/student-timetable/source/dev/TimetableOfClasses/AddAcademicDegree.cs#L119)
Commit 99e9dc4debfaf483d2128aa0ee83ebb6a154ed73

**Comment by RomaSkrund** [comment]
хочу взять

**Comment by RomaSkrund** [comment]
Здравствуйте, столкнулся с такой проблемой, при скачивании проекта из ветки dev, при открытии форм AddTeacher и AddAcademicDegree возникают такие ошибки (фото 1 и фото 2), в то же время при скачивании кода из ветки master такой ошибки нет, можно ли использовать проект скаченный из ветки master или есть способ решить эту проблему?
![2](https://user-images.githubusercontent.com/84276106/144742641-c31fa332-5dba-4efe-9481-630df1926ee7.jpg)
![1](https://user-images.githubusercontent.com/84276106/144742642-00dcd210-0037-4aa0-b69c-c1e046915073.jpg)

**Comment by YuriSilenok** [comment]
Дробый день,

Был способ, спрлсите в общем чате.

Спасибо,
Юрий

вс, 5 дек. 2021 г., 13:23 RomaSkrund ***@***.***>:

**Comment by RomaSkrund** [comment]
К сожалению, в общем чате ответ на свой вопрос не получил, поэтому буду исправлять проект, скаченный из ветки master.

**Comment by YuriSilenok** [comment]
Таким образом вы нарушите модель git flow

**Comment by RomaSkrund** [comment]
Как уже писал в общем чате, формы ветки dew заработали. Прошу прощения за доставленные неудобства.
