### ISSUE TITLE
Duplication issues in multiple files

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#1558]
[CodeFactor](https://www.codefactor.io/repository/github/students-of-the-city-of-kostroma/student-timetable) found an issue: Duplicate Code

It's currently on:
[TimetableOfClasses\Enclosures.cs:25-66](https://www.codefactor.io/repository/github/students-of-the-city-of-kostroma/student-timetable/source/dev/TimetableOfClasses/Enclosures.cs#L25)
[TimetableOfClasses\StudyWeek.cs:63-104](https://www.codefactor.io/repository/github/students-of-the-city-of-kostroma/student-timetable/source/dev/TimetableOfClasses/StudyWeek.cs#L63)
[TimetableOfClasses\Teachers.cs:99-140](https://www.codefactor.io/repository/github/students-of-the-city-of-kostroma/student-timetable/source/dev/TimetableOfClasses/Teachers.cs#L99)
[TimetableOfClasses\University.cs:97-138](https://www.codefactor.io/repository/github/students-of-the-city-of-kostroma/student-timetable/source/dev/TimetableOfClasses/University.cs#L97)
Commit 0417b8a3eb8fbfecbc11fdc4b2f7b978ed9c5c5e

**Comment by SergeySmi** [comment]
Хочу взять
