### ISSUE TITLE
Некорректное отображение столбца в "дисциплины"

### ISSUE THREAD

**Issue by Whitetech7417** [Students-of-the-city-of-Kostroma/Student-timetable#157]
**Шаги для реализации бага:**
Перейти по меню Справочники-Дисциплины

**Ожидаемый результат:**
Столбец "наименование" отображается (его видно изначально при открытии)

![image](https://user-images.githubusercontent.com/38256956/54282787-c64b6780-45ad-11e9-9c3d-9fd0e02f1a6a.png)

**Фактический результат:**

Не отображается корректно Столбец "численность"
На скриншоте заметно, что столбца "численность" между Код и Id не видно.
![image](https://user-images.githubusercontent.com/38256956/54282835-dcf1be80-45ad-11e9-835c-eb0dd0c79f1a.png)

**Comment by YuriSilenok** [comment]
@Whitetech7417 Зачтено

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
