### ISSUE TITLE
Разработать сценарии тестирования пригодных для автоматизации модульными тестами для метода Insert(Model model) сущности Группа

### ISSUE THREAD

**Issue by PopovMilan** [Students-of-the-city-of-Kostroma/Student-timetable#16]
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)
Реализовать сценарии пригодные для Unit-тестирования
[План разработки](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.p)
[Диаграмма классов](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_0)

**Comment by YuriSilenok** [comment]
Добрый день. 
Каким образом к этой задаче относиться метка Teacher?

**Comment by PopovMilan** [comment]
Добрый день.
 Понял, что совершил ошибку добавив лишнюю, не из своего задания, сущность.
Спасибо.

**Comment by YuriSilenok** [comment]
Зачтено

**Comment by ZhezlovaDaria** [comment]
Входные параметры | Позитивные классы | Негативные классы
-- | -- | --
A - Шифр (chipher) | а1∈[0-9]{2}-[А-Я]{2}[а-я]{2}-[0-9]{1}[а-я]{0,1} - _Название группы подходит под шифр._ **Допустим возврат значения true, если другие параметры корректны.** | а2 ∉ [0-9]{2}-[А-Я]{2}[а-я]{2}-[0-9]{1}[а-я]{0,1}  - _Название группы не подходит под шифр._ **Возврат значения false.**
B - Численность (population) | b1∈[0;50] - _Допустимое количество студентов._ **Допустим возврат значения true, если другие параметры корректны.** | b2∈(-∞;0] - _Недопустимое количество студентов._ **Возврат значения false.**
  |   | b3∈[50,+∞) - _Недопустимое количество студентов._ **Возврат значения false.**
  |   | b4∉Z - _Не целое число._ **Возврат значения false.**

Возможные комбинации классов эквивалентности с использованием стратегии Сильный-Нормальный: 
(а1, b1), (a2,b2), (a1,b3), (a2,b4).

[Сценарий issue-16.](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)

**Comment by YuriSilenok** [comment]
Здравствуйте,
так как подход в тестировании будет сменен (в место классов эквивалентности будет тестирование методом белый ящик) то классы эквивалентности не могут быть приняты в качестве ЛР, но если Вас интересует ошибки в том что Вы уже сделали, я могу проверить по Вашему желанию.
Спасибо.

**Comment by ZhezlovaDaria** [comment]
Состояние таблицы контроллера | Шифр chipher∈ [0-9]{2}-[А-Я]{2}[а-я]{2}-[0-9]{1}[а-я]{0,1} | Численность population∈[0;50]
-- | -- | --
Добавление данных в пустую таблицу | task-16-1 | task-16-1
Добавление данных с дублирующими атрибутами | task-16-2 | task-16-3

[Сценарий task-16](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)

**Comment by YuriSilenok** [comment]
Эти сценарии должны быть пригодны для для модульного тестирования. Это налагает ограничение, в Вашем случае (2. Нажать кнопку "Создать и закрыть" ) действия с графическим интерфейсом выполнятся не будут. Вы должны описать какие классы должны быть созданы и какие методы должны быть вызваны.

**Comment by ZhezlovaDaria** [comment]
[Исправлено](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548).

**Comment by YuriSilenok** [comment]
Зачтено
