### ISSUE TITLE
Разработать сценарии тестирования пригодных для автоматизации модульным тестированием метода Insert(Model model) сущности Кафедра

### ISSUE THREAD

**Issue by PopovMilan** [Students-of-the-city-of-Kostroma/Student-timetable#160]
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)
#982 - Описание модели

**Comment by YuriSilenok** [comment]
Задача снята и передана на реализацию @AnastasiaSpihtorenko

**Comment by AnastasiaSpihtorenko** [comment]
| Состояние таблицы контроллера | Сокращенное название | Полное название | Заведующий кафедрой | Институт |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| Таблица не имеет записей | task-160-1 | task-160-1 | task-160-1 | task-160-1 |
| Проверка наличия/отсутствия ограничения уникальности | task-160-2 | task-160-3 | task-160-4 | task-160-5 |

**Comment by YuriSilenok** [comment]
> Сценарии
План разработки
Диаграмма классов

Зачем это тут?

> task-160-1

где шаги и ожидаемый результат?
> task-160-2 - Ввод корректных данных в таблицу при условии, что атрибуты не дублируются

кажется это конфликтует c таблицей 1.

Спасибо,
Юрий

**Comment by AnastasiaSpihtorenko** [comment]
Здравствуйте, Юрий Викторович.
 
Ошибки исправлены.

Спасибо.

**Comment by YuriSilenok** [comment]
зачтено
