### ISSUE TITLE
Разработать сценарии тестирования пригодных для автоматизации модульным тестированием метода Delete(Model model) сущности Институт 

### ISSUE THREAD

**Issue by Takunava** [Students-of-the-city-of-Kostroma/Student-timetable#161]
[План разработки.](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_102)
[Сценарий.](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)
[Ссылка](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_0) на диаграмму классов.

**Comment by YuriSilenok** [comment]
задача снята

**Comment by Takunava** [comment]
@YuriSilenok 
Здравствуйте,
Я готов приступить к выполнению задачи

**Comment by YuriSilenok** [comment]
Здравсвуйте @Takunava 

Забирайте,

Спасибо,
Юрий

**Comment by YuriSilenok** [comment]
Эта задача уже реализована здесь #617
