### ISSUE TITLE
Разработать сценарии тестирования пригодных для автоматизации модульным тестированием метода Delete(Model model) сущности Кафедра

### ISSUE THREAD

**Issue by ghost** [Students-of-the-city-of-Kostroma/Student-timetable#162]
[Сценарий](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)
[План разработки](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_102)
[Ссылка](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_0) на диаграмму классов

**Comment by ghost** [comment]
| Состояние таблицы контроллера | Сокращенная запись кафедры [[А-Я][а-я]]| Полная запись кафедры [[А-Я][а-я]] | Заведующий кафедры [[А-Я][а-я]] |
| --- | --- | --- | --- |
| Удаление записи при совпадении всех атрибутов | task-162-1 | task-162-1 | task-162-1 |
| Удаление записи при совпадении только одного атрибута | task-162-2 | task-162-3 | task-162-4 |

**Comment by YuriSilenok** [comment]
Здравствуйте.
- Ожидаемый результат указывается к конкретному шагу.
- Я думаю что поиск удаляемой строки должен выполнятся по первичному ключу. Какой для сущности Кафедра может быть первичный ключ из существующих атрибутов?

Спасибо.

**Comment by ghost** [comment]
Здравствуйте.

- Не совсем понял
- Первичный ключ сокращенная запись

**Comment by YuriSilenok** [comment]
Здравствуйте.
> Не совсем понял

Обратите внимание на ожидаемые результаты сценария task-203-5, видитк цифру перед ожидаемым результатом, это ссылка на шаг в сценарии.

> Первичный ключ сокращенная запись

Поиск удаляемой записи должен осуществляться по первичному ключу. Если это так, то верный ли ожиддаемый результат для task-162-2 ?

**Comment by ghost** [comment]
Здравствуйте.

Исправлено, проверьте пожалуйста.

**Comment by YuriSilenok** [comment]
Здравствуйте.
1. Обратите на форматирование ячейки с зелёным фоном. Объединять не нужно ячейки. 
2. task-162-2. Почему все атрибуты идентичны прекондишену?

**Comment by YuriSilenok** [comment]
Здравствуйте.
1. Обратите на форматирование ячейки с зелёным фоном. Объединять не нужно ячейки. 
2. task-162-2. Почему все атрибуты идентичны прекондишену?

**Comment by ghost** [comment]
Здравствуйте.

Атрибуты исправлены

**Comment by YuriSilenok** [comment]
Зачтено
