### ISSUE TITLE
Разработать сценарий тестирования пригодных для автоматизации модульными тестами для метода Insert(Model model) сущности Министерство

### ISSUE THREAD

**Issue by FvckNeighbors** [Students-of-the-city-of-Kostroma/Student-timetable#163]
[Сценарии.](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)

**Comment by YuriSilenok** [comment]
Задача снята

**Comment by AlexandraKv** [comment]
| Состояние таблицы контроллера | Аббревиатура министерства [[А-Я]{1,10}] | Полное наименование министерства [[А-Я]{1}[а-я]{1,50} [ [а-я]{1,50}]{0,9}] | Населенный пункт размещения министерства [[[а-я]{1,3]. [А-Я]{1}[а-я]{1,50}] or [[[а-я]{1,3]. [А-Я]{1}[а-я]{1,50}]-[А-Я]{1}[а-я]{1,50}] or [[[а-я]{1,3]. [[а-я]{1,3]. [А-Я]{1}[а-я]{1,50}]-[А-Я]{1}[а-я]{1,50}] or [[[а-я]{1,3]. [[а-я]{1,3]. [А-Я]{1}[а-я]{1,50}] |
| ------------- | ------------- | ------------- | ------------- | 
| Таблица не имеет записей  | task-163-1 | task-163-1 | task-163-1 |
| В таблице существует запись с атрибутом, совпадающим с атрибутом добавляемой записи  | task-163-2 | task-163-3 | task-163-4 |
---
[Сценарий task-163](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)

**Comment by AlexandraKv** [comment]
https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548

**Comment by YuriSilenok** [comment]
- Пожалуйста, добавьте в описание задачи ссылку, а не в комментарии URL
- Откуда взялись такие атрибуты, может быть из таска на разработку?

**Comment by AlexandraKv** [comment]
Здравствуйте @YuriSilenok 
Замечания учтены и исправлены.

Заранее спасибо.

**Comment by YuriSilenok** [comment]
Здравствуйте,

Как на счет моего вопроса?
> Откуда взялись такие атрибуты, может быть из таска на разработку?

Спасибо,
Юрий

**Comment by AlexandraKv** [comment]
Атрибуты я взяла из задачи на разработку.

Спасибо,
Александра

**Comment by YuriSilenok** [comment]
Здравствуйте,

А где ссылка на Story?

Спасибо,
Юрий

**Comment by AlexandraKv** [comment]
Я добавила ссылку.

Спасибо, 
Александра

**Comment by YuriSilenok** [comment]
Зачтено
