### ISSUE TITLE
Разработать сценарии тестирования пригодных для автоматизации модульным тестированием метода Delete(Model model) сущности Аудитория

### ISSUE THREAD

**Issue by Pipyao** [Students-of-the-city-of-Kostroma/Student-timetable#164]
[Сценарий](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)
[План разработки](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_102)
[Ссылка](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_0) на диаграмму классов

**Comment by YuriSilenok** [comment]
Снято по не активности.

**Comment by YuriSilenok** [comment]
Почему эта задача открыта?

**Comment by Pipyao** [comment]
Для выполнения ЛР-04

**Comment by YuriSilenok** [comment]
А Вас не смущает что задача с Вас снята?

**Comment by Pipyao** [comment]
Но, она не была снята, а лишь закрыта и продолжала висеть на мне

**Comment by YuriSilenok** [comment]
А как на счет моего комментария от 17 апреля?

**Comment by Pipyao** [comment]
А что тогда делать? поднимать новую? просто эта всё еще была не занята.

**Comment by YuriSilenok** [comment]
как вы определили что она не занята?

**Comment by Pipyao** [comment]
Она не висела ни на ком другом, а в участвующих кроме Вас и Меня никого нет.

**Comment by YuriSilenok** [comment]
что вы моежете сказать об этой задаче #272

**Comment by Pipyao** [comment]
Так ведь это для Unit-тестов.

**Comment by YuriSilenok** [comment]
А эта задача для чего?

**Comment by YuriSilenok** [comment]
> Так ведь это для Unit-тестов.

значит ли это, что уже существуют сценарии и автотесты автоматизированы по ним для задачи которую Вы пеероткрыли?

**Comment by Pipyao** [comment]
Для того же, но моя была открыта много раньше.Эта задача была открыта 18 марта, а #272 7 апреля, при том что эта задача была закрыта лишь 17.

**Comment by Pipyao** [comment]
Их ошибка в открытии клонирующей задачи.

**Comment by YuriSilenok** [comment]
А Ваша ошибка в том, что у задачи просрочен дедлайн и ее выполнили другие люди. 
В командной разработке так бывает, если не Вы, то кто-то другой, проект не должен стоять на месте.
Итог:
Эта задача не может быть выполнена, так как проект больше в ней не нуждается.
Возможные ваши действия:
- ПРОДОЛЖИТЬ цепочку писем по сдаче лабораторной работой
- продолжить отстаивать эту работы
- то, на что у меня не хватило воображения

**Comment by Pipyao** [comment]
Понял, тогда я поднимаю новую задачу для другого метода, сущности?

**Comment by YuriSilenok** [comment]
Нет, Вы пишете мне письмо о том, что бы я выдал задание.
Так как семестр кончился, оно будет несколько специфичное, на исправление сбоев, это предполагает изменение кода автотестов и сценариев (скорее всего)

**Comment by Pipyao** [comment]
> Нет, Вы пишете мне письмо о том, что бы я выдал задание.
> Так как семестр кончился, оно будет несколько специфичное, на исправление сбоев, это предполагает изменение кода автотестов и сценариев (скорее всего)

Отправил.Жду.
