### ISSUE TITLE
Разработать сценарии тестирования пригодных для автоматизации модульным тестированием метода Insert(Model model) сущности ВУЗ

### ISSUE THREAD

**Issue by MihailBobylev** [Students-of-the-city-of-Kostroma/Student-timetable#166]
[План разработки](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_102).
[Сценарий](https://docs.google.com/spreadsheets/d/1z89kyDKWUYUOjZVjVTJZ_0lOJeD7eQB3OKzh6513cnc/edit?usp=sharing).
[Ссылка](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_0) на диаграмму классов.

**Comment by MihailBobylev** [comment]
Состояние | Наименование | Руководитель | Контактный телефон | Адрес электронной почты |  
-- | -- | -- | -- | -- | --
Пустая таблица | task-166-1 | task-166-1 | task-166-1 | task-166-1 |  
Добавление дублирующего атрибута | task-166-2 | task-166-3 | task-166-4 | task-166-5 |

**Comment by YuriSilenok** [comment]
Перенести в таблицу со сценариями, ссылка в описании задачи

**Comment by YuriSilenok** [comment]
Тесты не ориентированы на тестирование библиотеки

**Comment by YuriSilenok** [comment]
Зачтено

**Comment by KudelinRoman** [comment]
@YuriSilenok
Здравствуйте.
В ветке Testing не существует классов CWUZ и MWUZ.
Может эти классы существуют в какой-то другой ветке о которой я не знаю.
В ветке Testing я нашел 3 класса для вуза это классы: CHEI MHEI и MCHEI.
Но эти классы содержат на один аргумент больше чем в сценариях. (Есть поле "Полное название")
Один из этих классов недоступен (класс MCHEI пишет что нет доступа из-за уровня приватности)
Я попытался автоматизировать тесты с помощью этих двух классов но не вышло.
Вот код:
![image](https://user-images.githubusercontent.com/47320335/57573519-7b28c600-7431-11e9-8b10-72374458b1c9.png)

Этот тест зафейлился :
![image](https://user-images.githubusercontent.com/47320335/57573523-867bf180-7431-11e9-95ac-8329b099d34b.png)

Пожалуйста, подскажите что мне делать в этой ситуации.
Спасибо.
Куделин Роман.
17-ИСбо-2б.

**Comment by YuriSilenok** [comment]
Ох, я бы ожидал что Вы в своей задаче это все напишите. Могли бы Вы скопировать в свой таск этот вопрос?
