### ISSUE TITLE
Разработать сценарии тестирования пригодных для автоматизации модульным тестированием метода Delete(Model model) сущности ВУЗ

### ISSUE THREAD

**Issue by Parallusion** [Students-of-the-city-of-Kostroma/Student-timetable#169]
[План разработки.](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_102)
[Сценарий.](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)
[Ссылка на диаграмму классов.](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_0)

**Comment by Parallusion** [comment]
Состояние | Название | Руководитель | Адрес электронной почты | Контактный телефон |  
-- | -- | -- | -- | -- | --
Удалить по атрибуту существующих данных | task-169-1 | task-169-1 | task-169-1 | task-169-1 |  
Удаление по  атрибуту несуществующему данных | task-169-2 | task-169-3 | task-169-4 | task-169-5 |  
  |   |   |   |   |  
  |   |   |   |   |  
  |   |   |   |   |  
Test ID(номер теста) | Description(название теста) | Test Data(пусто) | Pre-condition(-ключ атрибута:значение) | Steps | Expected Result
task-169-1 | Удаление по атрибуту существующих данных из таблицы |   | 1. Запустить программу 2. Перейти по меню "Справочники - ВУЗы"3. Нажать на появившейся форме кнопку "Добавить"4. Ввести на появившейся форме следующие атрибуты: -Наименование: "КГУ" -Руководитель: "Жиба Михаил Ильич" -Контактный телефон: "+7(4942)133113" -Адрес электронной почты: "stfu@gmail.com"2) Нажать кнопку "Создать и закрыть" | 1. Запустить программу 2. Перейти по меню "Справочники - ВУЗы"3. Выбрать атрибут для удаления из списка атрибутов: "Название", "Руководитель", "Адрес электронной почты", "Контактный адрес" 4. Выбрать поле с необходимыми для удаления данными из выбранного атрибута 5.Нажать на кнопку "Удалить" 5. Нажать на кнопку "Сохранить", а затем на кнопку "Закрыть" | Из поля выбранного атрибута таблицы ВУЗы исчезли данные
task-169-2 | Удаление по атрибуту несуществующих данных из таблицы по атрибуту "Название" |   | 1. Запустить программу 2. Перейти по меню "Справочники-ВУЗы" 3. Выбрать атрибут "Название" 4. Выбрать поле с данными 5. Нажать на кнопку "Удалить" 6. Нажать на кнопку "Сохранить", а затем на кнопку "Закрыть" | 1. Запустить программу 2. Перейти по меню "Справочники - ВУЗы "3. Выбрать атрибут "Название" 4. Выбрать пустое поле атрибута 5. Нажать на кнопку "Удалить" | При нажатии кнопки "Удалить" на экране появится сообщение об ошибке: "Выбрано пустое поле для удаления данных по атрибуту "Название"
task-169-3 | Удаление по атрибуту несуществующих данных из таблицы по атрибуту "Руководитель" |   | 1. Запустить программу 2. Перейти по меню "Справочники-ВУЗы" 3. Выбрать атрибут "Руководитель" 4. Выбрать поле с данными 5. Нажать на кнопку "Удалить" 6. Нажать на кнопку "Сохранить", а затем на кнопку "Закрыть" | 1. Запустить программу 2. Перейти по меню "Справочники - ВУЗы "3. Выбрать атрибут "Руководитель" 4. Выбрать пустое поле атрибута 5. Нажать на кнопку "Удалить" | При нажатии кнопки "Удалить" на экране появится сообщение об ошибке: "Выбрано пустое поле для удаления данных по атрибуту "Руководитель"
task-169-4 | Удаление по атрибуту несуществующих данных из таблицы по атрибуту "Адрес электронной почты" |   | 1. Запустить программу 2. Перейти по меню "Справочники-ВУЗы" 3. Выбрать атрибут "Адрес электронной почты" 4. Выбрать поле с данными 5. Нажать на кнопку "Удалить" 6. Нажать на кнопку "Сохранить", а затем на кнопку "Закрыть" | 1. Запустить программу 2. Перейти по меню "Справочники - ВУЗы "3. Выбрать атрибут "Адрес электронной почты" 4. Выбрать пустое поле атрибута 5. Нажать на кнопку "Удалить" | При нажатии кнопки "Удалить" на экране появится сообщение об ошибке: "Выбрано пустое поле для удаления данных по атрибуту "Адрес электронной почты"
task-169-5 | Удаление по атрибуту несуществующих данных из таблицы по атрибуту "Контактный телефон" |   | 1. Запустить программу 2. Перейти по меню "Справочники-ВУЗы" 3. Выбрать атрибут "Контактный телефон" 4. Выбрать поле с данными 5. Нажать на кнопку "Удалить" 6. Нажать на кнопку "Сохранить", а затем на кнопку "Закрыть" | 1. Запустить программу 2. Перейти по меню "Справочники - ВУЗы "3. Выбрать атрибут "Контактный телефон" 4. Выбрать пустое поле атрибута 5. Нажать на кнопку "Удалить" | При нажатии кнопки "Удалить" на экране появится сообщение об ошибке: "Выбрано пустое поле для удаления данных по атрибуту "Контактный телефон"

**Comment by Parallusion** [comment]
Состояние | Название | Руководитель | Адрес электронной почты | Контактный телефон |  
-- | -- | -- | -- | -- | --
Удаление по атрибуту существующих данных | task-169-1 | task-169-1 | task-169-1 | task-169-1 |  
Удаление по  атрибуту несуществующему данных | task-169-2 | task-169-3 | task-169-4 | task-169-5 |  
  |   |   |   |   |  
  |   |   |   |   |  
  |   |   |   |   |  
Test ID(номер теста) | Description(название теста) | Test Data(пусто) | Pre-condition(-ключ атрибута:значение) | Steps | Expected Result
task-169-1 | Удаление по атрибуту существующих данных из таблицы |   | 1. Запустить программу 2. Перейти по меню "Справочники - ВУЗы"3. Нажать на появившейся форме кнопку "Добавить"4. Ввести на появившейся форме следующие атрибуты: -Наименование: "КГУ" -Руководитель: "Жиба Михаил Ильич" -Контактный телефон: "+7(4942)133113" -Адрес электронной почты: "stfu@gmail.com"2) Нажать кнопку "Создать и закрыть" | 1. Запустить программу 2. Перейти по меню "Справочники - ВУЗы"3. Выбрать атрибут для удаления из списка атрибутов: "Название", "Руководитель", "Адрес электронной почты", "Контактный адрес" 4. Выбрать поле с необходимыми для удаления данными из выбранного атрибута 5.Нажать на кнопку "Удалить" 5. Нажать на кнопку "Сохранить", а затем на кнопку "Закрыть" | Из поля выбранного атрибута таблицы ВУЗы исчезли данные
task-169-2 | Удаление по атрибуту несуществующих данных из таблицы по атрибуту "Название" |   | 1. Запустить программу 2. Перейти по меню "Справочники-ВУЗы" 3. Выбрать атрибут "Название" 4. Выбрать поле с данными 5. Нажать на кнопку "Удалить" 6. Нажать на кнопку "Сохранить", а затем на кнопку "Закрыть" | 1. Запустить программу 2. Перейти по меню "Справочники - ВУЗы "3. Выбрать атрибут "Название" 4. Выбрать пустое поле атрибута 5. Нажать на кнопку "Удалить" | При нажатии кнопки "Удалить" на экране появится сообщение об ошибке: "Выбрано пустое поле для удаления данных по атрибуту "Название"
task-169-3 | Удаление по атрибуту несуществующих данных из таблицы по атрибуту "Руководитель" |   | 1. Запустить программу 2. Перейти по меню "Справочники-ВУЗы" 3. Выбрать атрибут "Руководитель" 4. Выбрать поле с данными 5. Нажать на кнопку "Удалить" 6. Нажать на кнопку "Сохранить", а затем на кнопку "Закрыть" | 1. Запустить программу 2. Перейти по меню "Справочники - ВУЗы "3. Выбрать атрибут "Руководитель" 4. Выбрать пустое поле атрибута 5. Нажать на кнопку "Удалить" | При нажатии кнопки "Удалить" на экране появится сообщение об ошибке: "Выбрано пустое поле для удаления данных по атрибуту "Руководитель"
task-169-4 | Удаление по атрибуту несуществующих данных из таблицы по атрибуту "Адрес электронной почты" |   | 1. Запустить программу 2. Перейти по меню "Справочники-ВУЗы" 3. Выбрать атрибут "Адрес электронной почты" 4. Выбрать поле с данными 5. Нажать на кнопку "Удалить" 6. Нажать на кнопку "Сохранить", а затем на кнопку "Закрыть" | 1. Запустить программу 2. Перейти по меню "Справочники - ВУЗы "3. Выбрать атрибут "Адрес электронной почты" 4. Выбрать пустое поле атрибута 5. Нажать на кнопку "Удалить" | При нажатии кнопки "Удалить" на экране появится сообщение об ошибке: "Выбрано пустое поле для удаления данных по атрибуту "Адрес электронной почты"
task-169-5 | Удаление по атрибуту несуществующих данных из таблицы по атрибуту "Контактный телефон" |   | 1. Запустить программу 2. Перейти по меню "Справочники-ВУЗы" 3. Выбрать атрибут "Контактный телефон" 4. Выбрать поле с данными 5. Нажать на кнопку "Удалить" 6. Нажать на кнопку "Сохранить", а затем на кнопку "Закрыть" | 1. Запустить программу 2. Перейти по меню "Справочники - ВУЗы "3. Выбрать атрибут "Контактный телефон" 4. Выбрать пустое поле атрибута 5. Нажать на кнопку "Удалить" | При нажатии кнопки "Удалить" на экране появится сообщение об ошибке: "Выбрано пустое поле для удаления данных по атрибуту "Контактный телефон"

**Comment by Parallusion** [comment]
Состояние | Название | Руководитель | Адрес электронной почты | Контактный телефон |  
-- | -- | -- | -- | -- | --
Удаление по атрибуту существующих данных | task-169-1 | task-169-1 | task-169-1 | task-169-1 |  
Удаление по  атрибуту несуществующих данных | task-169-2 | task-169-3 | task-169-4 | task-169-5 |  
  |   |   |   |   |  
  |   |   |   |   |  
  |   |   |   |   |  
Test ID(номер теста) | Description(название теста) | Test Data(пусто) | Pre-condition(-ключ атрибута:значение) | Steps | Expected Result
task-169-1 | Удаление по атрибуту существующих данных из таблицы |   | 1. Запустить программу 2. Перейти по меню "Справочники - ВУЗы"3. Нажать на появившейся форме кнопку "Добавить"4. Ввести на появившейся форме следующие атрибуты: -Наименование: "КГУ" -Руководитель: "Жиба Михаил Ильич" -Контактный телефон: "+7(4942)133113" -Адрес электронной почты: "stfu@gmail.com"2) Нажать кнопку "Создать и закрыть" | 1. Запустить программу 2. Перейти по меню "Справочники - ВУЗы"3. Выбрать атрибут для удаления из списка атрибутов: "Название", "Руководитель", "Адрес электронной почты", "Контактный адрес" 4. Выбрать поле с необходимыми для удаления данными из выбранного атрибута 5.Нажать на кнопку "Удалить" 5. Нажать на кнопку "Сохранить", а затем на кнопку "Закрыть" | Из поля выбранного атрибута таблицы ВУЗы исчезли данные
task-169-2 | Удаление по атрибуту несуществующих данных из таблицы по атрибуту "Название" |   | 1. Запустить программу 2. Перейти по меню "Справочники-ВУЗы" 3. Выбрать атрибут "Название" 4. Выбрать поле с данными 5. Нажать на кнопку "Удалить" 6. Нажать на кнопку "Сохранить", а затем на кнопку "Закрыть" | 1. Запустить программу 2. Перейти по меню "Справочники - ВУЗы "3. Выбрать атрибут "Название" 4. Выбрать пустое поле атрибута 5. Нажать на кнопку "Удалить" | При нажатии кнопки "Удалить" на экране появится сообщение об ошибке: "Выбрано пустое поле для удаления данных по атрибуту "Название"
task-169-3 | Удаление по атрибуту несуществующих данных из таблицы по атрибуту "Руководитель" |   | 1. Запустить программу 2. Перейти по меню "Справочники-ВУЗы" 3. Выбрать атрибут "Руководитель" 4. Выбрать поле с данными 5. Нажать на кнопку "Удалить" 6. Нажать на кнопку "Сохранить", а затем на кнопку "Закрыть" | 1. Запустить программу 2. Перейти по меню "Справочники - ВУЗы "3. Выбрать атрибут "Руководитель" 4. Выбрать пустое поле атрибута 5. Нажать на кнопку "Удалить" | При нажатии кнопки "Удалить" на экране появится сообщение об ошибке: "Выбрано пустое поле для удаления данных по атрибуту "Руководитель"
task-169-4 | Удаление по атрибуту несуществующих данных из таблицы по атрибуту "Адрес электронной почты" |   | 1. Запустить программу 2. Перейти по меню "Справочники-ВУЗы" 3. Выбрать атрибут "Адрес электронной почты" 4. Выбрать поле с данными 5. Нажать на кнопку "Удалить" 6. Нажать на кнопку "Сохранить", а затем на кнопку "Закрыть" | 1. Запустить программу 2. Перейти по меню "Справочники - ВУЗы "3. Выбрать атрибут "Адрес электронной почты" 4. Выбрать пустое поле атрибута 5. Нажать на кнопку "Удалить" | При нажатии кнопки "Удалить" на экране появится сообщение об ошибке: "Выбрано пустое поле для удаления данных по атрибуту "Адрес электронной почты"
task-169-5 | Удаление по атрибуту несуществующих данных из таблицы по атрибуту "Контактный телефон" |   | 1. Запустить программу 2. Перейти по меню "Справочники-ВУЗы" 3. Выбрать атрибут "Контактный телефон" 4. Выбрать поле с данными 5. Нажать на кнопку "Удалить" 6. Нажать на кнопку "Сохранить", а затем на кнопку "Закрыть" | 1. Запустить программу 2. Перейти по меню "Справочники - ВУЗы "3. Выбрать атрибут "Контактный телефон" 4. Выбрать пустое поле атрибута 5. Нажать на кнопку "Удалить" | При нажатии кнопки "Удалить" на экране появится сообщение об ошибке: "Выбрано пустое поле для удаления данных по атрибуту "Контактный телефон"

**Comment by Parallusion** [comment]
Состояние | Название | Руководитель | Адрес электронной почты | Контактный телефон
-- | -- | -- | -- | --
Удаление по атрибуту существующих данных | task-169-1 | task-169-1 | task-169-1 | task-169-1
Удаление по  атрибуту несуществующих данных | task-169-2 | task-169-3 | task-169-4 | task-169-5

**Comment by YuriSilenok** [comment]
Перенести в таблицу указанную в описании задачи.

**Comment by YuriSilenok** [comment]
В ожидаемых результатах добавить как изменяется количество строк.

**Comment by Parallusion** [comment]
В ожидаемых результатах добавлена информация об изменении количества строк

**Comment by YuriSilenok** [comment]
1. Почему ссылка на сцеанрии указанная в таблице не ведет на общие сценарии?
2. Где первая таблица в комментариях установленного образца?
3. Зачем в комментариях таблица со сценариями?
4. Задачу перевешивают после того как напишут комментарии или закончат другую активность над задачей.

**Comment by Parallusion** [comment]
1. Ссылка поменяна на ссылку на общие сценарии.
2. Добавлена первая таблица в комментарии установленного образца.
3. Таблица со сценариями убрана.

**Comment by YuriSilenok** [comment]
Сценарий task-169-1
Прекондишен:
1. Cоздать объект класса MWUZ 
2. Передать в него атрибуты:
-Наименование: "КГУ"
-Руководитель: "Наумов Александр Рудольфович"
-Адрес электронной почты: "kgu.ru"
-Контактный телефон: "43-34-41"
3. Вызвать метод Insert(Model model) класса CWUZ, передав в него созданный объект класса MWUZ

Степы:
1. Cоздать объект класса MWUZ
2. Вызвать метод Delete(Model model) класса CWUZ, передавая в него созданный объект класса MWUZ

Вы создаете новый объект первым шагом, а с какими параметрами?

**Comment by Parallusion** [comment]
По логике, должны быть те же параметры, то есть у меня два варианта:
1. Либо не создавать новый объект, а просто вызвать метод Delete с объектом из Пре кондишена.
2. Либо создать новый объект с теми же параметрами, что и в Пре кондишене.
Думаю, что 2 вариант корректный.

**Comment by YuriSilenok** [comment]
- Согласен, второй вариант более близок к реальному поведению системы.
- task-169-3 я бы ожидал что поиск удаляемой строки должен производится только по ключевому атрибуту. Какой ключевой атрибут вы можете выделить для вашей сущности?

**Comment by Parallusion** [comment]
В task-169-3 ключевым атрибутом является "Руководитель". Исходный объект в поле атрибута "Руководитель" хранит поле с записью "Наумов Александр Рудольфович", а при удалении у объекта в поле атрибута "Руководитель" - "Коваленко Санёчек Михайлович". Следовательно удаление происходит только по ключевому атрибуту "Руководитель".

**Comment by YuriSilenok** [comment]
Первичный ключ Наименование.

**Comment by Parallusion** [comment]
1. Изменен Description  в сценариях: "несуществующих данных" -> "существующих данных"
2. Изменен ожидаемый результат: "return false. Количество строк не изменится" -> "return true. Количество строк уменьшится на 1"

**Comment by Parallusion** [comment]
1. Изменен Description  в сценариях: "несуществующих данных" -> "существующих данных"
2. Изменен ожидаемый результат: "return false. Количество строк не изменится" -> "return true. Количество строк уменьшится на 1"

**Comment by YuriSilenok** [comment]
Зачтено
