### ISSUE TITLE
Автоматизация unit-test для метода Insert(Model model) сущности Group

### ISSUE THREAD

**Issue by DenisSavelev** [Students-of-the-city-of-Kostroma/Student-timetable#17]
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)
Реализовать сценарии пригодные для Unit-тестирования
[План разработки](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.p)
[Диаграмма классов](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_0)

**Comment by YuriSilenok** [comment]
Добрый день.
У Вас не правильно выставлены метки.
Типы задач.
Задачи на разработку функциональности - помечается ярлыком Story. Все задачи относятся к одной из четырех сущностей: Преподаватель, Группа, Аудитория, Дисциплина. Задача должна иметь соответствующую этой сущности одноименную англоязычную метку. Если упомянут класс который начинается с большой буквы M, например MGroup, то задача должна быть помечена меткой Model. Если задача имеет цель разработки конструктор, метод вставки, метод обновления или удаления, то задача должна быть помечена меткой Controller. Если задача ставится на разработку конструктора, то указывается метка new(). Если задача ставиться на разработку метода Insert, Update, Delete то указывается соответственно метка Insert(Model model), Update(Model model), Delete (Model model).
Задачи на тестирование. Если задача относиться к тестовым сценариям для unit-тестирования, то ставиться метка unit-test. Если задача ставиться на написание сценариев то указывается метка Script. Если задача ставиться на автоматизацию тестирования, то ставить указывается метка Auto-test.

**Comment by DenisSavelev** [comment]
> Добрый день.
> У Вас не правильно выставлены метки.
> Типы задач.
> Задачи на разработку функциональности - помечается ярлыком Story. Все задачи относятся к одной из четырех сущностей: Преподаватель, Группа, Аудитория, Дисциплина. Задача должна иметь соответствующую этой сущности одноименную англоязычную метку. Если упомянут класс который начинается с большой буквы M, например MGroup, то задача должна быть помечена меткой Model. Если задача имеет цель разработки конструктор, метод вставки, метод обновления или удаления, то задача должна быть помечена меткой Controller. Если задача ставится на разработку конструктора, то указывается метка new(). Если задача ставиться на разработку метода Insert, Update, Delete то указывается соответственно метка Insert(Model model), Update(Model model), Delete (Model model).
> Задачи на тестирование. Если задача относиться к тестовым сценариям для unit-тестирования, то ставиться метка unit-test. Если задача ставиться на написание сценариев то указывается метка Script. Если задача ставиться на автоматизацию тестирования, то ставить указывается метка Auto-test.

**Comment by DenisSavelev** [comment]
> Добрый день.
> У Вас не правильно выставлены метки.
> Типы задач.
> Задачи на разработку функциональности - помечается ярлыком Story. Все задачи относятся к одной из четырех сущностей: Преподаватель, Группа, Аудитория, Дисциплина. Задача должна иметь соответствующую этой сущности одноименную англоязычную метку. Если упомянут класс который начинается с большой буквы M, например MGroup, то задача должна быть помечена меткой Model. Если задача имеет цель разработки конструктор, метод вставки, метод обновления или удаления, то задача должна быть помечена меткой Controller. Если задача ставится на разработку конструктора, то указывается метка new(). Если задача ставиться на разработку метода Insert, Update, Delete то указывается соответственно метка Insert(Model model), Update(Model model), Delete (Model model).
> Задачи на тестирование. Если задача относиться к тестовым сценариям для unit-тестирования, то ставиться метка unit-test. Если задача ставиться на написание сценариев то указывается метка Script. Если задача ставиться на автоматизацию тестирования, то ставить указывается метка Auto-test.

Я пересмотрел метки

**Comment by DenisSavelev** [comment]
Добрый вечер. Я пересмотрел метки

ср, 6 февр. 2019 г. в 13:13, Юрий Силенок <notifications@github.com>:

**Comment by YuriSilenok** [comment]
Здравствуйте.
На каком основании была закрыта задача, она выполнена?
Почему на меня не заасанили?
Спасибо

**Comment by DenisSavelev** [comment]
Здравствуйте, промахнулся видимо, я открыл

ср, 6 февр. 2019 г. в 20:43, Юрий Силенок <notifications@github.com>:

**Comment by YuriSilenok** [comment]
Здравствуйте.
Один вопрос решили, со вторым что? Почему на меня не заасанили (назначили)?
Спасибо.

**Comment by DenisSavelev** [comment]
Решил, не заметил 😅

ср, 6 февр. 2019 г. в 21:39, Юрий Силенок <notifications@github.com>:

**Comment by YuriSilenok** [comment]
Зачтено

**Comment by YuriSilenok** [comment]
Зачтено
