### ISSUE TITLE
Разработать сценарии тестирования пригодных для автоматизации модульным тестированием метода Insert(Model model) сущности Корпус

### ISSUE THREAD

**Issue by yuliagolubevaa5** [Students-of-the-city-of-Kostroma/Student-timetable#171]
[План разработки.](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_102)
[Сценарий.](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)
[Ссылка на диаграмму классов.](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_0)

**Comment by yuliagolubevaa5** [comment]
Здравствуйте, @YuriSilenok 
Можно уточнить какие поля находятся в таблице формы Корпуса? Просто я довольно слабо представляю себе какие именно атрибуты должны быть в таблице контроллера.
![image](https://user-images.githubusercontent.com/47320351/54949324-d79e5780-4f4f-11e9-98a8-654076858b2b.png)
Заранее благодарю.

**Comment by YuriSilenok** [comment]
Ответил устно,

**Comment by yuliagolubevaa5** [comment]
| Состояние таблицы контроллера | Шифр cipher ∈ [[А-Я]{1}  or [А-Я]{1}[1-10]{1}]  | Адрес address ∈ [[A-Я]{1}[а-я]{1,50},[1-150]{1} or [А-Я]{1}[а-я]{1,50} [А-Я]{1}[а-я]{1,50},[1-150]{1}] | Название name ∈ [[A-Я]{1}[а-я]{1,50}]  | Кол-во этажей floors [5] |
 | ----- | ---- | ---- | ---- | ---- |
 | ` Таблица не имеет записей ` | task-171-1 | task-171-1 | task-171-1 | task-171-1 |
 | ` В таблице существует запись с атрибутом, совпадающим с атрибутом добавляемой записи` | task-171-2 | task-171-3 | task-171-4 | task-171-5 |
---
[Сценарий task-171](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)

**Comment by yuliagolubevaa5** [comment]
@YuriSilenok , здравствуйте.
Не могли бы вы проверить правильность выполнения данной задачи?
Заранее спасибо.

**Comment by YuriSilenok** [comment]
1. Ожидаемый результат должен указывать на номер степа к которому он написан.
2. В ожидаемый результат добавить как будет изменяться количество строк в таблице.
3. Описание сценария не соответствует действительности. Например:

> Ввод корректных данных в таблицу при условии, что шифр с таким обозначением уже есть в таблице

Из прекондишена:

> 1. Создать объект класса MEnclosures 
> 2.Передать в него атрибуты: 
> -Шифр:"Е" 
> -Адрес: "Малышковская, 4"
> -Название: "Заволжский"
> -Кол-во этажей: "5"

Из шагов

> 2.Передать в него атрибуты: 
> -Шифр:"А1" 
> -Адрес: "Малышковская, 4"
> -Название: "Заволжский"
> -Кол-во этажей: "5"

Получается что только шифр и не совпадает с уже существующей записью, а нужно что бы только он и совпадал.

**Comment by yuliagolubevaa5** [comment]
@YuriSilenok , здравствуйте.
Замечания учла, [таблицу со сценариями](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548) исправила

**Comment by YuriSilenok** [comment]
Зачтено
