### ISSUE TITLE
Разработка сценариев тестирования для формы "Добавить преподавателя"

### ISSUE THREAD

**Issue by stasshtaub** [Students-of-the-city-of-Kostroma/Student-timetable#179]
Story: https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/66

[Ссылка на сценарий](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)

**Comment by YuriSilenok** [comment]
Почему Вы подняли эту задачу?

**Comment by stasshtaub** [comment]
@YuriSilenok вы сказали поднять ее для ЛР4 на лабораторной в понедельник

**Comment by YuriSilenok** [comment]
Да, теперь я вижу в чем причина, можете выполнять эту задачу Прошу обратить внимание что эта задача на написание функциональных тестов, а не модульных.

**Comment by YuriSilenok** [comment]
не актуально
