### ISSUE TITLE
Реализовать метод Delete(Model model) сущности Teacher

### ISSUE THREAD

**Issue by KudelinRoman** [Students-of-the-city-of-Kostroma/Student-timetable#18]
Разработать метод Delete(Model model) сущности Teacher
[План разработки](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.p)
[Ссылка](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit) на диаграмму классов

**Comment by YuriSilenok** [comment]
Добрый день. У Вас не хватает меток.

Типы задач.
Задачи на разработку функциональности - помечается ярлыком Story. Все задачи относятся к одной из четырех сущностей: Преподаватель, Группа, Аудитория, Дисциплина. Задача должна иметь соответствующую этой сущности одноименную англоязычную метку. Если упомянут класс который начинается с большой буквы M, например MGroup, то задача должна быть помечена меткой Model. Если задача имеет цель разработки конструктор, метод вставки, метод обновления или удаления, то задача должна быть помечена меткой Controller. Если задача ставится на разработку конструктора, то указывается метка new(). Если задача ставиться на разработку метода Insert, Update, Delete то указывается соответственно метка Insert(Model model), Update(Model model), Delete (Model model).
Задачи на тестирование. Если задача относиться к тестовым сценариям для unit-тестирования, то ставиться метка unit-test. Если задача ставиться на написание сценариев то указывается метка Script. Если задача ставиться на автоматизацию тестирования, то ставить указывается метка Auto-test.

**Comment by YuriSilenok** [comment]
зачтено

**Comment by YuriSilenok** [comment]
Зачтено
