### ISSUE TITLE
Разработка сценариев тестирования для формы "Добавить группу"

### ISSUE THREAD

**Issue by abramovaalina** [Students-of-the-city-of-Kostroma/Student-timetable#180]
Story: #74 

[Ссылка на сценарий](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)

**Comment by YuriSilenok** [comment]
Зачача снята по неактивности и закрыта так как уже реализована.
