### ISSUE TITLE
Разработка сценариев тестирования для формы "Добавить дисциплину"

### ISSUE THREAD

**Issue by ZhizhikinIvan** [Students-of-the-city-of-Kostroma/Student-timetable#181]
Story: #77 
[Ссылка на сценарий](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)

**Comment by YuriSilenok** [comment]
Задача снята
