### ISSUE TITLE
Разработка сценариев тестирования для формы "Добавить министерство"

### ISSUE THREAD

**Issue by sidelong44** [Students-of-the-city-of-Kostroma/Student-timetable#183]
Story: #182 

[Ссылка на сценарий](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)

**Comment by YuriSilenok** [comment]
Задача снята по бездействию.

**Comment by bolotovaksenya** [comment]
Здравствуйте, @YuriSilenok .
Дело в том, что при выполнении данной задачи наткнулась на похожую задачу для тестирования метода Insert (Model model) - значит ли это, что эта задача клонирует ту?

**Comment by YuriSilenok** [comment]
Дайте ссылку на ту задачу, пожалуйста.

**Comment by bolotovaksenya** [comment]
Здравствуйте, @YuriSilenok 
#163

**Comment by YuriSilenok** [comment]
Судя по формулировкам, Ваша задача это мануальные тесты для представления (Формы), а задача #163 это разработка автотестов для контроллера.

**Comment by bolotovaksenya** [comment]
| Функция тестирования | Аббревиатура министерства [[А-Я]{1,10}]  | Полное наименование министерства [[А-Я]{1}[а-я]{1,50} [ [а-я]{1,50}]{0,9}] | Населенный пункт размещения министерства [[[а-я]{1,3]. [А-Я]{1}[а-я]{1,50}] or [[[а-я]{1,3]. [А-Я]{1}[а-я]{1,50}]-[А-Я]{1}[а-я]{1,50}] or [[[а-я]{1,3]. [[а-я]{1,3]. [А-Я]{1}[а-я]{1,50}]-[А-Я]{1}[а-я]{1,50}] or [[[а-я]{1,3]. [[а-я]{1,3]. [А-Я]{1}[а-я]{1,50}]  | 
 | ----- | ---- | ---- | ---- | 
 | ` Проверка добавления полностью корректных данных ` | task-183-1 | task-183-1 | task-183-1 | 
 | `Проверка наличия ограничения на уникальность для каждого поля` | task-183-2 | task-183-3 | task-183-4 | 
---
[Сценарий task-183](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)

**Comment by YuriSilenok** [comment]
> Таблица имеет одну запись с полностью корректными данными

В таблице (в теории) всегда должна содержать корректные данные, если таковые имеются, значит это ошибка разработчиков. Я бы сказал что в первом столбце необходимо описать какую функцию вы собираетесь тестировать. Допустим в первой строке это было бы проверка возможности добавление строки с корректными данными. 

> В таблице существует запись, где все атрибуты (кроме 1) совпадают с атрибутами добавляемой записи

Видимо здесь Вы хотели проверить наличие/отсутствие ограничение уникальности для каждого атрибута. Соответственно для этого нужно иметь в таблице первоначальные данные.

**Comment by bolotovaksenya** [comment]
@YuriSilenok , замечания учла, таблицу исправила.

**Comment by YuriSilenok** [comment]
> Проверка добавления полностью дублирующей записи

Какую функциональность это проверяет?

**Comment by bolotovaksenya** [comment]
@YuriSilenok, Что Вы имеете в виду?

**Comment by YuriSilenok** [comment]
> Проверка добавления полностью дублирующей записи

Вы тестируете набор функций, в том числе и ограничения. 
Ваш тест проверяет работоспособность какой функциональности?

**Comment by bolotovaksenya** [comment]
@YuriSilenok , ограничение на ввод идентичной записи посредством проверки условия наличия подобной записи в таблице

**Comment by YuriSilenok** [comment]
у Вас ограничение сработает только если все атрибуты записи совпадут?

**Comment by bolotovaksenya** [comment]
@YuriSilenok . да, но возможно в нём нет необходимости, т.к. предыдущие тесты на проверку ограничения на уникальности каждого атрибута по отдельности.

**Comment by YuriSilenok** [comment]
> @YuriSilenok . да, но возможно в нём нет необходимости, т.к. предыдущие тесты на проверку ограничения на уникальности каждого атрибута по отдельности.

Все верно, этот тест не нужен

> Проверка добавления полностью некорректных для полей данных

каждый тест должен проверять одну функциональность, думаю с этой функциональностью та же история.

**Comment by bolotovaksenya** [comment]
@YuriSilenok , ошибки учла, исправила

**Comment by YuriSilenok** [comment]
Инвертировать дублирование атрибутов в тестовых сценариях.

**Comment by YuriSilenok** [comment]
Зачтено
