### ISSUE TITLE
Создать кнопку "Удалить дисциплины"

### ISSUE THREAD

**Issue by ZhizhikinIvan** [Students-of-the-city-of-Kostroma/Student-timetable#186]
На форме Дисциплины под таблицей в нижнем правом углу, рядом с кнопкой "Добавить", необходимо добавить кнопу с текстом "Удалить дисциплины". Копка должна быть привязана к нижнему и правому краю формы.

**Comment by YuriSilenok** [comment]
Задача снята

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой не указан дедлайн

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой не указан дедлайн

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой не указан дедлайн

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой не указан дедлайн

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой не указан дедлайн

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой не указан дедлайн

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой не указан дедлайн

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой не указан дедлайн

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой не указан дедлайн

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой не указан дедлайн

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by ZhizhikinIvan** [comment]
Здравствуйте, Юрий Викторович.

Почему вы закрыли задачу #186? Я бы добавил описание, но чуть позже, так
как сейчас занят 2мя другими задачами. Если не сложно откройте её заново и
я добавлю описание.

Жижикин Иван
17-ИДбо-3Б

пт, 3 июл. 2020 г. в 13:31, Юрий Силенок <notifications@github.com>:

**Comment by YuriSilenok** [comment]
![image](https://user-images.githubusercontent.com/14871471/86463796-d9e88780-bd36-11ea-98cd-1a1c9b20f7c1.png)
Эта задача была с вас [снята](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/186#issuecomment-492527431)

**Comment by ZhizhikinIvan** [comment]
Юрий Викторович, если вам не сложно, повесьте её обратно на меня. Описание добавлю, как закончу с остальными двумя задачами (в течении дня). 
И не могли бы вы поконкретней сформулировать условия задачи, где конкретно надо создать эту кнопку "Удалить дисциплины", ведь по идее её можно создать где угодно.

**Comment by YuriSilenok** [comment]
Вы не поняли, эта задача вообще сейчас не требуется и в ближайшем будущем вообще не потребуется.

**Comment by ZhizhikinIvan** [comment]
Тогда не могли бы вы выдать мне другую задачу, для закрытия задолженности по учёбе.
И да, теперь описание подходящее? :D
