### ISSUE TITLE
Разработать сценарии тестирования пригодных для автоматизации модульным тестированием метода Update(Model model) сущности Институт

### ISSUE THREAD

**Issue by Chippa99fm** [Students-of-the-city-of-Kostroma/Student-timetable#187]
[План разработки](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_102).
[Сценарий](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548).
[Ссылка на диаграмму классов](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_0).

**Comment by Chippa99fm** [comment]
Состояние таблицы контроллера | Краткое название [А-Я]{10} | Полное название[А-Я]{1}[а-я]{10},[А-Я]{1}[а-я]{10},[А-Я]{1}[а-я]{10},[А-Я]{1}[а-я]{10} | Директор[А-Я]{1},[а-я]{10} | Название вуза[А-Я]{10}
-- | -- | -- | -- | --
Передача корректных данных при условии что они не дублируют уже существующие значения (полностью отличные атрибуты) | task-187-1 | task-187-1 | task-187-1 | task-187-1
Передача корректных данных при условии, что дублируется один атрибут | task-187-2 | task-187-3 | task-187-4 | task-187-5
Передача корректных данных при условии, что ВУЗ и Институт дублирует уже существующие (дублирование ключа) | task-187-6 | task-187-6 | task-187-1 | task-187-6
Передача корректных данных при условии, что дублируются все атрибуты | task-187-7 | task-187-7 | task-187-7 | task-187-7

**Comment by Chippa99fm** [comment]
@YuriSilenok 
Здравствуйте, проверьте работу по ЛР№4.1, пожалуйста.

**Comment by YuriSilenok** [comment]
Что бы я начал ее проверять, ее нужно перевесить на меня.

**Comment by YuriSilenok** [comment]
**Первая таблица** была не правильно понята. в первом столбе Вы должны описать правило для всей строки. начиная со свторого столбца вы оперируете атрибутами. Например для первой строки "Пустое значение" я бы сказал что нужно написать "ввод пустого значения для одного атрибута"

**Вторая таблица** 
- Вырванивание в ячейке по левому краю
- Ожидаемый результат отновится к конкретному шагу, нужно указывать.
- Не у всех ячеек есть ганицы.

**Comment by YuriSilenok** [comment]
Так не пойдет. Я Вам показал пример, Вы исправили только пример, а остальное?

**Comment by Chippa99fm** [comment]
> Так не пойдет. Я Вам показал пример, Вы исправили только пример, а остальное?

Я исправил название и остальных строк, или пример имел ввиду другое?

**Comment by YuriSilenok** [comment]
Почему здесь говориться только об одном атрибуте? 
> Ввод значения при котором краткое название совпадает с предыдущим значением ячейки

**Comment by Chippa99fm** [comment]
> Почему здесь говориться только об одном атрибуте?
> 
> > Ввод значения при котором краткое название совпадает с предыдущим значением ячейки

А нужно, чтобы говорилось о нескольких? Там же проверяется только то, что будет, если ввести то же самое значение в краткое название

**Comment by YuriSilenok** [comment]
Я не понял Ваше высказывание, давайте с другой стороный посмотрим на все это.
Первая строка (Ввод пустого значения для атрибута) Вы указали один и тот же тест. Допустим Ваш тест не прошел (был получен неожиланный результат), как Вы определите из-за какого "пустого атрибута" Ваш тест не прошел?

**Comment by Chippa99fm** [comment]
То есть для каждого атрибута нужен свой тест?

**Comment by YuriSilenok** [comment]
Не всегда, но да, но количество строк в первой таблице резко сократится.

**Comment by Chippa99fm** [comment]
Здравствуйте, я исправил сценарии.
Спасибо.

**Comment by YuriSilenok** [comment]
> Ввод корректных данных при условии, что краткое название дублирует уже существующие (остальные абрибуты отличны)

Снова не то. Давайте Вы подойдете в понедельник  и мы пообщаемся о том, как это должно быть.

**Comment by YuriSilenok** [comment]
Рассказал на занятии

**Comment by Chippa99fm** [comment]
Здравствуйте, переделал таблицу.
Спасибо.

**Comment by YuriSilenok** [comment]
> Ввод корректных данных при условии что они не дублируют уже существующие значения (полностью отличные атрибуты)

Так куда вы данные вводите?

**Comment by Chippa99fm** [comment]
> > Ввод корректных данных при условии что они не дублируют уже существующие значения (полностью отличные атрибуты)
> 
> Так куда вы данные вводите?

В поля формы ?

**Comment by YuriSilenok** [comment]
> > > Ввод корректных данных при условии что они не дублируют уже существующие значения (полностью отличные атрибуты)
> > 
> > 
> > Так куда вы данные вводите?
> 
> В поля формы ?

А сценарии пишите для модульного тестирования?

**Comment by Chippa99fm** [comment]
> > > > Ввод корректных данных при условии что они не дублируют уже существующие значения (полностью отличные атрибуты)
> > > 
> > > 
> > > Так куда вы данные вводите?
> > 
> > 
> > В поля формы ?
> 
> А сценарии пишите для модульного тестирования?

Пишу их по примеру сценариев из спринтов

**Comment by YuriSilenok** [comment]
А почему сценарии из спринта правильные?

**Comment by Chippa99fm** [comment]
> А почему сценарии из спринта правильные?

Не могу знать. 
Они не правильные ?

**Comment by YuriSilenok** [comment]
я тоже не могу знать, они мной не проверяются.
А те сценарии которые были взяты за образец, они для тестирования через вэбинтерфейс или через модульное тестирование?

**Comment by Chippa99fm** [comment]
> я тоже не могу знать, они мной не проверяются.
> А те сценарии которые были взяты за образец, они для тестирования через вэбинтерфейс или через модульное тестирование?

Модульное тестировани

**Comment by YuriSilenok** [comment]
Здравствуйте,

модульное тестирование не предполагает использование графического интерфейса, это значит что вы не можете что-либо **вводить** куда-либо.

Как Вы думаете, как стоит видоизменить сценарии?

Спасибо,
Юрий

**Comment by Chippa99fm** [comment]
> Здравствуйте,
> 
> модульное тестирование не предполагает использование графического интерфейса, это значит что вы не можете что-либо **вводить** куда-либо.
> 
> Как Вы думаете, как стоит видоизменить сценарии?
> 
> Спасибо,
> Юрий

Вместо "Ввод" написать "Отправка" ?

**Comment by Chippa99fm** [comment]
> Здравствуйте,
> 
> модульное тестирование не предполагает использование графического интерфейса, это значит что вы не можете что-либо **вводить** куда-либо.
> 
> Как Вы думаете, как стоит видоизменить сценарии?
> 
> Спасибо,
> Юрий

Мои сценарии практически идентичны сценариям моих одногруппников, у них так же модульное тестирование. Не понимаю, что нужно видоизменить..

**Comment by YuriSilenok** [comment]
> Мои сценарии практически идентичны сценариям моих одногруппников, у них так же модульное тестирование.

Я все же стал говорить что их работы являются эталоном и могут быть использованы для образа.
Это так не работает, главное здесь логика.
Я хотчу донести что вы не вводите какие-либо значеня, а передаете их в конструктор, методы и т.д.
Ориентируйтесь на то, что эти сценарии должны быть автоматизированы.

Спасибо,
Юрий

**Comment by Chippa99fm** [comment]
> > Мои сценарии практически идентичны сценариям моих одногруппников, у них так же модульное тестирование.
> 
> Я все же стал говорить что их работы являются эталоном и могут быть использованы для образа.
> Это так не работает, главное здесь логика.
> Я хотчу донести что вы не вводите какие-либо значеня, а передаете их в конструктор, методы и т.д.
> Ориентируйтесь на то, что эти сценарии должны быть автоматизированы.
> 
> Спасибо,
> Юрий

Сделал поправку на то, что мы не вводим данные, а передаём их в конструктор.
Спасибо,
Михайлов Василий

**Comment by YuriSilenok** [comment]
Здравствуйте, @Chippa99fm 

>  -Краткое название:"ИПП"->"ИВТ"

Никаких рекомендаций по кодированию сценариев нет. Я видел подобное сокращение и указывал на эту ошибку, пожалуйста, опишите по шагам что это значит.

Спасибо, 
Юрий

**Comment by Chippa99fm** [comment]
> Здравствуйте, @Chippa99fm
> 
> > -Краткое название:"ИПП"->"ИВТ"
> 
> Никаких рекомендаций по кодированию сценариев нет. Я видел подобное сокращение и указывал на эту ошибку, пожалуйста, опишите по шагам что это значит.
> 
> Спасибо,
> Юрий

Берём и при изменении данных передаём краткое название "ИВТ" на замену краткому названию "ИПП"

**Comment by YuriSilenok** [comment]
Здравствуйте, @Chippa99fm

> Берём и при изменении данных передаём краткое название "ИВТ" на замену краткому названию "ИПП"

Это вопрос?

Спасибо,
Юрий

**Comment by Chippa99fm** [comment]
> Здравствуйте, @Chippa99fm
> 
> > Берём и при изменении данных передаём краткое название "ИВТ" на замену краткому названию "ИПП"
> 
> Это вопрос?
> 
> Спасибо,
> Юрий

Вы же попросили указать, что это значит. Я и указал.

**Comment by YuriSilenok** [comment]
Здравствуйте, @Chippa99fm

Уточняю, это нужно расписать в тестовых сценариях.

Спасибо,
Юрий

**Comment by Chippa99fm** [comment]
> Здравствуйте @Chippa99fm
> 
> Уточняю, это нужно расписать в тестовых сценариях.
> 
> Спасибо,
> Юрий

И везде, где есть такая стрелочка, означающая замену - нужно это расписать????

**Comment by Chippa99fm** [comment]
Здравствуйте, @YuriSilenok 

Извините, но почему такое должен расписывать только я, если у моих одногруппников стоят такие же обозначения замены без уточнений. 
Сжальтесь...

**Comment by YuriSilenok** [comment]
Здравствуйте @Chippa99fm 

Видимо потому что они реализовали эти сценарии в спринте,
а вы делаете ЛР04 и сдаете ее мне.

Не думаю что среди сданных лабораторных работ найдутся те, которые содержат такие же ошибки.

Вы знаете как проверить, сдан тот сценарий который бал взят за образец?

Спасибо,
Юрий.

**Comment by Chippa99fm** [comment]
Здравствуйте, @YuriSilenok

Нет, не знаю :c

Спасибо,
Михайлов Василий

**Comment by YuriSilenok** [comment]
Здравствуйте, @Chippa99fm 

Каждый сценарий имеет уникальный номер который формируется из номера задачи на его разработку.
Например сценарий который разработан выше Вашего ` task-26`
Эти суенарии соджержат точно такие же сокращения как у Вас, вероятно он и стал образцом.
Смотрим на задачу этих сценариев #26 и видим что она открыта
Кстати обратите внимание, что он идет по тем же ошибкам что и Вы, но вы ушли гораздо дальше.

Спасибо, 
Юрий.

**Comment by Chippa99fm** [comment]
Здравствуйте.
Я заменил в сценариях символ "->"
Спасибо.
Михайлов Василий.

**Comment by Chippa99fm** [comment]
> Здравствуйте, @Chippa99fm
> 
> Уточняю, это нужно расписать в тестовых сценариях.
> 
> Спасибо,
> Юрий

Здравствуйте, @YuriSilenok

Всё готово!

Спасибо,
Михайлов Василий

**Comment by YuriSilenok** [comment]
Здравствуйте, @Chippa99fm

разбираем этот сценарий
```
1.Создать обхект класс Minstitute 
 2.Предать в него атрибуты: 
 - краткое название:"ИПП"
  -Полное название:"Институт Педагогики и Психологии"
  -Директор:"Михайлов В.А."
 -Название вуза:"КГУ" 
 3.Вызвать метод Update(Model model) класса Cinstitute,передав в него созданный объект класса Minstitute
 4. Заменить: 
 -Краткое название:"ИПП" Заменяем на "ИВТ"
  -Полное название:"Институт Педагогики и Психологии" Заменяем на "Институт Вычислительной техники"
  -Директор:"Шварцнегер В.А." Заменяем на "Иванов .С.П"
 -Название вуза:"КГУ" Заменяем на "МГУ"
```
Как программно Вы представляете 4 шаг. Мне все равно непонячтно что нужно сделать при автоматизации под словом заменить? И какой Вы от этого ожидаете результат?

**Comment by Chippa99fm** [comment]
> Здравствуйте, @Chippa99fm
> 
> разбираем этот сценарий
> 
> ```
> 1.Создать обхект класс Minstitute 
>  2.Предать в него атрибуты: 
>  - краткое название:"ИПП"
>   -Полное название:"Институт Педагогики и Психологии"
>   -Директор:"Михайлов В.А."
>  -Название вуза:"КГУ" 
>  3.Вызвать метод Update(Model model) класса Cinstitute,передав в него созданный объект класса Minstitute
>  4. Заменить: 
>  -Краткое название:"ИПП" Заменяем на "ИВТ"
>   -Полное название:"Институт Педагогики и Психологии" Заменяем на "Институт Вычислительной техники"
>   -Директор:"Шварцнегер В.А." Заменяем на "Иванов .С.П"
>  -Название вуза:"КГУ" Заменяем на "МГУ"
> ```
> 
> Как программно Вы представляете 4 шаг. Мне все равно непонячтно что нужно сделать при автоматизации под словом заменить? И какой Вы от этого ожидаете результат?

4. Заменить:
Создаётся новй объект класса MUniversity и ему присваивается модель, поступающая на вход метода. После чего находим строку с нашм ВУЗом в таблице по ИНН.

Создаём новый объект класса DataRow.
- Передаём в столбец "Краткое название" новое название "ИВТ" на замену "ИПП".
- Передаём в столбец "Полное название" новое название "Институт Вычислительной техники" на замену "Институт Педагогики и Психологии".
- Передаём в столбец "Полное имя ректора" новое имя "Иванов .С.П" на заммену "Шварцнегер В.А"
 
- Передаём в столбец "Название ВУЗа" новое название "МГУ" на замену "КГУ"

**Comment by YuriSilenok** [comment]
Кажется что-то пошло не так.
Можете предоставить код для этого сценария?

**Comment by Chippa99fm** [comment]
Здравствуйте.
1 создаем модель Институт
MInstitute inst = new MInstitute("ИАСТ", "Институт Автоматизированных систем и технологий", "Шварцнегер В.А.", "КГУ");
2 Вызываем метод Insert и передаем в него нашу модель 
СInstitute g = new СInstitute ();
g.Insert(inst);
3 Изменяем ФИО ректора
inst.Namerektor="Иванов И.И";
4 Вызываем метод Update
g.Update(inst);
Будет примерно как-то так 
Спасибо.

**Comment by Chippa99fm** [comment]
@YuriSilenok , здравствуйте!
Я сделал. Проверьте, пожалуйста !

**Comment by YuriSilenok** [comment]
Ответил устно

**Comment by Chippa99fm** [comment]
@YuriSilenok , здравствуйте!
Я устранил выявленные вами недочёты и жду проверки.

**Comment by YuriSilenok** [comment]
-  5.Вызвать метод Update(Model model) класса Cinstitute,передав в него созданный объект класса Minstitute

Созданный объект в каком шаге?
- Какой ожидаемый результат к шагу 5?

**Comment by YuriSilenok** [comment]
4 и 5 шаги удалить

**Comment by YuriSilenok** [comment]
Зачтено
