### ISSUE TITLE
Автоматизация тестирования юнит-тестами для метода Update(Model model) сущности Group

### ISSUE THREAD

**Issue by DariaMann** [Students-of-the-city-of-Kostroma/Student-timetable#19]
[План разработки](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_102)
[Сценарий](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)
[Ссылка](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit) на диаграмму классов

**Comment by DariaMann** [comment]
План разработки

**Comment by YuriSilenok** [comment]
Здравствуйте.
Зачтено.
Спасибо.
