### ISSUE TITLE
Автоматизация unit-test метода Insert(Model model) сущности ВУЗ

### ISSUE THREAD

**Issue by MihailBobylev** [Students-of-the-city-of-Kostroma/Student-timetable#190]
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548) task-166

**Comment by YuriSilenok** [comment]
Выполнено #614
