### ISSUE TITLE
Автоматизация unit-test метода Insert(Model model) сущности Преподаватель

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Student-timetable#196]
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548) task-#13

**Comment by YuriSilenok** [comment]
Зачтено
