### ISSUE TITLE
Разработать сценарии тестирования конструктора CTeacher() : base("Преподаватель") для класса CTeacher унаследованного от класса Controller

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#2]
Реализовать сценарии пригодные для Unit-тестирования в [эту](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548) таблицу 
[План разработки](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit?usp=sharing)
[Ссылка](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit?usp=sharing) на диаграмму классов.

**Comment by itword7111** [comment]
Здравствуйте, что нужно писать в сценарии?

**Comment by itword7111** [comment]
мне писать следующий сценарий после 4 сценариев тут https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548 
?

**Comment by itword7111** [comment]
мне писать следующий сценарий после 4 сценариев тут - https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548
?

**Comment by YuriSilenok** [comment]
Здравствуйте.
Задание было выдано месяц назад.
Оно уже потеряло свою актуальность.
Поправьте свой комментарий так, что бы ссылка не отображала URL.
Думаю мы с Вами пойдем несколько другим путем.
Так как на задачи Вы реагируете долго, то Вы будете поднимать баги.
В [этом](https://drive.google.com/open?id=1k8ILnmYVi3Cz-mTge3h6RI0OV4DbAHviQseScRRpUxI) документе Вы можете ознакомиться с некоторым описанием того, как поднять задачу. Здесь важна специфика. 
Ознакомьтесь с  пониманием того что такое баг, из [этой](https://drive.google.com/file/d/1n-DpaZU-doYNRxV_nKp6YjdgwG-Typcu/view) книги.
И как образец бага, можете прочесть вот [эту](http://www.protesting.ru/testing/bugwriting.html) статью.
**ИТОГ:** Вы должны исследовать ПО и найти дефекты и поднять на них баги. 1 баг -  1 балл. Не забывайте смотреть уже поднятые баги. Все баги помечены меткой Bug. Поиск дефектов производить на ветке **Testing**.
Спасибо.

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу
