### ISSUE TITLE
Автоматизация тестирования юнит-тестами для класса MDiscipline

### ISSUE THREAD

**Issue by MihailBobylev** [Students-of-the-city-of-Kostroma/Student-timetable#20]
[План разработки](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_102).
[Сценарий](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548).
[Ссылка](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit) на диаграмму классов.

**Comment by YuriSilenok** [comment]
Здравствуйте.
Судя по Вашему заголовку, у Вас поднята задача на поднятие задачи. Я вам такую задачу ставил в письме, Вы соответственно должны задачу поднять на автоматизацию.
Почему Вы выставили метки Controller и Model?
Спасибо.

**Comment by YuriSilenok** [comment]
Я просил пояснить почему вы выставили метки Controller и Model, а не удалять их. Вопрос тогда второй, почему вы удалили эти метки?

**Comment by MihailBobylev** [comment]
Удалил из-за неправильно понятой задачи.  
Нам не нужен Controller, так как, если задача имеет цель разработки конструктор, метод вставки, метод обновления или удаления, то задача должна быть помечена меткой Controller, а у меня такого задания нет, а Model нужен, так как, если упомянут класс который начинается с большой буквы M, то задача должна быть помечена меткой Model.

**Comment by YuriSilenok** [comment]
Зачтено
