### ISSUE TITLE
Разработать сценарии тестирования пригодных для автоматизации модульным тестированием метода Insert(Model model) сущности Вид занятия

### ISSUE THREAD

**Issue by KudelinRoman** [Students-of-the-city-of-Kostroma/Student-timetable#203]
[План разработки](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_102)
[Ссылка на диаграмму классов](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_0)
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)

**Comment by KudelinRoman** [comment]
Состояние таблицы контроллера | Вид занятия сокращенное [[[А-Я]{1}[а-я]{1,5}.] or [[а-я]{1,5}.]] | Вид занятия полное [[[А-Я]{1}[а-я]{1,50}] or [[А-Я]{1}[а-я]{1,50} [А-Я]{1}[а-я]{1,50}]]
-- | -- | --
Ввод данных в пустую таблицу | task-203-1 | task-203-1
Ввод корректных данных в таблицу при условии, что атрибуты не дублируются | task-203-1 | task-203-2
Ввод корректных данных в таблицу при условии, что все атрибуты дублируются | task-203-3 | task-203-3
Ввод корректных данных в таблицу при условии, что дублируется только один атрибут | task-203-4 | task-203-5

**Comment by YuriSilenok** [comment]
зачтено
