### ISSUE TITLE
Привести имена столбцов в соответствие с программой

### ISSUE THREAD

**Issue by map82top** [Students-of-the-city-of-Kostroma/Student-timetable#204]
Изменить название столбцов и добавить недостающие во View(на форме), изменить и добавить соответствующие поля в Model. Изменить затронутый код в Controller.
Группа должна содержать следующие поля:

1.   Группа(string)
2.   Семестр(ushort)
3.   Направление подготовки(string)
4.   Смена(ushort)
5.   Студентов(ushort)
6.   Пар/день min(ushort)
7.   Пар/день max(ushort)
8. Выходные(string)

Преподаватели должна содержать следующие поля:

1.  Ф.И.О(string)
2.  Примечание(string)
3.  Кафедра(string)
4.  Метод. дни(string)
5.  Окна(string)
6.  Выходные(string)

**Comment by map82top** [comment]
Для выполнения задачи создай отдельную ветку от 17-ISbo-2b по шаблону, как мы делали. Как сделаешь делаешь запрос на мерж по тому же шаблону

**Comment by Chippa99fm** [comment]
Метод. дни - методические дни?
Нашли ,блин, где сокращения использовать
