### ISSUE TITLE
"Дисциплины",не создается новая дисциплина

### ISSUE THREAD

**Issue by itword7111** [Students-of-the-city-of-Kostroma/Student-timetable#205]
Когда заходишь в "Справочники", затем выбираешь "Дисциплины",при попытке создать дисциплину заполнив наименование и шифр, выводится сообщение о том что дисциплина не создана.
Шаги для реализации бага:
 1.Перейти по меню Справочники-Дисциплины
 2.Ввести в поле "Шифр дисциплины" - "Б1.Б.36"
 3.Ввести в поле "Наименование дисциплины" - "Информационные системы"
 4.Создать дисциплину
Название ветки: Testing
Ожидаемый результат:
 Создается новая дисциплина в справочнике "Дисциплины".
Фактический результат:
 Новая дисциплина не создается.
![Снимок5](https://user-images.githubusercontent.com/38357886/55503484-677e8880-5657-11e9-8166-2a49598fb882.PNG)

**Comment by YuriSilenok** [comment]
@itword7111 зачтено

**Comment by YuriSilenok** [comment]
Причина закрытия, где протестировано?

**Comment by YuriSilenok** [comment]
Возможные варианты Ваших комментариев к багу могут быть:
> Баг не воспроизводится в спринте 17-ISbo-2b-4

> Баг воспроизвелся в спринте 17-ISbo-2b-5

**Comment by DariaMann** [comment]
Баг не воспроизводится в спринте 17-ISbo-2a-4

**Comment by YuriSilenok** [comment]
Укажите веху 4 спринта
