### ISSUE TITLE
В справочнике "Преподаватели", создается пустая запись

### ISSUE THREAD

**Issue by itword7111** [Students-of-the-city-of-Kostroma/Student-timetable#206]
Шаги реализации бага:
1.В "Справочники" выбрать "Преподаватели".
2.Добавить преподавателя с заполненными по умолчанию полями, нажав "Создать и очистить".
3.Добавить преподавателя не заполняя поля.
Название ветки: Testing
Ожидаемый результат:
Второй преподаватель не создается, выводится сообщение о неправильном заполнении полей.
Фактический результат:
Создается пустая запись в справочнике "Преподаватели".
![Снимок6](https://user-images.githubusercontent.com/38357886/55504241-1c657500-5659-11e9-8d9f-47ff695c5b2d.PNG)

**Comment by YuriSilenok** [comment]
Зачтено

**Comment by map82top** [comment]
В ветке 17-ISbo-2b-6 баг не воспроизводится

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
