### ISSUE TITLE
Разработать сценарии тестирования пригодных для автоматизации модульными тестами для метода Delete(Model model) сущности Group

### ISSUE THREAD

**Issue by ZhezlovaDaria** [Students-of-the-city-of-Kostroma/Student-timetable#21]
[План разработки](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_102).
[Сценарий](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548).
[Ссылка](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_0) на диаграмму классов.

**Comment by YuriSilenok** [comment]
Здравствуйте.
Могли бы Вы обосновать такой набор меток?
Спасибо.

**Comment by ZhezlovaDaria** [comment]
Здравствуйте.

Метка "Delete(Model model)" относиться к методу, для которого необходимо написание сценария тестов.
Метка "Group" относиться к сущности.
Метка "Unit test" так как требуется автоматизация unit-test'a.
Метка "Auto test" как следствие предыдущего пункта: требуется автоматизация.

Метка Model была лишней.

Спасибо.

**Comment by YuriSilenok** [comment]
Противоречит ли состояние меток вот этому высказыванию из инструкции?
> Если задача имеет цель разработки конструктор, метод вставки, метод обновления или удаления, то задача должна быть помечена меткой Controller. Если задача ставиться на автоматизацию тестирования, то указывается метка Auto-test.

**Comment by ZhezlovaDaria** [comment]
Здравствуйте.

Да, противоречит.
Поняла, что допустила ошибку и метка "Auto test" здесь не требуется, так как целью является не сама автоматизация, однако требуется метка "Controller".
Так же добавила метку "Script", так как требуется написание сценариев.

Спасибо.

**Comment by YuriSilenok** [comment]
Зачтено

**Comment by YuriSilenok** [comment]
@isengrims Вы занимаетесь этой задачей?

**Comment by purplegen** [comment]
Да

**Comment by purplegen** [comment]
Состояние таблицы контроллера | Группа [[0-9]{2}-[А-Я]{2}[а-я]{2}-[0-9]{1}[а-я]{1}] | Семестр [1-2]{1} | Профиль подготовки [А-я]{1-256}[а-я]{0-256} | Смена [1-2]{1} | Студентов [0-50] | Пар/день min [0-6] | Пар/день max [1-6] | Выходные [А-Я]{1}[а-я]{1-10}
-- | -- | -- | -- | -- | -- | -- | -- | --
Удалить запись при совпадении всех атрибутов | task-21-1 | task-21-1 | task-21-1 | task-21-1 | task-21-1 | task-21-1 | task-21-1 | task-21-1
Удалить запись при совпадении только одного атрибута | task-21-2 | task-21-3 | task-21-4 | task-21-5 | task-21-6 | task-21-7 | task-21-8 | task-21-9
Удаление не существующих данных из таблицы | task-21-10 | task-21-10 | task-21-10 | task-21-10 | task-21-10 | task-21-10 | task-21-10 | task-21-10

**Comment by YuriSilenok** [comment]
@Students-of-the-city-of-Kostroma/17isb Поясните пожалуйста, почему Ваша команда не реализовала эту задачу во втором спринте?

**Comment by purplegen** [comment]
@YuriSilenok Здравствуйте

Скажите мне пожалуйста недочеты по сценариям, я делаю это для ЛР4.1

Спасибо

**Comment by YuriSilenok** [comment]
@isengrims здравствуйте,

у вас не было активности с 22 марта, обычно я снимаю задачи через неделю или две, в вашем случае есть фактор везения, я ее не заметил. 
Если окажется что эти сценарии уже существуют,  то окажется уже не нуждается в исполнении.

Так что, жду ответа от тимлида или старшего тестировщика.

Спасибо,
Юрий

**Comment by purplegen** [comment]
@YuriSilenok эти сценарии уже существуют. Как видите не очень корректно (если я могу так говорить)

![image](https://user-images.githubusercontent.com/45204879/58343051-c5ab3900-7e5a-11e9-9aec-1d1a970a82c9.png)

Спасибо

**Comment by KharlamovaAlexandra** [comment]
Добрый вечер, @YuriSilenok 

По неопытности  не была ( поднята новая/ замечена существующая ) задача на написание сценариев отдельно, но есть задача #316  реализованная в Sprint2  в ходе которой задание было выполнено

С уважением,
тимлид

**Comment by YuriSilenok** [comment]
Проверю, так как сценарии реализованные в спринте не покрывают необходимую функциональность.

**Comment by YuriSilenok** [comment]
Добрый день @isengrims 

- task-21-2 Удалить запись при совпадении поля "Группа"
Дело в том, что кроме группы у Вас совпадают и другие атрибуты, а должна только группа.

В остальном все хорошо. Перепроверьте сценарии на предмет совпадения только одного атрибута.

Спасибо,
Юрий

**Comment by purplegen** [comment]
Добрый день

Сделано @YuriSilenok 

Спасибо, 
Денис Плотников 
17-ИСбо-2б

**Comment by YuriSilenok** [comment]
Зачтено
