### ISSUE TITLE
Разработка нумерации строк в таблице Teachers

### ISSUE THREAD

**Issue by map82top** [Students-of-the-city-of-Kostroma/Student-timetable#210]
Для столбцов указанных в #204  Для данной таблице сделать, чтобы было вот так в режиме конструктора. В качестве примера использовать таблицу из ветки Testing
![image](https://user-images.githubusercontent.com/36793054/55398778-0d47cf80-5552-11e9-880c-fc55a3b1b2c2.png)

Скрыть столбец по умолчанию:"Чтобы скрыть первый столбец, вы можете установить RowHeadersVisible значение false вашего dataGrid"
Добавить еще один столбец у которого нет названия для нумерации строк
Перенумерацию производить в методе Insert и Remove соответствующего контроллера
В методе Inset просто присвоение последующего числа, а в Remove полная перенумерация всей таблицы.
Cделать возможным только выбор целой строки а не одной ячейки(свойство DataGrid)

Для выполнения задачи создается отдельная ветка от 17-ISbo-2b по шаблону, как мы делали. Перед созданием запроса на мерж убедиться, что проект запускается!
Запрос на мерж делается по тому же шаблону.

**Comment by map82top** [comment]
Для примера используй то что сделал Денис #212

**Comment by SamuraSwordS** [comment]
#213
