### ISSUE TITLE
Реализовать метод Delete(Model model) сущности Group унаследованного от класса Controller

### ISSUE THREAD

**Issue by Parallusion** [Students-of-the-city-of-Kostroma/Student-timetable#22]
[Диаграмма классов](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit?usp=sharing) представлена по ссылке. 

**Алгоритм поведения** 
Если поле шифр(cipher) есть в списке, то метод удаляет переданную группу. 
Если произошло удаление из таблицы, то метод вернёт истину, в других случаях - ложь.

**Comment by YuriSilenok** [comment]
Зачтено

**Comment by YuriSilenok** [comment]
Здравствуйте @KharlamovaAlexandra 
Это ваша задача к ЛР03
Спасибо.

**Comment by YuriSilenok** [comment]
Ошибочно поднято.
