### ISSUE TITLE
Автоматизация unit-test для метода Delete(Model model) сущности Group

### ISSUE THREAD

**Issue by bormolei** [Students-of-the-city-of-Kostroma/Student-timetable#23]
[Сценарий](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548).
[План разработки](https://docs.google.com/spreadsheets/d/11uPdKMmzZklleijGcBAKoStnVHY2_9qBwRPOpR1y0vM/edit#gid=389498935)
[Диаграмма классов.](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit)

**Comment by YuriSilenok** [comment]
Здравствуйте.
Ошибка в том что у вас поднята задача для создания задачи, а нужно было создать задачу на автоматизацию.
Могли бы обосновать почему не нужно другие метки добавлять?
А так же я не увидел у Вас веху
Спасибо.

**Comment by bormolei** [comment]
Добавил метку auto-test, так как автоматизация тестирования

**Comment by YuriSilenok** [comment]
Я бы сказал что еще одной метки не хватает

**Comment by bormolei** [comment]
Добавил метку Controller , так как идет парой с меткой Delete.

**Comment by YuriSilenok** [comment]
Зачтено
