### ISSUE TITLE
При открытии справочника "Ученые звания", открываются 2 формы

### ISSUE THREAD

**Issue by itword7111** [Students-of-the-city-of-Kostroma/Student-timetable#230]
Шаги реализации бага:
1.В "Справочники" выбрать "Ученые звания".
Название ветки: Testing
Ожидаемый результат:
 Появляется форма справочника "Ученые звания". 
![image](https://user-images.githubusercontent.com/38357886/55510440-f6df6800-5666-11e9-9e97-5f47affbc91b.png)

Фактический результат:
 Появляется 2 формы справочника "Ученые звания". 
![image](https://user-images.githubusercontent.com/38357886/55510580-41f97b00-5667-11e9-9d4d-7515dc786868.png)

**Comment by YuriSilenok** [comment]
@itword7111 Зачтено

**Comment by Takunava** [comment]
Баг не воспроизводиться в ветке Alliance-4, так как там актуальная версия нашей работы
