### ISSUE TITLE
При открытии справочника "Ученые степени", открываются 2 формы

### ISSUE THREAD

**Issue by itword7111** [Students-of-the-city-of-Kostroma/Student-timetable#231]
Шаги реализации бага:
1.В "Справочники" выбрать "Ученые степени".
Название ветки: Testing
Ожидаемый результат:
Появляется форма справочника "Ученые степени".
![image](https://user-images.githubusercontent.com/38357886/55510900-fd221400-5667-11e9-9f6a-a85420e85e35.png)

Фактический результат:
Появляется 2 формы справочника "Ученые степени".
![image](https://user-images.githubusercontent.com/38357886/55510866-e5e32680-5667-11e9-8ef6-61ed18e573a0.png)

**Comment by YuriSilenok** [comment]
@itword7111 зачтено

**Comment by YuriSilenok** [comment]
@PopovMilan почему вы сбросили эту задачу?

**Comment by PopovMilan** [comment]
@YuriSilenok Были тогда не совсем в теме по поводу задач-клонов. #301 Таск, который был поднят в нашем спринте, а данный был сброшен без пометки клон и ссылки на новый таск. Я правильно понял что нужно сделать?
