### ISSUE TITLE
При нажатии "Удалить" в справочнике "Преподаватели", когда фокус не находится на данных преподавателя, программа терпит крах

### ISSUE THREAD

**Issue by itword7111** [Students-of-the-city-of-Kostroma/Student-timetable#232]
Шаги реализации бага:
 1.В справочнике "Преподаватели" создать преподавателя с незаполненным полем -"Ученое звание".
![image](https://user-images.githubusercontent.com/38357886/55513909-82f58d80-566f-11e9-9cbb-808407b269c0.png)

 2.Создать еще двух преподавателей.
![image](https://user-images.githubusercontent.com/38357886/55513950-96085d80-566f-11e9-97f2-ff016173279a.png)
 3.Нажать на на поле преподавателя - "Ученое звание". Не нажимать на поля первого преподавателя.
![image](https://user-images.githubusercontent.com/38357886/55514283-568e4100-5670-11e9-92f8-4767de5d1602.png)
4.Нажать "Удалить"
![image](https://user-images.githubusercontent.com/38357886/55514303-660d8a00-5670-11e9-85c6-627b231f13f6.png)
5.Нажать на самое левое поле от второго преподавателя
![image](https://user-images.githubusercontent.com/38357886/55514423-b84eab00-5670-11e9-9431-d595540de4a4.png)
6.Нажать "Удалить"
![image](https://user-images.githubusercontent.com/38357886/55514453-cef50200-5670-11e9-8d50-421849dfced2.png)
7.Нажать "Удалить"
![image](https://user-images.githubusercontent.com/38357886/55514475-e03e0e80-5670-11e9-82da-326caff34f9c.png)

Название ветки: Testing
Ожидаемый результат:
 Когда фокус не находиться на преподавателе кнопка "Удалить", должна быть заблокирована.
 Фактический результат:
Программа терпит крах.
![image](https://user-images.githubusercontent.com/38357886/55514475-e03e0e80-5670-11e9-82da-326caff34f9c.png)

**Comment by YuriSilenok** [comment]
@itword7111 Зачтено

**Comment by map82top** [comment]
Баг устарел

**Comment by YuriSilenok** [comment]
Что значит баг устарел?
Он воспроизводится или не воспроизводится на каком-то спринте (ветке)

**Comment by MaximTrapeznikov** [comment]
закрыто, так как баг не актуален

**Comment by YuriSilenok** [comment]
@MaximTrapeznikov @map82top 
Вы меня не услышали.
Возможные варианты Ваших комментариев к багу могут быть:
> Баг не воспроизводится в спринте  17-ISbo-2b-4

> Баг воспроизвелся в спринте  17-ISbo-2b-5

**Comment by MaximTrapeznikov** [comment]
Баг не воспроизводится в спринте 17-ISbo-2b-5
