### ISSUE TITLE
В справочнике "Преподаватели" в поля где должны быть только буквы русского алфавита, ' ' и '-', можно ввести любые символы

### ISSUE THREAD

**Issue by itword7111** [Students-of-the-city-of-Kostroma/Student-timetable#233]
Шаги реализации бага:
 1.Нажать кнопку "Добавить" в справочнике "Преподаватели".
 2.Удалить строку в поле "Ученое звание"
![image](https://user-images.githubusercontent.com/38357886/55516515-15009480-5676-11e9-99c1-3e50ca3992f6.png)

 3.Скопировать строку "6g+ā "
 4.Вставить строку во все поля
![image](https://user-images.githubusercontent.com/38357886/55516587-52652200-5676-11e9-9e58-09821bb07a42.png)
 5.создать преподавателя
![image](https://user-images.githubusercontent.com/38357886/55516623-6c9f0000-5676-11e9-9b73-6fb28bf7b4ae.png)
Ожидаемый результат:
Недопустимые символы после вставки удаляются.
Фактический результат:
Недопустимые символы остаются
![image](https://user-images.githubusercontent.com/38357886/55516623-6c9f0000-5676-11e9-9b73-6fb28bf7b4ae.png)
Название ветки: Testing

**Comment by YuriSilenok** [comment]
@itword7111 Зачтено

**Comment by MaximTrapeznikov** [comment]
закрыто, так как баг не актуален

**Comment by YuriSilenok** [comment]
Возможные варианты Ваших комментариев к багу могут быть:
> Баг не воспроизводится в спринте 17-ISbo-2b-4

> Баг воспроизвелся в спринте 17-ISbo-2b-5

**Comment by MaximTrapeznikov** [comment]
Баг не воспроизводится в спринте 17-ISbo-2b-5
