### ISSUE TITLE
В "Справочники", Справочники -> в меню "Редактировать запись" и "Добавить запись", не работает кнопка "Отмена"

### ISSUE THREAD

**Issue by itword7111** [Students-of-the-city-of-Kostroma/Student-timetable#238]
Шаги реализации бага:
 1.В "Справочники" в выпадающем списке навести на "Справочнике" и нажать "Редактировать запись"
 2.В открывшемся меню нажать отмена.
![image](https://user-images.githubusercontent.com/38357886/55574980-7415e600-5716-11e9-9b5e-bc3aa931d81e.png)
Ожидаемый результат:
Окно "Редактировать запись" закроется.
Фактический результат:
Окно "Редактировать запись" останется без изменений.

**Comment by YuriSilenok** [comment]
Справочник-справочник, это заглушки, их не тестируйте, они так и должны работать, в место этого лучше поднемите задачу на улучшение с меткой improvment, что бы удалили формы редактирования/добавления записи из проекта.

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
