### ISSUE TITLE
Разработать сценарий тестирования для автоматизации модульного тестирования для класса MDiscipline

### ISSUE THREAD

**Issue by Jeen99** [Students-of-the-city-of-Kostroma/Student-timetable#24]
Написать сценарий тестирования пригодных для автоматизации unit-test для класса MDiscipline.
[Таблица](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)
[План разработки](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4dd88760eb_0_128)
[Диаграмма классов](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit)

**Comment by YuriSilenok** [comment]
Зачтено

**Comment by YuriSilenok** [comment]
@
