### ISSUE TITLE
В справочнике "Преподаватели" при обычном заполнении с клавиатуры полей преподавателя, возможно ввести текст так, чтобы заглавная буква была не в начале строки

### ISSUE THREAD

**Issue by itword7111** [Students-of-the-city-of-Kostroma/Student-timetable#241]
Шаги реализации бага:
1.Нажать кнопку "Добавить" в справочнике "Преподаватели".
2.Удалить строку в поле "Имя"
3.Нажать на другое поле и ввести строчную букву "м" в начале строки, сделать тоже самое со всеми полями кроме где должна быть строка, поле "Имя" можно не вводить "м" и вводить после того как ввели "м" во все другие поля
![image](https://user-images.githubusercontent.com/38357886/55576785-bb9e7100-571a-11e9-9236-d2bafdb347a1.png)
Ожидаемый результат:
Все первые буквы введенных строк становятся заглавными, все остальные буквы, если перед ними нет символов - " "или"-" становятся строчными .
Фактический результат:
Первые строчные буквы строк остаются без изменений(кроме поля где удаляли строку), заглавные буквы, находящиеся не в начале строки остаются без изменения 
![image](https://user-images.githubusercontent.com/38357886/55577356-171d2e80-571c-11e9-8a46-cbce91df2c32.png)

**Comment by YuriSilenok** [comment]
@itword7111 Зачтено.

**Comment by YuriSilenok** [comment]
В каком спринте этот баг был исправлен?

**Comment by map82top** [comment]
В этом

**Comment by YuriSilenok** [comment]
Все таски запланированные на спринт должны иметь веху спринта.
