### ISSUE TITLE
В справочнике "Преподаватели" при увеличении размеров самого правого пустого поля, поле  "Размер педагогического стажа" отображается не правильно

### ISSUE THREAD

**Issue by itword7111** [Students-of-the-city-of-Kostroma/Student-timetable#243]
Шаги реализации бага:
1.В "Справочники" выбрать "Преподаватели".
2.Растянуть правое поле
![image](https://user-images.githubusercontent.com/38357886/55578498-c1965100-571e-11e9-9006-bb9391d08570.png)
Ожидаемый результат:
При перемещении каретки, которая находится внизу в право до упора поле "Размер педагогического стажа" отображается так, что можно прочитать название поля и значение в нем.
Фактический результат:
поле  "Размер педагогического стажа" отображается не правильно
![image](https://user-images.githubusercontent.com/38357886/55578711-34073100-571f-11e9-8e59-ee7a8ff88ecd.png)

**Comment by YuriSilenok** [comment]
@itword7111 Зачтено

**Comment by map82top** [comment]
Баг устарел

**Comment by YuriSilenok** [comment]
Баг может воспроизводится или не воспроизводится на каком-то спринте (ветке)
Прежде чем приступить к исправлениям бага, тестировщик должен указать на какой версии ПО он его проверил. В нашем случае мы указываем спринт (ветку) на которой тестировался баг. Как правило это последний завершенный спринт. После этого разработчики приступают к его исправлению. После этого тестировщики могут проверить этот баг или на ветке текущего спринта. Желательно что бы тестировщик не лез в ветки предназначенные для тасков.

**Comment by MaximTrapeznikov** [comment]
закрыто, так как баг не актуален

**Comment by YuriSilenok** [comment]
Возможные варианты Ваших комментариев к багу могут быть:
> Баг не воспроизводится в спринте 17-ISbo-2b-4

> Баг воспроизвелся в спринте 17-ISbo-2b-5

**Comment by MaximTrapeznikov** [comment]
Баг не воспроизводится в спринте 17-ISbo-2b-5
