### ISSUE TITLE
В справочнике "Министерства" при увеличении размеров самого правого пустого поля, поле "Описание" отображается не правильно

### ISSUE THREAD

**Issue by itword7111** [Students-of-the-city-of-Kostroma/Student-timetable#244]
Шаги реализации бага:
1.В "Справочники" выбрать "Министерства".
2.Растянуть левый столбец
![image](https://user-images.githubusercontent.com/38357886/55579087-230aef80-5720-11e9-8d4b-c0caa8970869.png)

Ожидаемый результат:
При перемещении каретки, которая находится внизу в право до упора поле "Описание" отображается так, что можно прочитать название поля.
Фактический результат:
поле "Описание" отображается не правильно
![image](https://user-images.githubusercontent.com/38357886/55579105-3027de80-5720-11e9-88b9-c9f13f366c23.png)

**Comment by YuriSilenok** [comment]
Я могу ошибаться, но Вы растягивали левый столбец?

**Comment by itword7111** [comment]
исправил

**Comment by YuriSilenok** [comment]
@itword7111 зачтено

**Comment by YuriSilenok** [comment]
При изменении размеров формы все столбцы должны расширяться пропорционально.

**Comment by YuriSilenok** [comment]
Зачтено
