### ISSUE TITLE
Написать unit-тесты для метода Insert(Model model) сущности CTeacher

### ISSUE THREAD

**Issue by KudelinRoman** [Students-of-the-city-of-Kostroma/Student-timetable#246]
[Сценарии](https://docs.google.com/spreadsheets/d/113wjRI9iZ3VcwojsnDKf15tTzlalq_Lynckp6ReCelw/edit#gid=0)

**Comment by KudelinRoman** [comment]
Состояние таблицы контроллера | fullName ∈ [[A-Я]{1}[а-я]{1,50} or А-Я]{1}[а-я]{1,50}-[А-Я]{1}[а-я]{1,50}] | Примечание Note ∈ [А-я]&[0-1]&[.] | Кафедра department ∈ [А-Я] | Методические дни metodDays ∈ [А-я]&[,] | Окна windows ∈ [А-я]&[,] | Выходные weekends ∈ [А-я]&[,]
-- | -- | -- | -- | -- | -- | --
Добавление данных в пустую таблицу | task-246-1 | task-246-1 | task-246-1 | task-246-1 | task-246-1 | task-246-1
Добавление данных без дублирующих атрибутов | task-246-2 | task-246-2 | task-246-2 | task-246-2 | task-246-2 | task-246-2
Добавление данных с дублирующими атрибутами | task-246-7 | task-246-7 | task-246-7 | task-246-7 | task-246-7 | task-246-7
Добавление данных с одним дублирующим атрибутам | task-246-3 | task-246-4 | task-246-5 | task-246-6 | task-246-6 | task-246-6

**Comment by KharlamovaAlexandra** [comment]
Учтите комментарий к задаче #251 и переделайте задачу. Поля данного метода так же претерпели изменения и не соответствуют описанным в таблице,

**Comment by KudelinRoman** [comment]
Переделано

**Comment by KudelinRoman** [comment]
Изменено
Объедены   три столбца "Фамилия" "Имя" "Отчество" в один "ФИО"
Так как класс MTeacher принимает не три аргумента а один "ФИО"
Спасибо.

**Comment by KudelinRoman** [comment]
Тесты выполнены
