### ISSUE TITLE
Написать unit-тесты для метода Update(Model model) сущности CTeacher

### ISSUE THREAD

**Issue by KudelinRoman** [Students-of-the-city-of-Kostroma/Student-timetable#247]
[Сценарии](https://docs.google.com/spreadsheets/d/113wjRI9iZ3VcwojsnDKf15tTzlalq_Lynckp6ReCelw/edit#gid=0)

**Comment by VinogradovAlexandr781227** [comment]
Сценарий готов. Сделать таблицу на GitHub.

**Comment by KudelinRoman** [comment]
Состояние таблицы контроллера | Surname ∈ [[A-Я]{1}[а-я]{1,50} or А-Я]{1}[а-я]{1,50}-[А-Я]{1}[а-я]{1,50}] | Name ∈ [[A-Я]{1}[а-я]{1,50} or [А-Я]{1}[а-я]{1,50}-[А-Я]{1}[а-я]{1,50} ] | MiddleName ∈[[A-Я]{1}[а-я]{1,50} or [А-Я]{1}[а-я]{1,50}-[А-Я]{1}[а-я]{1,50} or null] | Примечание Note ∈ [А-я]&[0-1]&[.] | Кафедра department ∈ [А-Я] | Методические дни metodDays ∈ [А-я]&[,] | Окна windows ∈ [А-я]&[,] | Выходные weekends ∈ [А-я]&[,]
-- | -- | -- | -- | -- | -- | -- | -- | --
Изменение записи при условии что она не будет дублировать ни один атрибут из другой записи (возможно дублирование) | task-247-1 | task-247-1 | task-247-1 | task-247-1 | task-247-1 | task-247-1 | task-247-1 | task-247-1
Изменение записи при условии что она будет дублировать один атрибут из другой записи | task-247-2 | task-247-3 | task-247-4 | task-247-5 | task-247-6 | task-247-7 | task-247-7 | task-247-7
Изменение записи при условии что она будет дублировать другую записть (невозможно изменение) | task-247-8 | task-247-8 | task-247-8 | task-247-8 | task-247-8 | task-247-8 | task-247-8 | task-247-8
