### ISSUE TITLE
Написать unit-тесты для метода Delete(Model model) сущности CTeacher

### ISSUE THREAD

**Issue by KudelinRoman** [Students-of-the-city-of-Kostroma/Student-timetable#248]
[Сценарии](https://docs.google.com/spreadsheets/d/113wjRI9iZ3VcwojsnDKf15tTzlalq_Lynckp6ReCelw/edit#gid=0)

**Comment by VinogradovAlexandr781227** [comment]
Сценарий проработан. Добавить таблицу на GitHub.

**Comment by KudelinRoman** [comment]
Состояние таблицы контроллера | Surname ∈ [[A-Я]{1}[а-я]{1,50} or А-Я]{1}[а-я]{1,50}-[А-Я]{1}[а-я]{1,50}] | Name ∈ [[A-Я]{1}[а-я]{1,50} or [А-Я]{1}[а-я]{1,50}-[А-Я]{1}[а-я]{1,50} ] | MiddleName ∈[[A-Я]{1}[а-я]{1,50} or [А-Я]{1}[а-я]{1,50}-[А-Я]{1}[а-я]{1,50} or null] | Примечание Note ∈ [А-я]&[0-1]&[.] | Кафедра department ∈ [А-Я] | Методические дни metodDays ∈ [А-я]&[,] | Окна windows ∈ [А-я]&[,] | Выходные weekends ∈ [А-я]&[,]
-- | -- | -- | -- | -- | -- | -- | -- | --
Удаление по атрибуту существующих данных из таблицы | task-248-1 | task-248-1 | task-248-1 | task-248-1 | task-248-1 | task-248-1 | task-248-1 | task-248-1
Удаление по атрибуту несуществующих данных из таблицы по атрибуту одному из атрибутов | task-248-2 | task-248-2 | task-248-2 | task-248-1 | task-248-3 | task-248-4 | task-248-4 | task-248-4
