### ISSUE TITLE
Написать unit-тесты для метода Delete(Model model) сущности CGroup

### ISSUE THREAD

**Issue by KudelinRoman** [Students-of-the-city-of-Kostroma/Student-timetable#249]
[Сценарии](https://docs.google.com/spreadsheets/d/113wjRI9iZ3VcwojsnDKf15tTzlalq_Lynckp6ReCelw/edit#gid=0)

**Comment by VinogradovAlexandr781227** [comment]
Сценарий проработан. Добавить таблицу на GitHub.

**Comment by KudelinRoman** [comment]
Состояние таблицы контроллера | Group ∈ [[0-9]{2}-[А-Я]{2}[б,м]{1}[о,з]{1} - [0-9]{1}[" ",а-я]{1} | Semestr ∈[1-10]{1} | Specialty ∈ [А-Я]{1}[а-я] | Shift  ∈ [1-2]{1} | Students ∈  [0-50] | MinNumberOfClass ∈ [0-6]{1} | MaxNumberOfClass ∈ [0-6]{1} | Weekends ∈ [А-Я]{1}[а-я][,]
-- | -- | -- | -- | -- | -- | -- | -- | --
Удаление по атрибуту существующих данных из таблицы | task-249-1 | task-249-1 | task-249-1 | task-249-1 | task-249-1 | task-249-1 | task-249-1 | task-249-1
Удаление по атрибуту несуществующих данных из таблицы по атрибуту одному из атрибутов | task-249-2 | task-249-3 | task-249-4 | task-249-5 | task-249-6 | task-249-7 | task-249-8 | task-249-9
