### ISSUE TITLE
Написать unit-тесты для метода Update(Model model) сущности CGroup

### ISSUE THREAD

**Issue by KudelinRoman** [Students-of-the-city-of-Kostroma/Student-timetable#250]
[Сценарии](https://docs.google.com/spreadsheets/d/113wjRI9iZ3VcwojsnDKf15tTzlalq_Lynckp6ReCelw/edit#gid=0)
task-250-1

**Comment by KudelinRoman** [comment]
Состояние таблицы контроллера | Group ∈ [[0-9]{2}-[А-Я]{2}[б,м]{1}[о,з]{1} - [0-9]{1}[" ",а-я]{1} | Semestr ∈[1-10]{1} | Specialty ∈ [А-Я]{1}[а-я] | Shift  ∈ [1-2]{1} | Students ∈  [0-50] | MinNumberOfClass ∈ [0-6]{1} | MaxNumberOfClass ∈ [0-6]{1} | Weekends ∈ [А-Я]{1}[а-я][,]
-- | -- | -- | -- | -- | -- | -- | -- | --
Изменение записи при условии что она не будет дублировать ни один атрибут из другой записи (возможно дублирование) | task-250-1 | task-250-1 | task-250-1 | task-250-1 | task-250-1 | task-250-1 | task-250-1 | task-250-1
Изменение записи при условии что она будет дублировать один атрибут из другой записи кроме групппы (невозможно изменение если дублируется группа) | task-250-2 | task-250-3 | task-250-4 | task-250-5 | task-250-6 | task-250-7 | task-250-7 | task-250-7
Изменение записи при условии что она будет дублировать другую записть (невозможно изменение) | task-250-8 | task-250-8 | task-250-8 | task-250-8 | task-250-8 | task-250-8 | task-250-8 | task-250-8

**Comment by KharlamovaAlexandra** [comment]
Учтите комментарий в задаче #251 и в соответствии с теми же требованиями переделайте эту задачу.

**Comment by KudelinRoman** [comment]
Изменено

**Comment by KudelinRoman** [comment]
Ветка создана 
Ожидается ответ разработчиков
