### ISSUE TITLE
Написать unit-тесты для метода Insert(Model model) сущности CGroup

### ISSUE THREAD

**Issue by KudelinRoman** [Students-of-the-city-of-Kostroma/Student-timetable#251]
[Сценарии](https://docs.google.com/spreadsheets/d/113wjRI9iZ3VcwojsnDKf15tTzlalq_Lynckp6ReCelw/edit#gid=0)
ветка task-251 (уже создана)

**Comment by KudelinRoman** [comment]
Состояние таблицы контроллера | Group ∈ [[0-9]{2}-[А-Я]{2}[б,м]{1}[о,з]{1} - [0-9]{1}[" ",а-я]{1} | Semestr ∈[1-10]{1} | Specialty ∈ [А-Я]{1}[а-я] | Shift  ∈ [1-2]{1} | Students ∈  [0-50] | MinNumberOfClass ∈ [0-6]{1} | MaxNumberOfClass ∈ [0-6]{1} | Weekends ∈ [А-Я]{1}[а-я][,]
-- | -- | -- | -- | -- | -- | -- | -- | --
Добавление данных в пустую таблицу | task-251-1 | task-251-1 | task-251-1 | task-251-1 | task-251-1 | task-251-1 | task-251-1 | task-251-1
Добавление данных с одним дублирующим атрибутам | task-251-2 | task-251-3 | task-251-4 | task-251-5 | task-251-6 | task-251-7 | task-251-8 | task-251-9
Добавление данных без дублирующих атрибутов | task-251-10 | task-251-10 | task-251-10 | task-251-10 | task-251-10 | task-251-10 | task-251-10 | task-251-10
Добавление данных с дублирующими атрибутами | task-251-11 | task-251-11 | task-251-11 | task-251-11 | task-251-11 | task-251-11 | task-251-11 | task-251-11

**Comment by KharlamovaAlexandra** [comment]
Таблица заполнена не полностью. Во первых  состояний контроллера должно быть больше( можно для примера посмотреть задачу #246 ). Как минимум может еще быть добавление данных полностью идентичных или совершенно неидентичных.  В методе Insert существует больше полей, а не только численность и шифр группы ( например семестр или направление подготовки). Можно опираться на конструкторы и на данные которые в них передаются. Откуда взято название теста task-16-1 и остальные? Номер этой задачи 251. Логично назвать тесты task-251-1 и тд. Название тестов в данной таблице должно соответствовать названию тестов в таблице сценариев ( там указано  task-251-1 ). Количество тестов в сценариях и в данной таблице должны соответствовать друг другу. Нельзя просто опираться на работу Дарьи. Ее данные устарели. Метод для которого писала тесты она и для которого пишете вы значительно отличаются. Количество атрибутов с того момента как писала она и пишите вы возросло на 8 позиций.  Прошу учесть данные замечания и переделать таблицу и сценарии.

**Comment by KudelinRoman** [comment]
Исправлено

**Comment by KudelinRoman** [comment]
Тесты сделаны кроме одного (жду ответа разработчиков)
