### ISSUE TITLE
Разработать сценарии тестирования пригодных для автоматизации модульным тестированием для метода Update(Model model) сущности Group

### ISSUE THREAD

**Issue by ssas18** [Students-of-the-city-of-Kostroma/Student-timetable#26]
[План разработки](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_102).
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548).
[Ссылка](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_0) на диаграмму классов.

**Comment by YuriSilenok** [comment]
Здравствуйте.
Зачтено. 
Маленькое замечание. заголовок долежн отвечать на вопрос "Что сделать?"
Спасибо.

**Comment by YuriSilenok** [comment]
@SamuraSwordS Вы занимаетесь этой задачей?

**Comment by SamuraSwordS** [comment]
> @SamuraSwordS Вы занимаетесь этой задачей?

 да

**Comment by SamuraSwordS** [comment]
Состояние | Cipher ∈ [[0-9]{2}-[A-Z]{2}[б,м]{1}[о,з]{1} - [0-9]{1}[" ",а-я]{1} | Population ∈[0-20]{1}
-- | -- | --
Имеется один экземпляр (Невозможно дублирование) | task-26-1 | task-26-1
Несколько экземпляров (Возможно дублирование) | task-26-2 | task-26-3

**Comment by SamuraSwordS** [comment]
ID (номер теста) | Description (описание теста) | Test Data(пусто) | Pre-condition(ключ атрибута: значение) | Steps (шаги по реализации теста) | Expected Result
-- | -- | -- | -- | -- | --
  |   |   |   |   |  
task-166-1 | Ввод корректных данных, при условии, что  они не дублируют изменяемые данные |   | 1. Создать объект класс MGroup2. Передать в него атрибуты:-Шифр: "17-ИСбо-2а"-Численность: 123. Вызвать метод Insert(Model model) класса CGroup,передав в него созданный объект класса MGroup | 1. Создать объект класс MGroup2. Передать в него атрибуты:-Шифр: "17-ИСбо-2б"-Численность: 133. Вызвать метод Update(Model model) класса CGroup,передав в него созданный объект класса MGroup.4. Заменить:-Шифр: "17-ИСбо-2а" -> "17-ИСбо-2б" -Численность: 12 -> 13 | return true
task-166-2 | Ввод корректных данных, при условии, что шифр дублирует шифр существующего экземпляра |   | 1. Создать объект класс MGroup2. Передать в него атрибуты:-Шифр: "17-ИСбо-2а"-Численность: 123. Вызвать метод Insert(Model model) класса CGroup,передав в него созданный объект класса MGroup4. Создать объект класс MGroup5. Передать в него атрибуты:-Шифр: "17-ИДбо-3б"-Численность: 146. Вызвать метод Insert(Model model) класса CGroup,передав в него созданный объект класса MGroup | 1. Создать объект класс MGroup2. Передать в него атрибуты:-Шифр: "17-ИСбо-2б"-Численность: 133. Вызвать метод Update(Model model) класса CGroup,передав в него созданный объект класса MGroup.4. Заменить:-Шифр: "17-ИСбо-2а" -> "17-ИДбо-3б"-Численность: 12 -> 12 | return false
task-166-3 | Ввод корректных данных, при условии, что численность группы дублирует численность группы существующего экземпляра |   | 1. Создать объект класс MGroup2. Передать в него атрибуты:-Шифр: "17-ИСбо-2а"-Численность: 123. Вызвать метод Insert(Model model) класса CGroup,передав в него созданный объект класса MGroup4. Создать объект класс MGroup5. Передать в него атрибуты:-Шифр: "17-ИДбо-3б"-Численность: 146. Вызвать метод Insert(Model model) класса CGroup,передав в него созданный объект класса MGroup | 1. Создать объект класс MGroup2. Передать в него атрибуты:-Шифр: "17-ИСбо-2б"-Численность: 133. Вызвать метод Update(Model model) класса CGroup,передав в него созданный объект класса MGroup.4. Заменить:-Шифр: "17-ИСбо-2а" -> "17-ИСбо-2а"-Численность: 12 -> 14 | return true

**Comment by YuriSilenok** [comment]
Вторая таблица со сценариями должна быть размещена в гугл таблице, ссылка на которую есть в дискрипшене задачи.

**Comment by SamuraSwordS** [comment]
Сделано

**Comment by YuriSilenok** [comment]
1. Удалить из комментариев таблицу со сценариями
2. Description сценария task-26-1 не соответсвует запланированному.
3. Ожидаемые результаты не указывают к какому шагу они соответсвуют

**Comment by SamuraSwordS** [comment]
Изменено

**Comment by YuriSilenok** [comment]
1. Убрать искусственные переносы строк в ячейках, там где нет нового пункта.
2. task-26-1. В этом сценарии, по какому атрибуту будет происходить поиск изменяемой строки? Я бы предположил что целевая строка не будет найдена.

**Comment by YuriSilenok** [comment]
Что значит в сценарии task-26-1 этот шаг?
> 4. Заменить:
 -Шифр: "17-ИСбо-2а" -> "17-ИСбо-2б"
 -Численность: 12 -> 13

**Comment by SamuraSwordS** [comment]
Заменить значение атрибутов "старого" на значение "нового"(модели).

**Comment by YuriSilenok** [comment]
Так сценарии не пишут, систему сокращений в данном случае не стандартизирована.

**Comment by SamuraSwordS** [comment]
Могу предположить, что исправлено

**Comment by YuriSilenok** [comment]
> Ввод корректных данных, при условии, что  они не дублируют данные других экземпляров

Куда Вы вводите данные?

**Comment by SamuraSwordS** [comment]
Имел в виду , замена одних данных на другие

**Comment by YuriSilenok** [comment]
А что под заменой вы понимаете и самое главное, где?

**Comment by SamuraSwordS** [comment]
Ну может, наверное, лучше сказать, что "старые" значения полей обновятся на те , что мы подаём в новом объекте модели

**Comment by YuriSilenok** [comment]
Да, так лучше.

Есть вопросы относительно этого,
такой системы сокращений не существует.

> 4. Заменить:
-Шифр: "17-ИСбо-2а" -> "17-ИСбо-2б"
-Численность: 12 -> 13

**Comment by SamuraSwordS** [comment]
Изменил, в соответствии с тем, что написал выше.

**Comment by YuriSilenok** [comment]
С новыми сценариями мне стали понятны Ваши формулировки в Description.
Вы писали
> Ввод корректных данных, при условии, что численность не дублируют численность других экземпляров

Я предлагаю написать следующее
`Проверка отсутствия ограничения уникальности для атрибута "Численность"`

Сценарий task-26-1 не имеет особого смысла для проверки ограничения уникальности, так как для проверки любого ограничения, (не важно, проверяется его наличие или отсутствие, это все один и тот же тест с разными ожидаемыми результатами) нужно создать условие в которых это ограничение должно проявится если оно должно быть или могло бы проявится если оно не должно быть реализовано.

Вы тестируете метод Update и у Вас 2 атрибута один из которых первичный ключ и вы должны написать тесты которые проверяют что:
- можно изменить запись по первичному ключу
- нельзя изменить запись не по первичному ключу
- можно изменить запись что бы совпадал не ключевой атрибут.

Вот, это ваши три теста. Так как первичный ключ нельзя изменить то и ограничение уникальности у него нельзя проверить, это будет проверятся в тестах на метод Insert

**Comment by SamuraSwordS** [comment]
Исправил, надеюсь.

**Comment by YuriSilenok** [comment]
Все хорошо, одна мелочь, ожидаемый результат прописывается к конкретному шагу.

**Comment by YuriSilenok** [comment]
зачтено
