### ISSUE TITLE
Написание сценариев тестирования пригодных для автоматизации unit-test для метода конструктора сущности Group

### ISSUE THREAD

**Issue by FvckNeighbors** [Students-of-the-city-of-Kostroma/Student-timetable#27]
[План разработки](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_102).
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548).
[Ссылка](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_0) на диаграмму классов.

**Comment by YuriSilenok** [comment]
Добрый день.
Могли бы Вы пояснить почему были выбраны такие метки?
К какой части модели MVC относится тестируемая функциональность?
Спасибо.

**Comment by FvckNeighbors** [comment]
Добрый день.

Script - так как задача на разработку сценариев.
Auto test - так как автоматизация тестирования.
Unit test - потому что модульное тестирование.
new() - так как сценарий для метода конструктора.
Group - потому что задача затрагивает сущность Группа.

Данная тестируемая функциональность относится к компоненту Контроллер в модели MVC. Поэтому добавил метку Controller.

Спасибо.

**Comment by YuriSilenok** [comment]
Здравствуйте.
Можно ли назвать эти метки взаимоисключающими?
> Auto test - так как автоматизация тестирования.
Script - так как задача на разработку сценариев.

Вы читали раздел "Типы задач" в лабораторном практикуме?
Если Вам больше нечего делать по задаче, то вы должны ее с себя снять.
Спасибо.

**Comment by FvckNeighbors** [comment]
Здравствуйте. 
Извиняюсь за столь долгий ответ.
Да читал "типы задач", но не правильно понял сначала. Убрал auto test.
Благодарю

**Comment by YuriSilenok** [comment]
Здравствуйте @FvckNeighbors 
Зачтено.
Спасибо.
