### ISSUE TITLE
Написать unit-тесты для метода Insert(Model model) сущности CDiscipline

### ISSUE THREAD

**Issue by DariaMann** [Students-of-the-city-of-Kostroma/Student-timetable#271]
[Сценарии](https://docs.google.com/spreadsheets/d/1z1hOGq-4oyPyFAa48z-fIR2eT5mzkySlA4D8v01Kwuk/edit#gid=0)

**Comment by YuriSilenok** [comment]
добрый день, я обнаружил автотесты 271. тестовых тестовых сценариев в таким номером не существует. пожалуйста, исправьте номера. эта проблема выявлена в ветке Testing.

**Comment by ZhezlovaDaria** [comment]
Тест Task_271_5 являлся дубликатом Task_355_5, поэтому был удалён
