### ISSUE TITLE
Произвести мануальное тестирование формы "Аудитория"

### ISSUE THREAD

**Issue by DariaMann** [Students-of-the-city-of-Kostroma/Student-timetable#276]
Результаты мануального тестирования запишите в [таблице](https://docs.google.com/spreadsheets/d/1z1hOGq-4oyPyFAa48z-fIR2eT5mzkySlA4D8v01Kwuk/edit?usp=sharing).

**Comment by GubanovAndrey** [comment]
Мануальное тестирование кнопки добавить и "количества строк " проведено. Сценарий составлен.
