### ISSUE TITLE
Автоматизация тестирования юнит-тестами конструктора сущности Discipline

### ISSUE THREAD

**Issue by JennyShel18** [Students-of-the-city-of-Kostroma/Student-timetable#28]
Разработать сценарии, подходящие для unit-тестов в эту [таблицу](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)
[План разработки](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.p)
[Ссылка](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit) на диаграмму  классов

**Comment by YuriSilenok** [comment]
Здравствуйте,
Вы закончили с этой задачей?
Спасибо.

**Comment by JennyShel18** [comment]
Добрый вечер!
Никак не могу разобраться с метками, в данный момент села разбираться с
этой проблемой
Вопрос заключается в том, что не могу выбрать какие - либо лейблы и даже
ассайтить, почему то нельзя редактировать
Если поможете решить данную проблему, буду благодарна
Щелкунова Евгения
17-ИСбо-2а

чт, 7 февр. 2019 г. в 9:53 ПП, Юрий Силенок <notifications@github.com>:

**Comment by YuriSilenok** [comment]
Здравствуйте,
я вижу проблему, вы не приняли приглашение которое должно было Вам придти на почту.
Спасибо.

**Comment by YuriSilenok** [comment]
перевешивают задачу всегда в последнюю очередь.
Сперва изменения задачи, потом перевешивание.
Перевесьте на меня когда закончите

**Comment by JennyShel18** [comment]
Спасибо, поняла свою ошибку

**Comment by YuriSilenok** [comment]
Вы закончили?
Задача кому назначена?
Кто с ней должен поработать?

**Comment by YuriSilenok** [comment]
Вы читали раздел "типы задач" в лабораторной работе?

**Comment by JennyShel18** [comment]
Перечитала еще раз, надеюсь сейчас правильнее решение

**Comment by YuriSilenok** [comment]
Здравствуйте.
Могли бы вы пояснить текущий выбор меток?
Спасибо.

**Comment by JennyShel18** [comment]
Здравствуйте.
Так как все задачи относятся к одной из четырех сущностей, то я поставила
метку Discipline. Так как задача ставится на автоматизацию тестирования, то
указывается метка auto-test.
Спасибо.

пт, 8 февр. 2019 г. в 09:53, Юрий Силенок <notifications@github.com>:

**Comment by YuriSilenok** [comment]
Здравствуйте.
Нашел логическую ошибку в описании меток.
Думаю именно из-за этого у Вас не хватает одной метки.
Спасибо.
![image](https://user-images.githubusercontent.com/14871471/52519587-4ceaed00-2c6e-11e9-927f-8aec720cf627.png)

**Comment by JennyShel18** [comment]
Здравствуйте.
Спасибо, поняла свой недочёт.

**Comment by YuriSilenok** [comment]
Здравствуйте.
Теперь все верно. 
Зачтено. 
Спасибо.
