### ISSUE TITLE
"Преподаватели", программа вылетает после очистки поля

### ISSUE THREAD

**Issue by asOldEye** [Students-of-the-city-of-Kostroma/Student-timetable#280]
**Шаги:**
1. Открыть форму добавления преподавателя
2. Стереть одно из стандартных полей
![image](https://user-images.githubusercontent.com/37542164/55689797-aa12ce80-5991-11e9-9ca3-b3d5decee04c.png)
3 Нажать одну из кнопок, либо перейти в любое другое поле на форме

**Ожидаемый результат:**
Строка очищена и возникло предупреждение о том что она не должна быть пустой

**Фактический результат:**
Программа вылетает с ошибкой ArgumentOutOfRangeException
![image](https://user-images.githubusercontent.com/37542164/55689825-23122600-5992-11e9-9799-326e844d23d7.png)

**Comment by YuriSilenok** [comment]
@asOldEye зачтено

**Comment by map82top** [comment]
Баг устранен

**Comment by YuriSilenok** [comment]
Баг может воспроизводится или не воспроизводится на каком-то спринте (ветке)

**Comment by MaximTrapeznikov** [comment]
закрыто, так как баг не актуален

**Comment by YuriSilenok** [comment]
Возможные варианты Ваших комментариев к багу могут быть:
> Баг не воспроизводится в спринте 17-ISbo-2b-4

> Баг воспроизвелся в спринте 17-ISbo-2b-5

**Comment by MaximTrapeznikov** [comment]
Баг не воспроизводится в спринте 17-ISbo-2b-5
