### ISSUE TITLE
"Преподаватели", некорректное название формы

### ISSUE THREAD

**Issue by asOldEye** [Students-of-the-city-of-Kostroma/Student-timetable#281]
Реализована в ветку task-281
**Шаги:**
1. Открыть форму "Преподаватели"
![image](https://user-images.githubusercontent.com/37542164/55689915-45f10a00-5993-11e9-9313-f0ec1b897e02.png)
**Ожидаемый результат:**
Форма в программе на русском языке имеет русскоязычное название "Преподаватели"
**Фактический результат:**
Форма имеет название на английском языке

**Comment by YuriSilenok** [comment]
Зачтено

**Comment by map82top** [comment]
Баг исправлен

**Comment by YuriSilenok** [comment]
Баг может воспроизводится или не воспроизводится на каком-то спринте (ветке)
Прежде чем приступить к исправлениям бага, тестировщик должен указать на какой версии ПО он его проверил. В нашем случае мы указываем спринт (ветку) на которой тестировался баг. Как правило это последний завершенный спринт. После этого разработчики приступают к его исправлению. После этого тестировщики могут проверить этот баг или на ветке текущего спринта. Желательно что бы тестировщик не лез в ветки предназначенные для тасков.

**Comment by MaximTrapeznikov** [comment]
закрыто, так как багне актуален

**Comment by YuriSilenok** [comment]
Возможные варианты Ваших комментариев к багу могут быть:
> Баг не воспроизводится в спринте 17-ISbo-2b-4

> Баг воспроизвелся в спринте 17-ISbo-2b-5

**Comment by MaximTrapeznikov** [comment]
Баг не воспроизводится в спринте 17-ISbo-2b-5
