### ISSUE TITLE
"Преподаватели", нет ограничения на длину слов в полях

### ISSUE THREAD

**Issue by asOldEye** [Students-of-the-city-of-Kostroma/Student-timetable#283]
Реализовано в ветку task-283
**Шаги:**
1. Открыть форму "Преподаватели"
2. Ввести в любое из полей слово, превышающее 255 символов
![image](https://user-images.githubusercontent.com/37542164/55690113-d16b9a80-5995-11e9-98ce-a78f1aaec00a.png)

**Ожидаемый результат:**
Сообщение о превышении лимита длины слова в 255 символов при введении строки длинее 255 символов

**Фактический результат:**
Введенное слово принято программой

**Comment by map82top** [comment]
Для формы преподаватели:

- Имя 25
- Отчество 30
- Фамилия 50
- Примечание 256
- Кафедра 100
- Методические дни 70
- Окна: 70
- Выходные: 70

Для формы группа:

- Название 10
- Семестр 1
- Направление подготовки: 100
- Смена: 1
- Студентов: 2
- Пар min/max 1
- Выходные: 70

**Comment by map82top** [comment]
Баг исправлен

**Comment by YuriSilenok** [comment]
Баг может воспроизводится или не воспроизводится на каком-то спринте (ветке)
Прежде чем приступить к исправлениям бага, тестировщик должен указать на какой версии ПО он его проверил. В нашем случае мы указываем спринт (ветку) на которой тестировался баг. Как правило это последний завершенный спринт. После этого разработчики приступают к его исправлению. После этого тестировщики могут проверить этот баг или на ветке текущего спринта. Желательно что бы тестировщик не лез в ветки предназначенные для тасков.

Добавить еще одну задачу на  реализацию ограничений для группы. В запросе на слияние сослаться на добавленную задачу.

**Comment by MaximTrapeznikov** [comment]
закрыто, так как  баг не актуален

**Comment by YuriSilenok** [comment]
Возможные варианты Ваших комментариев к багу могут быть:
> Баг не воспроизводится в спринте 17-ISbo-2b-4

> Баг воспроизвелся в спринте 17-ISbo-2b-5

**Comment by MaximTrapeznikov** [comment]
Баг не воспроизводится в спринте 17-ISbo-2b-5
