### ISSUE TITLE
"Аудитории", не сохраняются введенные строки

### ISSUE THREAD

**Issue by asOldEye** [Students-of-the-city-of-Kostroma/Student-timetable#284]
**Шаги:**
1. Открыть форму "Аудитории"
2. Заполнить одну или более строк
![image](https://user-images.githubusercontent.com/37542164/55690279-daf60200-5997-11e9-9c27-21154bcb31e9.png)
3. Закрыть форму "Аудитории"
4. Снова открыть форму "Аудитории"

**Ожидаемый результат:**
Форма содержит ранее введенные строки

**Фактический результат:**
Таблица на форме пуста
![image](https://user-images.githubusercontent.com/37542164/55690283-ee08d200-5997-11e9-81c6-690bcfe0d9f8.png)

**Comment by YuriSilenok** [comment]
Зачтено

**Comment by Parallusion** [comment]
Не воспроизводится в ветке 17-ISbo-2a.
