### ISSUE TITLE
"Группы", столбцы продублированы

### ISSUE THREAD

**Issue by asOldEye** [Students-of-the-city-of-Kostroma/Student-timetable#286]
**Шаги:**
1. Открыть форму преподаватели

**Ожидаемый результат:**
Столбцы Шифр и Численность отображаются нормально. Сортировка работает у обоих

**Фактический результат**
Столбцы Шифр и Численность продублированы на английском языке. При этом сортировка не работает у столбцов именованных на русском и работает у столбцов именованных на английском
![image](https://user-images.githubusercontent.com/37542164/55690452-95870400-599a-11e9-8a69-a3242daf888a.png)

**Comment by YuriSilenok** [comment]
Добрый день.
Судя по всему Вы тестировали в ветке master. 
В теории она должны быть пуста, но был один студент который залил туда непонятно что и до сих пор ни как не исправит свои ошибки.
Тестировать нужно в ветке Testing.
Если этот баг в ней не воспроизводится.
По мимо всего прочего вы подняли клон задачи #144 
Спасибо.

**Comment by asOldEye** [comment]
Тестирование проводил во вчера взятой Testing. Баг воспроизвелся в Testing. Клон #144 потому что в ней(#144) название не отражает сути. Впредь буду внимательнее

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
