### ISSUE TITLE
"Расписание", некорректное название формы

### ISSUE THREAD

**Issue by asOldEye** [Students-of-the-city-of-Kostroma/Student-timetable#288]
**Шаги:**
1. Открыть форму Расписание

**Ожидаемый результат:**
Форма в программе на русском языке имеет русскоязычное название "Расписание"

**Фактический результат:**
Форма имеет название на английском языке
![image](https://user-images.githubusercontent.com/37542164/55690569-f531df00-599b-11e9-8120-18417e89a43c.png)
#1099

**Comment by YuriSilenok** [comment]
Зачтено

**Comment by YuriSilenok** [comment]
@bolotovaksenya ретест в ветке Testing после мержа, если не воспроизводится сообщить и закрыть

**Comment by YuriSilenok** [comment]
Снято по не активности
Эта задача не может быть использована для ликвидации задолженности.
