### ISSUE TITLE
Разработать сценарии тестирования пригодных для автоматизации модульным тестированием метода Delete(Model model) сущности Вид занятия

### ISSUE THREAD

**Issue by nrabotko** [Students-of-the-city-of-Kostroma/Student-timetable#291]
[План разработки](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_102)
[Ссылка на диаграмму классов](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_0)
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)

**Comment by nrabotko** [comment]
| Состояние таблицы контроллера  | Вид занятия сокращенное [[[А-Я]{1}[а-я]{1,5}.] or [[а-я]{1,5}.]] | Вид занятия полное [[[А-Я]{1}[а-я]{1,50}] or [[А-Я]{1}[а-я]{1,50} [А-Я]{1}[а-я]{1,50}]] |
| ------------- | ------------- | ------------- |
| Удаление по атрибуту существующих данных | task-291-1  | task-291-1 |
| Удаление по атрибуту несуществующих данных  | task-291-2  | task-291-3 |

**Comment by YuriSilenok** [comment]
кажется тесты по диагонали у вас получатся одинаковыми.
первое что вы должны проверить это то, что из системы можно удалить запись в которой совпадают все атрибуты
дальше вы проверяете то, что можно или нельзя удалить запись при совпадении только одного атрибута.
В завершении можно проверить что система не сломается если попытаться удалить из таблицы в которой ничего нет, соответственно значения атрибутов здесь не так важны.

**Comment by nrabotko** [comment]
Я исправила сценарий тестирования. Проверьте, пожалуйста.

**Comment by YuriSilenok** [comment]
Здравствуйте, сценарии не соответствуют таблице написанной в комментариях, поправьте сначала ее.

**Comment by nrabotko** [comment]
| Состояние таблицы контроллера  | Вид занятия сокращенное [[[А-Я]{1}[а-я]{1,5}.] or [[а-я]{1,5}.]] | Вид занятия полное [[[А-Я]{1}[а-я]{1,50}] or [[А-Я]{1}[а-я]{1,50} [А-Я]{1}[а-я]{1,50}]] |
| ------------- | ------------- | ------------- |
| Удалить запись при совпадении только всех атрибутов | task-291-1  | task-291-1 |
| Удалить запись при совпадении только одного атрибута | task-291-2  | task-291-2 |
| Удаление не существующих данных из таблицы  | task-291-3  | task-291-3 |

**Comment by nrabotko** [comment]
| Состояние таблицы контроллера  | Вид занятия сокращенное [[[А-Я]{1}[а-я]{1,5}.] or [[а-я]{1,5}.]] | Вид занятия полное [[[А-Я]{1}[а-я]{1,50}] or [[А-Я]{1}[а-я]{1,50} [А-Я]{1}[а-я]{1,50}]] |
| ------------- | ------------- | ------------- |
| Удалить запись при совпадении только всех атрибутов | task-291-1  | task-291-1 |
| Удалить запись при совпадении только одного атрибута | task-291-2  | task-291-3 |
| Удаление не существующих данных из таблицы  | task-291-4  | task-291-4 |

**Comment by YuriSilenok** [comment]
Зачтено
