### ISSUE TITLE
Разработать сценарии тестирования для класса MGroup пригодных в автоматизации.

### ISSUE THREAD

**Issue by map82top** [Students-of-the-city-of-Kostroma/Student-timetable#3]
Разработать сценарии пригодные для Unit-тестирования в эту [таблицу](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)
[План разработки](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.p)
[Ссылка](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit) на диаграмму классов

**Comment by YuriSilenok** [comment]
Добрый день @map82top 

[Ссылка](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548) на таблицу со сценариями должна остатья прежней.

Заасанить нужно на меня.

Других замечаний нет.

Спасибо.

**Comment by YuriSilenok** [comment]
Зачтено

**Comment by YuriSilenok** [comment]
@NesgovorovVS В тестах учесть что шифр группы должен соответствовать регулярному следующему выражению
`\d{2}-[А-Я]{2}[а-я]{2}-\d[а-я]{,1}`
Численность группы >=0

**Comment by YuriSilenok** [comment]
не актуально
