### ISSUE TITLE
Исправить баг у формы "Ученые звания"

### ISSUE THREAD

**Issue by KudelinRoman** [Students-of-the-city-of-Kostroma/Student-timetable#300]
Описание бага:
Нажимаем на "Ученые звания"
![image](https://user-images.githubusercontent.com/47320335/55758078-689c2500-5a5e-11e9-9a0b-242afbc3dbab.png)
Ожидается, что откроется одна форма 
Результат: открывается сразу две формы
![image](https://user-images.githubusercontent.com/47320335/55758179-ae58ed80-5a5e-11e9-8bdb-9892b5df7c22.png)

**Comment by map82top** [comment]
В ветке 17-ISbo-2b-6 данный баг не актуален
