### ISSUE TITLE
"Преподаватели", при создании и редактировании преподавателя в поле "Примечание" невозможно ввести латинские символы и знаки препинания

### ISSUE THREAD

**Issue by asOldEye** [Students-of-the-city-of-Kostroma/Student-timetable#310]
**Шаги:**
1. Открыть форму "Преподаватели"
2. Открыть форму "Добавить преподавателя"
2.1 Открыть форму "Редактирование преподавателя"
3. Ввести в поле "Примечание" строку, содержащую латинские символы и знаки препинания
3.1 Ввести в поле "Примечание" строку, содержащую латинские символы и знаки препинания

**Ожидаемый результат:**
Введены латинские символы и знаки препинания

**Фактический результат**
В строку не попадают латинские символы и знаки препинания, за исключением запятой и символа минус
![image](https://user-images.githubusercontent.com/37542164/55822762-fa606c80-5b08-11e9-9426-0604e644cc84.png)

**Comment by YuriSilenok** [comment]
@asOldEye зачтено

**Comment by YuriSilenok** [comment]
В каком спринте был исправлен этот баг?

**Comment by map82top** [comment]
В этом

**Comment by YuriSilenok** [comment]
все таские запланированные на спринт должны иметь веху спринта.

**Comment by YuriSilenok** [comment]
@asOldEye зачтено
