### ISSUE TITLE
"Преподаватели", уведомление предлагает удалить выбранный ряд когда ряд не выбран

### ISSUE THREAD

**Issue by asOldEye** [Students-of-the-city-of-Kostroma/Student-timetable#311]
Реализовано в task-311
**Шаги:**
1. Открыть форму "Преподаватели"
2. Нажать кнопку "Удалить"
2.1 Заполнить таблицу некоторыми значениями, удалить последний элемент и нажать кнопку "Удалить"

**Ожидаемый результат:**
Кнопка "Удалить" становится неактивной, либо при нажатии нет реакции, либо выводится уведомление о том, что ряд не выбран

**Фактический результат**
Выводится сообщение, утверждающее что какой-то ряд выбран и предлагающее удалить его
![image](https://user-images.githubusercontent.com/37542164/55823344-2cbe9980-5b0a-11e9-96cb-8c1e23a2c6dd.png)

**Comment by map82top** [comment]
Исправлено

**Comment by YuriSilenok** [comment]
Баг может воспроизводится или не воспроизводится на каком-то спринте (ветке)
Прежде чем приступить к исправлениям бага, тестировщик должен указать на какой версии ПО он его проверил. В нашем случае мы указываем спринт (ветку) на которой тестировался баг. Как правило это последний завершенный спринт. После этого разработчики приступают к его исправлению. После этого тестировщики могут проверить этот баг или на ветке текущего спринта. Желательно что бы тестировщик не лез в ветки предназначенные для тасков.

**Comment by YuriSilenok** [comment]
@asOldEye зачтено

**Comment by map82top** [comment]
Баг воспроизвелся в спринте 17-ISbo-2b-4
Баг не воспроизводится в спринте 17-ISbo-2b-5
