### ISSUE TITLE
Реализовать метод Insert(Model model) сущности Discipline

### ISSUE THREAD

**Issue by stasshtaub** [Students-of-the-city-of-Kostroma/Student-timetable#32]
**Поведение:** метод добавляет новую дисциплину в том случае если поля
```
string name;
string code;
```
являются уникальными и не пустыми. Если добавление в таблицу произошло, то метод вернет истину, в других случаях метод возвращает ложь.

[Ссылка](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit) на диаграмму классов.

**Comment by YuriSilenok** [comment]
Здравствуйте.
Измените дискрипшен в соответствии с этими задачами [1](https://gitlab.com/YuriSilenok/Student-timetable/issues/169) и [2](https://gitlab.com/YuriSilenok/Student-timetable/issues/187)
Спасибо.

**Comment by YuriSilenok** [comment]
Зачтено.

**Comment by netever** [comment]
@YuriSilenok 
Здравствуйте. 
Я не понимаю, что от меня требуется? Метод Insert уже реализован.
Спасибо.

**Comment by YuriSilenok** [comment]
Здравствуйте @netever 
Да, действительно, видимо это задача была поднята ошибочно.
Сейчас подберу что нибудь другое.
Спасибо.
