### ISSUE TITLE
Разработать статический метод  bool TableCompare(DataTable,DataTable) для класса Controller

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#321]
ЛР4.2

**Comment by Parallusion** [comment]
Добрый день.

Что делать, если у меня при запуске решения уже в списке ошибок есть ошибки, связанные с DataTable.DataSet, что не является моей задачей и не является моими ошибками написания кода? Из за ошибок я не могу запустить юнит тесты и не могу проверить правильно ли работает программа.
![image](https://user-images.githubusercontent.com/47377888/56080989-b8893c00-5e10-11e9-9b48-ca8ce54e38b5.png)

Спасибо.
Смирнов Илья.
17-ИСбо-2а

**Comment by Parallusion** [comment]
Добрый день.

Я убрал код в тестах, на который ругалась Visual Studio, это был чисто код для Unit Test, могу ли я залить обратно мою программу в таком виде? 
Поясняю: мой написанный код работает, прошёл все тесты, но я удалил код Unit Test-ов, на которые ругалась Visual Studio.

Спасибо.
Смирнов Илья.
17-ИСбо-2а

**Comment by YuriSilenok** [comment]
Зачтено
