### ISSUE TITLE
Поднятие задачи для написания сценариев тестирования пригодных для автоматизации unit-test для метода Update(Model model) сущности Discipline

### ISSUE THREAD

**Issue by NordScandinavian** [Students-of-the-city-of-Kostroma/Student-timetable#33]
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)
[План разработки](https://docs.google.com/spreadsheets/d/11uPdKMmzZklleijGcBAKoStnVHY2_9qBwRPOpR1y0vM/edit#gid=389498935)
[Диаграмма классов](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit)

**Comment by YuriSilenok** [comment]
Здравствуйте.
- У вас отсутствует дискрипен.
- Не хватает меток

Спасибо

**Comment by NordScandinavian** [comment]
Здравстуйте.
Добавил: 
- метку
- дискрипшн

Спасибо

**Comment by YuriSilenok** [comment]
Здравствуйте.
- [Ознакомьтесь ](https://docs.google.com/document/d/1k8ILnmYVi3Cz-mTge3h6RI0OV4DbAHviQseScRRpUxI/edit)с требованиями к заголовку и Ваша задача не должна ставиться на поднятие задача, а должна ставить задачу.
- Могли бы Вы пояснить такой набор меток?

Спасибо.

**Comment by NordScandinavian** [comment]
Здравствуйте,
Поменял метки в соответствии с поставленной задачей. 
Добавил дискрипшн. 
Спасибо.

**Comment by YuriSilenok** [comment]
Здравствуйте.

* [Ознакомьтесь ](https://docs.google.com/document/d/1k8ILnmYVi3Cz-mTge3h6RI0OV4DbAHviQseScRRpUxI/edit)с требованиями к заголовку и Ваша задача не должна ставиться на поднятие задачи, а должна ставить задачу.
* Могли бы Вы пояснить такой набор меток?

Спасибо.
