### ISSUE TITLE
Мануальное тестирование метода Delete(Model model) сущности CDiscipline

### ISSUE THREAD

**Issue by DariaMann** [Students-of-the-city-of-Kostroma/Student-timetable#333]
Произвести мануальное тестирование и заполнить свою таблицу с результатами.

**Comment by ivshr** [comment]
Ссылка на таблицу: https://docs.google.com/spreadsheets/d/1Buc_cdETmCodKrrSVG_ONygJ0jbsJ9JmpbOvjaqQiOw/edit#gid=0

**Comment by ivshr** [comment]
Ссылка на таблицу: https://docs.google.com/spreadsheets/d/1Buc_cdETmCodKrrSVG_ONygJ0jbsJ9JmpbOvjaqQiOw/edit#gid=0
