### ISSUE TITLE
Разработать сценарии тестирования пригодных для автоматизации модульным тестированием метода Insert(Model model) сущности Дисциплина

### ISSUE THREAD

**Issue by abramovaalina** [Students-of-the-city-of-Kostroma/Student-timetable#34]
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)
[План разработки](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.p)
[Диаграмма классов](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit)

**Comment by YuriSilenok** [comment]
Ответил устно

**Comment by YuriSilenok** [comment]
Здравствуйте,
Могли бы пояснить такой набор меток?
Спасибо.

**Comment by abramovaalina** [comment]
здравствуйте, 
unit test так как задача затрагивает модульное тестирование 
script так как нужно написать сценарий тестирования 
insert (Model model) задача относится к методу insert
auto test указано, что сценарий тестирования для автоматизации

**Comment by YuriSilenok** [comment]
Здравствуйте.

Вы не перевесили на меня задачу, почему?

Это цитата из инструкции.
> Если задача относиться к тестовым сценариям для unit-тестирования, то указывается метка unit-test. Если задача ставиться на написание сценариев то указывается метка Script. Если задача ставиться на автоматизацию тестирования, то указывается метка Auto-test.

Вы написали
> auto test указано, что сценарий тестирования для автоматизации

Значит ли это что формулировки "Если задача ставиться на автоматизацию тестирования" и "сценарий тестирования для автоматизации" являются равноценными?

Спасибо.

**Comment by abramovaalina** [comment]
Здравствуйте. Скорее всего это разные формулировки.

**Comment by YuriSilenok** [comment]
Поясните все Ваши действия.
Почему Вы убрали метки Auto test и Script и Добавили метку Controller?
С себя задачу снимайте, если закончили на нед ней работать.
И задачу нужно перевешивать только после того как Вы закончили над ней работать, а не до.

**Comment by abramovaalina** [comment]
auto test - я убрала потому что подумала, что это разные формулировки. значит метка неверная. 
script - возможно это было лишнее действие, так как данная метка используется если есть задача написать сценарий. как раз такая задача и поставлена. 
controller - добавила, так как задача относится к методу Insert.

**Comment by YuriSilenok** [comment]
Зачтено
