### ISSUE TITLE
Функционал окна "Группы"

### ISSUE THREAD

**Issue by katyatoc** [Students-of-the-city-of-Kostroma/Student-timetable#346]
### Функциональные кнопки окна "Группы":
**Кнопка "Печать":**
![печать](https://user-images.githubusercontent.com/48826518/56062808-4fed8100-5d76-11e9-8b99-71cfabcd482c.PNG)
Вызывает диалоговое окно "Мастер печати расписания групп", в котором можно выбрать расписание каких групп нужно распечатать.

**Кнопка "Стереть":**
![Стереть](https://user-images.githubusercontent.com/48826518/56082764-61419680-5e25-11e9-9ffc-e848ad1f32c6.PNG)
Вызывает окно подтверждения процесса стирания выбранных незакрепленных занятий конкретной группы.

**Кнопка "Закрепить занятия в группе":**
![Закрепить занятие в группе](https://user-images.githubusercontent.com/48826518/56082799-da40ee00-5e25-11e9-823e-a460a2316cdd.PNG)
Нажатием кнопки занятия в таблице закрепляются, в ячейке появляется красный флажок.

**Кнопка "Освободить занятия в группе":**
![Освободить занятие в группе](https://user-images.githubusercontent.com/48826518/56083368-930a2b80-5e2c-11e9-9206-5d562b966b65.PNG)
Нажатием кнопки занятия в таблице освобождаются, флажки исчезают со всех ячеек в таблице.

**Кнопка "Проверить":**
![Проверить](https://user-images.githubusercontent.com/48826518/56083448-d1ecb100-5e2d-11e9-9c80-dbdfabd1b1dc.PNG)
Нажатием кнопки запускает процесс проверки составления расписания. Вызывает информационное окно о результате.

**Кнопка "Найти":**
![Найти](https://user-images.githubusercontent.com/48826518/56083511-a8805500-5e2e-11e9-9e6c-a839cf4e488b.PNG)
Вызывает диалоговое окно "Мастер поиска расписания", в котором нужно выбрать расписание для поиска.

**Кнопка "Копировать":**
![Копировать](https://user-images.githubusercontent.com/48826518/56083524-ccdc3180-5e2e-11e9-82f2-7f2a14a7d543.PNG)
Вызывает окно для настройки копирования текущего расписания на последующие недели.

**Кнопка "Окно":**
![Окно](https://user-images.githubusercontent.com/48826518/56083545-03b24780-5e2f-11e9-9945-25c1cdca78e1.PNG)
Разворачивает окно "Группы" поверх других рабочих окон.

**Кнопка "Закрепить занятия в ВУЗе":**
![Закрепить занятия в ВУЗе](https://user-images.githubusercontent.com/48826518/56083556-247a9d00-5e2f-11e9-86cb-5ebeb6253d55.PNG)
Нажатием кнопки занятия в таблице закрепляются в ВУЗе, в ячейке появляется красный флажок.

**Кнопка "Освободить занятия в ВУЗе":**
![Освободить занятия в ВУЗе](https://user-images.githubusercontent.com/48826518/56083560-38be9a00-5e2f-11e9-9078-9286150271ff.PNG)
Нажатием кнопки занятия в таблице освобождаются в ВУЗе, флажки исчезают со всех ячеек в таблице.

**Кнопка "Отменить":**
![Отменить](https://user-images.githubusercontent.com/48826518/56083568-4bd16a00-5e2f-11e9-9be9-2b4dab49cebc.PNG)
Нажатием кнопки отменяется последнее действие.

**Окно выбора группы:**
![Окно Грцппы](https://user-images.githubusercontent.com/48826518/56083627-3c065580-5e30-11e9-8fe3-adcf570c67d6.PNG)
Стрелками или в горизонтальном выпадающем меню выбирается нужная группа. Также между группами можно переключаться кнопками в нижней части второй таблицы.

**Окна выбора недели:**
![Окно выбора недели](https://user-images.githubusercontent.com/48826518/56083629-41fc3680-5e30-11e9-9ca2-aa6dde4500cd.PNG)
Стрелками или в горизонтальном выпадающем меню выбирается нужная неделя.

Функционал таблицы:
В первой таблице в столбцах указаны дни недели и дата, в строках - номера пар. В ячейке название пары и вид занятия.
Во второй таблице информация о предмете в группе: группа(поток), всего пар, пар в неделю, +, #, &, название дисциплины, преподаватель, вид занятия, аудитория, спаривание, позиция пар.

Рекомендуемые цвета для таблицы:
#B22222 ![1](https://user-images.githubusercontent.com/48826518/56084282-c606ec00-5e39-11e9-807c-3b29390081e6.PNG)

#E9967A ![2](https://user-images.githubusercontent.com/48826518/56084291-ea62c880-5e39-11e9-9c0c-5de65735eeed.PNG)

#FFB6C1 ![3](https://user-images.githubusercontent.com/48826518/56084303-14b48600-5e3a-11e9-8e3a-26aced3518db.PNG)

#FFA500 ![4](https://user-images.githubusercontent.com/48826518/56084313-36ae0880-5e3a-11e9-9d42-091ba801b248.PNG)

#FFE4B5 ![5](https://user-images.githubusercontent.com/48826518/56084322-56ddc780-5e3a-11e9-875c-47b42406d312.PNG)

#D8BFD8 ![6](https://user-images.githubusercontent.com/48826518/56084332-74ab2c80-5e3a-11e9-8506-68e30e326f66.PNG)

#2F4F4F ![7](https://user-images.githubusercontent.com/48826518/56084345-9f958080-5e3a-11e9-8e6c-f8381567151f.PNG)

#696969 ![8](https://user-images.githubusercontent.com/48826518/56084372-e08d9500-5e3a-11e9-9f0c-9c24f861d610.PNG)

#87CEEB ![9](https://user-images.githubusercontent.com/48826518/56084381-087cf880-5e3b-11e9-81ce-961cf46a3890.PNG)

#5F9EA0 ![10](https://user-images.githubusercontent.com/48826518/56084387-2185a980-5e3b-11e9-9a0c-3cb91cda822d.PNG)

#556B2F ![11](https://user-images.githubusercontent.com/48826518/56084395-3c581e00-5e3b-11e9-9d43-5b43017ea6af.PNG)

**Comment by YuriSilenok** [comment]
Зачтено

**Comment by YuriSilenok** [comment]
Реализация этой функциональности не представляется возможным в текущей фазе.

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
