### ISSUE TITLE
Автоматизировать сценарии тестирования методом юнит-тестирования для метода Update(Model model) сущности Discipline

### ISSUE THREAD

**Issue by ghost** [Students-of-the-city-of-Kostroma/Student-timetable#35]
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)
[План разработки](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_102)
[Диаграмма классов](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_0)

**Comment by YuriSilenok** [comment]
Ответил устно

**Comment by YuriSilenok** [comment]
Здравствуйте.
- Не правильно перевесили задачу.
- Заголовок задачи не отвечает на нужный вопрос
- Не сценарий, а сценари_и_
- Не все метки выставлены
Спасибо.

**Comment by YuriSilenok** [comment]
Зачтено
