### ISSUE TITLE
Разработать функционал кнопки Изменить формы Ученые звания

### ISSUE THREAD

**Issue by Takunava** [Students-of-the-city-of-Kostroma/Student-timetable#358]
При нажатии на кнопку должно отрываться окно Изменение ученого звания с полями Сокращенное название и Полное название. 
На форме должны быть кнопки Сохранить и Отмена

**Comment by yuliagolubevaa5** [comment]
![image](https://user-images.githubusercontent.com/47320351/56387664-90914280-622d-11e9-8cd7-b8fe09fd96c5.png)
