### ISSUE TITLE
Разработка метода Update(Model model) сущности Discipline

### ISSUE THREAD

**Issue by badsster** [Students-of-the-city-of-Kostroma/Student-timetable#36]
**Поведение:**
В данный метод передается объект, проверяется его существование в таблице, если такой есть. Далее метод изменяет информацию о существующей группе в том случае ,если поля

` byte population;`

` string cipher;`

являются уникальными и не пустыми (производится проверка).
Если изменение произошло, то метод вернет истину, в других случаях метод возвращает ложь.
[Ссылка](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit?usp=sharing) на диаграмму классов.
task-36

**Comment by YuriSilenok** [comment]
Здравствуйте.
Могли бы пояснить такой набор меток?
Спасибо

**Comment by badsster** [comment]
Здравствуйте.
- Метка Story является меткой задачи на разработку функциональности и ставится, если данная задача:
а)создаётся преподавателем и берётся на исполнение студентом;
б)студент создаёт ветку имя которой соответствует описанному выше шаблону, где номер в имени ветки это номер задачи;
в)после положительной проверки изменений, студент выполняет мерж веток и перевешивает основную задачу на преподавателя;
г)после заключенных проверок, преподаватель выставляет баллы в журнал, перевешивает на исполнителя и закрывает задачу;
Все перечисленные пункты относятся к данной задаче.
- Метка Controller-задача на разработку кода реализующий логику ПО и если задача имеет отношение к методу Update, то задача должна быть помечена данной меткой. 
Спасибо. 
Завьялова Надежда. 
17-ИДбо-3б.

**Comment by YuriSilenok** [comment]
Здравствуйте @badsster 

Почему Вы не перевесили задачу?
Вы видели раздел [Типы задач и метки](https://docs.google.com/document/d/1k8ILnmYVi3Cz-mTge3h6RI0OV4DbAHviQseScRRpUxI/edit)?

Спасибо.

**Comment by YuriSilenok** [comment]
Здравствуйте @Chippa99fm
Эта Ваша задача на разработку.
Она еще не завершена по ЛР01 пользователем @badsster 
Но содержит все необходимые данные.
Спасибо.

**Comment by YuriSilenok** [comment]
@Chippa99fm Нехорошо подсказывать.
Зачтено.

**Comment by YuriSilenok** [comment]
Здравствуйте @badsster
Я задачу закрою, но ее доделать нужно.
Спасибо.

**Comment by badsster** [comment]
Здравствуйте, Юрий Викторович. 

Прошу прощения, я вспомнила о том, что забыла перекинуть данную задачу на вас.
Можно ли как-то доделать данную лабораторную работу?

Спасибо.

**Comment by YuriSilenok** [comment]
@badsster зачтено.
