### ISSUE TITLE
Разработка сценариев тестирования для метода insert(model model) сущности Ученое звание

### ISSUE THREAD

**Issue by Takunava** [Students-of-the-city-of-Kostroma/Student-timetable#361]
[Ссылка на сценарий](https://docs.google.com/spreadsheets/d/1Daw4lpusFJDZXALRDZjTkp_B9aNyv6GLZ5YqcaXXPec/edit#gid=0)

**Comment by yuliagolubevaa5** [comment]
| Состояние таблицы контроллера | Сокращённая запись Reduction_TextChanged ∈[ "Проф." or "Доц." or "проф." or "доц."]  |  Полная запись FullName_TextChanged ∈[ "Доцент" or "Профессор" or "доцент" or "профессор"] | 
 | ----- | ---- | ---- | 
 | ` Таблица не имеет записей ` | task-361-1 | task-361-1 | 
 | ` В таблице существует запись с атрибутом, совпадающим с атрибутом добавляемой записи` | task-361-2 | task-361-3 | 
---

**Comment by Pipyao** [comment]
Це в таблицу
Надо

**Comment by yuliagolubevaa5** [comment]
я знаю, так соориентироваться что делать оло

**Comment by Pipyao** [comment]
Тут нужны кейсы на ввод
Вопрос в том на ввод чего, данных в таблицу или выборки сос тороны юзера

**Comment by yuliagolubevaa5** [comment]
https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/171
это разве не то же самое??

**Comment by Pipyao** [comment]
То автоматизация

**Comment by Pipyao** [comment]
Зачтено

**Comment by YuriSilenok** [comment]
Метки Script нет, почему?

**Comment by YuriSilenok** [comment]
Сценарии пригодны для автоматизации? если да, то где метка?
