### ISSUE TITLE
Разработка сценариев тестирования для метода Delete(model model) сущности Ученое звание

### ISSUE THREAD

**Issue by Takunava** [Students-of-the-city-of-Kostroma/Student-timetable#362]
[Ссылка](https://docs.google.com/spreadsheets/d/1Daw4lpusFJDZXALRDZjTkp_B9aNyv6GLZ5YqcaXXPec/edit#gid=0)

**Comment by yuliagolubevaa5** [comment]
| Состояние таблицы контроллера | Сокращённая запись Reduction_TextChanged ∈[ "Проф." or "Доц." or "проф." or "доц."]  |  Полная запись FullName_TextChanged ∈[ "Доцент" or "Профессор" or "доцент" or "профессор"] | 
 | ----- | ---- | ---- | 
 | ` Удаление по атрибуту существующих данных ` | task-362-1 | task-362-1 | 
 | ` Удаление по атрибуту несуществующих данных` | task-362-2 | task-362-3 | 
---
