### ISSUE TITLE
Разработка сценариев тестирования метода Update(model model) сущности Ученое звание

### ISSUE THREAD

**Issue by Takunava** [Students-of-the-city-of-Kostroma/Student-timetable#363]
[Ссылка на сценарии](https://docs.google.com/spreadsheets/d/1Daw4lpusFJDZXALRDZjTkp_B9aNyv6GLZ5YqcaXXPec/edit#gid=0)

**Comment by yuliagolubevaa5** [comment]
| Состояние таблицы контроллера | Сокращённая запись Reduction_TextChanged ∈[ "Проф." or "Доц." or "проф." or "доц."]  |  Полная запись FullName_TextChanged ∈[ "Доцент" or "Профессор" or "доцент" or "профессор"] | 
 | ----- | ---- | ---- | 
 | ` Замена корректными данными всех полей ` | task-363-1 | task-363-1 | 
 | ` Ввод корректных данных данных только в одно поле ` | task-363-2 | task-363-3 | 
---
