### ISSUE TITLE
"Дисциплины", некорректное название формы "Добавить дисциплину"

### ISSUE THREAD

**Issue by asOldEye** [Students-of-the-city-of-Kostroma/Student-timetable#364]
**Шаги:**
1. Открыть форму "Дисциплины"
2. Открыть форму "Создать дисциплину"

**Ожидаемый результат:**
Форма в программе на русском языке имеет название на русском языке "Создать дисциплину"

**Фактический результат:**
Форма имеет некорректное название "AddDiscipline"
![image](https://user-images.githubusercontent.com/37542164/56230003-f2ae4400-6083-11e9-8886-924214fa26a3.png)

**Comment by YuriSilenok** [comment]
@asOldEye Зачтено в курсовую
@Students-of-the-city-of-Kostroma/17isa Проверить на предмет воспроизводимости бага.

**Comment by Jeen99** [comment]
Поправлено в #521
