### ISSUE TITLE
"Аудитории", в столбец "Вместительность" разрешается ввести нецелочисленное значение

### ISSUE THREAD

**Issue by asOldEye** [Students-of-the-city-of-Kostroma/Student-timetable#368]
**Шаги:**
1. Открыть форму "Аудитории"
2. Ввести в одной из строк в столбец "Вместительность" строку, не являющуюся числом

**Ожидаемый результат:**
Ввод строки, не являющейся целым числом, невозможен

**Фактический результат:**
Строка, не являющаяся числом введена и сохранена в поле
![image](https://user-images.githubusercontent.com/37542164/56239295-3eb7b380-6099-11e9-912e-af51a2ab7eee.png)

**Comment by Parallusion** [comment]
Не воспроизводится в ветке 17-ISbo-2a.

**Comment by YuriSilenok** [comment]
@asOldEye Зачтено

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
