### ISSUE TITLE
"Группы", возможно создать группу с некорректными значениями где "Пар/день min" больше чем "Пар/день max"

### ISSUE THREAD

**Issue by asOldEye** [Students-of-the-city-of-Kostroma/Student-timetable#369]
**Шаги:**
1. Открыть форму "Группы"
2. Открыть окно "Добавление группы"
3. Создать группу, в которой в поле "Пар/день min" значение больше, чем в поле "Пар/день max"

**Ожидаемый результат:**
Выведено сообщение о невозможности создать группу с данными значениями. Группа не создана

**Фактический результат:**
Значения приняты, группа создана
![image](https://user-images.githubusercontent.com/37542164/56240103-40827680-609b-11e9-8a43-b70d13cb8f39.png)

**Comment by YuriSilenok** [comment]
@asOldEye Зачтено в (ТРПО) 16-ИСбо-2а
@Students-of-the-city-of-Kostroma/17isb обратите внимание на этот баг. Я бы дал как минимум средний приоритет.

**Comment by YuriSilenok** [comment]
Возможные варианты Ваших комментариев к багу могут быть:
> Баг не воспроизводится в спринте 17-ISbo-2b-4

> Баг воспроизвелся в спринте 17-ISbo-2b-5

**Comment by map82top** [comment]
Баг воспроизвелся в спринте 17-ISbo-2b-4
Баг не воспроизводится в спринте 17-ISbo-2b-5
