### ISSUE TITLE
Разработать сценарии тестирования пригодных для автоматизации модульным тестированием метода Delete(model:Model) сущности Дисциплина

### ISSUE THREAD

**Issue by cdvinvate** [Students-of-the-city-of-Kostroma/Student-timetable#37]
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)
Реализовать сценарии пригодные для Unit-тестирования
[План разработки](https://docs.google.com/spreadsheets/d/11uPdKMmzZklleijGcBAKoStnVHY2_9qBwRPOpR1y0vM/edit#gid=389498935)
[Ссылка](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit) на диаграмму классов.

**Comment by YuriSilenok** [comment]
Здравствуйте @cdvinvate .
Обратите внимание что у в поле Assignees сейчас два пользователя.
Значит ли это что вы еще что-то делаете над задачей?
Обратите внимание на описание этого поля в [методичке](https://docs.google.com/document/d/1k8ILnmYVi3Cz-mTge3h6RI0OV4DbAHviQseScRRpUxI/edit).
Спасибо.

**Comment by cdvinvate** [comment]
Добрый день.
В поле Assignees два пользователя из-за моей невнимательности. 
Больше я не произвожу над задачей никаких действий.
Спасибо.

**Comment by YuriSilenok** [comment]
Добрый день.
Работа зачтена.
Спасибо.

**Comment by YuriSilenok** [comment]
задача снята

**Comment by MaximTrapeznikov** [comment]
Состояние таблицы контроллера | Shortname [А-Я]{10} | Fullname [А-Я]{1}[а-я]{10},[А-Я]{1}[а-я]{10},[А-Я]{1}[а-я]{10},[А-Я]{1}[а-я]{10} | CycleofDiscipline [А-я]&[0-1]&[.]
-- | -- | -- | --
Удалить запись при совпадении всех атрибутов | task-37-1 | task-37-1 | task-37-1
Удалить запись при совпадении только одного атрибута  | task-37-2 | task-37-3 | task-37-4
Удаление не существующих данных из таблицы | task-37-5 | task-37-5 | task-37-5

**Comment by YuriSilenok** [comment]
@MaximTrapeznikov почему эта задача была открыта?

**Comment by YuriSilenok** [comment]
Удаление существующей строки вы будете осуществлять по совпадению каких атрибутов?

**Comment by YuriSilenok** [comment]
@Students-of-the-city-of-Kostroma/17isa Почему эта задача на разработку сценариев тестированя не включена во второй спринт?

**Comment by YuriSilenok** [comment]
Здравствуйте,

если по этой задаче не будет активности в течении суток, то задача будет передана @IlyaPyatin 

Спасибо,
Юрий

**Comment by MaximTrapeznikov** [comment]
Здраствуйте, @YuriSilenok .

К вопросу: "Удаление существующей строки вы будете осуществлять по совпадению каких атрибутов?"

По совпадению всех атрибутов

Спасибо.

**Comment by MaximTrapeznikov** [comment]
Здраствуйте, @YuriSilenok .

Сценарии исправлены.

Спасибо.

**Comment by YuriSilenok** [comment]
Здравствуйте.

> К вопросу: "Удаление существующей строки вы будете осуществлять по совпадению каких атрибутов?"
> 
> По совпадению всех атрибутов

Если в этом тесте будет сбой, какая функциональность не работает?

Если Вы не повесите задачу на меня, значит я не должен её проверить.

Спасибо.

**Comment by MaximTrapeznikov** [comment]
Здраствуйте, @YuriSilenok .

Удаление существующей строки осущнствляется при совпадении ключевого атрибута "Полное название дисциплины".
Сценарии исправлены.
[Исправлено](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/37#issuecomment-493629282)

Спасибо.

**Comment by YuriSilenok** [comment]
Зачтено
