### ISSUE TITLE
"Дисциплины", на форме "Создание дисциплины" кнопка "Отмена" не работает

### ISSUE THREAD

**Issue by asOldEye** [Students-of-the-city-of-Kostroma/Student-timetable#370]
**Шаги:**
1. Открыть форму "Дисциплины"
2. Открыть форму "Создание дисциплины"
3. Нажать кнопку "Отмена"

**Ожидаемый результат:**
Форма "Создание дисциплины" закрылась

**Фактический результат:**
Ничего не происходит

**Comment by YuriSilenok** [comment]
Фукционал не был реализован на тот момент.
На данный моент баг не вопсроизводится.
