### ISSUE TITLE
В выпадающем меню "Справочники" при нажатии на пункт "Справочники" открывается форма "Аудитории"

### ISSUE THREAD

**Issue by asOldEye** [Students-of-the-city-of-Kostroma/Student-timetable#372]
**Шаги:**
1. Открыть выпадающее меню "Справочники"
2. Нажать на пункт "Справочники"
![image](https://user-images.githubusercontent.com/37542164/56242073-1b443700-60a0-11e9-9a2b-4ef4b8f11a1a.png)

**Ожидаемый результат:**
Ничего не происходит

**Фактический результат:**
Открывается форма "Аудитория"
![image](https://user-images.githubusercontent.com/37542164/56242124-39119c00-60a0-11e9-81c0-a8e93bf761ba.png)

**Comment by YuriSilenok** [comment]
@asOldEye Зачтено в (ТРПО) 16-ИСбо-2а
@Students-of-the-city-of-Kostroma/17isa Это была заглушка, пожалуйста, удалите вторые справочники.

**Comment by YuriSilenok** [comment]
Причина закрытия, где протестировано?

**Comment by YuriSilenok** [comment]
Возможные варианты Ваших комментариев к багу могут быть:
> Баг не воспроизводится в спринте 17-ISbo-2b-4

> Баг воспроизвелся в спринте 17-ISbo-2b-5

**Comment by DariaMann** [comment]
Баг не воспроизводится в спринте 17-ISbo-2a-4

**Comment by YuriSilenok** [comment]
Укажите веху 4 спринта
