### ISSUE TITLE
"Аудитории", некорректное название формы "Добавить аудиторию"

### ISSUE THREAD

**Issue by asOldEye** [Students-of-the-city-of-Kostroma/Student-timetable#377]
**Шаги:**
1. Открыть форму "Аудитории"
1. Открыть форму "Добавить аудиторию"

**Ожидаемый результат:**
Форма в программе на русском языке имеет название на русском языке "Добавить аудиторию"

**Фактический результат:**
Форма имеет некорректное название "AddAuditor"
![image](https://user-images.githubusercontent.com/37542164/56292208-69ece200-612f-11e9-9f12-3996706f55bb.png)

**Comment by YuriSilenok** [comment]
@asOldEye Зачтено (ТРПО) 16-ИСбо-2а

**Comment by YuriSilenok** [comment]
Причина закрытия какая? Где было протестировано?

**Comment by YuriSilenok** [comment]
Возможные варианты Ваших комментариев к багу могут быть:
> Баг не воспроизводится в спринте 17-ISbo-2b-4

> Баг воспроизвелся в спринте 17-ISbo-2b-5

**Comment by DariaMann** [comment]
Баг не воспроизводится в спринте 17-ISbo-2a-4

**Comment by YuriSilenok** [comment]
Укажите веху 4 спринта
