### ISSUE TITLE
"Аудитории", при добавлении аудитории в поле "Корпус" можно ввести только числовое значение

### ISSUE THREAD

**Issue by asOldEye** [Students-of-the-city-of-Kostroma/Student-timetable#378]
**Шаги:**
1. Открыть форму "Аудитории"
2. Открыть форму "Добавить аудиторию"
3. Ввести в поле "Корпус" строковое значение, например "Е" или "А1"

**Ожидаемый результат:**
Введенное значение принято полем

**Фактический результат:**
В поле принимаются только цифры, другие символы не вводятся
![image](https://user-images.githubusercontent.com/37542164/56292895-b97fdd80-6130-11e9-8b02-ea41de99105b.png)

**Comment by YuriSilenok** [comment]
Вы на последней версии ветки Testing тестирует? она в обед обновлял ась.

**Comment by asOldEye** [comment]
Да, тестирую на обновленной ветке. На ней воспроизводятся все вчера описанные мной баги в том числе

**Comment by YuriSilenok** [comment]
@asOldEye Зачтено (ТРПО) 16-ИСбо-2а

**Comment by Jeen99** [comment]
@YuriSilenok, Добрый день. 

Это можно считать багом? Мы реализовывали функционал в соответствие с программой РекторВуз. В этой программе поле **Корпус** содержит только числовое значение. 

![image](https://user-images.githubusercontent.com/32433285/56804661-34cb4880-682f-11e9-9a70-bc781d21834a.png)

**Comment by YuriSilenok** [comment]
В данный момент уже нет.
Но есть идея для фичи на будщий спринт.
Нужно сделать выпадающис список в место номера корпуса. В списке будет содержаться сокращенное название корпуса. Примеры можно посмотреть в нашем расписании
Интерфейс как у кафедры.
![image](https://user-images.githubusercontent.com/14871471/56807309-1ec18600-6837-11e9-9574-fd719244e399.png)
