### ISSUE TITLE
"Аудитории", допускается добавление аудитории с вместимостью 0

### ISSUE THREAD

**Issue by asOldEye** [Students-of-the-city-of-Kostroma/Student-timetable#379]
**Шаги:**
1. Открыть форму "Аудитории"
2. Открыть форму "Добавить аудиторию"
3. Добавить аудиторию, заполнить все поля, в поле "Число мест" оставить значение "0"

**Ожидаемый результат:**
Сообщение о некорректности значения в поле "Число мест"

**Фактический результат:**
Аудитория создана. Значение "Число мест" равно нулю
![image](https://user-images.githubusercontent.com/37542164/56293477-cf41d280-6131-11e9-86b7-24d8b7dbe891.png)

**Comment by YuriSilenok** [comment]
@asOldEye зачтено

**Comment by YuriSilenok** [comment]
Где протестировано?

**Comment by Jeen99** [comment]
@YuriSilenok, закрывать баг должен тестировщик. Я правильно понял?

**Comment by YuriSilenok** [comment]
Да, все так, но кроме этого нужен комментарий.
>@YuriSilenok, закрывать баг должен тестировщик. Я правильно понял?

Возможные варианты Ваших комментариев к багу могут быть:
> Баг не воспроизводится в спринте 17-ISbo-2b-4

> Баг воспроизвелся в спринте 17-ISbo-2b-5

**Comment by DariaMann** [comment]
Баг не воспроизводится в спринте 17-ISbo-2a-4

**Comment by YuriSilenok** [comment]
Укажите веху 4 спринта
