### ISSUE TITLE
Автоматизация unit-test для метода Insert(Model model) сущности Discipline

### ISSUE THREAD

**Issue by alexeylisica** [Students-of-the-city-of-Kostroma/Student-timetable#38]
[Сценарий](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)
[План разработки](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_102)
[Диаграмма классов](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_0)

**Comment by YuriSilenok** [comment]
Здравствуйте.
Зачтено.
Спасибо.
