### ISSUE TITLE
Отсутствие сообщения об ошибке при попытке продублировать существующую сущность

### ISSUE THREAD

**Issue by asOldEye** [Students-of-the-city-of-Kostroma/Student-timetable#380]
**Шаги:**
1. Открыть форму "Аудитории"
2. Добавить аудиторию
3. Добавить вторую аудиторию, у которой значения во всех полях будут идентичны соответствующим значениям первой аудитории (**"создать и закрыть"** или **"создать и очистить"**).

**Ожидаемый результат:**
Выведено сообщение о невозможности добавить аудиторию идентичную существующей. Дубликат аудитории не создан. Поля формы "Добавить аудиторию" не очищены

**Фактический результат:**
Дубликат аудитории не создан. Поля формы "Добавить аудиторию" очищены или закрыто само окно (в соответствии с нажатой кнопкой).

**Затрагиваемые формы:**
- Аудитории
- Дисциплины
- Профиль подготовки
- Направление подготовки

**Comment by YuriSilenok** [comment]
Шаг 3 несколько абстрактный, так как создать аудиторию можно двумя кнопками. Какой именно нужно было написать в шагах. Судя по фактическому результату, то Вы нажимали кнопку Создать и очистить.
![image](https://user-images.githubusercontent.com/14871471/56851324-518e7b80-6916-11e9-9354-20eb395a52f6.png)

**Comment by YuriSilenok** [comment]
@Students-of-the-city-of-Kostroma/17isa 
Сейчас конец вашего спринта который начался 22 числа, эта задача была поднята 17 числа.
Я ожидал что Вы заберете к себе в бэклог.
Кажется я уже писал об этом.
Когда я могу ожидать что вы, для своих предметных областей, просмотрите задачи и заберете их под контроль?

**Comment by YuriSilenok** [comment]
@asOldEye Пожалуйста, дайте более подробные шаги по воспроизведению бага.

**Comment by YuriSilenok** [comment]
Где протестировано?

**Comment by YuriSilenok** [comment]
Возможные варианты Ваших комментариев к багу могут быть:
> Баг не воспроизводится в спринте 17-ISbo-2b-4

> Баг воспроизвелся в спринте 17-ISbo-2b-5

**Comment by DariaMann** [comment]
Баг не воспроизводится в спринте 17-ISbo-2a-4

**Comment by YuriSilenok** [comment]
Укажите веху 4 спринта
