### ISSUE TITLE
Автоматизация тестирования юнит-тестами  для конструктора класса Auditor

### ISSUE THREAD

**Issue by AnastasiaSpihtorenko** [Students-of-the-city-of-Kostroma/Student-timetable#39]
[Сценарий](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)
[План разработки](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_102)
[Диаграмма классов](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_0)

**Comment by YuriSilenok** [comment]
Здравствуйте.
Одно замечание.
Если Вы перевешиваете задачу на другого человека, то с себя ее нужно снять, попробуйте.
Я пока кое-что здесь переименую, так как ошибся при выдаче задания.
Спасибо.

**Comment by YuriSilenok** [comment]
Зачтено
Оценка появиться через несколько минут, как сформирую списки группы
