### ISSUE TITLE
"Ученые звания", необработанное исключение при повторном нажатии кнопки "Удалить"

### ISSUE THREAD

**Issue by asOldEye** [Students-of-the-city-of-Kostroma/Student-timetable#393]
**Шаги:**
1. Открыть форму "Ученые степени"
2. Добавить две записи в таблицу
![image](https://user-images.githubusercontent.com/37542164/56385556-2924c400-6228-11e9-80f0-4132bf4254c2.png)
3. Удалить нижнюю запись
![image](https://user-images.githubusercontent.com/37542164/56385559-2f1aa500-6228-11e9-945a-e0500d731165.png)
4. Повторно нажать на кнопку "Удалить"

**Ожидаемый результат:**
Ничего не произошло

**Фактический результат:**
Показано окно с необработанным исключением "SystemOutOfRangeException"
![image](https://user-images.githubusercontent.com/37542164/56385564-35a91c80-6228-11e9-9890-13a5987f52ea.png)

**Comment by YuriSilenok** [comment]
@asOldEye зачтено

**Comment by YuriSilenok** [comment]
Я бы ожидал следующий сценарий для этого бага.
1. Тимлид найдя этот баг вешает на старшего тестировщика
2. Старший тестировщики определяет кто из тестировщики будет ответственным за этот ба и перевешивает на него. 
3. Тестировщики подтверждает что этот баг воспроизводится, с указанием спринта и перевешивает на старшего разработчика. 
4. Старший разработчик определяет, кто будет кодить и перевешивает на него. 
5. После кодинга мержа, разраб перевешивает на тестера
6. Тестер повторно проверяет баг и сообщает о результате с указанием спринта. Закрывает баг или отправляет разраб на доработку.

**Comment by ghost** [comment]
Здравствуйте. 

Что нам теперь делать?

**Comment by YuriSilenok** [comment]
Начните с пункта 5.

**Comment by Pipyao** [comment]
Done

**Comment by YuriSilenok** [comment]
Тестировщик сообщает о результате тестирования с указанием спринта и т.д.

**Comment by YuriSilenok** [comment]
> Тестировщик сообщает о результате тестирования с указанием спринта и т.д.

Где сообщения от тестировщика?

Что-то я по атрибутам не вижу ни ответственного за задачу, ни в каком спринте эта задача выполняется.

**Comment by nrabotko** [comment]
Исправление бага, возникающего при повторном нажатии кнопки "Удалить".
Данный баг был исправлен в [#602](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/602)

**Comment by YuriSilenok** [comment]
> Исправление бага, возникающего при повторном нажатии кнопки "Удалить".
> Данный баг был исправлен в [#602](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/602)

Я так и не понял, баг воспроизвелся или не воспроизводится и в какой ветке?
> Баг не воспроизвелся в ветке....из акрыть задачу если не воспроизводится

**Comment by ghost** [comment]
Баг был устранен в ветке Alliance-3
Запрос на слияние веток #602
