### ISSUE TITLE
"Ученые степени", кнопка "Изменить" не реагирует на нажатия

### ISSUE THREAD

**Issue by asOldEye** [Students-of-the-city-of-Kostroma/Student-timetable#394]
**Шаги:**
1. Открыть форму "Ученые степени"
2. Добавить запись в таблицу
3. Нажать кнопку "Изменить"

**Ожидаемый результат:**
Открылась форма "Редактирование ученой степени"

**Фактический результат:**
Ничего не происходит

**Comment by yuliagolubevaa5** [comment]
Находится в разработке
![image](https://user-images.githubusercontent.com/47320351/56387703-af8fd480-622d-11e9-8d39-9189d4a9afa5.png)

**Comment by YuriSilenok** [comment]
1. Тогда нужно сменить метку на ученую степень
2. Поместить на доску
3. Поместить в бэклог.

**Comment by YuriSilenok** [comment]
@nastyarabotko  Отдайте тестироващикам, пусть проверят в своей ветке и отпишут о результатах
Нехорошо то, что этот таск лежит без дела уже месяц.

**Comment by nrabotko** [comment]
Хорошо, будет сделано.

**Comment by YuriSilenok** [comment]
Веху

**Comment by yuliagolubevaa5** [comment]
![image](https://user-images.githubusercontent.com/47320351/57880447-7300ca00-7827-11e9-8434-206b1f6d991f.png)
При нажатии кнопки "Изменить" открывается форма "Изменение уч. звания". Ожидаемый результат совпадает с фактическим.

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
