### ISSUE TITLE
Автоматизация сценариев для метода Update(model:Model) сущности Teacher

### ISSUE THREAD

**Issue by Chippa99fm** [Students-of-the-city-of-Kostroma/Student-timetable#4]
Разработать сценарии пригодные для Unit-тестирования в эту [таблицу](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548).
[План разработки](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.p).
[Ссылка ](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit)на диаграмму классов.

**Comment by VinogradovAlexandr781227** [comment]
Вау!!! Классная работа!!!

**Comment by VinogradovAlexandr781227** [comment]
> Вау!!! Классная работа!!!

**Comment by Chippa99fm** [comment]
> Вау!!! Классная работа!!!

Спасибо!! Так приятно!!

**Comment by YuriSilenok** [comment]
Добрый день @Chippa99fm 

В заголовке задачи упомянута сущность преподаватель, в метках фигурирует группа.

@VinogradovAlexandr781227 не нужно устраивать беспредел, на каком основании вы закрыли таск? он выполнен?

**Comment by YuriSilenok** [comment]
Зачтено
