### ISSUE TITLE
Реализовать метод Insert(model:Model) класса Auditor

### ISSUE THREAD

**Issue by ifuwmnn** [Students-of-the-city-of-Kostroma/Student-timetable#40]
реализовать в ветку issue-169

Приступать после реализации конструктора #167

**Поведение**: метод добавляет новую аудиторию в том случае если поля

```csharp
        string number;
        byte floor; 
        string building;
        int spacious;
```

являются уникальными и не пустыми. Если добавление в таблицу произошло, то метод вернет истину, в других случаях метод возвращает ложь.

[Ссылка](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit?usp=sharing) на диаграмму классов.

**Comment by YuriSilenok** [comment]
Здравствуйте @ifuwmnn 
Вы закончили работать на задачей?
Спасибо.

**Comment by ifuwmnn** [comment]
Здравствуйте @YuriSilenok 
Я закончил задание.
Извените за долгое ожидание.
Спасибо.

**Comment by YuriSilenok** [comment]
Здравствуйте. @ifuwmnn 
Вам нужно указать веху (Milestone)
И сначала пишут комментарий, а потом перевешивают задачу.
Пожалуйста, сохраните форматирование описания как в исходной задаче.
Спасибо.

**Comment by YuriSilenok** [comment]
Здравствуйте @SamuraSwordS 
Эта Ваша задача на разработку.
Прошу учесть что эта задача еще не закончена пользователем @ifuwmnn
Но сведений в этой задаче достаточно для реализации ее.
Спасибо.

**Comment by YuriSilenok** [comment]
@SamuraSwordS зачтено, баллы выставлю.
Задача будет закрыта позже, после того как закончат с этой задачей все остальные.
Спасибо.

**Comment by ifuwmnn** [comment]
Здравствуйте @YuriSilenok
Я закончил задание.
Извините за долгое ожидание.
Спасибо.

**Comment by YuriSilenok** [comment]
@ifuwmnn  зачтено.
