### ISSUE TITLE
Привести имена столбцов в соответствие с программой

### ISSUE THREAD

**Issue by MariNazarova** [Students-of-the-city-of-Kostroma/Student-timetable#401]
Необходимо сделать во вкладке "Справочники. Виды занятий подготовки" два столбца "Полное название вида занятий" и "Сокращённое название вида занятий" по данному образцу.

![image](https://user-images.githubusercontent.com/47637247/56391148-76a82d80-6236-11e9-9240-3d6a092acc0f.png)

Проделывать это необходимо в форме TypesOfOccupations проекта.

**Comment by YuriSilenok** [comment]
Когда ожидать изменений по этой задаче?

**Comment by MariNazarova** [comment]
Задача реализована в третьем спринте

**Comment by MariNazarova** [comment]
> Когда ожидать изменений по этой задаче?

Задача реализована в третьем спринте
