### ISSUE TITLE
Разработка сортировки таблицы Виды занятий подготовки

### ISSUE THREAD

**Issue by MariNazarova** [Students-of-the-city-of-Kostroma/Student-timetable#404]
Разобраться в способах сортировки строк таблицы 

Сортировка должна работать следующим образом: нажимается один из столбцов таблицы и таблица сортируется по этому столбцу по возрастанию/убыванию его значений (противоположное тому, которое было ранее)

После пересортировки выбранная строка не должна терять фокус.
По окончании сортировки должна производиться перенумерация.

**Comment by YuriSilenok** [comment]
Задача не актуальна
