### ISSUE TITLE
Разработать сценарии тестирования пригодные для автоматизации модульным тестированием для конструктора класса CAuditor

### ISSUE THREAD

**Issue by ivshr** [Students-of-the-city-of-Kostroma/Student-timetable#41]
[Сценарий](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)
[План разработки](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.p)
[Диаграмма классов](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit)

**Comment by YuriSilenok** [comment]
Здравствуйте.
Могли бы Вы пояснить выбор меток зеленого (#0e8a16) цвета?
Спасибо.

**Comment by ivshr** [comment]
Здравствуйте.

Метка Script - указывается, если задача ставиться на написание сценариев. Метка Auto test была указана по ошибке.

Спасибо.
Щербаков Иван.
17-ИДбо-3а.

**Comment by YuriSilenok** [comment]
Поздравляю @ivshr  
Зачтено

**Comment by YuriSilenok** [comment]
Проглядел, Вы забыли поставить метку контроллера.

**Comment by ivshr** [comment]
Спасибо.
Щербаков Иван.
17-ИДбо-3.
