### ISSUE TITLE
Разработка сценариев тестирования для формы "Изменить преподавателя"

### ISSUE THREAD

**Issue by alexeylisica** [Students-of-the-city-of-Kostroma/Student-timetable#417]
Story: [#194](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/194)
[Ссылка на сценарий](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)

**Comment by YuriSilenok** [comment]
Задача закрыта по не активности
