### ISSUE TITLE
Разработать сценарии тестирования пригодные для автоматизации модульным тестированием для класса MAuditor

### ISSUE THREAD

**Issue by Tokotoru** [Students-of-the-city-of-Kostroma/Student-timetable#42]
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)
[План разработки](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_102)
[Диаграмма классов](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit)

**Comment by YuriSilenok** [comment]
Здравствуйте @Tokotoru .
Обратите внимание что заголовок задачи должен отвечать на вопрос "что сделать?", об этом было прописано в задании.

Могли бы Вы пояснить выбор меток?

**Comment by Tokotoru** [comment]
Добрый вечер.

Заголовок задачи был исправлен.

Метка Auditor - задача относится к типу Аудитория.
Метка Model - название класса начинается с большой буквы M.
Метка Skript - задача на написание сценариев.
Метка Unit test - задача относится к тестовым сценариям для unit-тестирования.
Метка new() удалена. 
Метка Model добавлена.

Спасибо.
Рагожник Никита.
17-ИДбо-3а.

**Comment by YuriSilenok** [comment]
Добрый день. 
Теперь все верно.
Зачтено.
Спасибо.

**Comment by map82top** [comment]
Какие ограничения могут быть на поле корпус?

**Comment by map82top** [comment]
Входной   параметр | Позитивный класс | Негативный класс
-- | -- | --
А - номер аудитории | a1 ∈ [1; +∞) - целое число -  удачное создание   класса(удачное измение значения свойства) | a2 ∈ (-∞; 1) - целое число - ошибка при создание класса(ошибка   при измение значения свойства)
a3 ∈ не целые числа - ошибка при создание класса(ошибка при измение значения   свойства)
B - этаж | b1 ∈ [1; +∞) - целое число -  удачное создание класса(удачное измение   значения свойства) | b2 ∈ (-∞; 1) - целое число - ошибка при создание класса(ошибка при измение значения   свойства)
b3 ∈ не целое число - целое число - ошибка при создание класса(ошибка при измение   значения свойства)
С - корпус | Любое значение   (существует, потому что без него невозможно создать конструктор)
D -   вместительность аудитории | d1 ∈ [1; 1000] - целое число -  удачное создание класса(удачное измение значения свойства) | d2 ∈ (-∞; 1) - целое число - ошибка при создание класса(ошибка   при измение значения свойства)
d3 ∈ (1000; +∞) - целое число - ошибка при создание класса(ошибка при измение значения   свойства)
d4 ∈ не целые числа - ошибка при создание класса(ошибка при измение значения   свойства)

**Comment by map82top** [comment]
Входной   параметр | Позитивный класс | Негативный класс
-- | -- | --
А - номер аудитории | a1 ∈ [1; +∞) - _целое число_ -  **удачное создание   класса(удачное изменение значения свойства)** | a2 ∈ (-∞; 1) - _целое число_ - **ошибка при создание класса(ошибка   при изменении значения свойства)**
  |   | a3 ∈ не целые числа - **ошибка при создание класса(ошибка при изменении значения   свойства)**
B - этаж | b1 ∈ [1; +∞) - _целое число_ -  **удачное создание класса(удачное изменение   значения** свойства) | b2 ∈ (-∞; 1) - _целое число_ - **ошибка при создание класса(ошибка при изменении значения   свойства)**
  |   | b3 ∈ не целое число  -   **ошибка при создание класса(ошибка при изменении значения свойства)**
С - корпус | Любое значение   (существует, потому что без него невозможно создать конструктор)
D - вместительность аудитории | d1 ∈ [1; 1000] - _целое число_ -  **удачное создание класса(удачное изменение значения свойства)** | d2 ∈ (-∞; 1) - _целое число_ - **ошибка при создание класса(ошибка   при изменении значения свойства)**
  |   | d3 ∈ (1000; +∞) - _целое число_ - **ошибка при создание класса(ошибка   при изменении значения свойства)**
  |   | d4 ∈ не целые числа - **ошибка при создание класса(ошибка при изменении значения свойства)**





Комбинации классов эквивалентности в соответствии со стратегий Сильный-Нормальный:
(a1,b2,c,d1), (a2,b1,c,d2), (a3,b3,c,d3), (a1,b1,c,d4), (a1,b1,c,d1)
[Сценарии тестирования.xlsx](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/files/2902208/default.xlsx)

**Comment by map82top** [comment]
Входной параметр | Позитивный класс | Негативный класс
-- | -- | --
А - номер аудитории | a1 ∈ [1; +∞) - целое число -  удачное создание класса(удачное изменение значения свойства) | a2 ∈ (-∞; 1) - целое число - ошибка при создание класса(ошибка при изменении значения свойства)
a3 ∈ не целые числа - ошибка при создание класса(ошибка при изменении значения свойства)
B - этаж | b1 ∈ [1; +∞) - целое число - удачное создание класса(удачное изменение значения свойства) | b2 ∈ (-∞; 1) - целое число - ошибка при создание класса(ошибка при изменении значения свойства)
b3 ∈ не целое число - целое число - ошибка при создание класса(ошибка при изменении значения свойства)
С - корпус | Любое значение (существует, потому что без него невозможно создать конструктор)
D - вместительность аудитории | d1 ∈ [1; 1000] - целое число - удачное создание класса(удачное изменение значения свойства) | d2 ∈ (-∞; 1) - целое число - ошибка при создание класса(ошибка при изменении значения свойства)
d3 ∈ (1000; +∞) - целое число - ошибка при создание класса(ошибка при изменении значения свойства)
d4 ∈ не целые числа - ошибка при создание класса(ошибка при изменении значения свойства)

**Comment by map82top** [comment]
Входной   параметр | Позитивный класс | Негативный класс
-- | -- | --
А - номер аудитории | a1 ∈ [1; +∞) - целое число -  удачное создание   класса(удачное изменение значения свойства) | a2 ∈ (-∞; 1) - целое число - ошибка при создание класса(ошибка   при изменении значения свойства)
  |   | a3 ∈ не целые числа - ошибка при   создание класса(ошибка при изменении значения свойства)
B - этаж | b1 ∈ [1; +∞) - целое число -  удачное создание класса(удачное изменение   значения свойства) | b2 ∈ (-∞; 1) - целое число - ошибка при создание класса(ошибка при изменении значения   свойства)
  |   | b3 ∈ не целое число -  ошибка при создание класса(ошибка при   изменении значения свойства)
С - корпус | Любое значение   (существует, потому что без него невозможно создать конструктор)
D - вместительность аудитории | d1 ∈ [1; 1000] - целое число -  удачное создание класса(удачное изменение значения свойства) | d2 ∈ (-∞; 1) - целое число - ошибка при создание класса(ошибка   при изменении значения свойства)
  |   | d3 ∈ (1000; +∞) - целое число - ошибка при создание класса(ошибка   при изменении значения свойства)
  |   | d4 ∈ не целые числа - ошибка при   создание класса(ошибка при изменении значения свойства)

**Comment by YuriSilenok** [comment]
Здравствуйте,
так как подход в тестировании будет сменен (в место классов эквивалентности будет тестирование методом белый ящик) то классы эквивалентности не могут быть приняты в качестве ЛР, но если Вас интересует ошибки в том что Вы уже сделали, я могу проверить по Вашему желанию.
Спасибо.

**Comment by map82top** [comment]
Да, проверьте, пожалуйста.

**Comment by YuriSilenok** [comment]
Здравствуйте.
В классах эквивалентности там где Вы пишите _целое число_. Это необязательная часть, используется при неочевидности или сложности описания границ класса эквивалентности. Но если указывать их, то нужно указывать отличительные особенности. То есть, целые числа большие нуля в математической записи a1 ∈ [1; +∞) ∩ ℤ 
[Здесь](https://ru.wikipedia.org/wiki/%D0%A2%D0%B0%D0%B1%D0%BB%D0%B8%D1%86%D0%B0_%D0%BC%D0%B0%D1%82%D0%B5%D0%BC%D0%B0%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D1%85_%D1%81%D0%B8%D0%BC%D0%B2%D0%BE%D0%BB%D0%BE%D0%B2) Вы можете найти шпаргалку по всем значкам
[Здесь ](https://unicode-table.com/ru/search/?q=%D0%9F%D0%B5%D1%80%D0%B5%D1%81%D0%B5%D1%87%D0%B5%D0%BD%D0%B8%D0%B5)Вы можете найти и скопировать любой символ таблицы юникод.
Из [диаграммы классов](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit) Вы могли увидеть поля и их типы. Можно было задаться вопросом, а почему номер аудитории это строка, ответ прост, что бы можно было записать в него префикс, например **Е-330**. То есть, это уже не число.
А в [этом](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/79) таске, сказано что номер аудитории это строковое поле.
По поводу корпуса, пустая строка это строковое значение которое может принимать строка, null хоть и спорно, но тоже туда. Проверить просто, переменной строкового типа можно присвоить **значение** null.
Вопрос в том, должна ли создаваться аудитория у которой не указан корпус.
По поводу численности, откуда была взята 1000?
В [этой](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/79) задаче ставятся другие критерии
Даже если по какой-то причине удалось выделить всего один класс, то у него все равно должна быть цифра. То есть с1 как Вашем случае.
Еще немного про нецелые числа, они оправданы если есть возможность их вводить или передавать. В нашем конструкторе такой возможности нет.
По поводу комбинирования, когда по одному из параметров заканчиваются классы, продолжают их комбинировать по кругу. (исключения могут составлять зависимые входные параметры, но об этом расскажет Людмила Юрьевна) в идеале у вас должны били получиться комбинации.
(a1,b1,c1,d1)
(a2,b2,c1,d2)
(a3,b3,c1,d3)
(a1,b1,c1,d4)
По поводу файла который прикрепили, нужно было реализовывать сценарии в [общую гугл-таблицу](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548) на которую дана ссылка и соответственно туда нужно было реализовать сценарии, посмотрите эту таблицу, там есть набросок.

**Comment by map82top** [comment]
К сожалению, когда вы давали задание вы не дали ссылку на задачу #79, поэтому я не знал какие значения являются валидными. Спасибо за развёрнутое объяснение!

**Comment by YuriSilenok** [comment]
Добрый вечер.

Пожалуйста, зайдите на гитхаб в эту задачу, посмотрите как выглядит [Ваше сообщение](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/42#issuecomment-467972176).

В мире тестирования предполагают только то, где может быть баг, а относительно того, как должна работать исследуемая функциональность всегда задают кучу вопросов и могут положиться только на спецификацию (или задачи с пометкой Story).

Спасибо.
