### ISSUE TITLE
Провести мануальное тестирование привода имен столбцов в соответствие с программой сущности MTrainingProfile

### ISSUE THREAD

**Issue by DariaMann** [Students-of-the-city-of-Kostroma/Student-timetable#426]
Результаты запишите в [таблице](https://docs.google.com/spreadsheets/d/1t9y-_UcpycOjfdrDpgDd9lZcBNyQTyJblwOuONH859U/edit#gid=0)

**Comment by GubanovAndrey** [comment]
Мануальное тестирование провел
