### ISSUE TITLE
Автоматизация сценариев для метода Update(model:Model) класса CAuditor унаследованного от класса Controller

### ISSUE THREAD

**Issue by ghost** [Students-of-the-city-of-Kostroma/Student-timetable#44]
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548
)
[Ссылка](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit
) на диаграмму классов.
Имя файла, содержащего автотесты UT_CAuditor

**Comment by YuriSilenok** [comment]
Зачтено

**Comment by YuriSilenok** [comment]
Здравствуйте @AndreiDevyaterikov.
Вы не прошли тестирование по гугл форме, 3 пункт в лабораторной работе.
По самой задаче замечаний нет.
Спасибо.

**Comment by YuriSilenok** [comment]
Здравствуйте @AndreiDevyaterikov 
Видел что Вы заполнили форму, а раз проблема решена, пора перевешивать задачу.
Спасибо.

**Comment by YuriSilenok** [comment]
Зачтено
