### ISSUE TITLE
При добавлении или изменении преподавателя, нет возможности указать что отчество не существует.

### ISSUE THREAD

**Issue by Chippa99fm** [Students-of-the-city-of-Kostroma/Student-timetable#447]
Шаги:
1. Открыть форму "Преподаватели"
2. Нажать кнопку "Добавить"
2.1 Заполнить строку нужными значениями, кроме отчества, нажать "добавить"
Ожидаемый результат:
Данные добавятся в таблицу, а у поля "отчество" будет значение - null

Фактический результат:
Нельзя не указывать поле "отчество" т.к. оно является обязательным

**Comment by Chippa99fm** [comment]
Реализовано в task-447
Шаги:
1. Открыть форму "Преподаватели"
2. Нажать кнопку "Добавить"
2.1 Заполнить строку нужными значениями, кроме отчества, нажать "добавить"
Ожидаемый результат:
Данные добавятся в таблицу, а у поля "отчество" будет значение - null

Фактический результат
Нельзя не указывать поле "отчество" т.к. оно является обязательным

**Comment by YuriSilenok** [comment]
@Students-of-the-city-of-Kostroma/17isb 
баг в целом не должен содержать слово баг, для этого есть метки или тип задачи.
текущее название не до конца отображает суть проблемы.
есть правило "ЧТО ГДЕ КОГДА" для заголовка проблемы. 
я бы ожидал увидеть приблизительно следующий заголовок.
При добавлении или изменении преподавателя, нет возможности указать что отчество не существует.
это кстати выглядит уже не как баг, а как улучшение.
эту проблему можно решить добавив чекбокс с текстом "Нет отчества" при нажатии на которое текстовое поле для отчества будет становиться неактивным.

**Comment by YuriSilenok** [comment]
Вы поймали волну, но если это становится фича, нужно формулировать что должны реализовать разрабы (в идеальном мире)(но это не критично, и так поймут)
> @Chippa99fm Chippa99fm added improvement  and removed Bug  labels
