### ISSUE TITLE
Автоматизация тестирования юнит-тестами для класса MAuditor  

### ISSUE THREAD

**Issue by nrabotko** [Students-of-the-city-of-Kostroma/Student-timetable#45]
Протестировать код по существующим сценариям, которые описаны в этой [таблице](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit?usp=sharing)
[План разработки](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.p)
[Ссылка](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit) на диаграмму классов

**Comment by YuriSilenok** [comment]
Добрый день @nastyarabotko .
Я ошибочно добавил Вас не в ту команду.
На почту должно придти еще одно приглашение в правильную команду.
Работа зачтена.
Спасибо.
