### ISSUE TITLE
Разработать форму "Институт"

### ISSUE THREAD

**Issue by nrabotko** [Students-of-the-city-of-Kostroma/Student-timetable#452]
Профиль подготовки содержит следующие поля:  

       1.  Краткое название института (string)
       2.  Полное название института (string) 
       3.  Директор института (string) 
       4.  Добавить кнопки "Удалить", "Добавить" и "Изменить"

 Модель и Контроллер для Профиля реализуются по аналогии с уже существующими классами в LibOfTimetableOfClasses.

 Для выполнения задачи создать отдельную ветку от Alliance-2-design по шаблону, как мы делали. После выполнения задания сделать запрос на мерж по тому же шаблону.

**Comment by ghost** [comment]
Разработана форма "Институт"
