### ISSUE TITLE
Разработать метод Update(Model model) сущность Auditor

### ISSUE THREAD

**Issue by MariNazarova** [Students-of-the-city-of-Kostroma/Student-timetable#46]
Поведение:
в метод передается объект, проверяется его существование в таблице, если такой есть, далее метод изменяет информацию о существующей аудитории в том случае если поля
```
string number;
string building;
```
являются уникальными и не пустыми (производится проверка). Если изменение произошло, то метод вернет истину, в других случаях метод возвращает ложь. 
[Ссылка](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit) на диаграмму классов.

**Comment by YuriSilenok** [comment]
Добрый день @MariNazarova
Вы закончили работать над задачей?
Если да, то обратите внимание что поле Assignees не заполнено.
Спасибо.

**Comment by YuriSilenok** [comment]
Зачтено

**Comment by YuriSilenok** [comment]
Здравствуйте @netever,
Это Ваша новая задача на реализацию.
Спасибо.

**Comment by YuriSilenok** [comment]
Зачтено
