### ISSUE TITLE
Разработать сценарии тестирования для сортировки таблицы "Вид занятия"

### ISSUE THREAD

**Issue by ivshr** [Students-of-the-city-of-Kostroma/Student-timetable#477]
очень плохое описание

**Comment by YuriSilenok** [comment]
не актуально

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче
