### ISSUE TITLE
Написать unit-тесты для метода Update(Model model) сущности CUniversity

### ISSUE THREAD

**Issue by VinogradovAlexandr781227** [Students-of-the-city-of-Kostroma/Student-timetable#497]
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=983700952)

**Comment by YuriSilenok** [comment]
@Students-of-the-city-of-Kostroma/17isb 
Мы с вами обсуждали что сценарии должны быть в обще таблице.
Сколько вам нужно времени чтобы:
1. Перенести все сценарии в общую таблицу?
2. Из всех задача всех спринтов удалить ссылки на вашу таблицу?
