### ISSUE TITLE
Список ошибок

### ISSUE THREAD

**Issue by Jeen99** [Students-of-the-city-of-Kostroma/Student-timetable#499]
1) Задать минимальный размер форм (Аудитория, Дисциплина, Профиль подготовки)
2) Убрать вывод сообщения при попытке удалить пустую строку (Профиль подготовки)
3) Поправить название формы "Добавить профиль"
4) Поправить название формы "Добавить дисциплину"

**Comment by YuriSilenok** [comment]
Название задачи не отражает ее сути.
По сути у Вас здесь 4 задачи.
Объединение приведет к путанице.
Больше так не делать.

**Comment by YuriSilenok** [comment]
Задача следующая.
Поднять 4 таска. 
На каждый из этих тасков должен ссылаться уже созданный 502 пулреквест.
Метки этого таска убрать 
Сменить заголовок этого таска на "Задача поднята ошибочно"
Закрыть эту задачу.

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
