### ISSUE TITLE
Разработать сценарии тестирования пригодные для автоматизации модульным тестированием метода Delete(Model model) сущности Преподаватель

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Student-timetable#5]
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=1813879881)

**Comment by YuriSilenok** [comment]
Добрый день  @KharlamovaAlexandra 

Для этой задачи нет описания.
Обратите внимание на [аналог](https://gitlab.com/YuriSilenok/Student-timetable/issues/183) вашей задачи, не все метки присутсвуют.

Спасибо.

**Comment by KharlamovaAlexandra** [comment]
Добрый день!

Нужно ли оповещать вас по почте после того как задание было переделано или
вы увидите это сами?

С уважением, Харламова Александра
17-ИСбо-2б


вт, 5 февр. 2019 г. в 10:14, Юрий Силенок <notifications@github.com>:

**Comment by YuriSilenok** [comment]
Добрый день.

Что бы я задачу посмотрел, нужно ее заасанить на меня.

Спасибо.

**Comment by YuriSilenok** [comment]
Зачтено

**Comment by YuriSilenok** [comment]
Здравствуйте @KharlamovaAlexandra 
Поясните пожалуйста, почему Вы делали не свое задание?
Ваша задание было 
> поднять задачу на разработку метода Update(Model model) сущности Teacher

А Вы подняли задачу на написание сценариев.
Спасибо

**Comment by KharlamovaAlexandra** [comment]
Добрый вечер!

Видимо возникло какое - то недоразумение. Мне пришло два письма с домашним
заданием и получилось так, что я не обратила внимание на первое и начала
выполнять задание из второго.Прилагаю скриншоты писем.

С уважением, Харламова Александра
17-Исбо-2б

сб, 16 февр. 2019 г. в 21:55, Юрий Силенок <notifications@github.com>:

**Comment by YuriSilenok** [comment]
Добрый день.
Если Вы пишете письмо на адрес гитхаба, то ваши фото  и другие файлы могу не прикрепиться, как это произошло сейчас. Лучше отвечать на гитхабе. Всегда проверяйте корректность сообщений.

Я нашел эти два письма. Это произошло по нескольким причинам.

1. Была прервана цепочка писем, (это требование из документа "Как писать письма?") тему нужно было переименовать, а не писать новое письмо.
2. Вы правильно подметили что Вы не обратили внимание на первое письмо. Внимательное прочтение писем позволило бы избежать этой ситуации.

Спасибо.

**Comment by YuriSilenok** [comment]
Задача снята по не активности

**Comment by YuriSilenok** [comment]
Снято по не активности

**Comment by YuriSilenok** [comment]
Если вы изменили сценарии, в таске нужно указать что именно изменилось.
