### ISSUE TITLE
Таблица содержащая сведения о группах должна иметь только один уникальный столбец

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#50]
Столбец **byte population;** необходимо вывести из составного ключа.
Этот баг затрагивает #14

**Comment by netever** [comment]
@YuriSilenok 
Здравствуйте.
Хочу уточнить, нужно ли мне изменения заливать в 14 таск или делать пул реквест именно на этот?
Спасибо.

**Comment by YuriSilenok** [comment]
Здравствуйте @netever 
Для этого бага task-50 делается новая ветка, все как обычно.
Спасибо.

**Comment by YuriSilenok** [comment]
@netever Зачтено
