### ISSUE TITLE
При изменении ВУЗа можно задать дублирующий ИНН и сохранить. 

### ISSUE THREAD

**Issue by KudelinRoman** [Students-of-the-city-of-Kostroma/Student-timetable#512]
Шаги:
1. Создать два ВУЗа с разными атрибутами
2. Вызвать метод Update (кнопочка изменить) для одного из ВУЗов
3. Изменить ИНН на тот который у другого ВУЗа.
4. Нажать "Сохранить"
В итоге в таблице ИНН не измениться, но действие сохранить пройдет (Ожидалось бы предупреждение о повторном ИНН и запрет сохранения)
Из-за этого не проходит тест.
![image](https://user-images.githubusercontent.com/47320335/56840429-2d885700-6890-11e9-9f8c-1d0b2e383616.png)
[Проверка тестов](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/runs/112319456)

**Comment by KudelinRoman** [comment]
unit-тесты написаны.
Чтобы убедиться в устранении этого бага выполните тесты.

**Comment by YuriSilenok** [comment]
Заголовок бага должен ответить на вопросы что где когда не работает.
А сейчас у вас на таск разработки больше похоже.

**Comment by YuriSilenok** [comment]
Чтобы убедиться в выполнении исправления этого бага, должна быть ветка на баг и коммит который исправляет этот баг который спровоцирует успешное прохождение автотеста.
> Чтобы убедиться в устранении этого бага выполните тесты.

**Comment by map82top** [comment]
Баг не существует

**Comment by YuriSilenok** [comment]
@map82top Говорить о том что баг не существует не совсем корректно.
Правильнее говорить что он воспроизводится или не воспроизводится, а в идеальном мире указывается версия программного продукта на которой баг воспроизвелся или не воспроизвелся. В Вашем случае в место версии ПО будет название ветки в которой он не воспроизвелся.

**Comment by YuriSilenok** [comment]
Я теперь понял что Вы имели ввиду. Я бы ожидал здесь такую формулировку. 
Проверьте воспроизводится ли баг при помощи существующего (тут можно указать номер если под рукой) тестового сценария.
> Чтобы убедиться в устранении этого бага, выполните тесты.

**Comment by YuriSilenok** [comment]
В каком спринте баг не воспроизводится?

**Comment by map82top** [comment]
Баг воспроизвелся в спринте 17-ISbo-2b-4
Баг не воспроизводится в спринте 17-ISbo-2b-5
