### ISSUE TITLE
Создать форму "Параметры". Вкладка День.

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#517]
Форма вызывается из меню Настройки-Параметры.
Имеет название формы **параметры** и повторяет интерфейс как на изображении.
Реализовать только вкладку День
![image](https://user-images.githubusercontent.com/14871471/56850664-361f7280-690e-11e9-8c0a-9ff501b7c731.png)

**Comment by YuriSilenok** [comment]
Задача снята по не активности и передана @DenisSavelev

**Comment by YuriSilenok** [comment]
В качестве ЛР03 вы делали эту задачу?

**Comment by DenisSavelev** [comment]
> В качестве ЛР03 вы делали эту задачу?

Да

**Comment by DenisSavelev** [comment]
> > В качестве ЛР03 вы делали эту задачу?
> 
> Да

Что с третьей лабораторной? Я выполнил в срок

**Comment by YuriSilenok** [comment]
в скором времени  проверю

**Comment by YuriSilenok** [comment]
зачтено
