### ISSUE TITLE
Создать форму "Параметры". Вкладка Даты

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#518]
Форма вызывается из меню Настройки-Параметры.
Имеет название формы параметры и повторяет интерфейс как на изображении.
Реализовать только вкладку Даты
![image](https://user-images.githubusercontent.com/14871471/56850826-72ec6900-6910-11e9-8527-e1252993b4f7.png)

**Comment by YuriSilenok** [comment]
Добрый день,

Если в течении суток по задаче не будет активности, то она будет передана @IlyaPyatin 

Спасибо,
Юрий

**Comment by IlyaPyatin** [comment]
@YuriSilenok Здравствуйте,

Где находится форма меню "Настройки"?

Спасибо.

**Comment by YuriSilenok** [comment]
задача снята по не активности

**Comment by YuriSilenok** [comment]
почему запрос #1114 был закрыт?

**Comment by YuriSilenok** [comment]
зачтено
