### ISSUE TITLE
 Программа вылетает при введении в поле "ФИО" формы ВУЗ, только фамилии и имени

### ISSUE THREAD

**Issue by Proffet78** [Students-of-the-city-of-Kostroma/Student-timetable#525]
Шаги:

1) Добавить ВУЗ
2) В поле "ФИО" ввести Иванов Иван
3) Нажать "Сохранить"
В итоге программа вылетает 

![viu1q9rWyPw](https://user-images.githubusercontent.com/47320491/56853758-ce305280-6934-11e9-84ea-0945a1fe3444.jpg)

**Comment by map82top** [comment]
Этот один и тот же баг

**Comment by Proffet78** [comment]
Один работает при изменении, а другой при создании.

**Comment by map82top** [comment]
Но ошибка в коде из-за которой возникают эти проблемы одна
