### ISSUE TITLE
В поле "Телефон" формы "ВУЗы", нет привязки к определенному кол-ву символов

### ISSUE THREAD

**Issue by Proffet78** [Students-of-the-city-of-Kostroma/Student-timetable#529]
В поле "Телефон" формы вузы можно изначально задать или изменить номер, у которого кол-во символов не будет соответствовать стандартам. ( Стандарт это 8-9**-***-**-**)

![g0A7B8l0Sac](https://user-images.githubusercontent.com/47320491/56854321-2d926080-693d-11e9-94d3-3e100cc3870a.jpg)

**Comment by map82top** [comment]
В номере телефона в зависимости от города может быть различное количество цифр в номере.
Поэтому это не является багом
