### ISSUE TITLE
Добавить в ветку 17-ISbo-2b-5 изменений из ветки Testing 

### ISSUE THREAD

**Issue by map82top** [Students-of-the-city-of-Kostroma/Student-timetable#542]
Необходимо решить конфликты и получить обновления из ветки тестинг командой git merge

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу
