### ISSUE TITLE
невозможно добавить дисциплину

### ISSUE THREAD

**Issue by ssas18** [Students-of-the-city-of-Kostroma/Student-timetable#558]
После добавления дисциплин, а далее их полного удаления, при попытке создать новую дисциплину, вылезает данная ошибка
![image](https://user-images.githubusercontent.com/47377817/56972487-bf83ae80-6b73-11e9-9faf-8e8eff46f9ed.png)

**Comment by Jeen99** [comment]
@ssas18, Судя по скриншоту - это старая версия программы. Пожалуйста, перепроверь на новой. Из ветки 17-ISbo-2a-4. 

Команды для гитбаша, чтобы обновить репозиторий и перейти в рабочую ветку:
```
git pull
git checkout 17-ISbo-2a-4
```
