### ISSUE TITLE
Форма добавления "Направления подготовки" не появляется при нажатии кнопки

### ISSUE THREAD

**Issue by bormolei** [Students-of-the-city-of-Kostroma/Student-timetable#559]
При нажатии на кнопку "добавить" на форме "Направление подготовки" не появляется форма добавления направления подготовки.
![image](https://user-images.githubusercontent.com/46655821/56980907-3f1a7900-6b86-11e9-880c-7de1ad20268c.png)

**Comment by Jeen99** [comment]
В текущий момент это не баг, т.к. это форма до конца еще не реализована.
