### ISSUE TITLE
При нажатии на кнопку удаление ничего не происходит

### ISSUE THREAD

**Issue by bormolei** [Students-of-the-city-of-Kostroma/Student-timetable#560]
Описание бага:
В разделе "Направление подготовки"
![image](https://user-images.githubusercontent.com/46655821/56981667-24e19a80-6b88-11e9-9606-9aaef573cf9a.png)
при пустой таблице активна кнопка "Удалить".
При нажатии на кнопку ничего не происходит

**Comment by Jeen99** [comment]
В текущий момент это не баг, т.к. это форма до конца еще не реализована.
