### ISSUE TITLE
"Направление подготовки" не корректный ввод в поле "код направления подготовки" в форме добавления

### ISSUE THREAD

**Issue by bormolei** [Students-of-the-city-of-Kostroma/Student-timetable#578]
1.Заходим в справочники - "Направление подготовки"
2.Заполняем поля в форме
![image](https://user-images.githubusercontent.com/46655821/57096455-fc8ba480-6d1d-11e9-94ce-bc69ec169932.png)
Пример кода подготовки (09.03.02)
В данной форме не ставятся знаки препинания, а только буквы.

**Comment by Jeen99** [comment]
Знаки не ставятся в поле **Код направления**

**Comment by bormolei** [comment]
Не повторилось

**Comment by YuriSilenok** [comment]
@bormolei баг воспроизводится или не воспроизводится в какой-то ветке

**Comment by bormolei** [comment]
В ветке 17-ISbo-2a-6 не воспроизводится,была добавлена возможность поставить знак "."
