### ISSUE TITLE
 Автоматизация unit-test для метода Update(Model model) сущности Teacher

### ISSUE THREAD

**Issue by VinogradovAlexandr781227** [Students-of-the-city-of-Kostroma/Student-timetable#6]
[Сценарий](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)
[План разработки](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.p)
[Диаграмма классов](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit)

**Comment by Chippa99fm** [comment]
Работа хороша!!

**Comment by VinogradovAlexandr781227** [comment]
> Работа хороша!!

Пасяба))

**Comment by YuriSilenok** [comment]
Добрый день.

Метки не соответвуюь заголовку.
ССылка на сценарии не ведет к общему документу.

Спасибо.

**Comment by YuriSilenok** [comment]
Зачтено
