### ISSUE TITLE
Автоматизировать сценарии тестирования в unit-тесты для метода Update(Model model) сущности CTeacher

### ISSUE THREAD

**Issue by PopovMilan** [Students-of-the-city-of-Kostroma/Student-timetable#611]
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=1813879881)

**Comment by YuriSilenok** [comment]
Добрый день.
Что значит дописать тесты? 
Если имеется ввиду их разработка, то метка Auto test не верно стоит и на какую функциональность не хватает тестов? 
Если имеется ввиду автоматизация, какие именно сценарии еще нужно автоматизировать?

**Comment by YuriSilenok** [comment]
Есть ли прогресс по моему вопросу?

**Comment by YuriSilenok** [comment]
То, что Вы переименовали заголовок, не значит что вопрос должен остаться без ответа.
Кстати написать unit-тесты не стало более понятным. Вы сценарии тестирования пишите или пишите код unit-тестов?

**Comment by YuriSilenok** [comment]
UP

**Comment by PopovMilan** [comment]
Пишем код unit-тестов.

**Comment by YuriSilenok** [comment]
> Пишем код unit-тестов.

Значит должно присутствовать слово автоматизация в заголовке.

**Comment by PopovMilan** [comment]
Задача не требует выполнения, так как при мерже ветки 17-ISbo-2b были получены все необходимые тесты.

**Comment by YuriSilenok** [comment]
Ссылку на мерж о котором идёт речь

**Comment by YuriSilenok** [comment]
Up

**Comment by PopovMilan** [comment]
#606
