### ISSUE TITLE
Автоматизировать сценарии тестирования в unit-тесты для метода Insert(Model model) сущности CTeacher

### ISSUE THREAD

**Issue by PopovMilan** [Students-of-the-city-of-Kostroma/Student-timetable#613]
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=1813879881)

**Comment by YuriSilenok** [comment]
Тот же вопрос
https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/611#issuecomment-491479177

**Comment by YuriSilenok** [comment]
Измените тему по образцу

**Comment by PopovMilan** [comment]
Задача не требует выполнения, так как при мерже ветки 17-ISbo-2b были получены все необходимые тесты.
