### ISSUE TITLE
Автоматизировать сценарии для метода Insert(Model model) сущности ВУЗ

### ISSUE THREAD

**Issue by KudelinRoman** [Students-of-the-city-of-Kostroma/Student-timetable#614]
[План разработки.](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_102)
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)
[Ссылка](https://docs.google.com/spreadsheets/d/1z89kyDKWUYUOjZVjVTJZ_0lOJeD7eQB3OKzh6513cnc/edit#gid=0) на диаграмму классов
[task-166](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/166)

**Comment by KudelinRoman** [comment]
@YuriSilenok
Здравствуйте.
В ветке Testing не существует классов CWUZ и MWUZ.
Может эти классы существуют в какой-то другой ветке о которой я не знаю.
В ветке Testing я нашел 3 класса для вуза это классы: CHEI MHEI и MCHEI.
Но эти классы содержат на один аргумент больше чем в сценариях. (Есть поле "Полное название")
Один из этих классов недоступен (класс MCHEI пишет что нет доступа из-за уровня приватности)
Я попытался автоматизировать тесты с помощью этих двух классов но не вышло.
Вот код:

![image](https://user-images.githubusercontent.com/47320335/57573924-761b4500-7438-11e9-8ded-460412712f80.png)

Этот тест зафейлился :

![image](https://user-images.githubusercontent.com/47320335/57573922-71ef2780-7438-11e9-9492-8010ba516b08.png)

Пожалуйста, подскажите что мне делать в этой ситуации.
Спасибо.
Куделин Роман.
17-ИСбо-2б.

**Comment by YuriSilenok** [comment]
Добрый день.
- Почему Вы ожидали наличие классов CWUZ и MWUZ
- могу предположить что HEI это аббревиатура от high educational institution
- ВУЗ занимался 17-ИСбо-2б спишитесь с ними, желательно в этом таске, выясните где актуальные сценарии на метод вставки контроллера ВУЗ. Поиск по метка положительного результата не дал.
- думаю Вы в рамках таска на автоматизация можете сделать этот метод публичным.
- в автотестах экземпляр контроллера не нажно создавать, все экземпляры создаются автоматически и доступны через класс Controllers.

**Comment by KudelinRoman** [comment]
Здравствуйте.
Я ожидал увидеть наличие классов CWUZ и MWUZ, потому что они написаны в сценариях.
![image](https://user-images.githubusercontent.com/47320335/57574183-d44a2700-743c-11e9-8577-07a306dc7768.png)
Пользовался этими сценариями так как вы указали мне ссылку на таск в котором они были разработаны. 
В классе Controllers нет этого экземпляра.
Скриншот доказательство:
![image](https://user-images.githubusercontent.com/47320335/57574172-a82ea600-743c-11e9-9c87-ace66b629e53.png)
Спасибо.

**Comment by YuriSilenok** [comment]
По всей видимости команда назвала его как CUniversity. Вы в понедельник сможете придти? Если да, то в начале обсуждения спринта напомните мне об этом таске.

**Comment by KudelinRoman** [comment]
Здравствуйте.
Смогу, но немного опоздаю.
12 мая 2019 г. 8:10 пользователь "Юрий Силенок" <notifications@github.com>
написал:

**Comment by YuriSilenok** [comment]
Ответил устно

**Comment by YuriSilenok** [comment]
Зачтено
