### ISSUE TITLE
Разработать сценарии тестирования пригодных для автоматизации модульным тестированием метода Insert(Model model) сущности Институт

### ISSUE THREAD

**Issue by nrabotko** [Students-of-the-city-of-Kostroma/Student-timetable#616]
[Таблица сценариев](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=1153322464)

**Comment by YuriSilenok** [comment]
Я бы ожидал:
-  увидеть комментарий тестировщика о том, что сценарии разработаны в таком-то количестве разработаны с просьбой проверить сценарии. После чего под комментарием была бы записи о изменении ответственного.
- комментарий от старшего тестировщика о том, что сценарии проверены и не имеют замечаний, перевешивание задачи обратно на тестировщика, который в последствии ее закроет.

Пожалуйста, воспроизведите этот сценарий.

**Comment by yuliagolubevaa5** [comment]
Разработано 4 сценария тестирования для данного метода. Прошу проверить их на наличие каких-либо замечаний.

**Comment by Pipyao** [comment]
Все 4 сценария проверены, замечаний не обнаружено.
