### ISSUE TITLE
Исправить ошибки в юнит-тестах для методов Update(Model model), Insert (Model model), Delete (Model model) сущности Институт 

### ISSUE THREAD

**Issue by nrabotko** [Students-of-the-city-of-Kostroma/Student-timetable#618]
[Таблица сценариев](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=1153322464)

**Comment by Takunava** [comment]
Необходимо исправить названия тестов UT_Update_CInstitute

**Comment by nrabotko** [comment]
Название тестов исправлено.
