### ISSUE TITLE
Разработать сценарии тестирования пригодных для автоматизации модульным тестированием метода Delete(Model model) сущности Преподаватель

### ISSUE THREAD

**Issue by PopovMilan** [Students-of-the-city-of-Kostroma/Student-timetable#620]
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=1813879881)

**Comment by YuriSilenok** [comment]
Закрыто так как является дубликатом #5 
Забирайте себе 5 таск. Там все равно нет активности.
