### ISSUE TITLE
Разработать сценарии тестирования пригодных для автоматизации модульным тестированием метода Insert(Model model) сущности Преподаватель

### ISSUE THREAD

**Issue by PopovMilan** [Students-of-the-city-of-Kostroma/Student-timetable#621]
Duplicate of #13

**Comment by YuriSilenok** [comment]
Это клон закрытой задачи #13,
Если нужна доработка сценариев, то лучше переоткрыть её с соответствующим комментарием или использовать имеющиеся сценарии там.

**Comment by YuriSilenok** [comment]
> Если нужна доработка сценариев, то лучше переоткрыть её с соответствующим комментарием или использовать имеющиеся сценарии там.

@PopovMilan оказывается я говорил о том, что нужно написать комментарий. Вы игнорируете меня?

**Comment by PopovMilan** [comment]
Ни в коем случае не игнорирую.
Видимо не совсем осознаю, что нужно сделать, прошу прощения.
Необходимо изучить старые сценарии, и перенести в свой что необходимо, а наш таск оставлять открытым, с ссылкой на старый таск?

**Comment by YuriSilenok** [comment]
Текущая формулировка не подходит для того что бы он был открыт, так как является клоном.
Либо переоткрыть старую задачу, что и было сделано, либо создать задачу которая содержит заголовок близкий к реальности.

**Comment by YuriSilenok** [comment]
Текущая формулировка не подходит для того что бы он был открыт, так как является клоном.
Либо переоткрыть старую задачу, что и было сделано, либо создать задачу которая содержит заголовок близкий к реальности.

**Comment by YuriSilenok** [comment]
Что вы выбрали?

**Comment by YuriSilenok** [comment]
Up

**Comment by PopovMilan** [comment]
Данная задача не акутальна, так как есть готовый таск #13 . Получается, переоткрыть старую задачу.

**Comment by YuriSilenok** [comment]
Задача как раз актуальна, раз вы ее открыли, но она является клоном, ставьте метку клона и комментарий с ссылкой на клон по образцу
![image](https://user-images.githubusercontent.com/14871471/57874679-cec45680-7819-11e9-9384-d9ad3ebdbb47.png)

**Comment by YuriSilenok** [comment]
Закрыта не правильно

**Comment by MyachevM** [comment]
Duplicate of #13
