### ISSUE TITLE
Разработать сценарии тестирования пригодных для автоматизации модульным тестированием метода Update(Model model) сущности Преподаватель

### ISSUE THREAD

**Issue by PopovMilan** [Students-of-the-city-of-Kostroma/Student-timetable#622]
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=1813879881)

**Comment by YuriSilenok** [comment]
Как не странно, для апдейта контроллера преподавателя таск так и не был поднят. Так что это не клон.

**Comment by YuriSilenok** [comment]
Почему таск был закрыт?

**Comment by PopovMilan** [comment]
Задание было выполнено, только в другом таске.

**Comment by YuriSilenok** [comment]
Видимо тот другой таск является дубликатом, а этот основной.
