### ISSUE TITLE
Исправить Unit-тесты которые были поломаны

### ISSUE THREAD

**Issue by VinogradovAlexandr781227** [Students-of-the-city-of-Kostroma/Student-timetable#623]
[Сценарии](https://docs.google.com/spreadsheets/d/113wjRI9iZ3VcwojsnDKf15tTzlalq_Lynckp6ReCelw/htmlview#gid=0)

**Comment by YuriSilenok** [comment]
Разве в результате найденного бага нужно исправлять тест? Я считал что в результате найденного бага справляется ошибка в коде программы.

**Comment by KudelinRoman** [comment]
Была не правильно сформулирована тема.
Некоторые тесты поломались. Необходимо проверить и исправить их.

**Comment by YuriSilenok** [comment]
А сценарии нужно переделывать?
Если это было плановое изменение функциональности, то нужно указать ссылку на таск из-за которого приходится что-то переделывать.

**Comment by KudelinRoman** [comment]
Скорее всего ошибки произошли [здесь](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/592) (Это ссылка на пулреквест)
[Ссылка на задачу](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/591)

**Comment by YuriSilenok** [comment]
А сценарии тестирования вы переделали?

**Comment by YuriSilenok** [comment]
UP

**Comment by YuriSilenok** [comment]
Пожалуйста, дайте ответ на мой вопрос.

**Comment by KudelinRoman** [comment]
Здравствуйте, да мы корректировали сценарии. Но немного.
Спасибо.
13 мая 2019 г. 12:18 пользователь "Юрий Силенок" <notifications@github.com>
написал:
