### ISSUE TITLE
Слияние ветки task-596 в ветку Union-3

### ISSUE THREAD

**Issue by PopovMilan** [Students-of-the-city-of-Kostroma/Student-timetable#624]
Слияние ветки task-596 (#596) c исправлениями для unit-тестов метода Update(Model model) сущности CUniversity (task_496_10) (#496) в ветку Union-3

**Comment by YuriSilenok** [comment]
Обратите внимание как изменился заголовок задачи и описание. 
Какую информацию я туда добавил?

**Comment by PopovMilan** [comment]
Информация, из какой ветки (task-596). 
Моя ошибка, осознал.

**Comment by YuriSilenok** [comment]
Не только, я в описание добавил ссылки на все таски связанные с этим таском.
