### ISSUE TITLE
У профиля подготовки реализовать выбор Направления подготовки

### ISSUE THREAD

**Issue by MihailBobylev** [Students-of-the-city-of-Kostroma/Student-timetable#630]
У **Профиля подготовки** реализовать выбор **"Направления подготовки"**. 
Добавить поле и кнопку, реализующую выбор.
В поле **"Направления подготовки"** должна стоять блокировка ввода на прямую.
Предусмотреть случай удаления **Направления подготовки**.

Для реализации этой задачи придется добавить доп. поле в Модель и Контроллер **"Профиля подготовки"**, которое будет хранить **"Направление подготовки"**(string).

===================================================================

На форме "Редактировать профиль подготовки" и "Добавить профиль подготовки" должна располагаться:
- заблокированное для редактирование текстовое поле отображающее шифр направления подготовки
- правее текстового поля "Шифр направления подготовки" располагается кнопка с текстом ". . ."
При клике на кнопку  ". . ." открывается форма "Направления подготовки". Эта форма сохраняет весь функционал как при обычном открытии направлений подготовки и имеет дополнительный функционал, дающий возможность на двойной клик по ячейке таблицы с направлениями подготовке, выбрать направление подготовки. После двойного клика по таблице, форма с выбором направления подготовки закрывается, а в заблокированное текстовое поле помещается шифр направления подготовки.

Для соединения таблиц (контроллеров использовать класс DataRelation. Пример реализации находится в ветке [Demo-DataRelation](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/tree/Demo-DataRelation) в классе [RefData.cs](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/Demo-DataRelation/LibOfTimetableOfClasses/RefData.cs)

При попытке удалить Направление подготовки которое связано с Профилем подготовки, отобразить пользователю информационное сообщение о невозможности удалить это направление подготовки.

**Comment by YuriSilenok** [comment]
Нужна метка Story
