### ISSUE TITLE
Разработан сценарий тестирования пригодный для автоматизации модульным тестированием метода Update(Model model) сущности Преподаватель

### ISSUE THREAD

**Issue by MyachevM** [Students-of-the-city-of-Kostroma/Student-timetable#636]
Duplicate of #622

**Comment by PopovMilan** [comment]
Проверено

**Comment by YuriSilenok** [comment]
Заголовок должен отвечать на вопрос "Что сделать?".

**Comment by YuriSilenok** [comment]
Зачем Вы подняли этот дубликат?

**Comment by PopovMilan** [comment]
Вышла ошибка. Нужно было закрыть прямо в том таске, плохо с телефона смог объяснить, что именно сделать, или не об этом речь?

**Comment by YuriSilenok** [comment]
Если это дубликат у него нужно поставить соответсвующую метку, в комментарий написать Duplicate of #номер таска для которого этот таск является дубликатом

**Comment by YuriSilenok** [comment]
Почему мои комментарии игнорируются?

**Comment by MyachevM** [comment]
Duplicate of #622
