### ISSUE TITLE
Разработан сценарий тестирования пригодный для автоматизации модульным тестированием метода Insert(Model model) сущности Преподаватель 

### ISSUE THREAD

**Issue by MyachevM** [Students-of-the-city-of-Kostroma/Student-timetable#637]
#13
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=1813879881)

**Comment by PopovMilan** [comment]
Проверено

**Comment by YuriSilenok** [comment]
Кажется здесь нужно написать что таск был поднять ошибочно. Это верное утверждение?

**Comment by PopovMilan** [comment]
Да, это верное утверждение. Таск поднят ошибочно.
