### ISSUE TITLE
Разработан сценарий тестирования пригодный для автоматизации модульным тестированием метода Delete(Model model) сущности Преподаватель 

### ISSUE THREAD

**Issue by MyachevM** [Students-of-the-city-of-Kostroma/Student-timetable#638]
Duplicate of #5

**Comment by PopovMilan** [comment]
Проверено

**Comment by YuriSilenok** [comment]
Кажется здесь нужно написать что таск был поднять ошибочно, это верное утверждение?

**Comment by YuriSilenok** [comment]
UP

**Comment by YuriSilenok** [comment]
Метку поставили, отлично, а комментарий о том что задача является дубликатом такого-то задачи
![image](https://user-images.githubusercontent.com/14871471/57987536-51078180-7a8b-11e9-9ec9-0815199a4d4a.png)

**Comment by MyachevM** [comment]
Duplicate of #5
