### ISSUE TITLE
Выдается не обработанное исключение при удалении измененных записей в сущности "Аудитория".

### ISSUE THREAD

**Issue by bormolei** [Students-of-the-city-of-Kostroma/Student-timetable#642]
Описание бага:
Данный баг был обнаружен в ветке 17-ISbo-2a-5
Зайти в раздел "Аудитории"
![image](https://user-images.githubusercontent.com/46655821/57586833-56e9e980-7504-11e9-8243-d76ef6f720a1.png)
Создать 2 аудитории
![image](https://user-images.githubusercontent.com/46655821/57586852-84369780-7504-11e9-9f1a-f4fbff322961.png)
Заменить в первой аудитории кафедру
![image](https://user-images.githubusercontent.com/46655821/57586860-a8927400-7504-11e9-80be-b03cd8086b9e.png)
Удалить первую, а затем вторую аудиторию.
Ожидаемый результат - таблица очистится успешно.
Фактический результат 
![image](https://user-images.githubusercontent.com/46655821/57586991-97e2fd80-7506-11e9-9974-f6eadae7ecbc.png)

**Comment by bormolei** [comment]
Не воспроизводится

**Comment by YuriSilenok** [comment]
@bormolei ознакомьтесть с [этой](https://habr.com/ru/company/docsvision/blog/264163/) статьей и исправльте заголовок бага и запроса на слияние

**Comment by bormolei** [comment]
Названия исправлены.

**Comment by YuriSilenok** [comment]
Закрыто неправильно

**Comment by YuriSilenok** [comment]
Я Не Увидел в описании в какой версии программы Вы нашли этот баг и не увидел в комментарии при закрытии версию программы на которой баг не воспроизвелся.

**Comment by bormolei** [comment]
Исправлено название. Баг перестал воспроизводиться в ветке 17-ISbo-2a-5
