### ISSUE TITLE
План на 6 Sprint

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Student-timetable#649]
Задача на 6 Sprint:
-Выбор Вуза у Корпуса
-Убрать все модальные окна
-Доделать то, что не понравилось в 5 спринте ( messagebox с кнопкой для открытия формы направления подготовки, чтобы можно было создать запись )

13.05 - Выданы первые задачи разработчикам. Требуется сдать до 15.05
14.05 - Выданы первые задачи для тестирования ( мануального ) до 17.05
15.05 - Выдана еще часть задач на тестирование до вечера 18.05
15.05 - Выдана вторая часть задач разработчикам. До вечера 17.05
16.05 - Приняты утром до конца первые задачи от разработчиков и вечером вторые
17.05 - Сдано мануальное тестирование
18.05 - Доделывание недоделок. Найдены новые баги. Баги назначены на исправление.
19.05 - Баги исправлены. Мерж в ветку Testing. Отдых

**Comment by YuriSilenok** [comment]
> -Доделать то, что не понравилось в 5 спринте

А что не понравилось?
Себя поставьте ответственным, а когда работа над спринтом будет завершена, можете на меня перевесить

**Comment by KharlamovaAlexandra** [comment]
Спринт завершён
