### ISSUE TITLE
Разработать сценарии тестирования пригодных для автоматизации модульным тестированием метода Delete(Model model) сущности Министерство

### ISSUE THREAD

**Issue by SergeAlekseev** [Students-of-the-city-of-Kostroma/Student-timetable#650]
[План разработки.](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_102)
[Сценарий.](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)
[Ссылка на диаграмму классов.](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_0)

**Comment by SergeAlekseev** [comment]
| Состояние таблицы контроллера  | Аббревиатура министерства [[А-Я]{1,10}] | Полное наименование министерства [[А-Я]{1}[а-я]{1,50} [ [а-я]{1,50}]{0,9}] | Населенный пункт размещения министерства [[[а-я]{1,3]. [А-Я]{1}[а-я]{1,50}] or [[[а-я]{1,3]. [А-Я]{1}[а-я]{1,50}]-[А-Я]{1}[а-я]{1,50}] or [[[а-я]{1,3]. [[а-я]{1,3]. [А-Я]{1}[а-я]{1,50}]-[А-Я]{1}[а-я]{1,50}] or [[[а-я]{1,3]. [[а-я]{1,3]. [А-Я]{1}[а-я]{1,50}] |
| ------------- | ------------- | ------------- | ------------- |
| Удалить запись при совпадении всех атрибутов | task-650-1  | task-650-1 | task-650-1 |
| Удалить запись при совпадении только одного атрибута | task-650-2  | task-650-3 | task-650-4 |
| Удаление не существующих данных из таблицы  | task-650-5  | task-650-5 | task-650-5 |

**Comment by YuriSilenok** [comment]
Добрый день,
- в сценарии task-650-2 ошибочное описание
- task-650-3 и task-650-4 слетело форматирование границы

В целом все хорошо

**Comment by YuriSilenok** [comment]
Видимо Вы хотели написать что все исправили.
Зачтено.

Поднимайте задачу на автоматизацию и приступайте к автоматизации
