### ISSUE TITLE
"Профиль подготовки", проверка реализованности выбора Направления подготовки

### ISSUE THREAD

**Issue by DariaMann** [Students-of-the-city-of-Kostroma/Student-timetable#651]
Протестировать [#632](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/632) в ветке task-630

**Comment by GubanovAndrey** [comment]
Баг не воспроизводится в спринте 17-ISbo-2a-4

**Comment by YuriSilenok** [comment]
Какой баг?

**Comment by GubanovAndrey** [comment]
Прошу прощения. Выбор Направления подготовки был реализован в спринте 17-ISbo-2a-4
