### ISSUE TITLE
Выдается не обработанное исключение при удалении измененных записей в сущности "Профиль Подготовки.

### ISSUE THREAD

**Issue by bormolei** [Students-of-the-city-of-Kostroma/Student-timetable#652]
Описание бага:
Данный баг был обнаружен в ветке 17-ISbo-2a-5
Зайти в раздел "Профиль подготовки"
![image](https://user-images.githubusercontent.com/46655821/57642647-89591c80-75c0-11e9-95df-c623ee0295c5.png)
Создать 2 строки с заполненными данными
![image](https://user-images.githubusercontent.com/46655821/57642710-b1488000-75c0-11e9-8612-b5c9fe83fe3c.png)
Заменить в 1 строке поле "Краткое название профиля подготовки"
![image](https://user-images.githubusercontent.com/46655821/57643005-59f6df80-75c1-11e9-98a2-755b5407b498.png)
Удалить первую, а затем вторую строку.
Ожидаемый результат - успешное удаление обеих строк.
Фактический результат
![image](https://user-images.githubusercontent.com/46655821/57642830-f8cf0c00-75c0-11e9-87f9-5e3c5aec9415.png)

**Comment by bormolei** [comment]
Не воспроизвелся

**Comment by YuriSilenok** [comment]
@bormolei ознакомьтесть с [этой](https://habr.com/ru/company/docsvision/blog/264163/) статьей и исправльте заголовок бага и запроса на слияние

**Comment by bormolei** [comment]
Названия исправлены.

**Comment by YuriSilenok** [comment]
- нет версии ПО в которой найден баг
- нет версии по в которой перестал воспроизводится
- заголовок не отвечает на вопрос где?

**Comment by bormolei** [comment]
Исправлено название. Баг перестал воспроизводиться в ветке 17-ISbo-2a-5
