### ISSUE TITLE
Добавление нового преподавателя 

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#66]
Пользователь должен иметь возможность добавлять нового преподавателя.
Список преподавателей находиться на форме **Преподаватели** по пути Справочник-Преподаватели
Пользователь заполняет форму **Добавить преподавателя** и нажимает на кнопку **Создать**
После этого форма **Добавить преподавателя** закрывается, а в коде создается экземпляр модели Преподаватель и передается методу Insert контроллера Преподаватель.
Экземпляры контроллеров находятся в классе Controllers.
Ветка task-66

**Comment by KharlamovaAlexandra** [comment]
Здравствуйте, @YuriSilenok 
Хочу уточнить задание. Мне нужно создать метод +MTeacher(surname:string,name:string,middleName:string,academicRank:string, sizeOfTeacheingExperience:byte):base()  класса +MTeacher в https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/Testing/LibOfTimetableOfClasses/MTeacher.cs данном документе? 

Харламова Александра, 17-ИСбо-2б

**Comment by YuriSilenok** [comment]
Добрый день @KharlamovaAlexandra 
Нет. О создании метода не шла речь. В задании сказано что Вы должны создать экземпляр модели Преподаватель. Вы знаете что такое "создать экземпляр класса"?
Спасибо.

**Comment by KharlamovaAlexandra** [comment]
Здравствуйте, @YuriSilenok

Получается мне надо в методе private void AddTeacher(object sender, EventArgs e) создавать  MTeacher newTeacher = (MTeacher)model и вызывать метод Insert класса CTeacher? 

Спасибо,
Харламова Александра, 
17-ИСбо-2б

**Comment by YuriSilenok** [comment]
Добрый день, @KharlamovaAlexandra
Ход мысли верный.
Реализуйте задачу, если я увижу ошибки, я укажу на них.
Спасибо.

**Comment by YuriSilenok** [comment]
@KharlamovaAlexandra Что Вас побудило переименовать заголовок задачи?

**Comment by KharlamovaAlexandra** [comment]
Добрый день

Посмотрела на задание одногруппника, который сделал так же. Извиняюсь, так
не надо было делать.

Харламова Александра 17-Исбо-2б

**Comment by KharlamovaAlexandra** [comment]
Здравствуйте, @YuriSilenok
Тогда что значит "Добавить в описание задачи название добавленной ветки." в задании?
Харламова Александра, 17-ИСбо-2б

**Comment by YuriSilenok** [comment]
Видимо это не очень очевидно.
Добавлю это в задание к ЛР01 и продублирую письмом.
![2019-02-19_13-41-55](https://user-images.githubusercontent.com/14871471/53009476-a6ac9d80-344c-11e9-971f-da02303e2985.png)

**Comment by YuriSilenok** [comment]
Suggestions - имеет смысл "советовать", "предлагать"
Вы назначили меня проверяющим в запросе?

**Comment by YuriSilenok** [comment]
Зачтено
