### ISSUE TITLE
Исправить ошибки в тестах для сущности Институт

### ISSUE THREAD

**Issue by Takunava** [Students-of-the-city-of-Kostroma/Student-timetable#661]
Исправить следующие ошибки:
![image](https://user-images.githubusercontent.com/47320250/57718575-46617c80-7686-11e9-81e9-e748d6697f52.png)
Ошибочные тесты находятся в ветке [task#609](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/657)

**Comment by nrabotko** [comment]
Ошибки в юнит-тестам для сущности Институт исправлены. #609 

![изображение](https://user-images.githubusercontent.com/47633682/57727785-08228800-769b-11e9-8167-d033003d1d69.png)

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
