### ISSUE TITLE
"Группы", сообщение о том, что группу добавить нельзя не выводится при добавлении первой группы

### ISSUE THREAD

**Issue by itword7111** [Students-of-the-city-of-Kostroma/Student-timetable#662]
Когда заходишь в "Справочники", затем выбираешь "Группы",при создании первой группы изменив параметр на недопустимое значение, не выводится сообщение о том что группу нельзя создать, а просто создается новая группа с параметрами по умолчанию.
Шаги для реализации бага:
1.Перейти по меню Справочники-Группы
2.Ввести в поле "Группа" - "00-®-0а"
3.Нажать кнопку - "Сохранить"
Название ветки: Alliance-4
Ожидаемый результат:
Выводится сообщение об ошибке
![image](https://user-images.githubusercontent.com/38357886/57728185-f42b5600-769b-11e9-968e-e58606ea4542.png)
Фактический результат:
Не выводится сообщение об ошибке, создается группа со значениями по умолчанию
![image](https://user-images.githubusercontent.com/38357886/57728258-3359a700-769c-11e9-9b52-0c4d57a232b5.png)

**Comment by ghost** [comment]
Здравствуйте.

Не наша предметная область.

**Comment by itword7111** [comment]
Здравствуйте

вт, 14 мая 2019 г. в 23:23, Андрей Девятериков <notifications@github.com>:

**Comment by itword7111** [comment]
понял

**Comment by itword7111** [comment]
на кого баг занести не подскажешь?

ср, 15 мая 2019 г. в 18:08, Павел Калашников <pavelkalashnikov9819@gmail.com

**Comment by itword7111** [comment]
не этот, а другой, который я в справочнике институт нашел

**Comment by YuriSilenok** [comment]
@itword7111 расшарил на вас таблицу с распределением предметных областей по командам

**Comment by YuriSilenok** [comment]
Расшарил на Вас таблицу с составом команд, 
Каждый из участников команд имеет действительные имена и фамилии написанные на русском или транслитом
Когда вы будете перевешивать задачу, вы сможете таким образом искать нужного человека,
если савсем все плохо, указывайте проект, но в этом слдуае нет гарантии что таск сразу заметят.

**Comment by YuriSilenok** [comment]
Проверю баг в ближайшем релизе

**Comment by YuriSilenok** [comment]
Снято по не активности

**Comment by venecon1** [comment]
Странно что баг воспроизводился с такими данными так как commit https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/commit/9e53d784cd04fdfb28c42721411299d1cc4b536f#diff-7c3cb1075125cb306633ac81d0eb753b добавил ограничение на ввод символов в поле "Группа" при помощи метода SelectionOfLetters1. 
Но по багу скажу что не реализовано проверка на правильность, группы а данная ошибка которой ожидает автор бага. Связана с ошибкой одинаковых названий. Из-за того что по умолчанию одна группа вторую нельзя добавить.

**Comment by YuriSilenok** [comment]
Добрый день,

Я понял что Вы разбирались в деталях бага.
Балл ставиться если баг был исправлен. 

Спасибо, 
Юрий.

**Comment by YuriSilenok** [comment]
> Странно что баг воспроизводился с такими данными так как commit [9e53d78#diff-7c3cb1075125cb306633ac81d0eb753b](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/commit/9e53d784cd04fdfb28c42721411299d1cc4b536f#diff-7c3cb1075125cb306633ac81d0eb753b) добавил ограничение на ввод символов в поле "Группа" при помощи метода SelectionOfLetters1.
> Но по багу скажу что не реализовано проверка на правильность, группы а данная ошибка которой ожидает автор бага. Связана с ошибкой одинаковых названий. Из-за того что по умолчанию одна группа вторую нельзя добавить.

Я не понял Вашего вопроса.

**Comment by venecon1** [comment]
> > Странно что баг воспроизводился с такими данными так как commit [9e53d78#diff-7c3cb1075125cb306633ac81d0eb753b](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/commit/9e53d784cd04fdfb28c42721411299d1cc4b536f#diff-7c3cb1075125cb306633ac81d0eb753b) добавил ограничение на ввод символов в поле "Группа" при помощи метода SelectionOfLetters1.
> > Но по багу скажу что не реализовано проверка на правильность, группы а данная ошибка которой ожидает автор бага. Связана с ошибкой одинаковых названий. Из-за того что по умолчанию одна группа вторую нельзя добавить.
> 
> Я не понял Вашего вопроса.

Суть в том что окно возникает из-за того что не может быть две группы с одним названием. А так как если введено с ошибкой название группы она заменяется на значение по умолчанию, но так как такое уже есть оно не позволяет добавить. Так что бага тут нет.

**Comment by YuriSilenok** [comment]
Вы переводщите деньги, по умолчанию сумма перевода 10000, минимальная сумма 10 рублей, вы ввели 1 рубль и нажали перевести, и в место отказа от пеервода у вас перевелась сумма 10000. 

Если программа делает то, что ее не просили, то это баг. 
Я думаю баг здесь в том, что программа меняет введенное зачение на дефолтное.

**Comment by YuriSilenok** [comment]
снято по бездейсвию
