### ISSUE TITLE
 RefData перенести статические поля в проект LibOfTimetableOfClasses класс

### ISSUE THREAD

**Issue by GubanovAndrey** [Students-of-the-city-of-Kostroma/Student-timetable#663]
План - отчёт на Sprint7 #773
Разработка Sprint 7 #774
В проекте TimetableOfClasses класс RefData перенести статические поля в проект LibOfTimetableOfClasses класс Controllers
В проекте TimetableOfClasses удалить файл RefData
В проекте LibOfTimetableOfClasses переименовать файл и класс Controllers на RefData
Исправить возникшие ошибки и выполнить все автотесты

**Comment by KudelinRoman** [comment]
"В проекте TimetableOfClasses класс RefData перенести статические поля в проект LibOfTimetableOfClasses класс Controllers"
В переносе нет смысла так как класс Controllers уже содержит те поля которые имеются в RefData

**Comment by YuriSilenok** [comment]
Controllers поля нужно объеденить исключив дубликаты, а Controllers должен переименовать в RefData. Должен остаться только один класс хранящий доступ к контроллерам с именем RefData

**Comment by KudelinRoman** [comment]
Будет выполнено после 11 вечера
21 мая 2019 г. 14:57 пользователь "Юрий Силенок" <notifications@github.com>
написал:
