### ISSUE TITLE
Мануальное тестирование сущности Преподователь

### ISSUE THREAD

**Issue by PopovMilan** [Students-of-the-city-of-Kostroma/Student-timetable#665]
План #758
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)

Количество тестов - 24
Пройдено - 24 
Сбои - 0
Заблокировано - 0
Не выполнено - 0

**Comment by YuriSilenok** [comment]
Где отчет о тестировании?

**Comment by PopovMilan** [comment]
А какова форма отчета?

**Comment by YuriSilenok** [comment]
На лекции были? посмотрите на то, что должен проверить ст. тестировщик в таких задачах. Эти сведения и должны быть тут отображены, форма не так важна, список это будет или таблица.
