### ISSUE TITLE
Добавить в форму Преподаватель колонку "Учёное звание" и выпадающий список в форму AddTeacher

### ISSUE THREAD

**Issue by PopovMilan** [Students-of-the-city-of-Kostroma/Student-timetable#669]
План #758
В таблице формы Teacher добавить колонку "Учёное звание" после "Учёная степень". 

В форму AddTeacher после поля "Учёная степень" добавить: 
1. Подпись "Ученое звание" (Microsoft Sans Serif; 9,75pt)
2. Выпадающий список с именем AcademicTitle и шрифтом Microsoft Sans Serif; 9,75pt

**Comment by YuriSilenok** [comment]
Больше конкретики. Нужно описать что вы изменяет в форме.

**Comment by FvckNeighbors** [comment]
Выполнено

**Comment by YuriSilenok** [comment]
> Больше конкретики. Нужно описать что вы изменяет в форме.

Меня заигнорили?
И в заголовок пулреквеста тоже больше деталей должно быть!

Вы должны написать в заголовке "что?" и "где?" нужно сделать, "где?" у вас написано, а "что?", нет.

**Comment by FvckNeighbors** [comment]
Не игнорил, добавил изменения в описании, забыл ответить. Сейчас добавим изменения.
