### ISSUE TITLE
"Институт",в поле полное название института можно ввести некорректное значение 

### ISSUE THREAD

**Issue by itword7111** [Students-of-the-city-of-Kostroma/Student-timetable#672]
В "Справочники" выбираем "Институт",при добавлении института, заполнив поле "полное название института" некорректно, добавляется институт.

Шаги для реализации бага:
1.Перейти по меню Справочники-Институт, предварительно создав вуз в справочнике-ВУЗы
2.Нажать на кнопку добавить
3.Заполнить поля, корректными значениями, а в поле  "полное название института" ввести """г"
4.Нажать кнопку "Создать и очистить"
Название ветки: master
Ожидаемый результат:
Выводится сообщение об ошибке
![image](https://user-images.githubusercontent.com/38357886/57786235-ceee2480-773b-11e9-889b-ba71cdbaedb7.png)
Фактический результат:
Создается новый институт
![image](https://user-images.githubusercontent.com/38357886/57786320-ee854d00-773b-11e9-98ba-714ce7b0ea81.png)

Корректная запись в поле "полное название института":

1. допустимые символы в записи -  буквы русского алфавита и пробел
2.Первый символ должен быть заглавной буквой, больше заглавных букв в строке быть не должно
3.Пробел может находиться только между 2 буквами
  Пример: Институт автоматизированных систем и технологий
#769 
#772

**Comment by YuriSilenok** [comment]
@itword7111 как бы вы определили правила для поля полное название института?

**Comment by itword7111** [comment]
наверное оно должно начинаться с заглавной буквы и без кавычек

**Comment by YuriSilenok** [comment]
> KwiSatifikethi

Это подходит?

**Comment by itword7111** [comment]
ну такое значение занести в поле можно

**Comment by itword7111** [comment]
не очень понял вопрос к чему подходит?

**Comment by YuriSilenok** [comment]
подходит ли под Вашу формулировку, допустимы ли такие значения и сразу еще другой пример

> 교수진

**Comment by itword7111** [comment]
проходят только символы русского алфавита

**Comment by itword7111** [comment]
ну и ещё некоторые

**Comment by itword7111** [comment]
а в поле Директор вуза тоже должны быть символы только русского алфавита?

**Comment by itword7111** [comment]
Там по заданию директор вообще из преподавателей должен выбираться

**Comment by itword7111** [comment]
это надо как баг заносить ?

**Comment by YuriSilenok** [comment]
Вначале сформулируйте правило ограничивающее ввод символов, тогда это станет ожидаемым результатом.

**Comment by itword7111** [comment]
а где его сформулировать в этом issue да

**Comment by YuriSilenok** [comment]
если вы собираетесь формулировать для полного названия института, то да, в этом issue. Я бы сказал что это больше попахивает улучшением (другая метка), нежели багом, но такие улучшения тоже засчитываются, главное что бы они были детально и четко сформулированы.

**Comment by YuriSilenok** [comment]
> нежели багом

**Comment by Pipyao** [comment]
Проверено, баг более не воспроизводится в ветке Alliance-5.

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
