### ISSUE TITLE
Заменить ComboBox у поля Профиль подготовки в форме AddGroup на TextBox и кнопку "выбрать"

### ISSUE THREAD

**Issue by SergeAlekseev** [Students-of-the-city-of-Kostroma/Student-timetable#675]
Переделать форму AddGroup 
Заменить ComboBox у поля Профиль подготовки на TextBox и кнопку "выбрать" 
В TextBox ввод запрещен. При нажатии на "выбрать" открывается таблица Профили подготовки. 
По двойному щелчку мыши мы выбираем нужную нам строку и сохраняем в публичной переменной формы Профили подготовки 
(необходимо создать)После этого форма закрывается. 
Из объекта формы берется выбранная строка из котой берется краткое название Профили подготовки и вставляется в TextBox 
У формы группы должно быть 2 режима, один для выбора строки в списке(когда делаешь двойной клик по строке она считается выбранной, сохраняется в публичной переменной класса(свойстве) и форма закрывается)

**Comment by YuriSilenok** [comment]
метка улучшения лишняя. Улучшения ставятся когда нужна фича вне плана разработки.

**Comment by YuriSilenok** [comment]
Я бы ожидал что на этот таск будет ссылаться таск на изменение сценариев тестирования
