### ISSUE TITLE
В "Ученые звания", можно добавить некорректные ученые звания

### ISSUE THREAD

**Issue by itword7111** [Students-of-the-city-of-Kostroma/Student-timetable#676]
Название ветки: master

Шаги для реализации бага:
1. открыть справочник-Ученые звания
2.нажать "добавить"
3.ввести в оба поля 1
4.нажать создать и закрыть 
Ожидаемый результат:
Выводится сообщение об ошибке
![image](https://user-images.githubusercontent.com/38357886/57803033-138bb700-7760-11e9-9554-ef875e4a9523.png)
Фактический результат:
Создается ученое звание
![image](https://user-images.githubusercontent.com/38357886/57803072-29997780-7760-11e9-9509-153a2c1aeb87.png)

Корректная запись в поле "Сокращенная запись уч. звания":

1.допустимые символы в записи - строчные буквы русского алфавита, пробел, тире
2.Пробел и тире могут находиться только между 2 буквами
Пример: д-р архитектуры

Корректная запись в поле "Полная запись уч. звания":

1.допустимые символы в записи - строчные буквы русского алфавита, пробел
2.Пробел  может находиться только между 2 буквами
Пример: доктор архитектуры

**Comment by YuriSilenok** [comment]
стоп
почему вы в мастере тестируете?

**Comment by itword7111** [comment]
я скачал репозиторий этой ветки Alliance-4, указывать  Alliance-4?

**Comment by YuriSilenok** [comment]
есть таблица [распределения областей](https://docs.google.com/spreadsheets/d/1Xcr7JeJcxqfHLDJ5X-tqPnQGkiIjZc0n2VDs9AxW6Aw/edit#gid=0)
Есть 4 основные ветки в которых ведется работы, это 
Альянс
Союз
17-ИСбо-2а
17-ИСбо-2б

В последних ветках этих команд и нужно копаться.

Например союз.
![image](https://user-images.githubusercontent.com/14871471/57803310-be9c7080-7760-11e9-90ca-d87ded6598e8.png)
Последняя ветка четвертая, в ней и копайтесь.

**Comment by YuriSilenok** [comment]
> я скачал репозиторий этой ветки Alliance-4, указывать Alliance-4?

Если вы в альянсе, то в описании бага почему мастер указан?

> Название ветки: master

**Comment by itword7111** [comment]
я ошибся это неправильное issue в Alliance-4 нету этого бага

**Comment by YuriSilenok** [comment]
Значит закрывайте

**Comment by itword7111** [comment]
а как закрыть?

**Comment by YuriSilenok** [comment]
![image](https://user-images.githubusercontent.com/14871471/57803610-8184ae00-7761-11e9-9030-7747855901cc.png)

**Comment by YuriSilenok** [comment]
Себя ответственным за этот баг укажите, задачи не должны оставаться без ответственного

**Comment by YuriSilenok** [comment]
@itword7111 кажется вы открыли баги все подряд, этот баг даже не исправлялся, так как был найден в устаревшей ветке.

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
