### ISSUE TITLE
Нельзя добавить корректное ученое звание в "Ученые звания"

### ISSUE THREAD

**Issue by itword7111** [Students-of-the-city-of-Kostroma/Student-timetable#677]
Название ветки: Alliance-4
Шаги реализации бага:
1.Открыть справочник "Ученые звания"
2.Нажать "добавить"
3.В поле "Сокращенная запись уч. звания" ввести "д-р наук"
4.В поле "Полная запись уч. звания" ввести "доктор наук"
5.Нажать "создать и закрыть"
Ожидаемый результат:
создается новая ученая степень
Фактический результат:
![image](https://user-images.githubusercontent.com/38357886/57804377-38355e00-7763-11e9-9193-fdb0a7715850.png)
![image](https://user-images.githubusercontent.com/38357886/57804403-42eff300-7763-11e9-93b6-5726e6c6387f.png)
#769 
#772

**Comment by ghost** [comment]
Метка ученое звание

**Comment by ghost** [comment]
Баг устранен

**Comment by yuliagolubevaa5** [comment]
![image](https://user-images.githubusercontent.com/47320351/57881465-076c2c00-782a-11e9-9b6d-791e08c8d362.png)
При вводе корректных полной и сокращенной записей ученого звания ожидаемый результат совпадает с фактическим - появляется новая запись уч. звания 
![image](https://user-images.githubusercontent.com/47320351/57881529-2e2a6280-782a-11e9-85a2-269198217699.png)

**Comment by YuriSilenok** [comment]
@itword7111 здесь непонятная ситуация для меня, можете ли вы воспроизвести этот баг в последнем релизе?

**Comment by itword7111** [comment]
В последней версии ветки Alliance-4 этого бага нет
 
![image](https://user-images.githubusercontent.com/38357886/58055870-d82a2780-7b67-11e9-83fa-1c94d7033693.png)

**Comment by YuriSilenok** [comment]
Сам баг это задача, и он есть и не живёт в ветках. Баг описывает шаги по воспроизведению сбоя и другие технические детали для воспроизведения сбоя. Сбой это появление ошибки которая находится в какой-то ветке. Когда ошибка исправлена проверяют баг на предмет воспроизводимрсти сбоя. От этого всегда говорят что баг воспроизводится там-то или не воспроизводится там-то

**Comment by Takunava** [comment]
В последней версии программы в ветке Alliance-5 данный баг не воспроизводиться

**Comment by AndreiDevyaterikov** [comment]
Этап разработки #772
