### ISSUE TITLE
В "Ученые звания" можно добавить некорректное уч. звание 

### ISSUE THREAD

**Issue by itword7111** [Students-of-the-city-of-Kostroma/Student-timetable#678]
Название ветки: Alliance-4
Шаги реализации бага:
1.Открыть справочник "Ученые звания"
2.Нажать "добавить"
3.В поле "Сокращенная запись уч. звания" ввести "...а"
4.В поле "Полная запись уч. звания" ввести "...а"
5.Нажать "создать и закрыть"
Ожидаемый результат:
появляется сообщение об ошибке
![image](https://user-images.githubusercontent.com/38357886/57807060-17700700-7769-11e9-8086-b10db900f874.png)
Фактический результат:
![image](https://user-images.githubusercontent.com/38357886/57807084-222a9c00-7769-11e9-9b7b-01bca939c7c6.png)

**Comment by YuriSilenok** [comment]
Поторопились

**Comment by YuriSilenok** [comment]
Вы планируете продолджать ветку task#678 для решения этой задачи?

**Comment by ghost** [comment]
Да, так как еще нет апрува мержа ветки, а апрува нет, так как еще не исправлены тесты

**Comment by ghost** [comment]
Баг устранён

**Comment by Pipyao** [comment]
Проверено, устранён.

**Comment by YuriSilenok** [comment]
@itword7111 зачтено

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
