### ISSUE TITLE
Программа терпит крах при удалении записи в "Ученые звания"

### ISSUE THREAD

**Issue by itword7111** [Students-of-the-city-of-Kostroma/Student-timetable#680]
Название ветки: Alliance-4

1 способ воспроизведения
Шаги реализации бага:
1.Открыть справочник "Ученые звания"
2.Нажать "добавить"
3.В поле "Сокращенная запись уч. звания" ввести "д"
4.В поле "Полная запись уч. звания" ввести "д"
5.Нажать "создать и очистить"
6.В поле "Сокращенная запись уч. звания" ввести "г"
7.В поле "Полная запись уч. звания" ввести "г"
8.Нажать "создать и закрыть"
9.Выбрать первую запись нажать "Изменить", в открывшейся форме тоже нажать "Изменить"
10.удалить первую запись
11.изменить оставшуюся записьзапись(также как в пункте 9)
Ожидаемый результат:
![image](https://user-images.githubusercontent.com/38357886/57853619-e1756600-77ee-11e9-98a0-92dc9bcdf00b.png)

Фактический результат:
![image](https://user-images.githubusercontent.com/38357886/57853659-f94cea00-77ee-11e9-8ad5-7720a4c1664c.png)

2 способ воспроизведения
Шаги реализации бага:
1.Открыть справочник "Ученые звания"
2.Нажать "добавить"
3.В поле "Сокращенная запись уч. звания" ввести "д"
4.В поле "Полная запись уч. звания" ввести "д"
5.Нажать "создать и очистить"
6.В поле "Сокращенная запись уч. звания" ввести "г"
7.В поле "Полная запись уч. звания" ввести "г"
8.Нажать "создать и закрыть"
9.В правом верхнем углу нажать на "стрелочку", которая находится в столбце "Полная запись уч. звания", чтобы порядок записей в таблице поменялся
![image](https://user-images.githubusercontent.com/38357886/57813117-bc91dc00-7777-11e9-9df1-034e6996f3a7.png)
10.Выбрать последнюю запись нажать "Изменить", в открывшейся форме тоже нажать "Изменить"
10.удалить последнюю запись
11.изменить оставшуюся запись(также как в пункте 10)
Ожидаемый результат:
![image](https://user-images.githubusercontent.com/38357886/57813130-cf0c1580-7777-11e9-8e1f-676c87f45a16.png)
Фактический результат:
![image](https://user-images.githubusercontent.com/38357886/57813161-dcc19b00-7777-11e9-8acb-295423f572b8.png)

**Comment by ghost** [comment]
Баг устранен

**Comment by itword7111** [comment]
наверное новый баг автоматом тоже

**Comment by itword7111** [comment]
похожий алгоритм воспроизведения бага

**Comment by itword7111** [comment]
хотя там баг в другом справочнике

**Comment by Takunava** [comment]
если это другой баг поднимай отдельно, и пиши что да как

**Comment by itword7111** [comment]
поднял недавно

**Comment by itword7111** [comment]
пофиксили и стало немного по другому алгоритму ломаться ща напишу

**Comment by AndreiDevyaterikov** [comment]
Задача является уже не актуальной, имеется такая же с другой формулировкой

**Comment by itword7111** [comment]
сделано

**Comment by ghost** [comment]
Нужно было не изменяя описания первого бага, написать про новый баг. Исправь пожалуйста

**Comment by YuriSilenok** [comment]
Если наблюдается сбой под который подходит заголовок бага, но для воспроизведения сбоя используется другой сценарий, то в комментариях к багу описывают новый сценарий.
Кроме этого в описание бага может указывается второй сценарий воспроизведения

**Comment by itword7111** [comment]
Я просто в описании бага добавил оба сценария, это правильно?

**Comment by ghost** [comment]
Да пусть будет, так, только  в след раз пиши новым комментарием

**Comment by itword7111** [comment]
ок

**Comment by itword7111** [comment]
3 способ воспроизведения
Шаги реализации бага:
1. Открыть справочник "Ученые звания"
2. Нажать "добавить"
3. В поле "Сокращенная запись уч. звания" ввести "T"
4. В поле "Полная запись уч. звания" ввести "T"
5. Нажать "создать и очистить"
6. В поле "Сокращенная запись уч. звания" ввести "Y"
7. В поле "Полная запись уч. звания" ввести "Y"
8. Нажать "создать и закрыть"
9. Выбрать вторую запись нажать "Изменить", в открывшейся форме тоже нажать "Изменить"
10. удалить вторую запись
11. изменить оставшуюся запись(также как в пункте 9)
Ожидаемый результат:
![image](https://user-images.githubusercontent.com/38357886/57867511-f4e1fa80-7809-11e9-8ea8-7371d7095532.png)
Фактический результат:
![image](https://user-images.githubusercontent.com/38357886/57867430-d24fe180-7809-11e9-8b5a-10018e09b213.png)

**Comment by YuriSilenok** [comment]
В шагах после точки ставьте пробелы для правильного форматирования.
Вот все правила форматирования, они достаточно общие что бы использовать их не только здесь.
https://guides.github.com/features/mastering-markdown/#

**Comment by ghost** [comment]
Разве описание 3-его бага не копирует описание 2-ого бага?

**Comment by itword7111** [comment]
Вроде во 2 способе воспроизведения мы нажимаем стрелочку меняя порядок записей в справочнике. В 3 похоже на 2 но без нажатия стрелочки

**Comment by ghost** [comment]
Только что проверил 2ой сценарий бага, он не был выявлен, я пробовал 3 раза

**Comment by ghost** [comment]
С 3 сценарием аналогично, только там вылезает окно о том что, поля заполнены не корректно.
Предусматривается ввод только русских букв 
Будет исправлено

**Comment by ghost** [comment]
Баг устранён

**Comment by Pipyao** [comment]
Проверено, баг устранён и более не воспроизводится.

**Comment by YuriSilenok** [comment]
В какой ветке  или версии ПО не воспроизводится баг?

**Comment by nrabotko** [comment]
Баг был устранен #710

**Comment by Pipyao** [comment]
Баг не воспроизводиться в актуальной ветке Alliance-4.

**Comment by YuriSilenok** [comment]
Где устраняли и так есть ссылка, мне нужно понимание  где тестировали (пытались воспроизвести баг)

**Comment by Pipyao** [comment]
Новый таск не создавался.

**Comment by YuriSilenok** [comment]
< Баг не воспроизводиться в актуальной ветке Alliance-4.

Все хорошо, этого комментария я ожидал

**Comment by YuriSilenok** [comment]
@itword7111  Зачтено

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
