### ISSUE TITLE
Всплывает сообщение об ошибке когда поля заполнены корректно.Справочник - "Институт"

### ISSUE THREAD

**Issue by itword7111** [Students-of-the-city-of-Kostroma/Student-timetable#682]
Название ветки: Alliance-4
Шаги реализации бага:
1.Открыть справочник "Институт", предварительно создав запись в справочнике "ВУЗы"
2.Нажать "добавить"
3.В поле "ВУЗ" выбрать любой вуз, в остальные поля ввести "А"
4.Нажать "создать и очистить"
5.В поле "ВУЗ" выбрать любой вуз, в остальные поля ввести "М"
6.Нажать "создать и закрыть"
7.Выбрать первую запись нажать "Изменить", в открывшейся форме выбрать вуз и тоже нажать "Изменить"
8.удалить первую запись
9.изменить оставшуюся запись(также как в пункте 7)
Ожидаемый результат:
При нажатии изменить запись изменятся окно "Изменение института" закрывается
![image](https://user-images.githubusercontent.com/38357886/57809992-73d62500-776f-11e9-94f0-f6c330332a65.png)
Фактический результат:
![image](https://user-images.githubusercontent.com/38357886/57809960-6325af00-776f-11e9-9222-ab923d357261.png)
![image](https://user-images.githubusercontent.com/38357886/57809968-6882f980-776f-11e9-8d81-9ee8347d7aaa.png)

**Comment by ghost** [comment]
Баг устранён

**Comment by YuriSilenok** [comment]
@AndreiDevyaterikov баг **не воспроизводится** в какой ветке?

**Comment by YuriSilenok** [comment]
Что-то название таска и запроса противоречат

**Comment by ghost** [comment]
- Этот баг уже **не воспроизводится** в ветке Alliance-4

- Имелось ввиду что, **теперь** не всплывает сообщение об ошибке, возможно название запроса не совсем корректное

**Comment by Pipyao** [comment]
Проверено, баг исправлен и более не воспроизводится.

**Comment by YuriSilenok** [comment]
@itword7111 зачтено

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
