### ISSUE TITLE
Программа терпит крах при удалении записи в "Ученые звания"

### ISSUE THREAD

**Issue by itword7111** [Students-of-the-city-of-Kostroma/Student-timetable#683]
Название ветки: Alliance-4
Шаги реализации бага:
1.Открыть справочник "Ученые звания"
2.Нажать "добавить"
3.В поле "Сокращенная запись уч. звания" ввести "д"
4.В поле "Полная запись уч. звания" ввести "д"
5.Нажать "создать и очистить"
6.В поле "Сокращенная запись уч. звания" ввести "г"
7.В поле "Полная запись уч. звания" ввести "г"
8.Нажать "создать и закрыть"
9.В правом верхнем углу нажать на "стрелочку", которая находится в столбце "Полная запись уч. звания", чтобы порядок записей в таблице поменялся
![image](https://user-images.githubusercontent.com/38357886/57811285-86059280-7772-11e9-9511-361839af75e6.png)
10.Выбрать последнюю запись нажать "Изменить", в открывшейся форме тоже нажать "Изменить"
10.удалить последнюю запись
11.изменить оставшуюся запись(также как в пункте 10)
Ожидаемый результат:
![image](https://user-images.githubusercontent.com/38357886/57811401-cd8c1e80-7772-11e9-8333-63054d67eaa9.png)
Фактический результат:
![image](https://user-images.githubusercontent.com/38357886/57811361-b6e5c780-7772-11e9-9c14-c8662d88228e.png)

**Comment by ghost** [comment]
Из 2ух одинаковых задач должна остаться одна, если в старой появился другой баг, писать надо там

**Comment by itword7111** [comment]
тоесть этот issue закрыть а там поменять да?

**Comment by ghost** [comment]
Тот я закрыл, дальнейшие баги по этой задаче писать здесь

**Comment by itword7111** [comment]
ок

**Comment by ghost** [comment]
Хотя лучше в ту напиши, я её заново открыл.
Эту закрываю

**Comment by YuriSilenok** [comment]
@itword7111 Зачтено

**Comment by YuriSilenok** [comment]
Эта задача не может быть зачтена, так как судя по всему является дубликатом, ссылку на которою ни кто не предоставил

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
