### ISSUE TITLE
В справочнике "Ученые звания", могут быть несколько записей с одинаковым полем - "Полная запись уч. звания"

### ISSUE THREAD

**Issue by itword7111** [Students-of-the-city-of-Kostroma/Student-timetable#685]
Название ветки: Alliance-4
Шаги реализации бага:
1.Открыть справочник "Ученые звания"
2.Нажать "добавить"
3.В поле "Сокращенная запись уч. звания" ввести "е е"
4.В поле "Полная запись уч. звания" ввести "е е"
5.Нажать "создать и очистить"
6.В поле "Сокращенная запись уч. звания" ввести "е е е"
7.В поле "Полная запись уч. звания" ввести "е е"
8.Нажать "создать и закрыть"
Ожидаемый результат:
Новая запись не добавляется
![image](https://user-images.githubusercontent.com/38357886/57812838-e26ab100-7776-11e9-8197-f8c6e876a3f9.png)

Фактический результат:
![image](https://user-images.githubusercontent.com/38357886/57812810-d0890e00-7776-11e9-81d1-ba454f1fa894.png)

**Comment by ghost** [comment]
Баг устранен

**Comment by YuriSilenok** [comment]
Баг может воспроизводится или не воспроизводится в какой-то ветке, пожалуйста, уточните что вы имели ввиду под устарел

**Comment by ghost** [comment]
Я имел ввиду устранен, как и написано

**Comment by Pipyao** [comment]
Проверено, баг устранён и не воспроизводится в ветке Alliance-4.

**Comment by YuriSilenok** [comment]
@itword7111 Я бы ожидал еще какой-нибудь комментарий от Вас, а том могу пропустить Ваши баги как обычные.

**Comment by YuriSilenok** [comment]
@itword7111 Зачтено

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
