### ISSUE TITLE
Исправить ошибки в тестах для сущности Ученое звание

### ISSUE THREAD

**Issue by ghost** [Students-of-the-city-of-Kostroma/Student-timetable#689]
Исправить  следующие ошибки :
![image](https://user-images.githubusercontent.com/47637325/57854000-cfe08e00-77ef-11e9-8b68-29ecb27d0be6.png)
Ошибочные тесты находятся в #688

**Comment by nrabotko** [comment]
Ошибки были исправлены ветке Alliance-4 (#688) под commit " task-689 remove UT_MTitle "

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
