### ISSUE TITLE
Создать проверку наличия в таблице "Профили подготовки" хоть одной записи при запуске формы Добавить группу.

### ISSUE THREAD

**Issue by SamuraSwordS** [Students-of-the-city-of-Kostroma/Student-timetable#690]
При открытии формы "Добавить группу" должна происходить проверка наличия записей в таблице формы "Профили подготовки", в случае отсутствия записей в таблице "всплывает" окно с предупреждением о данном, и возможностью перейти в форму "Профиль подготовки".

**Comment by YuriSilenok** [comment]
Интресная фича, опишите детальнее как это должно работать, смысл понятен, а вот основание на то, что в результате проверки должны еще модальные окна открываться, нет.
![image](https://user-images.githubusercontent.com/14871471/57907190-4da2a900-7885-11e9-8751-9624e544bb3b.png)
Не стесняйтесь дублировать информацию (не обязательно дословно) в вопросе MessageBox.

**Comment by map82top** [comment]
> Интресная фича, опишите детальнее как это должно работать, смысл понятен, а вот основание на то, что в результате проверки должны еще модальные окна открываться, нет.
> ![image](https://user-images.githubusercontent.com/14871471/57907190-4da2a900-7885-11e9-8751-9624e544bb3b.png)
> Не стесняйтесь дублировать информацию (не обязательно дословно) в вопросе MessageBox.

Вы же сами говорили, что при отсутствии записей должно вылезать предупреждении с возможностью открыть таблицу и добавить записи?
Открытие в режиме модального окна мы уберем

**Comment by YuriSilenok** [comment]
Вы меня не поняли.
Я имел ввиду что, где в таске описано того, что UI должна именно так вести себя?

**Comment by map82top** [comment]
Задание было дано лично, а в таске оно не написано я не знаю почему
