### ISSUE TITLE
Откатить изменения

### ISSUE THREAD

**Issue by Jeen99** [Students-of-the-city-of-Kostroma/Student-timetable#692]
Необходимо откатить коммиты созданные в #630.

**Comment by YuriSilenok** [comment]
Задача сложнее чем просто нажать на кнопку Revert?
![image](https://user-images.githubusercontent.com/14871471/57876515-2bc20b80-781e-11e9-965b-365cd6e127ae.png)

**Comment by Jeen99** [comment]
@YuriSilenok, спасибо за замечания, забыл что это можно сделать через GitHub. Однако появилась проблема , не могу добавить себя в ревью, чтобы подтвердить изменения.
