### ISSUE TITLE
Автоматизация unit-test метода Delete(Model model) сущности Министерство

### ISSUE THREAD

**Issue by SergeAlekseev** [Students-of-the-city-of-Kostroma/Student-timetable#694]
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548) task-#650

**Comment by YuriSilenok** [comment]
Снято по бездействию

**Comment by DemiKor** [comment]
@YuriSilenok Отсутствует контроллер для сущности Министерство

**Comment by YuriSilenok** [comment]
Задача закрыта так как нет контроллера Министерства
