### ISSUE TITLE
Реализовать выбор у Аудитории Корпуса

### ISSUE THREAD

**Issue by Jeen99** [Students-of-the-city-of-Kostroma/Student-timetable#696]
Реализовать у **Аудитории** выбор  **Корпуса**.
В поле **Корпус** должна стоять блокировка ввода на прямую. 
Предусмотреть случай удаления **Корпуса**.

При попытке удалить **Корпуса**, которое связано с **Аудиторией**, отобразить пользователю информационное сообщение о невозможности удалить этот **корпус**.

Для соединения таблиц (контроллеров использовать класс **DataRelation**. Пример реализации находится в ветке [Demo-DataRelation](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/tree/Demo-DataRelation) в классе [RefData.cs](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/Demo-DataRelation/LibOfTimetableOfClasses/RefData.cs)

**Comment by YuriSilenok** [comment]
Мне страшно спрашивать, почему на последнем спринте вы замержили с синтаксическими ошибками?

**Comment by Jeen99** [comment]
Кроме не исправных Юнит-тестов там нет ошибок, если верить CI. 
![image](https://user-images.githubusercontent.com/32433285/58099644-bd49c880-7be4-11e9-9905-06006c0eaf5d.png)
На работу основной программы это никак не виляет, а тесты все равно планируется править, так почему не замержить?

**Comment by YuriSilenok** [comment]
Необходимо устранить замечания:
- Откатил ваши изменения из ветку спринта  #792. В ветке могут быть сбои по автотестам, но нельзя допускать ломанного проекта, в том числе и автоматической библиотеки.
- ваша ветка task-696 была пущена из конца 5 спринта, почему?

**Comment by YuriSilenok** [comment]
- Вы пустите новую ветку task-696-1 от последнего коммита текущего спринта.
- В ней измените функциональность, если ваша функциональность будет содержать настолько сильные изменения что автотесты не будут компилироваться, то должны быть созданы 2 задачи на изменение сценариев и исправление автотестов в той же ветке. 
- Когда тестировщики подтвердят что автотестыв исправлены в ветке task-696-1, тогда и будет мерж.

**Comment by Jeen99** [comment]
> * В ней измените функциональность, если ваша функциональность будет содержать настолько сильные изменения что автотесты не будут компилироваться, то должны быть созданы 2 задачи на изменение сценариев и исправление автотестов в той же ветке. Когда тестировщики подтвердят что автотестыв исправлены, тогда и будет мерж.

Я должен сам поднять эти задачи или сообщить это главному тестировщику?

**Comment by YuriSilenok** [comment]
Вы должны сообщить
https://docs.google.com/presentation/d/187r1uDGzXg_CqAncaExp_TSQBLoPOgIoXfYTNeabWNU/edit#slide=id.g5785e0de3c_0_212
![image](https://user-images.githubusercontent.com/14871471/58100680-c63b9980-7be6-11e9-9c15-eaa86f6727a9.png)
Внимательнее на лекциях

**Comment by Jeen99** [comment]
> * ваша ветка task-696 была пущена из конца 5 спринта, почему?

Не обратил на это внимание. Это на что-то влияет и как это можно отследить через Гитхаб?

**Comment by YuriSilenok** [comment]
![image](https://user-images.githubusercontent.com/14871471/58100749-ec613980-7be6-11e9-8b8b-9269c3cdcb19.png)

Визулально можно посмотреть [здесь](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/network)
Линия ветки уходит в прошлое.
Проследите синию линию

Косвенно, можно понять по мержконфликтам, что у Вас и произошло.
Их почти не должно быть при мерже тасков

**Comment by YuriSilenok** [comment]
Вы со вчерашнего вечера держите спринт в поломанном состоянии.
Это плохо. Я надеюсь в дальнейшем мы будем из\бегать дальнейших систуаций.
![image](https://user-images.githubusercontent.com/14871471/58101021-7f9a6f00-7be7-11e9-83ce-50d21fce8222.png)

**Comment by Jeen99** [comment]
Хорошо. Просто раньше мы немного по другому действовали, сначала разработчики выполняли задачу и после этого писались тесты.

**Comment by YuriSilenok** [comment]
Да, все верно, тесты были под новую функциональность, сейчас идеть болезненный процесс (переделывание существующей функциональности). Это накладывает ограничение.
На следующей лекции будем разбирать более детально все эти ситуации на примерах.

**Comment by Jeen99** [comment]
Как мне нужно уведомить глав. тестировщика? Прикрепить сюда с просьбой выполнить задачу или поднять задачу или это не имеет значение и подойдет любой сбособ, даже переписка в ВК?

**Comment by YuriSilenok** [comment]
лучше в запросе на слияние через сабаку перечислить старшего тестировщика и тимлида (куда без него) что бы обратили на, то их автоматически тесты больше не работают. можте отправить из в слайды. Все в вкомментарии.

**Comment by Jeen99** [comment]
> В ней измените функциональность, если ваша функциональность будет содержать настолько сильные изменения что автотесты не будут компилироваться, то должны быть созданы 2 задачи на изменение сценариев и исправление автотестов в той же ветке.

Каким образом теперь загрузить отмененные изменения в новую ветку? Использовать cherry-pick?

**Comment by Jeen99** [comment]
@YuriSilenok,  А вот эту работу #630 не нужно тоже откатывать?

**Comment by Jeen99** [comment]
Тесты стали не актуальны уже в #630. И если сейчас править тесты для задачи #696, то часть ошибок останется.

**Comment by YuriSilenok** [comment]
Больше ничего открытывать не будет, сейчас главное усилие нужно пустить на исправление в текущей задаче. Есть возможность пускать ветки от конкретного коммита (что бы использовать рабочий проект с автотестами) еще можно пустить ветку от таска (если только в ней есть функуиональность).

**Comment by YuriSilenok** [comment]
> Тесты стали не актуальны уже в #630

Вы можете восстановить ветку и в ней продолжить работу, под другой задачей, и еще одним запросом залить изменения.

**Comment by Jeen99** [comment]
> Больше ничего открытывать не будет, сейчас главное усилие нужно пустить на исправление в текущей задаче. Есть возможность пускать ветки от конкретного коммита (что бы использовать рабочий проект с автотестами) еще можно пустить ветку от таска (если только в ней есть функуиональность).

Правильно я понимаю, что в таком случае нужно сначала восстановить тесты для #630. А потом уже создавать ветку task-696-1 для #696, иначе так и будет висеть ошибка в task-696-1.

**Comment by YuriSilenok** [comment]
Не совсем понимаю уже, возможно устал.

Могу предположить что в обеих ветках у вас одна причина сбоев, можете пофиксить в одной из них, а потом из нормальной ветки смержить туда, где есть ошибки, причем это можно сделать без запроса, при помощи команды git merge

**Comment by Jeen99** [comment]
Примерно так и хотели делать, правда ошибки в ветках все же разные.
