### ISSUE TITLE
Автоматизация тестирования юнит-тестами для автоматизации unit-test для метода Delete(Model model) сущности Teacher

### ISSUE THREAD

**Issue by SamuraSwordS** [Students-of-the-city-of-Kostroma/Student-timetable#7]
[План разработки](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.p).

[Сценарий](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548).

[Ссылка](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit) на диаграмму классов.

**Comment by YuriSilenok** [comment]
Добрый день,
почему была удалена метка контроллера, обратите внимание на описание метки Преподаватель.
Спасибо.

**Comment by YuriSilenok** [comment]
Зачтено
