### ISSUE TITLE
Написание сценариев тестирования пригодных для автоматизации модульного тестирования для метода Update(Model model) сущности Auditor  

### ISSUE THREAD

**Issue by MyachevM** [Students-of-the-city-of-Kostroma/Student-timetable#71]
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)
[Ссылка](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit) на диаграмму классов.

**Comment by MyachevM** [comment]
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)
[Ссылка](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit) на диаграмму классов.

**Comment by YuriSilenok** [comment]
Здравствуйте.
- Вы подняли задачу на поднятие задачи?
- Метки не соответствуют описанию из ЛР
- Описание задачи содержи неправильно оформленную ссылку.
- Комментарий и описание это не одно  и то же. Описание всегда можно отредактировать. Удалите комментарий, если эта функция еще доступна.
Спасибо.

**Comment by YuriSilenok** [comment]
Здравствуйте @MyachevM 
- На какой вопрос должен отвечать заголовок?
- Метки не соответствую описанию из ЛР, если Вы считаете что соответствуют, то поясните почему.
Спасибо.
