### ISSUE TITLE
Программа терпит крах при удалении изменённого профиля 

### ISSUE THREAD

**Issue by Proffet78** [Students-of-the-city-of-Kostroma/Student-timetable#722]
Баг воспроизводиться в v0.14-Testing
Ликвидация долгов по Sprint3 #927

Форма «профиль подготовки»

Шаги:
1) создаём 2 профиля подготовки (1 и 2 , краткое название совпадает с полным)
2) берём профиль 2, нажимаем изменить
3) меняем краткое название с 2 на 1
4) нажимаем сохранить -> выдаёт сообщение
5) выходим с редактора изменений ( нажимаем на крестик)
6) выделяем профиль 1
7) нажимаем удалить
8) вылетает программа

Ожидаемый результат:
Удаляется профиль.

Фактический результат:
Программа падает при удалении изменённого профиля.

![1E9504B7-9CC8-432A-A028-898C2B0FEF1F](https://user-images.githubusercontent.com/47320491/57970439-f9cdb800-7989-11e9-89dc-21313e2f783e.jpeg)

![ADB3CD93-4C16-4768-9530-E2B556C8B3E0](https://user-images.githubusercontent.com/47320491/57970441-094d0100-798a-11e9-8d36-d8f34c5cfcd0.jpeg)

**Comment by SergeAlekseev** [comment]
Баг воспроизводился в ветке 17-ISbo-2b-6 (6 спринт), сейчас в ветке 17-ISbo-2b-7 (7 спринт), уже не воспроизводится, значит исправлен и можно закрывать задачу.
