### ISSUE TITLE
Нельзя изменить первую строку в форме "Ученые звания" и "Институт"

### ISSUE THREAD

**Issue by ghost** [Students-of-the-city-of-Kostroma/Student-timetable#726]
Способ воспроизведения:

1. Создать 2 строки в таблице "Ученые звания"
2. Изменить первую строку 
Ожидаемый результат: Строка изменится 
Фактический результат: Строка не изменилась

**Comment by ghost** [comment]
Баг устранен

**Comment by Pipyao** [comment]
Проверено, баг устранён и не воспроизводится в ветке Alliance-4.

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
