### ISSUE TITLE
Доработать отображение выпадающих список в AddTeacher и добавить проверку

### ISSUE THREAD

**Issue by FvckNeighbors** [Students-of-the-city-of-Kostroma/Student-timetable#730]
План #758 

- Изменить отображение выпадающего списка (DropDownStyle) Учёная степень и Учёное звание с Simple на DropDownList

- Добавить проверку на пустое поле выпадающего списка Учёная степень 
- Добавить проверку на пустое поле выпадающего списка Учёное звание

**Comment by YuriSilenok** [comment]
> Изменить отображение выпадающего списка Учёная степень
> Изменить отображение выпадающего списка Учёное звание

Я вот не понял что тут нужно было сделать.
Дайте более подробное описание

**Comment by FvckNeighbors** [comment]
> * Изменить отображение выпадающего списка (DropDownStyle) Учёная степень и Учёное звание с Simple на DropDownList

Исправил
