### ISSUE TITLE
Ошибка при вставке некорректных данных в таблицу ВУЗы

### ISSUE THREAD

**Issue by litdex** [Students-of-the-city-of-Kostroma/Student-timetable#739]
Описание бага:
1. Заходим в раздел вузы, жмем добавить запись(или изменить)
2. Копируем некорректные данные (например строку qwerty)
3. Вставляем в "полное название"
![Screenshot_3](https://user-images.githubusercontent.com/38160123/57981863-044d8780-7a46-11e9-885c-9fa0a9f5792f.png)
4. Получаем необработанное исключение
![Screenshot_5](https://user-images.githubusercontent.com/38160123/57981874-26470a00-7a46-11e9-8b25-7c1721e00bd6.png)

**Comment by litdex** [comment]
Здравствуйте, @YuriSilenok
Баг не воспроизводится в v0.20-Testing

Спасибо,
Максим

**Comment by YuriSilenok** [comment]
@litdex зачтено как найденый баг.
