### ISSUE TITLE
Создать форму Добавить группу

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#74]
На форме **Группы** под таблицей в нижнем правом углу добавить кнопу с текстом **Добавить**. Он должна быть привязана к нижнему и правому краю формы. При нажатии на кнопку **Добавить** должна открыться форма **Добавить группу**.

Форма добавить группу должна содержать элементы управления: 

- Строковое поле для ввода Шифра группы
- Числовое поле для ввода численности группы. Минимальная численность 0, максимальная численность 50, с шагом 1.
- Кнопка Отмена
- Кнопка Создать и очистить
- Кнопка Создать и закрыть

Поля ввода должны быть привязаны к левой и правой границе формы.
Кнопки должны находиться внизу формы в один ряд и привязаны к правому нижнему краю формы.

**Comment by YuriSilenok** [comment]
Здравствуйте @Proffet78 .
Так как Вы не проявляли активность по этой задаче, она снята с Вас.
Сообщите письмом когда Вы будете готовы выполнять лабораторные работы.
Спасибо.

**Comment by YuriSilenok** [comment]
Здравствуйте @GubanovAndrey 
Так как Вы не проявляли активность по этой задаче, она снята с Вас.
Сообщите письмом когда Вы будете готовы выполнять лабораторные работы.
Спасибо.

**Comment by GubanovAndrey** [comment]
Здравствуйте.

Я готов приступить к  лабораторной работе № 3.1, снятой по бездействию.

Спасибо.
Губанов Андрей
17-ИСбо-2а

вс, 3 мар. 2019 г. в 10:20, Юрий Силенок <notifications@github.com>:

**Comment by YuriSilenok** [comment]
Добрый день.

Жду от Вас письма на почту

Спасибо

*Yuri Silenok* | QA Analyst, Consolidated FT team | *Exactpro*


BUILD SOFTWARE TO TEST SOFTWARE


*D*&*M:* +7 953 665 79 34 | *W: *exactpro.com
*Follow us:* LinkedIn
<https://www.linkedin.com/company/exactpro-systems-llc/>| Twitter
<https://twitter.com/exactpro>| Facebook
<https://www.facebook.com/exactpro/>| Instagram
<https://instagram.com/exactpro>| Youtube
<https://www.youtube.com/channel/UCFF2_9hAmg4YwEBohNYRsdg>

Exactpro приглашает на практику студентов ИТ-специальностей по направлениям
тестирование, разработка программного обеспечения, системное
администрирование.

Во время практики вы узнаете, как мы тестируем программное обеспечение
мировых финансовых организаций и разрабатываем инструменты для
тестирования, поработаете в команде профессионалов и получите возможность
поучаствовать в реальных проектных задачах.

Мы ждем ваше резюме на cv@exactpro.com с пометкой "прохождение практики" и
указанием интересующего вас направления.
Уточнить мое расписание Вы можете в этом
<https://calendar.google.com/calendar?cid=eXVyaS5zaWxlbm9rQGdtYWlsLmNvbQ>
календаре


вт, 5 мар. 2019 г. в 19:18, Губанов Андрей <notifications@github.com>:

**Comment by YuriSilenok** [comment]
Зачтено
