### ISSUE TITLE
Не реализовано ограничение на ввод  в таблице Профиль подготовки

### ISSUE THREAD

**Issue by litdex** [Students-of-the-city-of-Kostroma/Student-timetable#740]
Описание :
В разделе "профиль подготовки" нету ограничение на ввод данных, можно ввести очень огромное число, также длина строки "краткого названия" профиля подготовки может превышать длину "полного названия". 
![Screenshot_7](https://user-images.githubusercontent.com/38160123/57982559-b9387200-7a4f-11e9-939a-0e9c5466a352.png)

Ожидается:
1. Ограничение длины вводимой информации до оптимальной.
2. Длина "краткое название" должна быть меньше или равна "полное название"

**Comment by Jeen99** [comment]
Максим. количество символов для столбца **"Полное названия профиля подготовки"** - 40 символов.

**Comment by Jeen99** [comment]
Ограничение желательно реализовать в модели "Профиль подготовки".

**Comment by litdex** [comment]
Баг успешно исправлен

**Comment by YuriSilenok** [comment]
> Баг успешно исправлен

Вами?

Вы должны попытатьтся его воспроизвести и указать воспроизвелся он или нет на каком-то релизе
еще необходжимо указать на каком релизе начал воспроизводится этот баг?

**Comment by litdex** [comment]
@YuriSilenok добрый день, хотел проверить его в testing 0.15, но файл exe не запускается

**Comment by YuriSilenok** [comment]
Баг не воспроизводится в ветке Testing [коммит](7c38697b2a3fe2c2e3383b0288bc3b02eac44b48)

**Comment by YuriSilenok** [comment]
@litdex зачтено за найденый баг

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
