### ISSUE TITLE
Невозможно изменить информацию о группе после добавления

### ISSUE THREAD

**Issue by litdex** [Students-of-the-city-of-Kostroma/Student-timetable#741]
План - отчёт на Sprint7 #773
Разработка Sprint 7 #774
Описание бага: 
Невозможно изменить информацию о группе после добавления. Выдает некорректную ошибку
![Screenshot_8](https://user-images.githubusercontent.com/38160123/57982772-69a77580-7a52-11e9-9c77-bdf7869a4ea3.png)

**Comment by YuriSilenok** [comment]
Здравствуйте, @litdex 

Я бы ожидал что Ваши баги будут содержать сценарий воспроизведения бага.
Ознакомьтесь пожалуйста https://habr.com/ru/company/docsvision/blog/264163/

Спасибо,
Юрий

**Comment by litdex** [comment]
Здравствуйте, @YuriSilenok 

Зачтите пожалуйста задания, на которые я вас заасигнил

Спасибо,
Максим

**Comment by litdex** [comment]
Здравствуйте, @YuriSilenok 
Баг не воспроизводится в v0.20-Testing

Спасибо,
Максим

**Comment by YuriSilenok** [comment]
@litdex зачтено как найденный баг
