### ISSUE TITLE
Выполнить слияние Alliance-4 --> Testing

### ISSUE THREAD

**Issue by Takunava** [Students-of-the-city-of-Kostroma/Student-timetable#752]
очень плохое описание

**Comment by Takunava** [comment]
Слияние успешно выполнено #762

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
