### ISSUE TITLE
Разработать метод Delete(Model model) сущности Auditor

### ISSUE THREAD

**Issue by Khajiit-stole-nothing** [Students-of-the-city-of-Kostroma/Student-timetable#76]
**Поведение**: метод удаляет переданную аудиторию в том случае если поля
```
string number;
byte floor; 
string building;
int spacious;
```
есть в списке. Если удаление из таблицы произошло, то метод вернет истину, в других случаях возвращается ложь.
[Ссылка](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit) на диаграмму классов.

**Comment by YuriSilenok** [comment]
Зачтено

**Comment by YuriSilenok** [comment]
Ошибся.
У Вас не верно заполнено поле Assignees

**Comment by YuriSilenok** [comment]
Зачтено

**Comment by YuriSilenok** [comment]
зачтено
