### ISSUE TITLE
Этап разработки для Sprint 1 - DreamTeam

### ISSUE THREAD

**Issue by NordScandinavian** [Students-of-the-city-of-Kostroma/Student-timetable#766]
План #765

**Comment by FvckNeighbors** [comment]
Моей команде на этом спринте нужно связать вашу таблицу Кафедра с нашей таблицей. Поэтому хотелось бы кое-что уточнить. Я правильно понимаю, закрытие этапа разработки означает, что вы не будете больше ничего разрабатывать? Просто форма Кафедра, без функционала - ваша задача на спринт? Или вы будете реализовывать добавление/удаление Кафедры?

**Comment by sidelong44** [comment]
Всё верно, на этот спринт разработка закончена, дальнейшее добавление функционала будет в следующем спринте
