### ISSUE TITLE
План на Sprint 5 - Альянс

### ISSUE THREAD

**Issue by nrabotko** [Students-of-the-city-of-Kostroma/Student-timetable#769]
- [x]  Исправить баги ( 23.05.2019 ) #677 #672 

- [x]  Этапы тестирования:
         -  Переделать сценарии тестирования ( 23.05.2019 )
        - Провести мануальное тестирование ( 24.05.2019 ) 
        - Убрать клонирующие сценарии тестирования (22.05.2019)  

- [x]  Добавить комментарии с помощью /// в контроллер и модуль (24.05.2019) #787 

В comment написать ссылку на задачу через #805

**Comment by YuriSilenok** [comment]
Перевесите на меня, когда спринт будет завершен

**Comment by nrabotko** [comment]
@YuriSilenok, хорошо

**Comment by YuriSilenok** [comment]
Этот спринт сдан?

**Comment by nrabotko** [comment]
Здравствуйте Юрий Викторович,

Да, этот спринт сдан вам 27 мая.

Спасибо,
Анастасия Работько.
17-ВТбо-1б.

вс, 2 июн. 2019 г., 15:17 Юрий Силенок <notifications@github.com>:
