### ISSUE TITLE
Создать форму Добавить дисциплину

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#77]
На форме **Дисциплины** под таблицей в нижнем правом углу добавить кнопу с текстом **Добавить**. Он должна быть привязана к нижнему и правому краю формы. При нажатии на кнопку **Добавить** должна открыться форма **Добавить дисциплину**.

Форма **Добавить дисциплину** должна содержать элементы управления:

* Строковое поле для ввода Шифра дисциплины
* Строковое поле для ввода Названия дисциплины
* Кнопка Отмена
* Кнопка Создать и очистить
* Кнопка Создать и закрыть

Поля ввода должны быть привязаны к левой и правой границе формы.
Кнопки должны находиться внизу формы в один ряд и привязаны к правому нижнему краю формы.

**Comment by Rogachev99** [comment]
Добавленная ветка: task-77

**Comment by YuriSilenok** [comment]
> Добавленная ветка: task-77

Куда вы должны были написать об этом?

**Comment by Jeen99** [comment]
> 
> 
> > Добавленная ветка: task-77
> 
> Куда вы должны были написать об этом?

Я не правильно задание понял?
![default](https://user-images.githubusercontent.com/32433285/53071224-a2d35680-34f2-11e9-8fc2-9f2fb00c6bcb.png)

**Comment by YuriSilenok** [comment]
Этот скрин видели?
![2019-02-19_13-41-55](https://user-images.githubusercontent.com/14871471/53074967-1f6b3280-34fd-11e9-9b86-f5b49a77e02e.png)

**Comment by YuriSilenok** [comment]
Зачтено
