### ISSUE TITLE
Разработка сценариев тестирования для формы Кафедра

### ISSUE THREAD

**Issue by abramovaalina** [Students-of-the-city-of-Kostroma/Student-timetable#771]
Этап тестирования #767 
План #765

1. Открыть "Справочники" - Найти раздел "Кафедры".
2. Открыть "Кафедры" - Открывается новая форма. 
3. На форме должны быть расположены блоки (Сокращенное название, Полное название, Заведующий кафедрой, Институт).
4. Расположены кнопки (Удалить, Изменить, Добавить), при нажатии ничего не происходит.
5. При изменении размеров формы, кнопки закреплены в правой нижней части. Блоки растягиваются. Установлен минимальный размер.

**Comment by abramovaalina** [comment]
1. Открыть "Справочники" - Найти раздел "Кафедры" - Найден 
2. Открыть "Кафедры" - Открывается новая форма - Открылась 
3. На форме расположены блоки (Сокращенное название, Полное название, Заведующий кафедрой, Институт) - Расположены 
4. Расположены кнопки (Удалить, Изменить, Добавить) - Расположены, при нажатии ничего не происходит. 
5. При изменении размеров формы, кнопки закреплены в правой нижней части. Блоки растягиваются. Установлен минимальный размер.

**Comment by sidelong44** [comment]
Нужно перенести сценарии тестирования в [таблицу](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548).
Рекомендую заняться @badsster по #964, чтобы двум людям не выполнять одну и ту же работу.
К сведению, @abramovaalina
