### ISSUE TITLE
Разработка Sprint 7

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Student-timetable#774]
План  #773
Спринт 7 посвящен исправлению багов.
Найденные и принятые на исправление баги:

1.  #739 Ошибка при вставке некорректных данных в таблицу ВУЗы.
2.  #783 Программа падает при удалении пустой таблицы.
3. #779 Программа падает при двойном клике по заголовку таблицы.
4. #741 Невозможно изменить информацию о группе после добавления
5. #778 Не отображается запись в графе окна
6. #782 Наличие недопустимых символов в таблице
7. #794  Нет ограничения уникальности значений для столбца "Почта" в таблице "ВУЗы" при добавлении нового ВУЗа
8. #795 Нет ограничения для одинаковых записей для столбца "Телефон" в таблице "ВУЗы" при добавлении нового ВУЗа
9. #796 Нет ограничения некорректных символов в таблице "Профиль подготовки" при добавлении нового профиля подготовки 
10. #804 Падение программы при удалении измененной записи таблицы "Профиль подготовки"
11. #827 Программа не дает изменять профиль подготовки у группы
12. #828 Программа падает при сохранении нового корпуса корпуса
13. #884 У корпуса невозможно изменить ВУЗ

Задачи на разработку не связанные  с исправлением багов:

1. #763 Документация кода относящегося к справочнику ВУЗы
2. #760 Документация кода относящегося к справочнику Группы
3. #663 RefData перенести статические поля в проект LibOfTimetableOfClasses класс
4. #764 Документация кода относящегося к справочнику Корпус
4. #761 Документация кода относящегося к справочнику Преподаватель

Сделано дополнительно:
#751 
#749

**Comment by YuriSilenok** [comment]
Кажется вы не в ту сторону ссылки ставите, задачи на этап разработки должны ссылаться.

**Comment by KharlamovaAlexandra** [comment]
@YuriSilenok  Моя вина, плохо объяснила. Исправим. Мы используем двухсторонние ссылки, мне так удобнее следить

**Comment by KharlamovaAlexandra** [comment]
Разработка в Sprint7 окончена
