### ISSUE TITLE
Программа падает при двойном клике по заголовку таблицы

### ISSUE THREAD

**Issue by cdvinvate** [Students-of-the-city-of-Kostroma/Student-timetable#779]
План - отчёт на Sprint7 #773
Провести мануальное тестирование #780
Разработка Sprint 7 #774
План - отчёт на Sprint7 #773
Провести мануальное тестирование #780
Разработка Sprint 7 #774
Ликвидация долгов за 1 спринт #920
Шаги реализации бага: 
1.Открыть справочник "Группы" 
2.Нажать "добавить" 
3.В "профиль подготовки" нажать "выбрать"
4.Двойным кликом нажать на "Краткое названия профиля подготовки" 
Ожидаемый результат:
![image](https://user-images.githubusercontent.com/47520627/58043771-bf5d4a00-7b46-11e9-8364-87639b521ff8.png)

Фактический результат:
![Снимок экрана (19)](https://user-images.githubusercontent.com/47520627/58043896-16fbb580-7b47-11e9-8c10-e57e770ae539.png)
Аналогично с другим заголовком таблицы.

**Comment by Proffet78** [comment]
@YuriSilenok ,
Здравствуйте, 
В понедельник, после пары мы с вами договорились, что я могу взять два бага исправить их и вы сможете засчитать мне лабораторную работу ( ЛР3.1)

С уважением, Машарин Валерий 17-ИСбо-2б

**Comment by YuriSilenok** [comment]
Здравствуйте,

@isengrims, Вы закрыли баг, на каком основании? Вы попытались воспроизвести баг?
@cdvinvate, Вы нашли баг, в какой версии он у Вас воспроизвелся?

Спасибо,
Юрий

**Comment by purplegen** [comment]
Здравствуйте, 

@YuriSilenok баг был исправлен, поэтому задача и закрыта.

Спасибо,
Денис Плотников 17-ИСбо-2

**Comment by YuriSilenok** [comment]
Сам баг это задача, и он есть и не живёт в ветках. Баг описывает шаги по воспроизведению сбоя и другие технические детали для воспроизведения сбоя. Сбой это появление ошибки которая находится в какой-то ветке (обнаруживаются автотестами) или релизе (обанруживаются мануально). Когда ошибка исправлена проверяют баг на предмет воспроизводимости сбоя. От этого всегда говорят что баг воспроизводится там-то или не воспроизводится там-то

**Comment by cdvinvate** [comment]
Здравствуйте,

@YuriSilenok, баг был найден в ветке testing

Спасибо,
Дмитрий Иванцов 17-ИДбо-3

**Comment by Proffet78** [comment]
Ликвидация долгов за ЛР03.2 #929

**Comment by cdvinvate** [comment]
В релизе v0.16-Testing баг не воспроизводится.
