### ISSUE TITLE
Провести мануальное тестирование 

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Student-timetable#780]
Задача на тестирование #775
Ликвидация долгов за 1 спринт #920 
Ликвидация долгов за 3 спринт #922 

В Sprint 7  провести мануальное тестирование областей: Преподаватель, Группа, Корпус, ВУЗ, Выбор направления подготовки у группы, Выбор ВУЗа у корпуса.

Найденные баги:
1) #778  Не отображается запись в графе окна
2) #779  Программа падает при двойном клике по заголовку таблицы
3) #782  Наличие недопустимых символов в таблице
4) #783  Программа падает при удалении пустой таблицы
5) #794  Нет ограничения уникальности значений для столбца "Почта" в таблице "ВУЗы" при добавлении нового ВУЗа
6) #795  Нет ограничения для одинаковых записей для столбца "Телефон" в таблице "ВУЗы" при добавлении нового ВУЗа
7) #796  Нет ограничения некорректных символов в таблице "Профиль подготовки" при добавлении нового профиля подготовки
8) #804  Падение программы при удалении измененной записи таблицы "Профиль подготовки"
9) #827  Программа не дает изменять профиль подготовки у группы
10) #884 У корпуса невозможно изменить ВУЗ

**Comment by cdvinvate** [comment]
# 782

**Comment by YuriSilenok** [comment]
В описании используйте однотипные форматирование

**Comment by cdvinvate** [comment]
Понял, спасибо.

**Comment by cdvinvate** [comment]
Для защиты выполнения Sprint 1 и Sprint 3 необходимо 10 багов, 1 баг был найден в Sprinte 6:
#704  Программа падает при двойном клике по заголовку таблицы
На паре от 20 мая были обговорены все условия и то, что данный баг может входить в число 10.

**Comment by YuriSilenok** [comment]
@cdvinvate 
Для учета этих Вы можете создать задачу, ликвидация долгов по лабораторной работе №100 или спринту №200. И сделать перекресные ссылки, в задаче на 8 багов, в багах, на эту задачу.
