### ISSUE TITLE
Наличие недопустимых символов в таблице

### ISSUE THREAD

**Issue by cdvinvate** [Students-of-the-city-of-Kostroma/Student-timetable#782]
План - отчёт на Sprint7 #773
Провести мануальное тестирование #780
Разработка Sprint 7 #774
Ликвидация долгов за 1 спринт #920
Шаги реализации бага:
1.Открыть справочник "Группы"
2.Нажать "добавить"
3.В "профиль подготовки" нажать "выбрать"
4.Нажать "добавить"
5.Ввести в поля формы одни числа
Ожидаемый результат:
Программа не дает вводить цифры пользователю либо выдает предупреждение
Фактический результат:
![image](https://user-images.githubusercontent.com/47520627/58045987-bff8df00-7b4c-11e9-9f9f-05e0eda527f2.png)

**Comment by map82top** [comment]
Данный баг исправлен в пул риквесте #848, поэтому я закрываю данную задачу.

**Comment by cdvinvate** [comment]
В релизе v0.16-Testing баг не воспроизводится.
