### ISSUE TITLE
Программа падает при удалении пустой таблицы

### ISSUE THREAD

**Issue by cdvinvate** [Students-of-the-city-of-Kostroma/Student-timetable#783]
План - отчёт на Sprint7 #773
Провести мануальное тестирование #780
Разработка Sprint 7 #774
Ликвидация долгов за 1 спринт #920

Шаги реализации бага:
1.Открыть справочник "ВУЗы"
2.Нажать "удалить"
Ожидаемый результат:
![image](https://user-images.githubusercontent.com/47520627/58048732-e8380c00-7b53-11e9-9c02-c156f625c0f5.png)

Фактический результат:
![image](https://user-images.githubusercontent.com/47520627/58048685-c9397a00-7b53-11e9-95a0-14e53bbaf0e8.png)

**Comment by map82top** [comment]
@Proffet78  Здесь так же не должно быть чего-нибудь сложного, просто добавить условие

**Comment by YuriSilenok** [comment]
Почему task-783 пущен от Testing?

**Comment by map82top** [comment]
> Почему task-783 пущен от Testing?

Неопытность исполнителя задачи. Я ему не сказал откуда надо ветку пускать

**Comment by map82top** [comment]
@Proffet78 Ветку нужно делать от 17-ISbo-2b-7

**Comment by YuriSilenok** [comment]
Здравствуйте, @map82top 

Видимо нужно написать ему в этой задаче о том, что следующая ветка должна называться task-783-1

Спасибо,
Юрий

**Comment by Proffet78** [comment]
@YuriSilenok ,
Здравствуйте, 
В понедельник, после пары мы с вами договорились, что я могу взять два бага исправить их и вы сможете засчитать мне лабораторную работу ( ЛР3.2)

С уважением, Машарин Валерий 17-ИСбо-2б

**Comment by YuriSilenok** [comment]
Здравствуйте,

@Proffet78, я не увидел существенных изменений в запросе #825 я не уверен что баг не воспроизводится.
@isengrims, Вы закрыли баг, на каком основании? Вы попытались воспроизвести баг?
@cdvinvate, Вы нашли баг, в какой версии он у Вас воспроизвелся?

Спасибо,
Юрий

**Comment by purplegen** [comment]
Здраствуйте, 

@YuriSilenok В 7 спринте не воспроизводится, в 6 воспроизводится

Спасибо

**Comment by Proffet78** [comment]
Ликвидация долгов за ЛР03.1 #929

**Comment by cdvinvate** [comment]
В релизе v0.16-Testing баг не воспроизводится.
