### ISSUE TITLE
Убрать клонирующие сценарии тестирования для методов Update(Model model), Delete(Model model), Insert(Model model) сущности Институт

### ISSUE THREAD

**Issue by nrabotko** [Students-of-the-city-of-Kostroma/Student-timetable#784]
[Таблица сценариев](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=1153322464)
#806 

P.S. Заменить клонирующие юнит-тесты на мануальные тесты

**Comment by yuliagolubevaa5** [comment]
Заменила клонирующие юнит-тесты на мануальные. @Pipyao , прошу проверить правильность сделанных исправлений.

**Comment by Pipyao** [comment]
Исправление внесены верные, сценарии-клоны были заменены.
