### ISSUE TITLE
Разработать сценарии тестирования пригодных для мануального тестирования для метода Delete(Model model) сущности Институт

### ISSUE THREAD

**Issue by nrabotko** [Students-of-the-city-of-Kostroma/Student-timetable#785]
[Таблица сценариев](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=1153322464)
#806

**Comment by yuliagolubevaa5** [comment]
Были разработаны сценарии мануального тестирования для метода Delete (Model model) в кол-ве 3 шт. Прошу проверить выполнение данной задачи @Pipyao

**Comment by Pipyao** [comment]
Проверено, все 3 сценария расписаны верно.
