### ISSUE TITLE
Разработать сценарии теститрования пригодные для мануального тестирования для метода Update(Model model) сущности Института

### ISSUE THREAD

**Issue by nrabotko** [Students-of-the-city-of-Kostroma/Student-timetable#786]
[Таблица сценариев](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=1153322464)
#806

**Comment by YuriSilenok** [comment]
Здесь должна быть ссылка на этап тестирования, а не на план спринта.

**Comment by yuliagolubevaa5** [comment]
Были разработаны сценарии мануального тестирования для метода Update (Model model) Прошу проверить выполнение данной задачи @Pipyao

**Comment by Pipyao** [comment]
Сколько сценариев было разработано?

**Comment by yuliagolubevaa5** [comment]
@Pipyao , четыре, 2 из них включают в себя проверку каждого атрибута.

**Comment by Pipyao** [comment]
Проверено, сценарии расписаны верно.
