### ISSUE TITLE
Добавить комментарии в Institute, AcademicTitle

### ISSUE THREAD

**Issue by nrabotko** [Students-of-the-city-of-Kostroma/Student-timetable#787]
Добавить краткий итог о типе или члене ( `<summary>` )
Прокомментировать все публичные методы и классы, поля, свойства, конструкторы во всем решении. 
#769 
#772

**Comment by YuriSilenok** [comment]
Ссылки на план в задачах можно не делать, достаточно только на этап

**Comment by Takunava** [comment]
Комментарии добалены

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу
