### ISSUE TITLE
Улучшить добавление справочника "Преподаватели" (Ученая степень)

### ISSUE THREAD

**Issue by 16-vt-1a** [Students-of-the-city-of-Kostroma/Student-timetable#788]
При добавления нового справочника "Преподаватели" не удается выбрать ученую степень у преподавателя , ибо справочник "ученая степень" пуст (При первом использовании программы не сразу понятно, что сначала необходимо заполнить справочник "ученая степень", после чего будет возможность выбрать ее в добавлении справочника "Преподаватели"). 
Реализовать вместо выпадающего списка чекбокс с отключенной функцией ввода значений, это текстовое поле должно хранить первичный ключ ученой степени. Ученая степень выбирается кнопкой, расположенной правее этого чекбокса, текст которой (. . .)  При нажатии должен открыться справочник, по двойному клику которому должна быть возможность выбрать ученую степень, открываемая таким образом форма должна сохранить весь функционал. Либо добавить подсказки, что сначала нужно заполнить справочник "Ученая степень". 
Версия программы (v0.14)

Этап разработки #809

**Comment by YuriSilenok** [comment]
@16-vt-1a Укажите правильную версию ПО

**Comment by YuriSilenok** [comment]
Меня поставите ответственным когда придет время засчитывать балл

**Comment by YuriSilenok** [comment]
@16-vt-1a v0.14 не является полным названием.

**Comment by FvckNeighbors** [comment]
Данная функциональность была уже сделана #887

**Comment by 16-vt-1a** [comment]
все исправили

**Comment by YuriSilenok** [comment]
зачтено
