### ISSUE TITLE
Улучшить добавление справочника "Преподаватели" (Ученое звание)

### ISSUE THREAD

**Issue by 16-vt-1a** [Students-of-the-city-of-Kostroma/Student-timetable#789]
При добавления нового справочника "Преподаватели" не удается выбрать Ученое звание у преподавателя , ибо справочник "Ученое звание" пуст (При первом использовании программы не сразу понятно, что сначала необходимо заполнить справочник "Ученое звание", после чего будет возможность выбрать ее в добавлении справочника "Преподаватели"). Реализовать переход к заполнению Ученого звания из преподавателя, либо добавить подсказки, что сначала нужно заполнить справочник "Ученое звание". 
Версия программы (v0.14-Testing)

Этап разработки #809

**Comment by YuriSilenok** [comment]
@16-vt-1a Укажите правильную версию ПО

**Comment by YuriSilenok** [comment]
@16-vt-1a v0.14 не является полным названием.

**Comment by YuriSilenok** [comment]
Меня поставите ответсвенным когда придет время засчитывать балл

**Comment by FvckNeighbors** [comment]
Данная функциональность была уже сделана #887

**Comment by 16-vt-1a** [comment]
Все сделали

**Comment by YuriSilenok** [comment]
Зачтено
