### ISSUE TITLE
Провести мануальное тестирование

### ISSUE THREAD

**Issue by Proffet78** [Students-of-the-city-of-Kostroma/Student-timetable#791]
Задача на тестирование #775

В Sprint 7 провести мануальное тестирование областей: Преподаватель, Группа, Корпус, ВУЗ, Выбор направления подготовки у группы, Выбор ВУЗа у корпуса.

Найденные баги:
1) #828 Программа падает при сохранении нового корпуса корпуса 
2) #878 Изменение краткого названия профиля, при добавлении нового профиля подготовки
3) #879 Невозможно добавить нового преподавателя
4) #880 Невозможно создать нового преподавателя, не создавая заранее ученую степень и звание
5) #881 Невозможно добавить ВУЗ с одинаковым кратким названием
6) #882 Возможность существования двух, разных по названию, корпусов, на одном адресе и с одним телефоном

**Comment by Proffet78** [comment]
Для защиты выполнения Sprint 3, необходимо 8 багов, 3 бага были найдены в Sprinte 6:
1) #721 Изменение ФИО ректора, при редактировании ВУЗа ,
2) #719 Программа терпит крах при удалении преподавателя в форме «Преподаватели» 
3) #722 Программа терпит крах при удалении изменённого профиля


На паре от 20 мая было обговорено что данные баги могут входить в число 8.

**Comment by YuriSilenok** [comment]
@Proffet78 
Для учета этих Вы можете создать задачу, ликвидация долгов по лабораторной работе №100 или спринту №200. И сделать перекресные ссылки, в задаче на 8 багов, в багах, на эту задачу.
