### ISSUE TITLE
Нет ограничения уникальности значений для столбца "Почта" в таблице "ВУЗы" при добавлении нового ВУЗа

### ISSUE THREAD

**Issue by cdvinvate** [Students-of-the-city-of-Kostroma/Student-timetable#794]
План - отчёт на Sprint7 #773
Провести мануальное тестирование #780
Разработка Sprint 7 #774
Ликвидация долгов за 1 спринт #920
Шаги реализации бага:
1.Открыть справочник "ВУЗы"
2.Нажать "добавить"
3.Заполнить поля формы
4. Создать еще один ВУЗ с такой же электронной почтой
Ожидаемый результат:
Программа сообщит пользователю, что данная почта уже занята и невозможно добавить ВУЗ.
Фактический результат:
![image](https://user-images.githubusercontent.com/47520627/58107925-91820f00-7bf3-11e9-8628-f70b2adf7db4.png)

**Comment by YuriSilenok** [comment]
Здравствуйте, @cdvinvate,

заголовок бага должен отвечать на три вопроса 
https://habr.com/ru/company/docsvision/blog/264163/
- Что не работает?
- Где не работает?
- Когда не работает?

В данном случае вы можете написать

> Нет ограничения (Что?) для столбеца "Почта" в таблице "ВУЗы" (Где?) при добавлении нового ВУЗа (Когда?)

Спасибо,
Юрий

**Comment by cdvinvate** [comment]
Здравствуйте @YuriSilenok 

Приму на вооружение.

Спасибо,
Дмитрий

**Comment by cdvinvate** [comment]
В релизе v0.16-Testing баг не воспроизводится.
