### ISSUE TITLE
Создать справочник "Учебная неделя"

### ISSUE THREAD

**Issue by DemiKor** [Students-of-the-city-of-Kostroma/Student-timetable#798]
Создать справочник "Учебная неделя" на которой располагается таблица со столбцами:
* номер
* наименование

Кнопки:
* Удалить
* Изменить
* Добавить

В качестве образца оформления и поведения использовать справочник "Преподаватели"

**Comment by YuriSilenok** [comment]
Здравствуйте, @DemiKor 

Используйте правильное форматирование списков
https://guides.github.com/features/mastering-markdown/

Спасибо,
Юрий

**Comment by DemiKor** [comment]
Выполнено в ветке task-798
Пул реквест заведен

**Comment by YuriSilenok** [comment]
- Еще раз напоминаю что нужно правильно использовать форматирование для списков, если вы не понимаете о чем я говорю, спросите.
- Заголовок запроса на слияние должно повторять по сути заголовок задачи с ответом на вопрос "что было сделано?"
- Обратите на комментарий в запросе

**Comment by YuriSilenok** [comment]
- По поводу атрибутов задачи. Эта задача в рамках спринта или ЛР выполняется?

**Comment by DemiKor** [comment]
* Задача выполняется в рамках ликвидации долга

**Comment by DemiKor** [comment]
Здравствуйте, @YuriSilenok
Не было активности в связи с сессией
Исправил ошибки, которые были записаны в прошлом пуле, и завел новый

**Comment by YuriSilenok** [comment]
> * Задача выполняется в рамках ликвидации долга

долга по спринту или ЛР? 

этот вопрос был вызван отсутствием атрибута Веха

**Comment by DemiKor** [comment]
Долг по зачету годовой давности

**Comment by YuriSilenok** [comment]
Когда закончите с запросом на слияние, перевесьте задачу на меня, я зачту балл.

**Comment by YuriSilenok** [comment]
зачтено

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
