### ISSUE TITLE
Автоматизировать unit-тесты класса CTrainingProfile

### ISSUE THREAD

**Issue by DariaMann** [Students-of-the-city-of-Kostroma/Student-timetable#799]
Исправить тест на выбора Направления подготовки у Профиля подготовки 
Результаты запишите в [таблицу](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=54897640)

**Comment by YuriSilenok** [comment]
Я потом спрошу какие автоматические тесты были изменены этим таском
