### ISSUE TITLE
Автоматизация тестирования юнит-тестами для класса MGroup

### ISSUE THREAD

**Issue by Proffet78** [Students-of-the-city-of-Kostroma/Student-timetable#8]
Протестировать код по существующим сценариям, которы описаны в этой [таблице](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit?usp=sharing)
[План разработки](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.p)
[Ссылка](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit) на диаграмму классов

**Comment by YuriSilenok** [comment]
Добрый день.

Задача должна быть заасанина на того кто с ней должен поработать, то есть на меня. Я посмотрел и ссылка на сценарии должна вести на общую таблицу. Так же у вас должна быть метка Model/

Спасибо.

**Comment by Proffet78** [comment]
> Разработать сценарии пригодные для Unit-тестирования в эту [таблицу](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit?usp=sharing)
> [План разработки](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.p)
> [Ссылка](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit) на диаграмму классов

**Comment by YuriSilenok** [comment]
Если вы не работаете над задачей в данный момент, задачц с себя нужно снимать.
Вам не в комментарии нужно ссылку вставить новую ссылку, а в дискрипшен.
Его можно отредактировать кнопкой Edit.
![image](https://user-images.githubusercontent.com/14871471/52277277-5bcb5a00-2965-11e9-9bc8-3d1d2f89a89a.png)

**Comment by Proffet78** [comment]
Добрый день! 

Я исправил ваше замечание!

Спасибо.

**Comment by YuriSilenok** [comment]
Добрый день,

Ваш дискрипшен говорит о разработке сценариев тестирование, а заголовок говорит об автоматизации тестирования, что у Вас на самом деле?

Спасибо.

**Comment by YuriSilenok** [comment]
Клсаа MGroup относиться к модели, сам таск относиться к автоматизации тестирования, проверьте метки, у вас есть лишние.

**Comment by YuriSilenok** [comment]
У Вас та же ошибка что и [здесь](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/10#issuecomment-460665820)

**Comment by YuriSilenok** [comment]
МGroup относиться к модели, и должен иметь соответвующую метку и не должен иметь метку на контроллер.

**Comment by YuriSilenok** [comment]
зачтено
