### ISSUE TITLE
Автоматизировать unit-тесты класса CAuditor

### ISSUE THREAD

**Issue by DariaMann** [Students-of-the-city-of-Kostroma/Student-timetable#800]
Автоматизировать тест на выбор у Аудитории Корпуса.
Результаты в запишите [таблицу](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=54897640)

**Comment by YuriSilenok** [comment]
Здравствуйте, @DariaMann 

Я бы не тпонял каие номера тестовых сценариев я должен автоматизировать.
Как Вы это орпеделяете?

Спасибо,
Юрий
