### ISSUE TITLE
Автоматизировать unit-тесты класса CDiscipline

### ISSUE THREAD

**Issue by DariaMann** [Students-of-the-city-of-Kostroma/Student-timetable#801]
Протестировать и исправить unit-тесты, если были выявлены ошибки.
Результаты в запишите [таблицу](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=54897640)

**Comment by YuriSilenok** [comment]
Агрегированные результаты должны попать в задачу, я буду спрашивать сколько тестов и как прогнались в результате выполнения этого таска.

**Comment by YuriSilenok** [comment]
Здравствуйте, @DariaMann 

Какова причина закрытия задачи?
Я бы ожидал, что причина внезапных закрытий должна быть указана всегда.

Спасибо,
Юрий

**Comment by DariaMann** [comment]
Здравствуйте, @YuriSilenok 

Unit-тесты на данный класс не требуют автоматизации так как они не были изменены. По этому я закрыла задачу.

Спасибо,
Дарья
