### ISSUE TITLE
В "Ученые звания" можно добавить, некорректную запись

### ISSUE THREAD

**Issue by itword7111** [Students-of-the-city-of-Kostroma/Student-timetable#815]
#954
Название ветки: Alliance-5 Фиксация 0e454f9
Баг воспроизводится в v0.18-Testing
Шаги реализации бага:
1. Открыть справочник "Ученые звания"
2. Нажать "добавить"
3. В поле "Сокращенная запись уч. звания" ввести "   е"
4. В поле "Полная запись уч. звания" ввести "   е"
5. Нажать "создать и закрыть"
Ожидаемый результат:
создается новая ученая степень
![image](https://user-images.githubusercontent.com/38357886/58130013-c27a3800-7c23-11e9-8509-54a393d89db2.png)
Фактический результат:
![image](https://user-images.githubusercontent.com/38357886/58130036-c8701900-7c23-11e9-961d-45e334cf9a12.png)

**Comment by YuriSilenok** [comment]
- Здравсвуйте, Вы знаете как найти команду ответсвенную за эту предметную область?
-  используйте правильное форматирование для списков https://guides.github.com/features/mastering-markdown/
- В какой версии ПО вы это нашли?

**Comment by itword7111** [comment]
версия v0.14-Testing

**Comment by itword7111** [comment]
assign делать на туже команду, на которую вешал (кто делает ветку Alliance-5 )
?

ср, 22 мая 2019 г. в 14:30, Юрий Силенок <notifications@github.com>:

**Comment by itword7111** [comment]
а в какой ветке мне баги искать в  Alliance-5   ?

чт, 23 мая 2019 г. в 10:27, Павел Калашников <pavelkalashnikov9819@gmail.com

**Comment by Takunava** [comment]
Здравствуйте, 
я не вижу тут собственно бага скорей похоже на улучшение

**Comment by Takunava** [comment]
Собственно данная задача выполнена в ветку #851
