### ISSUE TITLE
Добавить изменения из ветки 17-ISbo-2a-6 в ветку Testing

### ISSUE THREAD

**Issue by ZhezlovaDaria** [Students-of-the-city-of-Kostroma/Student-timetable#816]
очень плохое описание

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче
