### ISSUE TITLE
Этап разработки на спринт 7 группы 17-ИСбо-2а

### ISSUE THREAD

**Issue by ZhezlovaDaria** [Students-of-the-city-of-Kostroma/Student-timetable#820]
План #819

Этапы разработки: 
- [x] Устранить все предупреждения в проекте (#834)
- [x] Задокументировать код (#836, #837)
- [x] Исправить баги, поступившие за первые пять дней спринта (#855)

**Comment by Parallusion** [comment]
Все задачи выполнены.
