### ISSUE TITLE
Программа не дает изменять профиль подготовки у группы

### ISSUE THREAD

**Issue by cdvinvate** [Students-of-the-city-of-Kostroma/Student-timetable#827]
План - отчёт на Sprint7 #773
Провести мануальное тестирование #780
Разработка Sprint 7 #774
Ликвидация долгов за 3 спринт #922
Шаги реализации бага:
1.Открыть справочник "Группы" 
2.Нажать "добавить" 
3.Во всплывшем окне нажимаем "да"
4. В открывшемся окне создаем два профиля подготовки
5. Выбираем один из них двойным кликом
6. В окне "добавление группы" жмем "сохранить"
7. Жмем на кнопку изменить и выбираем другой профиль подготовки
8 .В окне "добавление группы" жмем "сохранить"
Ожидаемый результат:
У записи изменится поле "профиль подготовки"
Фактический результат:
![image](https://user-images.githubusercontent.com/47520627/58195267-3bcf6480-7cd0-11e9-841c-9a8ac077b8f3.png)

**Comment by map82top** [comment]
@KharlamovaAlexandra 
Баг на данный момент времени не воспроизводится в ветке 17-ISbo-2b-7

**Comment by YuriSilenok** [comment]
1. Указать версию релиза где был найден баг
2. Разработчик может проверить в спринтовой ветке это баг но не закрывая указать ветку где не воспроизвелся
3. Тестировщик нашедший баг проверяет в релизе. Указывает номер релиза.

**Comment by cdvinvate** [comment]
Баг был найден в ветке testing и в ветке 17-ISbo-2b-7 был исправлен

**Comment by cdvinvate** [comment]
В релизе v0.16-Testing баг не воспроизводится.
