### ISSUE TITLE
Программа падает при сохранении нового корпуса

### ISSUE THREAD

**Issue by Proffet78** [Students-of-the-city-of-Kostroma/Student-timetable#828]
План - отчёт на Sprint7 #773
Провести мануальное тестирование #791
Разработка Sprint 7 #774
Баг воспроизводиться в v0.15-Testing
Ликвидация долгов по Sprint3 #927

Шаги :
1) Открыть форму "Корпус"
2) Нажать кнопку "добавить"
3) заполнить все поля
4) нажать кнопку "добавить вуз"
5) добавить вуз (заполнив все поля)
6) добавить вуз в корпус
7) нажать кнопку "добавить вуз"
8) изменить название вуза
9) сохранить
10) выйти из формы "ВУЗы"
11) заменить вуз в форме корпуса
12) сохранить

Ожидаемый результат:
Создается новый корпус

Фактический результат:
Программа падает при сохранении

![2](https://user-images.githubusercontent.com/47320491/58195417-9963b100-7cd0-11e9-8a9a-185f2d891c58.PNG)
![1](https://user-images.githubusercontent.com/47320491/58195424-9c5ea180-7cd0-11e9-88b7-255f5b7a60b2.PNG)

**Comment by YuriSilenok** [comment]
Опечатка в заголовке

**Comment by YuriSilenok** [comment]
Вы мой комментарий заигнорили?
