### ISSUE TITLE
Автоматизировать сценарии для метода Delete(model:Model) класса CAuditor унаследованного от класса Controller

### ISSUE THREAD

**Issue by Pipyao** [Students-of-the-city-of-Kostroma/Student-timetable#83]
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)
[Ссылка](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit) на диаграмму классов.
Имя файла, содержащего автотесты UT_CAuditor

**Comment by YuriSilenok** [comment]
Здравствуйте.
- Заголовок не отвечает на нужный вопрос
- Нет описания к задаче
- Поле Assignees заполнено не верно
- Метки заполнены не верно
Спасибо.

**Comment by Pipyao** [comment]
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)
[Ссылка](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit) на диаграмму классов.
Имя файла, содержащего автотесты UT_CAuditor

**Comment by YuriSilenok** [comment]
Здравствуйте.
Вторая подсказка о том, что такое описание задачи.
![image](https://user-images.githubusercontent.com/14871471/53175069-4eb49900-35fc-11e9-86cc-40697871306e.png)

- Заголовок не отвечает на нужный вопрос.
- Нет описание задачи

Советую прочитать более внимательно инструкция к [ЛР01](https://docs.google.com/document/d/1k8ILnmYVi3Cz-mTge3h6RI0OV4DbAHviQseScRRpUxI/edit)

**Comment by YuriSilenok** [comment]
Зачтено
