### ISSUE TITLE
Устранить все предупреждения в проекте

### ISSUE THREAD

**Issue by Jeen99** [Students-of-the-city-of-Kostroma/Student-timetable#834]
Этап разработки: #820

Сейчас в проекте есть предупреждения, по большей части они связаны с неиспользуемыми переменными. Необходимо устранить предупреждения (**отключать их не нужно! =)** ).

![image](https://user-images.githubusercontent.com/32433285/58212415-6385f300-7cf7-11e9-98f0-ae7685753a76.png)

_Ветку для которой нужно делать правки (17-ISbo-2a-7). Свою ветку task-*** создавать от 17-ISbo-2a-7._

**Comment by Jeen99** [comment]
@YuriSilenok, какие метки должны стоять у данной задачи?

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой
