### ISSUE TITLE
У сущности Преподаватель реализовать функционал выбора Кафедры путем связывания с таблицей Кафедра

### ISSUE THREAD

**Issue by FvckNeighbors** [Students-of-the-city-of-Kostroma/Student-timetable#838]
Добавить выпадающий список для выбора Кафедры в форму добавления Преподавателя. Связать выпадающий список с таблицей Кафедры.

**Comment by VinogradovAlexandr781227** [comment]
@YuriSilenok , добрый день.
От какой ветки нужно ответвляться? Т.к. в ветке Testing нет модели и контроллера "Кафедры"?
Спасибо.

**Comment by YuriSilenok** [comment]
Дизайнеры не доделали мерж, решаю эту проблему здесь #1110

**Comment by YuriSilenok** [comment]
Обновите локальную копию ветки Testing  и проверьте, появились ли интересующие Вас классы

**Comment by YuriSilenok** [comment]
если в течении 7 дней активности по задаче не будет, задача будет снята

**Comment by YuriSilenok** [comment]
снято по неактивности
