### ISSUE TITLE
План на Sprint 3 - 17-ИДбо-3а

### ISSUE THREAD

**Issue by ivshr** [Students-of-the-city-of-Kostroma/Student-timetable#839]
Номер| Описание
-- | -- 
 №1 #1012 #1021| Разработать функционал для формы "Вид занятия". Реализовать функции: Добавить, Изменить, Удалить (+Вопрос при удалении), Сортировка, Количество строк в таблице, Привести имена столбцов в соответствие с программой http://rector.spb.ru/setup4u.exe. При разработке, учитывать написание комментариев. 
 №2 #842 #1020 #1040 #1042 #1043 #1044 | Разработать сценарии тестирования и автоматические тесты для формы "Вид занятия" 
 №3 #844 #873 #875 #877 #997| Провести автоматическое тестирование формы "Вид занятия"
 №4 #846 #872 #874 #876  | Выполнить мануальное тестирование формы "Вид занятия". Составить отчёт о результатах тестирование
[№5](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/1080)  | Выполнить merge в ветку Testing

**Comment by YuriSilenok** [comment]
спринт сдан
