### ISSUE TITLE
Создать форму таблицы Вид занятия

### ISSUE THREAD

**Issue by MariNazarova** [Students-of-the-city-of-Kostroma/Student-timetable#840]
Разработка формы таблицы для кнопки [добавить](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/398)
В соответствиями с [функциональными требованиями](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/1021) к разработке

**Comment by YuriSilenok** [comment]
Эта задача должна иметь:
- более подробное описание графического интерфейса
- ссылку на этап разработки
- метку Story
