### ISSUE TITLE
Создание таблицы формы Вид занятия

### ISSUE THREAD

**Issue by MariNazarova** [Students-of-the-city-of-Kostroma/Student-timetable#841]
Создать таблицу в форме
[Этап разработки](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/1012)
[План спринта 3](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/839)

**Comment by YuriSilenok** [comment]
- Эта задача является частью задачи #840?
- почему на задачу по созданию таблицы был создан запрос на слияние по созданию формы и контроллера #845?
