### ISSUE TITLE
Этап тестирования для спринта 3. 17-ИДбо-3а

### ISSUE THREAD

**Issue by MasterDesigner** [Students-of-the-city-of-Kostroma/Student-timetable#842]
Разработать автотесты для модели сущности MTypesOfOccupation
Разработать автотесты для контроллера  сущности CTypesOfOccupation
Разработать сценарий тестирования для модели (описать действия программы) сущности TypesOfOccupation
Разработать сценарий тестирования для контроллера (описать действия программы)  сущности TypesOfOccupation
Разработать сценарий тестирования для представления (описать действия пользователя)сущности TypesOfOccupation
[Сценарий](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=812383542) 
Выполнить в соответствии с [планом](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/839)

**Comment by YuriSilenok** [comment]
Не указана сущность для которой будет вестись тестирование

**Comment by MasterDesigner** [comment]
> Не указана сущность для которой будет вестись тестирование

Исправил

**Comment by YuriSilenok** [comment]
Закрыт по неактивности
