### ISSUE TITLE
Автоматизация сценариев. 17-ИДбо-3а

### ISSUE THREAD

**Issue by MasterDesigner** [Students-of-the-city-of-Kostroma/Student-timetable#844]
Разработать автотесты для модели (Model Model)
Разработать автотесты для контроллера (Controller)
[План на спринт 3](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/839)

**Comment by YuriSilenok** [comment]
- если вы сделали задачу на разработку всех автотестов, тогда каждая задача на разработку автотесов (как подчиненная задача) должна ссылаться на эту задачу.
- согласно Вашего описания я не могу понять для какой сущности будут автоматизированы тесты (меток тоже нет)
