### ISSUE TITLE
Модульное тестирование Вид занятий. 17-ИДбо-3а

### ISSUE THREAD

**Issue by MasterDesigner** [Students-of-the-city-of-Kostroma/Student-timetable#846]
Провести мануальное тестирование для 3 спринта
[План на спринт 3](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/839)

**Comment by YuriSilenok** [comment]
- нужна ссылка на таблицу сценариев
- нужно обозначить источник (номер задачи) в которой разрабатывались сценарии и для которой разрабатывались сценарии
