### ISSUE TITLE
Нельзя добавить учёную степень с тире

### ISSUE THREAD

**Issue by FvckNeighbors** [Students-of-the-city-of-Kostroma/Student-timetable#858]
Название ветки: Union-5
Шаги реализации бага:
1. Открыть справочник "Ученая степень"
2. Нажать "Добавить"
3. В поле "Сокращенная запись ученой степени" ввести К-т"
4. В поле "Полная запись ученая степень" ввести "Кандидат"
5. Нажать "Создать и закрыть"

Ожидаемый результат:
Ученая степень успешно добавится

Фактический результат:
![image](https://user-images.githubusercontent.com/47320314/58289215-7b747a00-7dbe-11e9-82a0-ab0414a5c887.png)

Этап разработки #809

**Comment by Mikleproxorov** [comment]
Данный баг больше не воспроизводиться.
