### ISSUE TITLE
Доработать проверки полей в форме Институт 

### ISSUE THREAD

**Issue by Takunava** [Students-of-the-city-of-Kostroma/Student-timetable#869]
Требования к проверкам полей:
1.Ограничение по символам - 50 символов.
2. Минимальное кол-во символов - 1 символ.
3.Если поле не заполнено - выводить предупреждение о том, какое поле не заполнено. Если поле заполнено ошибочно - предупреждать об этом.
Этап разработки #772

**Comment by YuriSilenok** [comment]
Вы доработали функциональность, и есть вопросы:
- почему вы стали менять автотетсы без задачи на это?
- Где задача на изменение сценариев ссылающаяся на эту задачу?
- Где задача на разработку новых сценариев для новых ограничений  ссылающаяся на эту задачу?
- Где задача на автоматизацию сценариев тестированя для новых сценариев тестирования  ссылающаяся на эту задачу?
- Где задача на мануальное тестирование этих ограничений  ссылающаяся на эту задачу?
- Почему нет меток которые указывают какую часть архитектуры затронут эти изменения?

**Comment by Takunava** [comment]
Здравствуйте,
метки я забыл поставить моя ошибка, а UT я изменил чтобы нормально прошли тесты, и сказал тестировщикам, как можно видеть выше задачи уже начали поднимать.

**Comment by Takunava** [comment]
Задача выполнена
