### ISSUE TITLE
Мануальное тестирование формы добавления Вида занятия

### ISSUE THREAD

**Issue by MasterDesigner** [Students-of-the-city-of-Kostroma/Student-timetable#872]
Произвести мануальное тестирование и заполнить свою таблицу с результатами.
Этап https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/842 тестирования
[Таблица](https://docs.google.com/spreadsheets/d/1cKQcFnioprGTfVmXnvlxUJMDc2T76tS3rFDfatkAEWw/edit?usp=sharing)
[План на спринт 3](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/839)
[Таск на разработку сценария](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/1020)

**Comment by YuriSilenok** [comment]
ссылка на этап + метки
