### ISSUE TITLE
Автоматизировать сценарии тестирования методом юнит-тестирования для метода Insert(Model model) класса СTypesOfOccupation

### ISSUE THREAD

**Issue by MasterDesigner** [Students-of-the-city-of-Kostroma/Student-timetable#873]
Этап тестирования https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/842
[Сценарий](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=812383542)
[План на спринт 3](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/839)
[Таск на разработку сценария](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/1020)

**Comment by YuriSilenok** [comment]
Ссылка на план + метки
