### ISSUE TITLE
Мануальное тестирование формы изменения Вида занятия

### ISSUE THREAD

**Issue by MasterDesigner** [Students-of-the-city-of-Kostroma/Student-timetable#874]
Произвести мануальное тестирование и заполнить свою таблицу с результатами.
Этап тестирования https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/842
[Таблица](https://docs.google.com/spreadsheets/d/18H1KMkdLOGQap2s1incsICBm8a_SF7DbDw6iGudFrb8/edit?usp=sharing)
[План на спринт 3](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/839)
[Таск на разработку сценария](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/1020)

**Comment by YuriSilenok** [comment]
метки + ссылка на этап
