### ISSUE TITLE
Невозможно добавить нового преподавателя

### ISSUE THREAD

**Issue by Proffet78** [Students-of-the-city-of-Kostroma/Student-timetable#879]
Баг воспроизводиться в v0.15-Testing
Ликвидация долгов по Sprint3 #927

Шаги:

1) Открыть форму "Преподаватели"
2) Нажать кнопку "добавить"
3) заполнить все поля
4) нажать кнопку "сохранить"
5) выдает сообщение, что не все поля заполнены, хотя все заполнено,также не понятно , какие поля введены некорректно.

Ожидаемый результат:
Создание нового преподавателя.

Фактический результат:
Выдает сообщение, что не все поля заполнены, хотя все заполнено,также не понятно , какие поля введены некорректно.

![3](https://user-images.githubusercontent.com/47320491/58339906-45350a00-7e53-11e9-96a2-de5da15f5a14.PNG)

**Comment by map82top** [comment]
Данный баг возникает из-за отсутсвия проверок на корректность вводимых данных
в моделях и на формах Ученые степени и Ученые звания. Эти сущности не относятся
к сфере нашей ответственности, поэтому мы переводим ее тем, кто отвечает за эти формы.

Требования, которые мы предъявляем к краткому названию ученой степени:

- длинна 25
- первая буква заглавная
- можнно вводить русские или английские буквы, пробелы, тире

Требования, которые мы предъявляем к краткому названию ученого звания:

- длинна 25
- первая буква заглавная
- можнно вводить русские или английские буквы, пробелы, тире

**Comment by Mikleproxorov** [comment]
Проверки в уч. степени и уч.звании уже были добавлены. Данный такс больше не актуален, поэтому закрываем.
