### ISSUE TITLE
Невозможно создать нового преподавателя, не создавая заранее ученую степень и звание

### ISSUE THREAD

**Issue by Proffet78** [Students-of-the-city-of-Kostroma/Student-timetable#880]
План - отчёт на Sprint7 #773
Провести мануальное тестирование #791
Баг воспроизводиться в v0.15-Testing
Разработка Sprint 7 #774
Ликвидация долгов по Sprint3 #927

Шаги:

1) Открыть форму "Преподаватели"
2) Нажать кнопку "добавить"
3) заполнить все поля 

Ожидаемый результат:
возможность заполнение полей ученое звание и степень, не создавая их заранее, в итоге создать преподавателя.

Фактический результат:
НЕВОЗМОЖНО заполнить поля ученое звание и степень, не создавая их заранее.Преподавателя сохранить( (создать нельзя)
Проще говоря, нужно добавить кнопку-ссылку.

![6](https://user-images.githubusercontent.com/47320491/58341026-f046c300-7e55-11e9-8ebd-e3485c5b9d2c.PNG)

**Comment by YuriSilenok** [comment]
@Proffet78 пожалуйста, добавьте нумерацию шагов, ожидаемый результат, фактический результат, придерживайтесь пожалуйста общепринятых требований
