### ISSUE TITLE
Автоматизация тестирования модульными тестами  для метода Delete(Model model) сущности Auditor

### ISSUE THREAD

**Issue by NesgovorovVS** [Students-of-the-city-of-Kostroma/Student-timetable#89]
[сценарий](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)
[Диаграмма классов](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit)
[план разработки](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_102)

**Comment by YuriSilenok** [comment]
Зачтено
