### ISSUE TITLE
Невозможно изменить поле "Директор института" на форме "Изменение института"

### ISSUE THREAD

**Issue by yuliagolubevaa5** [Students-of-the-city-of-Kostroma/Student-timetable#890]
1. Перейти на вкладку "Изменение института" 
![image](https://user-images.githubusercontent.com/47320351/58355618-ae317780-7e7d-11e9-832c-428794f9b42f.png)
2. Ввести новые данные в поле "Директор института", либо с помощью кнопки "Добавить" и ввести данные на форме "Добавить преподавателя"
![image](https://user-images.githubusercontent.com/47320351/58355821-46c7f780-7e7e-11e9-836a-f9a456f08c79.png)
3. Нажать на кнопку "Изменить"
Ожидаемый результат: Изменение данных в таблице
Фактический результат: Вывод сообщения об ошибке 
![image](https://user-images.githubusercontent.com/47320351/58355935-91497400-7e7e-11e9-98e1-815284d1988c.png)

**Comment by venecon1** [comment]
Данный баг более не воспроизводиться. Либо автором указана не полная последовательности действий. Я проверил были ли фиксы связанных файлов их не был. Следовательно баг или локальный или действия описаны не точно. Так как в соответсвии с тестами из [таблицы ](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=1153322464) проведенными мною мануально все тесты прошли проверку. Кроме task-786-3 и task-786-2 так как там надо менять краткое название, которое в актуальной версии сменить нельзя.

**Comment by YuriSilenok** [comment]
Баг не воспроизвелся в ветке Testing и v0.20-Testing
зачту как за иследовательскую работу. 
баг дейвствительно был поднят плохо.
