### ISSUE TITLE
Исправить ошибки в существующих unit-тестах

### ISSUE THREAD

**Issue by VinogradovAlexandr781227** [Students-of-the-city-of-Kostroma/Student-timetable#892]
Задача на написание unit -тестов #910
Исправить следующие тесты
Task_397_2
Task_397_3
Task_496_7
Task_496_8
task_396_2
task_396_3
Task_497_1
Task_497_7
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=983700952)
Родительская задача #775

**Comment by YuriSilenok** [comment]
- Нужно указать список автотестов, перечислите их в описании задачи
- Где ссылка на родительскую задачу?

**Comment by KudelinRoman** [comment]
Здравствуйте. 
Дополнили описание задачи.
Спасибо.
