### ISSUE TITLE
В справочнике "Ученые звания" в поля можно вводить некорректные символы

### ISSUE THREAD

**Issue by itword7111** [Students-of-the-city-of-Kostroma/Student-timetable#893]
#954
Название ветки: Alliance-5 Фиксация 0e454f9
Баг воспроизводится в v0.18-Testing
Шаги реализации бага:
1. Открыть справочник "Ученые звания"
2. Нажать "добавить"
3. В поле "Сокращенная запись уч. звания"вставить скопированную строку - "ā "
4. В поле "Полная запись уч. звания" вставить скопированную строку - "ā "
5. Нажать "создать и закрыть"
Ожидаемый результат:
![image](https://user-images.githubusercontent.com/38357886/58359878-40da1280-7e8e-11e9-887e-1666ecc3fa81.png)
Фактический результат:
![image](https://user-images.githubusercontent.com/38357886/58359893-52bbb580-7e8e-11e9-84f9-b1d33086285e.png)

**Comment by Takunava** [comment]
Как мне кажется данная задача не является багом

**Comment by itword7111** [comment]
improvement или bug ставить?

**Comment by ghost** [comment]
@itword7111 
Более подробный сценарии реализации бага, а именно вод таких символов(без numpad)

**Comment by Takunava** [comment]
> improvement или bug ставить?

Это скорее улучшение, и то я не понимаю как и зачем вы вводили эти символы

**Comment by ghost** [comment]
Считаю, что такие символы не уместны, их никто не будет вводить

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой
