### ISSUE TITLE
В справочнике "Институт" не выводится сообщение об ошибке

### ISSUE THREAD

**Issue by itword7111** [Students-of-the-city-of-Kostroma/Student-timetable#894]
#954
Название ветки: Alliance-5
Шаги реализации:
1. Открыть справочник "Институт", предварительно создав запись в справочнике "ВУЗы", вуз не должен называться "АА"
2. Нажать "добавить"
3. Во все поля ввести "АА"
4. Нажать "создать и закрыть"
Ожидаемый результат:
![image](https://user-images.githubusercontent.com/38357886/58360433-77655c80-7e91-11e9-899a-a42130b396f5.png)
Фактический результат:
![image](https://user-images.githubusercontent.com/38357886/58360454-9532c180-7e91-11e9-92f6-2898f35c6326.png)

**Comment by Takunava** [comment]
В какой версии воспроизводится данный баг?

**Comment by itword7111** [comment]
![image](https://user-images.githubusercontent.com/38357886/58370174-26df1500-7f0c-11e9-98c4-75a54a6a3c62.png)

**Comment by itword7111** [comment]
в последней вроде

**Comment by Pipyao** [comment]
Проверено, баг более не воспроизводится в ветке Alliance-5.
