### ISSUE TITLE
Автоматизация тестирования юнит-тестами конструктора CTeacher() для сущности Teacher

### ISSUE THREAD

**Issue by yuliagolubevaa5** [Students-of-the-city-of-Kostroma/Student-timetable#9]
Сценарий Unit-тестирования в [этой](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548) таблице
[План тестирования](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit?usp=sharing)
[Ссылка](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit?usp=sharing) на диаграмму классов.[](url)

**Comment by YuriSilenok** [comment]
зачтено
