### ISSUE TITLE
Изменить структуру класса Controller

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#90]
Класс **Controller** унаследовать от класса **DataTable** и убрать атрибут абстрактности.
Из класса **Controller**:

- Убрать статическое поле **DataSet**
- Убрать поле **table**
- Входной параметр конструктора передать в конструктор родителя.
- Методы **Insert, Update, Select** удалить.

Автоматические тесты выполнять не нужно, в место них проверить, что класс Controller не имеет синтаксических ошибок.

**Comment by YuriSilenok** [comment]
@ssas18 здравствуйте, 
Так как Вы не проявляли активность долгое время эта задача передается @Proffet78

**Comment by Proffet78** [comment]
@YuriSilenok , здравствуйте!
Не совсем понимаю подзадачу номер 3:
"Входной параметр конструктора передать в конструктор родителя."
Не могли бы вы мне разъяснить пожалуйста!

Спасибо!

**Comment by YuriSilenok** [comment]
Здравствуйте.
Этой подсказки достаточно?
```
myClass(int x):base(x)
{

}
```
Спасибо.

**Comment by Proffet78** [comment]
Здравствуйте! 

Прошу помощи.
Что мне с этим делать ?
Я пытался отправить коммит.

Спасибо,
![default](https://user-images.githubusercontent.com/47320491/53916883-53edfb00-4074-11e9-92c3-d77af6e9abcc.PNG)

**Comment by YuriSilenok** [comment]
Здравствуйте.

Попробуйте перевести то, что написано желтым.
Если это не поможет, напишите мне о том, что вы поняли из перевода.

Спасибо.

**Comment by Proffet78** [comment]
Здравствуйте! 

Перевод того, что написано желтым:
Обновления были отклонены, так как подсказка текущей ветви находится позади его удаленный аналог. Интеграция удаленных изменений (например "git pull ...") перед тем, как снова нажать. см. "примечание о быстрой перемотке вперед" в "git push --help" для деталей.

Спасибо

**Comment by YuriSilenok** [comment]
Здравствуйте, зачем Вы это мне написали? 
> Здравствуйте!
> 
> Перевод того, что написано желтым:
> Обновления были отклонены, так как подсказка текущей ветви находится позади его удаленный аналог. Интеграция удаленных изменений (например "git pull ...") перед тем, как снова нажать. см. "примечание о быстрой перемотке вперед" в "git push --help" для деталей.
> 
> Спасибо

**Comment by Proffet78** [comment]
Здравствуйте! 

Изначально, когда я перевел, я не совсем понял, что от меня требовалось, поэтому я написал это вам. Позднее я сам смог разобраться, просто забыл удалить комментарий, прошу меня извинить, постараюсь больше не загружать вас ненужной информацией!

Спасибо.

**Comment by YuriSilenok** [comment]
Здравствуйте.
- Комментарии могут удаляться только если они ошибочные
- Я не просил присылать мне перевод, я просил что бы Вы рассказали свое понимание этого перевода. И вообще происходящей ситуации.

Спасибо.

**Comment by YuriSilenok** [comment]
Почему [этот](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/141) запрос у Вас Выполнен?

**Comment by Proffet78** [comment]
Здравствуйте.

Этот запрос был ошибочным. Так как я впервые начал работать с GitHub, я не до конца понимал, что мне нужно было сделать и поэтому я изначально сделал его, и потом сам выполнил и закрыл, моя ошибка.  Потом я уточнил у своих одногруппников и в связи с этим,  я создал новый [запрос](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/146) .

Спасибо.

**Comment by YuriSilenok** [comment]
Нужно откатить изменения.

**Comment by Proffet78** [comment]
Здравствуйте.
Не совсем понимаю как это сделать (откатить изменения). Не могли бы вы мне помочь?
Спасибо.

**Comment by YuriSilenok** [comment]
Ответственный за задачу Вы, не перевешивайте ее на меня.

**Comment by YuriSilenok** [comment]
Под откатом изменений понимается команда revert. Она позволяет выполнить обратные действия некоторому коммиту. Вам следует прочесть о том как выполняется эта команда и и попробовать откатить изменения в вашем репозитории который вы получили в ЛР02. У Вас как раз там должен быть коммит на мерж двух веток.

**Comment by YuriSilenok** [comment]
Извините, но эта задача не является актальной
