### ISSUE TITLE
Провести мануальное тестирование для метода Update(Model model) сущности Институт

### ISSUE THREAD

**Issue by yuliagolubevaa5** [Students-of-the-city-of-Kostroma/Student-timetable#905]
[Таблица сценариев](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=1153322464)
#806

**Comment by bolotovaksenya** [comment]
Было проведено мануальное тестирование для данного метода, тесты, кроме тех, что ссылаются на баг #890, прошли успешно.
