### ISSUE TITLE
Исправить сломанные тесты

### ISSUE THREAD

**Issue by VinogradovAlexandr781227** [Students-of-the-city-of-Kostroma/Student-timetable#908]
Задача на написание unit -тестов #910

[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=983700952)
#775

**Comment by YuriSilenok** [comment]
- Обратите внимание но май вопрос в запросе на слияние #911 
- Где список сценариев которые были исправлены?
