### ISSUE TITLE
Создать  интерфейс для классов наследников контроллера

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#91]
Создать интерфейс с именем **IController** и объявить методы **Insert, Update, Delete** каждый из которых возвращает тип **bool** и имеет входной параметр **Model model**
Классы наследники от родителя класса **Controller,** должны так же унаследоваться от интерфейса **IController** 

Ветка task-91.

**Comment by YuriSilenok** [comment]
Здравствуйте.
Так как Вы не проявляли активности по этой задачи, задача с Вас снята.
Сообщите мне когда будете готовы браться за ЛР03.
Спасибо.

**Comment by YuriSilenok** [comment]
Здравствуйте @Parallusion 
Теперь это Ваша задача.
Спасибо.

**Comment by Parallusion** [comment]
Добрый вечер.

При запуске юнит тестов (кнопка выполнить все), сборка проходит успешно (внизу пишет об этом), но результат выполнения тестов не отображается вообще никак. С чем может быть это связано?

Спасибо
Смирнов Илья.
17-ИСбо-2А
![image](https://user-images.githubusercontent.com/47377888/53700094-f05b9780-3dff-11e9-894b-e99d9f701721.png)

**Comment by YuriSilenok** [comment]
Здравствуйте.

Попробуйте очистить и перетроить решение, для этого:
- В обозревателе роешения кликнуть ПКМ на решение и выбрать Очистить решение
- В обозревателе решения кликнуть ПКМ на решение и выбрать Перестроить решение
- В верхнем меню Тест - Выполнить - Все тесты (используйте обозреватель тестов для просмотра результатов тестирования и не используйте для первичного запуска тестов)

Спасибо.

**Comment by Parallusion** [comment]
Здравствуйте.

Сделал всё по инструкции, к сожалению, НЕ заработало. 
1 скрин. Результат очистки.
2 скрин. Результат перестроения.
3 скрин. Результат выполнения тестов.
![image](https://user-images.githubusercontent.com/47377888/53713522-3a726680-3e5c-11e9-95fa-f8f53c204dbf.png)
![image](https://user-images.githubusercontent.com/47377888/53713532-41997480-3e5c-11e9-9824-724e213d0241.png)
![image](https://user-images.githubusercontent.com/47377888/53713556-4ceca000-3e5c-11e9-96fc-ed262a4ca84b.png)

Спасибо.
Смирнов Илья.
17-ИСбо-2а

**Comment by YuriSilenok** [comment]
Здравствуйте.
Я хотел бы подключиться через TeamViewer к вашему компьютеру и посмотреть что не так.
Если Вы согласны, отправьте мне на почту ID и пароль и время когда я бы мог подключиться.
Вы используете VS2017?
Спасибо.

**Comment by Parallusion** [comment]
![image](https://user-images.githubusercontent.com/47377888/53739215-46811700-3ea2-11e9-8086-ecde728bda29.png)
Не получается запушить обратно на сайт. В чём проблема?

Спасибо. 
Смирнов Илья.
17-ИСбо-2А

**Comment by YuriSilenok** [comment]
Выполните git pull, git status, покажите результат. Подозреваю реверт вы делали через вэб-интерфейс, а последние изменения с сервера не получили.

**Comment by Parallusion** [comment]
Первый revert делал не я, а другой студент и откатывал он свои изменения, которые слил в Testing. А потом у меня сам commit прошёл успешно, изменения видны в комите под названием commit, они корректны. А затем я использовал revert на некорректный коммит и изменения некорректного комита должны были откатиться. Так что по логике должно быть всё нормально.

Правильный вариант решения задачи находится в commit, который в свою очередь находится в запросе, который я подал на вас, посмотрите пожалуйста.

**Comment by YuriSilenok** [comment]
Я бы сказал что все это мы должны обсуждать в запросе на слияние

**Comment by YuriSilenok** [comment]
Зачтено
