### ISSUE TITLE
В справочнике "Ученые звания", при изменении размеров окна "Добавление уч. звания" кнопки отражаются не корректно  

### ISSUE THREAD

**Issue by itword7111** [Students-of-the-city-of-Kostroma/Student-timetable#914]
#954
Название ветки: Alliance-5 Фиксация 0e454f9e
Баг воспроизводится в ветке Testing Фиксация 627ac450
Шаги реализации бага:
1. Открыть справочник "Ученые звания"
2. Нажать "добавить"
3. Уменьшить размер высоты окна

Ожидаемый результат:
кнопки остаются в нижней части окна, 
Фактический результат:
![image](https://user-images.githubusercontent.com/38357886/58375144-2a4abe80-7f55-11e9-84ac-0d04d6e1dbb0.png)

**Comment by YuriSilenok** [comment]
@itword7111 
У нас сейчас существуют релизы и я бы ожидал что Вы будете искать баги в последнем релизе и перепроверять исправление бага в релизе. 
Пожалуйста, подтвердите что баг воспроизводится в последнем релизе с указанием версии релиза.

**Comment by Pipyao** [comment]
Проверено, баг более не воспроизводится в ветке Alliance-5.

**Comment by itword7111** [comment]
@YuriSilenok  Если баг в последнем релизе не воспроизводиться, нужно что-то писать?
