### ISSUE TITLE
В справочнике "Ученые звания" при изменения значения поля на тоже значение, всплывает сообщение об ошибке

### ISSUE THREAD

**Issue by itword7111** [Students-of-the-city-of-Kostroma/Student-timetable#915]
#954
Название ветки: Alliance-5 фиксация 0e454f9e
В ветке Testing Фиксация 627ac45 при реализации бага на 6 этапе программа терпит крах
Баг воспроизводиться в v0.18-Testing
Шаги реализации бага:
1. Открыть справочник "Ученые звания"
2. Нажать "добавить"
3. В поле "Сокращенная запись уч. звания"Ее"
4. В поле "Полная запись уч. звания" ввести "Еее"
5. Нажать "создать и закрыть"
6. Нажать "изменить" в появившемся окне тоже нажать "изменить"
7. Удалить запись из справочника
8. Повторить действия со 2 пункта по 6 включительно

Ожидаемый результат:
![image](https://user-images.githubusercontent.com/38357886/58375227-c45f3680-7f56-11e9-9b83-a7333b056798.png)

Фактический результат:
![image](https://user-images.githubusercontent.com/38357886/58375224-be695580-7f56-11e9-806c-4aaa92f9c1d4.png)

**Comment by YuriSilenok** [comment]
@itword7111 
У нас сейчас существуют релизы и я бы ожидал что Вы будете искать баги в последнем релизе и перепроверять исправление бага в релизе. 
Пожалуйста, подтвердите что баг воспроизводится в последнем релизе с указанием версии релиза.

**Comment by itword7111** [comment]
Это оно?
![image](https://user-images.githubusercontent.com/38357886/58378648-fea0f600-7f9f-11e9-9551-0ef28aae4952.png)
Кроме названия ветки, нужно указывать фиксацию?(a8a44ad1)
с 24 числа была последняя фиксация на текущий момент, баг актуален

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой
