### ISSUE TITLE
Ликвидация долгов за 1 спринт

### ISSUE THREAD

**Issue by cdvinvate** [Students-of-the-city-of-Kostroma/Student-timetable#920]
Проведение мануального тестирования #780 
Найденные баги:
1) #778  Не отображается запись в графе окна
2) #779  Программа падает при двойном клике по заголовку таблицы
3) #782  Наличие недопустимых символов в таблице
4) #783  Программа падает при удалении пустой таблицы
5) #794  Нет ограничения уникальности значений для столбца "Почта" в таблице "ВУЗы" при добавлении нового ВУЗа

**Comment by cdvinvate** [comment]
Для защиты выполнения Sprint 1 необходимо найти 5 багов(по рекомендации тимлида). Об этом есть пометка в таблице об успеваемости.

**Comment by KharlamovaAlexandra** [comment]
Баги подняты на одну и ту же ошибку по вине тимлида( меня )

**Comment by YuriSilenok** [comment]
зачтено 1 остальные не проверялись

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
