### ISSUE TITLE
Ликвидация долгов за 3 спринт

### ISSUE THREAD

**Issue by cdvinvate** [Students-of-the-city-of-Kostroma/Student-timetable#922]
Проведение мануального тестирования #780
Найденные баги:
1) #795  Нет ограничения для одинаковых записей для столбца "Телефон" в таблице "ВУЗы" при добавлении нового ВУЗа
2) #796  Нет ограничения некорректных символов в таблице "Профиль подготовки" при добавлении нового профиля подготовки
3) #804  Падение программы при удалении измененной записи таблицы "Профиль подготовки"
4) #827  Программа не дает изменять профиль подготовки у группы
5) #884 У корпуса невозможно изменить ВУЗ

**Comment by cdvinvate** [comment]
Для защиты выполнения Sprint 3 необходимо найти 5 багов(по рекомендации тимлида). Об этом есть пометка в таблице об успеваемости. Еще 1 баг был найден в Sprinte 6:

#704 Программа падает при двойном клике по заголовку таблицы
На паре от 20 мая были обговорены все условия и то, что данный баг может входить в число найденных.

**Comment by KharlamovaAlexandra** [comment]
Баги подняты на одну и ту же ошибку по вине тимлида( меня )

**Comment by YuriSilenok** [comment]
Зачтено 4 из 5

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
