### ISSUE TITLE
Ликвидация долгов по Sprint3

### ISSUE THREAD

**Issue by Proffet78** [Students-of-the-city-of-Kostroma/Student-timetable#927]
Здравствуйте!
На паре от 20 мая было обговорено, что необходимо найти 8 багов, для защиты выполнения sprint 3, в котором я не участвовал. Вот все баги, которые я нашёл:

1. #828 Программа падает при сохранении нового корпуса корпуса
2. #878 Изменение краткого названия профиля, при добавлении нового профиля подготовки
3. #879 Невозможно добавить нового преподавателя
4. #880 Невозможно создать нового преподавателя, не создавая заранее ученую степень и звание
5. #881 Невозможно добавить ВУЗ с одинаковым кратким названием
6. #882 Возможность существования двух, разных по названию, корпусов, на одном адресе и с одним телефоном
7. #721 Изменение ФИО ректора, при редактировании ВУЗа ,
8. #719 Программа терпит крах при удалении преподавателя в форме «Преподаватели»
9. #722 Программа терпит крах при удалении изменённого профиля

**Comment by Proffet78** [comment]
Здравствуйте!
Последние 3 бага, были найдены в 6 спринте, вы сказали, что мы их тоже можем учесть.
Спасибо.

**Comment by YuriSilenok** [comment]
> Шаги реализации бага: 

- Откуда взялась такая формулировка?
- Баги должны содержать фактический и ожидаемый результат
- Шаги должны быть оформлены в виде нумерованного списка. https://guides.github.com/features/mastering-markdown/

**Comment by Proffet78** [comment]
Здравствуйте, @YuriSilenok 

* Формулировка взялась от предложения разработчиков, описывать шаги реализации, так как формулировки "шаги реализации бага" вы не давали, я исправил этот недочет.
* Теперь все баги содержат фактический и ожидаемый результат.
* Теперь шаги оформлены в виде нумерованного списка!

Спасибо!

**Comment by YuriSilenok** [comment]
Добрый день @Proffet78 
- Фактический и ожидаемый результат прописывается после шага приводящий к сбою
- Когда баг поднят, нужно указать версию ПО в котором этот баг найден.
- Когда разработчики заявляют что они исправили ошибку, Вы пытаетесь при помощи сценария в баге воспроизвести сбой. И пишите об этом отчет, что мол в такой-то версии баг не воспроизводится или воспроизводится в такой-то версии.

**Comment by YuriSilenok** [comment]
зачтено

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by Proffet78** [comment]
Здравствуйте,
Возможно эта задача уже не актуальна, так как у меня закрыты все долги по семестру и проставлен зачёт.
Спасибо.

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
