### ISSUE TITLE
Ликвидация долгов за ЛР03.1 и ЛР03.2

### ISSUE THREAD

**Issue by Proffet78** [Students-of-the-city-of-Kostroma/Student-timetable#929]
Здравствуйте, 

В понедельник (20.05) , после пары мы с вами договорились, что я могу взять два бага исправить их и вы сможете засчитать мне две лабораторные работы ( ЛР3.1 и ЛР3.2).

Я выполнил задание, прошу вас проверить:
1) #783 
2) #779

**Comment by YuriSilenok** [comment]
- относительно бага #783 запрос на слияние #825 в котором нет никаких исправлений. Если это так, то я не могу зачесть этот баг.

- #779 зачет в качестве ЛР 3.1

**Comment by Proffet78** [comment]
@YuriSilenok,Здравствуйте!

На счёт бага #783, изначально в первом запросе на слияние #790, я добавил условие, при котором баг будет исправлен, но я его залил не из той ветки, по неопытности, также там не отстроена табуляция! (ниже прикрепляю скрин)
В связи с этим вопрос, возможно ли в таком случае засчитать ?
![raaR_EIkQAY](https://user-images.githubusercontent.com/47320491/58691371-6dad8e80-8394-11e9-8d6d-93d5d13f1aa1.jpg)

Спасибо!

**Comment by YuriSilenok** [comment]
Найдите нужный запрос на слияние и в нем добавьте ссылку на Ваш баг.

**Comment by Proffet78** [comment]
Здравствуйте, @YuriSilenok 

Добавил ссылку в запросе на слияние на баг #783, а также на данную задачу !

Спасибо!

**Comment by YuriSilenok** [comment]
Добрый день @Proffet78 

Запрос #790 не был смержен, значит те исправления которые были там сделали не попали в релиз и значит они не могут быть засчитаны. Возможно вы в другой ветке вносили изменения или это не вы исправили ошибку?

Спасибо,
Юрий

**Comment by YuriSilenok** [comment]
задача закрыта по не активности

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой не указан дедлайн

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой не указан дедлайн

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой не указан дедлайн

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой не указан дедлайн

**Comment by Proffet78** [comment]
Здравствуйте,
Возможно эта задача уже не актуальна, так как у меня закрыты все долги по семестру и проставлен зачёт.
Спасибо.

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой не указан дедлайн

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой не указан дедлайн

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой не указан дедлайн

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой не указан дедлайн
