### ISSUE TITLE
Выполнить слияние Alliance-5 --> Testing

### ISSUE THREAD

**Issue by Takunava** [Students-of-the-city-of-Kostroma/Student-timetable#935]
Этап разработки #772

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by Takunava** [comment]
Задача закрыта в связи с тем, что веха в которой она находиться закрыта

**Comment by Takunava** [comment]
А также с тем, что [слияние](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/939) было проведено 
pull#939

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу
