### ISSUE TITLE
Программа терпит крах, если удалить преподавателя когда таблица преподавателей пуста

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#94]
Steps:
1. Перейти по меню Справочники-Преподаватели
2. Нажать на кнопку Удалить.
Ожидаемый результат: Никаких изменений.
Фактический результат: System.ArgumentOutOfRangeException: "Индекс за пределами диапазона. Индекс должен быть положительным числом, а его размер не должен превышать размер коллекции.

**Comment by VinogradovAlexandr781227** [comment]
Здравствуйте. Можно ли сделать вот так? Или это не очень рентабельно?

try { DG.Rows.RemoveAt(DG.SelectedCells[0].RowIndex); } catch { MessageBox.Show("Ошибка"); }

**Comment by YuriSilenok** [comment]
Здравствуйте.
Нет. Отлов исключений это всегда долгая операция.
В ожидаемом результате прописано что никаких изменений не должно произойти, это значит что и всплывающих сообщений тоже не должно быть.
При исправлении ошибок нужно ликвидировать ошибку, а не бороться с ее последствиями (сбоями)
Спасибо.

**Comment by YuriSilenok** [comment]
Задача снята по бездействию

**Comment by YuriSilenok** [comment]
@Pipyao Это Ваша новая задача

**Comment by VinogradovAlexandr781227** [comment]
Здравствуйте

Я готов приступить к лабораторной работе 3.1, снятой по бездействию.

Спасибо
Александр Виноградов
17-ИСбо-2б

пн, 4 мар. 2019 г. в 16:37, Юрий Силенок <notifications@github.com>:

**Comment by YuriSilenok** [comment]
Добрый день.

Вы должны были написать мне на почту

Спасибо

*Yuri Silenok* | QA Analyst, Consolidated FT team | *Exactpro*


BUILD SOFTWARE TO TEST SOFTWARE



вт, 5 мар. 2019 г. в 19:17, Александр Виноградов <notifications@github.com>:

**Comment by YuriSilenok** [comment]
Здравствуйте @Pipyao 
Если это действительно так, то Вам необходимо перевесить текущую задачу на пользователя @VinogradovAlexandr781227 и написать письмо в ветку в котором Вы уже просили выдать задачу.

> Я поговорил с тем, кто должен делать работу 94. Он не против переадресации задания на меня. Он сказал что не начинал ещё её делать и не против. Нельзя ли так сделать и отослать ему новую задачу? Скрины переписки могу предоставить.

**Comment by YuriSilenok** [comment]
@VinogradovAlexandr781227 Задача снята по бездействию

**Comment by VinogradovAlexandr781227** [comment]
Здравствуйте.

Не переназначайте задачу 94 и 133 (148). В выходные я их загружу. Я забыл
про то что не доделал 133, а про 94 думал что загрузил. Мой косяк.

Спасибо
Александр Виноградов
17-ИСбо-2б

ср, 20 мар. 2019 г. в 22:02, Юрий Силенок <notifications@github.com>:

**Comment by YuriSilenok** [comment]
не актуально
было исправлено в другом баге
