### ISSUE TITLE
Разработать сценарии тестирования пригодных для автоматизации модульным тестированием метода Update(Model model) сущности Кафедра

### ISSUE THREAD

**Issue by PopovMilan** [Students-of-the-city-of-Kostroma/Student-timetable#940]
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)

**Comment by PopovMilan** [comment]
Состояние таблицы контроллера | Сокращенная запись кафедры [[А-Я][а-я]] | Полная запись кафедры [[А-Я][а-я]] | Заведующий кафедры [[А-Я][а-я]]
-- | -- | -- | --
Изменение записи при совпадении всех атрибутов | task-940-5 | task-940-5 | task-940-5
Изменение записи при совпадении только одного атрибута | task-940-2 | task-940-3 | task-940-4
Изменение записи когда все атрибуты отличаются | task-940-1 | task-940-1 | task-940-1

**Comment by PopovMilan** [comment]
Здравствуйте, Юрий Викторович
Проверьте пожалуйста л.р. №4.1
Спасибо.

**Comment by YuriSilenok** [comment]
Таблица 1 выглядит нормально.
Пожалуйста, приведите описание сценариев в соответствие с таблицей 1.

**Comment by PopovMilan** [comment]
Здравствуйте, Юрий Викторович.
Извините за глупый вопрос,  а что является таблицей 1?
Не совсем понял

**Comment by YuriSilenok** [comment]
Видимо Вы делаете не по инструкции. 
![image](https://user-images.githubusercontent.com/14871471/58764218-30502900-856d-11e9-8eb0-d379c36d40b8.png)

**Comment by PopovMilan** [comment]
Прошу прощения, за еще глупый вопрос.
Ошибка в порядке ограничений? Или чего то не хватает в моей таблице?

**Comment by PopovMilan** [comment]
Состояние таблицы контроллера | Сокращенная запись кафедры [[А-Я][а-я]] | Полная запись кафедры [[А-Я][а-я]] | Заведующий кафедры [[А-Я][а-я]]
-- | -- | -- | --
Изменение записи при отличии всех атрибутов | task-940-1 | task-940-1 | task-940-1
Изменение записи при совпадении только одного атрибута | task-940-2 | task-940-3 | task-940-4
Изменение записи при совпадении всех атрибутов  | task-940-5 | task-940-5 | task-940-5

**Comment by PopovMilan** [comment]
Вроде так, если я правильно вас понял.

**Comment by YuriSilenok** [comment]
зачтено
