### ISSUE TITLE
План на спринт №2 - DreamTeam

### ISSUE THREAD

**Issue by sidelong44** [Students-of-the-city-of-Kostroma/Student-timetable#952]
# Работа с моделью Кафедра.

Требуется создать класс-модель _Кафедра_ с полями:
* Краткое название (`shortTitle`);
* Полное название (`fullTitle`);
* Заведующий кафедрой (`departmentHead`);
* Институт (`Institute`).

Для каждого поля реализовать соответствующие readonly-свойства и статические методы их валидации. Метод валидации должен возвращать boolean-значение успешности проверки поля в соответствии с правилами для него. При создании экземпляра модели, валидация также должна проводиться.

Реализовать форму добавления кафедры (для образца подойдет форма _Добавить преподавателя_). 

Зоны ответственности:
* Определение необходимых проверок для полей модели, проверка кода, разработка кода | @sidelong44 (senior developer)
* Разработка кода | @IlyaPyatin (developer)
* Разработка сценария тестирования (таблицей) для представления | @badsster (tester)
* Разработка сценариев для unit-тестов модели | @abramovaalina (automation engineer)
* Разработка автоматизированных сценариев для unit-тестов | @alexeylisica (automation tester)
* Мануальное тестирование | @ZhizhikinIvan (manual tester) 
* Разработка unit-тестов | @NordScandinavian (unit tester)
* Проверка тестовых сценариев, проверка unit и автоматизированных тестов | @sidelong44 (senior tester)

Команда на спринт:
@sidelong44 @abramovaalina @NordScandinavian @badsster @ZhizhikinIvan @alexeylisica @IlyaPyatin

**Comment by YuriSilenok** [comment]
Проверю на занятии
