### ISSUE TITLE
Не корректно работает кнопка отмены в форме направление подготовки 

### ISSUE THREAD

**Issue by GubanovAndrey** [Students-of-the-city-of-Kostroma/Student-timetable#957]
1)Нажимаешь кнопку "добавить" в форме направление подготовки.
2)Нажимаешь кнопку "отмена"   (Не заполняя форму вообще).
Ожидаемый результат : форма закроется. 
Реальный результат : Выводит ошибку о том , что код направления подготовки введен не правильно.

**Comment by GubanovAndrey** [comment]
![Снимок](https://user-images.githubusercontent.com/47377845/58499294-847f9580-8188-11e9-8c53-d8968a7c6c9a.PNG)

**Comment by YuriSilenok** [comment]
Передано по бездействию

**Comment by YuriSilenok** [comment]
Вы пропустили первый шаг описаный в запросе https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1103#issuecomment-506713261.
Если Вы не понимаете что Вы должны сделать, Вы должны задать вопрос.

**Comment by YuriSilenok** [comment]
Вы нарушили последовательность действий, почему вы сначало перевесили на меня задачу, а потом пошли закрывать запрос?

**Comment by YuriSilenok** [comment]
закрыто по неактивности

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
