### ISSUE TITLE
Невозможно создать запись в таблице Профиль подготовки с дублирующим атрибутом Краткое название профиля подготовки 

### ISSUE THREAD

**Issue by GubanovAndrey** [Students-of-the-city-of-Kostroma/Student-timetable#958]
1)Нажать на кнопку "создать" в форме профиль подготовки.
2)Создать объект класс MTrainingProfile с кратким названием, которое уже использовалось. 
Ожидаемый результат: количество записей увеличиться на одну.
Реальный результат: вывод ошибки.
![Снимок2](https://user-images.githubusercontent.com/47377845/58501466-2acd9a00-818d-11e9-812f-ac549f9b52fa.PNG)

**Comment by YuriSilenok** [comment]
@Proffet78 
Краткое название профиля подготовки может дублироваться, уникальным значением для профиля подготовки является шифр направления подготовки.
- Исправить ошибку воспроизводимую в баге.
- Проверить описание и исправить при необходимости в Story #630, сценариях тестирования, автотестах.

**Comment by YuriSilenok** [comment]
Задача снята по бездействию

**Comment by YuriSilenok** [comment]
на меня задачи вешаются только после мержей
