### ISSUE TITLE
 Некорректное название столбца в форме профиль подготовки ("ширф")

### ISSUE THREAD

**Issue by GubanovAndrey** [Students-of-the-city-of-Kostroma/Student-timetable#959]
Опечатка в названии первого столбца 
![Снимок3](https://user-images.githubusercontent.com/47377845/58502014-4e451480-818e-11e9-9241-4a86bd45fd89.PNG)

**Comment by YuriSilenok** [comment]
Задача снята

**Comment by YuriSilenok** [comment]
Воспроизводится в v0.20-Testing

**Comment by YuriSilenok** [comment]
на меня задачу вешать после мержа

**Comment by YuriSilenok** [comment]
Зачтено
