### ISSUE TITLE
Разработать сценарии тестирования формы Добавить кафедру

### ISSUE THREAD

**Issue by sidelong44** [Students-of-the-city-of-Kostroma/Student-timetable#963]
План #952 
Этап тестирования #961 
Добавлять сценарии в [таблицу](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548).

Сценарии должны содержать проверку корректности валидаций формы

**Comment by badsster** [comment]
Сценарий по форме "Добавить кафедру" задачи #771 написан и занесен в таблицу.

**Comment by YuriSilenok** [comment]
Сценарии не дописаны

**Comment by alexeylisica** [comment]
Сценарий по форме "Добавить кафедру" задачи #963 написан и занесен в таблицу. Разработано 9 сценариев.
