### ISSUE TITLE
Обновить сценарии тестирования для формы Кафедра

### ISSUE THREAD

**Issue by sidelong44** [Students-of-the-city-of-Kostroma/Student-timetable#964]
План #952 
Этап тестирования #961 

Перенести сценарии из #771 в [таблицу](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw).
Дополнить сценарий проверки работы кнопки Добавить кафедру

**Comment by badsster** [comment]
Сценарий для представления дополненной формы "Кафедра" был написан в таблице сценариев.
@ZhizhikinIvan можно проводить мануальное тестирование.

**Comment by YuriSilenok** [comment]
Номера сценариев не меняются. Если вы обновляли сценарии 771 таском 964, номера так и останутся 771,

**Comment by YuriSilenok** [comment]
А где столбцы с шагами и прекондишеном?
В качестве образца по столбцам смотрите лист ЛР04.1

**Comment by badsster** [comment]
Номера сценариев исправлены, подскажите, где найти ЛР04.1?

**Comment by sidelong44** [comment]
@YuriSilenok 
> А где столбцы с шагами и прекондишеном?

Исправлено
