### ISSUE TITLE
Разработать сценарии unit-тестов модели Кафедра

### ISSUE THREAD

**Issue by sidelong44** [Students-of-the-city-of-Kostroma/Student-timetable#965]
План #952 
Этап тестирования #961 
Добавлять сценарии в [таблицу](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw).

**Comment by abramovaalina** [comment]
Сценарий добавлен в [таблицу](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=223449593)
