### ISSUE TITLE
Провести мануальное тестирование формы Кафедра и формы Добавить кафедру

### ISSUE THREAD

**Issue by sidelong44** [Students-of-the-city-of-Kostroma/Student-timetable#967]
План #952 
Этап тестирования #961 

Сценарий тестирования формы _Кафедра_ #771
Сценарий тестирования формы _Добавить кафедру_ #963

**Comment by ZhizhikinIvan** [comment]
Мануальное тестирование провёл. Ошибок не обнаружил.

**Comment by sidelong44** [comment]
Задача выполнена
