### ISSUE TITLE
Кнопка удаления группы из таблицы Группы

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#97]
Перейдите по верхнему меню Справочники-Группы.
В правом нижнем углу формы Группы разместить 2 кнопки, удалить и правее добавить.
При нажатии на кнопку удалить, удаляется выделенная запись в таблице Группы. Если запись не выделена, никаких действий происходить не должно.

**Comment by YuriSilenok** [comment]
Добрый день.

Когда Вам пришло уведомление о задаче, вы по ссылке должны были попасть на вкладку Issue.
Вкладка Code содержит сам репозиторий, который вам нужно склонировать.
Для большего понимания я добавлю ссылку на репозиторий в инструкцию к ЛР03
На 8 слайде вы можете увидеть фрагмент знакомого интерфейса.

Эту форму Вы сможете найти запустив проект из склонированного репозитория.
Я добавлю в описание вашей задачи как ее найти.

Пожалуйста. Если у вас возникают вопросы по задаче, то задавайте их в комментариях к задаче
 
Спасибо

**Comment by ghost** [comment]
Добрый вечер.

У меня не получается создать строку.
При нажатии на кнопку "Добавить"  сообщается о необработанном исключении 

System.InvalidOperationException: "Строки нельзя программным способом добавить в коллекцию строк DataGridView, если элемент управления привязан к данным."

Вот то, как я пытаюсь добавить строку 

```
            DataGridViewCell Population = new DataGridViewTextBoxCell();
            DataGridViewCell Chiper = new DataGridViewTextBoxCell();
            DataGridViewRow row = new DataGridViewRow();
            Population.Value = 0;
            Chiper.Value = 0;
            row.Cells.AddRange(Population, Chiper);
            this.DG_Group.Rows.Add(row);
```

**Comment by YuriSilenok** [comment]
Здравствуйте.

Вы молодец. Правильно поставили вопрос. Все верно, мешают привязанные ресурсы. Так как мы эксплуатируем паттерн MVC, то вы не должны пытаться манипулировать представлением (или в частности графическим интерфейсом). Нужно управлять данными через контроллер. Найдите форму AddTeacher. Там есть кнопка создающая преподавателя через контроллер. Думаю у вас получиться сделать по аналогии. Возможно Вы сможете найти найти задачу которая ставилась на эту кнопку. Там есть немного вспомогательной информации. Так же можете попробовать найти диаграмму классов. Она поможет понять иерархию классов. Или можете построить диаграмму вызовов в VS, но если с ней не работали, она может Вас запутать.

Желаю удачи.

**Comment by ghost** [comment]
Добрый вечер.

Должна ли функционировать кнопка "Добавить" ?

**Comment by YuriSilenok** [comment]
Нет, кнопка "Добавить" не должна функционировать, если хотите, можете повесить на нее заглушку по добавлению одной записи, потом она будет открывать форму где пользователь сможет заполнить данные для создаваемой группы.

**Comment by YuriSilenok** [comment]
зачтено

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой не указан дедлайн

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой не указан дедлайн

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой не указан дедлайн

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой не указан дедлайн

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой не указан дедлайн

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой не указан дедлайн

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой не указан дедлайн

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой не указан дедлайн

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой не указан дедлайн

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой не указан дедлайн

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу
