### ISSUE TITLE
Разработать сценарии тестирования класса Logs

### ISSUE THREAD

**Issue by Mikleproxorov** [Students-of-the-city-of-Kostroma/Student-timetable#978]
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=1813879881)
#991 функционал
#955  План
#956 Этап тестирования

**Comment by Mikleproxorov** [comment]
Задача выполнена.

**Comment by YuriSilenok** [comment]
в описании должна быть ссылка на Story описывающая работку функционала

**Comment by Mikleproxorov** [comment]
Добавил ссылку.

**Comment by YuriSilenok** [comment]
> #956 План

956 это не план

**Comment by YuriSilenok** [comment]
а где ссылка на этап тестирования?
