### ISSUE TITLE
Написать сценарии тестирования пригодных для автоматизации модульного тестирования для метода Delete(Model model) сущности Teacher.

### ISSUE THREAD

**Issue by ZhizhikinIvan** [Students-of-the-city-of-Kostroma/Student-timetable#98]
[План разработки](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_102)
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)
[Диаграмма классов](https://docs.google.com/presentation/d/1sLkafCqJTvIAcyZ1jfNw0JrZq8o33WYKGot23z7EfzA/edit#slide=id.g4e940e7976_0_0)

**Comment by YuriSilenok** [comment]
Здравствуйте.
Обратите внимание на замечания:
- Тема не соответствует требованиям
- Метки не соответствует требованиям
- Веха была указана после того как Вы перевесили задачу.
- Не сценарий и сценарии

Спасибо

**Comment by YuriSilenok** [comment]
Здравствуйте.
Обратите внимание на замечания:
* На какой вопрос должен отвечать заголовок?
* Почему Вы выбрали такой набор меток?

Спасибо
