### ISSUE TITLE
Cоздать форму "Добавить кафедру"

### ISSUE THREAD

**Issue by ghost** [Students-of-the-city-of-Kostroma/Student-timetable#980]
План #952
Этап разработки #960

Создать визуальную часть формы "Добавить кафедру"

Форма должна содержать 4 поля:
* Краткое название
* Полное название
* Заведующий кафедрой
* Институт

Форма должна содержать 2 кнопки:

* Добавить
* Очистить

Файл формы должен располагаться тут: `TimetableOfClasses/AddDepartment.cs`
Форма Кафедра тут: `TimetableOfClasses/Department.cs`, смотреть в ветке `17-IDbo-3b-1`
За пример реализации взять файл: `TimetableOfClasses/AddTeacher.cs`

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой не указан дедлайн

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу
