### ISSUE TITLE
Улучшение валидаторов для моделей

### ISSUE THREAD

**Issue by sidelong44** [Students-of-the-city-of-Kostroma/Student-timetable#988]
Предлагаю упростить валидацию моделей и использовать написанный мной класс ValidationUtils (сейчас находится в ветке 17-IDbo-3b-2).

Данное улучшение поможет сократить код и унифицировать проверки данных во всех моделях.

**Comment by YuriSilenok** [comment]
Валидация должна производится в статических методах модели. Название модели начинается с буквы M. 1 метод валидации предназначен для проверки одного поля в модели. Модель должна содержать поля содержащие сведения инициализация которых выполняется в конструкторе и в нем же используются методы валидации. В случае не успешной валидации должно быть выброшено исключение.

**Comment by YuriSilenok** [comment]
кажется Вы это реализовали, прикрепить пожалуйста в запросе ссылку на этот таск

**Comment by sidelong44** [comment]
Добрый день. В каком запросе? В PR?

**Comment by YuriSilenok** [comment]
Да, в пулреквесте.

**Comment by YuriSilenok** [comment]
Закрыто по окончанию процесса обучения и смерженному запросу.

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
