### ISSUE TITLE
Написать сценарии тестирования пригодные для автоматизации unit-test для метода Delete(Model model) сущности Discipline

### ISSUE THREAD

**Issue by sidelong44** [Students-of-the-city-of-Kostroma/Student-timetable#99]
[Сценарии](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=2120214548)
[План разработки](https://docs.google.com/spreadsheets/d/11uPdKMmzZklleijGcBAKoStnVHY2_9qBwRPOpR1y0vM/edit#gid=389498935)
[Диаграмма классов](https://docs.google.com/drawings/d/1o-V0BRXdX8lOUZobmxeg3WgOUZHcyNoL7iSdGPOcBnQ/edit)

**Comment by YuriSilenok** [comment]
Зачтено

пн, 25 февр. 2019 г., 1:40 Ilya Sergeev <notifications@github.com>:
