### ISSUE TITLE
Исправить сбои в файле UT_Insert_Croup

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#995]
- Выяснить причины сбоев (при необходимости уточнить у преподавателя баг или фича)
- Исправить сценарии если они устарели (изменилась функциональность)
- Исправить автотесты в соответствии со сценариями

**Comment by YuriSilenok** [comment]
Перечислить test id тестовых сценариев, которые претерпели изменения.
Сослаться на таск по разработке тестовых сценариев.

**Comment by SamuraSwordS** [comment]
Претерпели изменения сценарии: task-251-1, task-251-3, task-251-4, task-251-5, task-251-6, task-251-7, task-251-8, task-251-9, task-251-10.
#251

**Comment by YuriSilenok** [comment]
зачтено
