### ISSUE TITLE
Создать форму "Параметры". Вкладка Звонки

### ISSUE THREAD

**Issue by MyachevM** [Students-of-the-city-of-Kostroma/Student-timetable#998]
Форма вызывается из меню Настройки-Параметры.
Имеет название формы параметры и повторяет интерфейс как на изображении.
Реализовать только вкладку Звонки
![image](https://user-images.githubusercontent.com/47633738/58822483-4e3a8e00-8640-11e9-8bfc-ae12d381de66.png)

**Comment by MyachevM** [comment]
Я создал задачу для @FvckNeighbors для закрытия Лаб.1, поэтому назначил ответственным вас для проверки @YuriSilenok

**Comment by YuriSilenok** [comment]
@MyachevM Поднято верно. ЛР01 зачтена

**Comment by YuriSilenok** [comment]
Задача снята по не активности

**Comment by ZEUS4942** [comment]
Создал форму "Параметры". Вкладка Звонки.
Проверяющий @YuriSilenok 
Вот ссылка на task:
https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/tree/task-998

**Comment by YuriSilenok** [comment]
Когда в заспросе на слияние юудет дано разрешение на слияние и слияние Вами будет выполнено, эту задачу необходимо перевесить на меня.

Обо всех манипуляциях мне приходит уведомление. Я не пропущу Ваш запрос. Не нужно писать в основной задаче о том что запрос готов к проверке, Вы должны указать мнея в соответсвующем поле, что и было Вами сделано.

И да, https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/tree/task-998
это не ссылка, а URL, [вот](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/tree/task-998) ссылка. и это ссылка не на таск, а на ветку в репозитории, а хотели вы вставить ссылку не на таск, а на запрос на слияние.

**Comment by YuriSilenok** [comment]
Зачтено
